### ISSUE TITLE
Backups abort upon finding a symlink

### ISSUE THREAD

**Issue by LPGhatguy** [wbond/package_control#1000]
This morning, I had my TypeScript package with important logs wiped out by a Package Control package upgrade. It didn't back up the folder because it had a symlink in it -- and I was notified of this.

Would it be possible to have one of:
- Support copying of symlinks when backing up plugins
- Abort an upgrade if a backup wasn't successful

This was on OS X with Sublime Text 3083.

**Comment by wbond** [comment]
Can you send a debug log of this happening please?

**Comment by LPGhatguy** [comment]
Where would a log of this be saved on the system? I hit the same issue on my Windows 10 machine as well.

**Comment by wbond** [comment]
It is not saved, you'll have to copy the error from the ST console after it happens.

**Comment by wbond** [comment]
But yeah, you shouldn't hand edit a package from a source you don't control because Package Control could upgrade it at any time. Instead, fork the package and use git/hg to clone it, or rename the package and delete any package-metadata.json since that is a file PC uses to know it controls a package. Then you can deal with upgrades as you wish.

**Comment by wbond** [comment]
Ping for a debug log.

**Comment by LPGhatguy** [comment]
Apologies for the delay, there's been quite a crunch at the office.

Are there any tricks to reproducing a package installation/upgrade so I could get a log for you?

**Comment by LPGhatguy** [comment]
With a new package upgrade, I was able to reproduce this again and nab some sort of log!

http://hastebin.com/aramasicid.txt

Additionally, there was a nasty popup complaining about permissions being denied for a folder inside of the plugin folder.

**Comment by FichteFoll** [comment]
Unrelated, but you should really update SublimeREPL. The mnemonic messages are quite annoying and haven been fixed months ago.
