### ISSUE TITLE
Persistent Package Control notice: Updated missing Python _ssl module for Linux

### ISSUE THREAD

**Issue by Hipp04** [wbond/package_control#1001]
Every time I open Sublime Text I get a notice from Package Control with the following message:
"
Package Control just installed or upgraded the missing Python _ssl module for Linux since Sublime Text does not include it.

Please restart Sublime Text to make SSL available to all packages.
"

It started last week. Restarting Sublime and/or the machine doesn't seem to get rid of it. I'm just getting tired of clicking "OK" each time.

I've googled the issue and can't seem to find anyone else encountering it. Has anyone else had this issue and determined a fix?

Using:
Ubuntu 15.04
Sublime Text Build 3083
Package Control version 3.1.2

Debug Output:
DPI scale: 1.2
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/jon/.config/sublime-text-3/Packages
state path: /home/jon/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/jon/.config/sublime-text-3/Installed Packages
ignored_packages: ["AutoHotkey"]
pre session restore time: 0.153076
warning: mnemonic b not found in menu caption SFTP/FTP
startup time: 0.226674
first paint time: 0.232299
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-pytz
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Blade Spacer.BladeSpacer
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin CSS Format.css_format
reloading plugin Emmet.emmet-plugin
reloading plugin GhostText.FocusSublimeWindow
reloading plugin GhostText.GhostText
reloading plugin GotoDocumentation.goto_documentation
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin HTMLBeautify.HTMLBeautify
reloading plugin InsertDate.insert_date
reloading plugin JsFormat.js_formatter
reloading plugin Origami.origami
reloading plugin PHP Codebeautifier.phpcbf
reloading plugin PHP Companion.PHP Companion
reloading plugin PHPUnit.phpunit
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PhpDoc.CodeDoc
reloading plugin PhpNamespace.PhpNamespaceCopy
reloading plugin PhpNamespace.classes
reloading plugin PhpNamespace.namespaces
reloading plugin PhpNamespace.utils
reloading plugin Phpcs.phpcs
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Tag.Edit
reloading plugin Tag.Tag
reloading plugin Tag.tag_classes
reloading plugin Tag.tag_close_tag
reloading plugin Tag.tag_close_tag_on_slash
reloading plugin Tag.tag_indent
reloading plugin Tag.tag_insert_as_tag
reloading plugin Tag.tag_lint
reloading plugin Tag.tag_remove
reloading plugin Tag.tag_remove_attributes
reloading plugin Xdebug Client.main
reloading plugin PlainTasks.PlainTasks
reloading plugin Print to HTML.PrintToHTML
reloading plugin SFTP.SFTP
SFTP: enabling custom linux ssl module
SFTP: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin Search in Project.search_in_project
plugins loaded
GhostText is starting now…
Setting on request handler
HTTP Start
Package Control: Downloading bootstrapped dependency ssl-linux
Package Control: Download Debug
  URL: http://packagecontrol.io/ssl/1.0.1/ssl-linux.sublime-package
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Urllib HTTP Debug General
  Connecting to packagecontrol.io on port 80
Package Control: Urllib HTTP Debug Write
  GET /ssl/1.0.1/ssl-linux.sublime-package HTTP/1.1
  User-Agent: Package Control v3.1.2
  Connection: Keep-Alive
  Host: packagecontrol.io
  Accept-Encoding: bzip2,gzip,deflate
Package Control: Urllib HTTP Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Tue, 22 Sep 2015 22:00:26 GMT
  Content-Type: application/octet-stream
  Content-Length: 772251
  Last-Modified: Tue, 03 Feb 2015 14:37:32 GMT
  Connection: keep-alive
  ETag: "54d0dd2c-bc89b"
  Strict-Transport-Security: max-age=15552000
  Accept-Ranges: bytes
Emmet: No need to update PyV8
Package Control: Skipping cache since the response is a zip file
Package Control: Successfully downloaded bootstraped dependency ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
Package Control: Linux SSL: unloading http module so ssl will be available
Package Control: Linux SSL: unloading urllib module so ssl will be available
Package Control: Successfully installed bootstrapped dependency ssl-linux
Package Control: The package AutoHotkey is being re-enabled after a Package Control operation was interrupted
ignored packages updated to: []
Package Control: Installing 1 missing package
Package Control: Fetching list of available packages
  Platform: linux-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
warning: mnemonic b not found in menu caption SFTP/FTP
Package Control: Caching https://packagecontrol.io/channel_v3.json in /home/jon/.config/sublime-text-3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
ignored packages updated to: ["AutoHotkey"]
reloading Packages/User/Package Control.sublime-settings
warning: mnemonic b not found in menu caption SFTP/FTP
reloading Packages/User/Preferences.sublime-settings
warning: mnemonic b not found in menu caption SFTP/FTP
Package Control: Fetching list of available packages
  Platform: linux-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
Package Control: The package "AutoHotkey" is either not available on this platform or for this version of Sublime Text
Package Control: Skipping automatic upgrade, last run at 2015-09-22 17:42:45, next run at 2015-09-22 18:42:45 or after
Package Control: Urllib HTTP Debug General
  Closing connection to packagecontrol.io on port 80 after 1 request

**Comment by Hipp04** [comment]
Found solution here: https://github.com/wbond/package_control/issues/989

**Comment by OmeGak** [comment]
How did you fix it exactly? I tried this and keeps happening:

```
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
rm -f rm 0_package_control_loader.sublime-package 0_package_control_loader.sublime-package-new
cd ../Packages
rm -rf bz2
```

**Comment by wbond** [comment]
@OmeGak What OS and version of Sublime Text are you using? Those instructions are for OS X and ST3 when having trouble with an old version of the bz2 dependency. This issue is about ST3 on Linux with the ssl dependency.

**Comment by OmeGak** [comment]
Just copied that snippet from #989. I'm on Linux and ST3 but removed those files/directory in the correct path and I kept getting the same _ssl message. In any case, it was fine after I rebooted today.

**Comment by jaimergp** [comment]
I did the steps suggested by @ndi-root in #989. The only difference is, that in this case, the problem is the ssl-linux package, not bz2.  So:

1. Close ST3
2. Delete `~/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package` file and `~/.config/sublime-text-3/Packages/ssl-linux` folder. 
3. Start ST3. The same message will pop up one last time, but the next time you open ST3 it won't.

**Comment by luisaceituno** [comment]
In my case I had to do the following:

1. Do what @jaimergp said in step 1 and step 2
2. Delete the Package Control package (in my case by deleting `/opt/sublime_text/Packages/Package Control.sublime-package` and `~/.config/sublime-text-3/Installed Packages/Package Control.sublime-package`)
3. Reinstall package control
4. Start ST3. I had 2 messages pop up this time, and then it was okay for all subsequent launches.
