### ISSUE TITLE
Error executing: /usr/bin/security dump-trust-settings 

### ISSUE THREAD

**Issue by flipphillips** [wbond/package_control#1002]
## One-line Description
PC throws an error w/ dialog on startup re: the keychain on Mac OS X 10.11

## Broader Description
On occasion, Package Control starts up at the beginning of a ST3 startup and displays an error of the form:
```
Package Control

Error executing: /usr/bin/security dump-trust-settings -d

SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
...
...
```

## Replication / regression

It happens at startup but not every startup. Difficult to replicate but I'm presuming you know where this work is being done. Furthermore- I _just_ noticed a PC upgrade. So I have upgraded to see if this fixes this problem. 

Happens across 2x machines at least, both running El Cap/10.11 and shared preferences / configuration via Dropbox

## Relevant configuration notes
Mac Book Pro Retina + Mac Pro
Mac OS X 10.11 GM
ST3 3095
PC 3.1.0

<img width="436" alt="macos_ _-bash_ _bash_ _80x24_and_bin_ _-bash_ _bash_ _80x24_and_twitter___mentions" src="https://cloud.githubusercontent.com/assets/671183/10051938/1489b620-61f2-11e5-9c5d-b0b130e89300.png">

**Comment by wbond** [comment]
Package Control only dumps the trust settings about once a week since it can take a few seconds to do so. This is most likely why you only see it occasionally.

I've been working on a bunch of other, mostly unrelated crypto code that deals with dumping these trust settings also, albeit without launching a subprocess, but instead using the OS X APIs. It may make more sense to switch over to that code since it is more well tested and would not suffer from the perils of scraping command line tool output.

Just incase anyone is reading and wants to know the direction am considering, please see https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/trust_list.py#L21-L140.

**Comment by wbond** [comment]
I should also note, it appears that this output is likely caused because "custom" trust settings exist for one or more certs in your system keychain.

**Comment by flipphillips** [comment]
Indeed there is something 'up' with my keychain there. Curious.

**Comment by musashinm** [comment]
Same here.

**Comment by fabienbellanger** [comment]
I have the same problem

**Comment by ashokfernandez** [comment]
+1

**Comment by zhanghan177** [comment]
+1 Appears after upgrading to os x 10.11

**Comment by jordan314** [comment]
I'm seeing it too in El Capitan. Could it be the SIP settings limiting /usr/bin?

**Comment by dadaclonefly** [comment]
+1 after upgrading OS X 10.11

**Comment by bottledsmoke** [comment]
+1 after upgrading to OS X 10.11

**Comment by mrexodia** [comment]
What worked for me was to remove all certificates shown when you execute `/usr/bin/security dump-trust-settings -d` (mine was expired is why I tried).

When re-adding the HTTPS certificate using Safari everything worked again.

**Comment by tzm41** [comment]
<img width="532" alt="screen shot 2015-10-15 at 14 05 18" src="https://cloud.githubusercontent.com/assets/5728283/10522935/cfa6f724-7345-11e5-9c87-7f5df0d692d7.png">

**Comment by harshal-gajare** [comment]
![image](https://cloud.githubusercontent.com/assets/5017173/10530155/774a3ba4-7372-11e5-9ad2-4733ce29e593.png)

**Comment by harshal-gajare** [comment]
I am getting this error as well 

Mac OS X 10.11

Package Control

Error executing: /usr/bin/security dump-trust-settings -d

SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
Number of trusted certs = 3
Cert 0: SAP Passport CA
   Number of trust settings : 2
   Trust Setting 0:
      Policy OID            : Apple X509 Basic
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 1:
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
Cert 1: GTE CyberTrust Global Root
Cert 2: Class 3 Public Primary Certification Authority

VCS-based packages can be ignored with the "ignore_vcs_packages" setting.

**Comment by davidsouza** [comment]
+1

**Comment by lincetto** [comment]
+1

**Comment by nemofang** [comment]
Same issue here after upgrading to OSX 10.11.

**Comment by ajaydwarkani** [comment]
+1

**Comment by davidhq** [comment]
+1

**Comment by johntdyer** [comment]
same issue here

**Comment by sashkab** [comment]
+1

**Comment by urda** [comment]
:-1: Having the same issue...

```
Package Control

Error executing: /usr/bin/security dump-trust-settings -d

SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
Number of trusted certs = 4
Cert 0: Urda Certificate Authority
   Number of trust settings : 2
   Trust Setting 0:
      Policy OID            : Apple X509 Basic
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 1:
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
Cert 1: http://openvpn.net/localca.html #1437602575
   Number of trust settings : 0
Cert 2: GTE CyberTrust Global Root
Cert 3: Class 3 Public Primary Certification Authority

VCS-based packages can be ignored with the "ignore_vcs_packages" setting.
```

<img width="420" alt="screenshot 2015-10-17 23 54 49" src="https://cloud.githubusercontent.com/assets/1648492/10562449/90382e00-752a-11e5-9eb6-a5d323fbaae9.png">

**Comment by yangj1e** [comment]
+1

**Comment by envomer** [comment]
same issue here. any fix yet?

**Comment by frbonomi** [comment]
+1

**Comment by jon-van** [comment]
+1 as well

**Comment by pstinnett** [comment]
+1

**Comment by jtlindsey** [comment]
Same problem here.

![screen shot 2015-10-20 at 6 25 24 pm](https://cloud.githubusercontent.com/assets/7409277/10622850/ff974cb6-7757-11e5-8cff-84a3600516dc.png)

![screen shot 2015-10-20 at 6 24 45 pm](https://cloud.githubusercontent.com/assets/7409277/10622863/1031260a-7758-11e5-9d43-98a08db55e45.png)


![screen shot 2015-10-20 at 6 24 19 pm](https://cloud.githubusercontent.com/assets/7409277/10622870/17e5f218-7758-11e5-8686-518a1031017e.png)

**Comment by margaritis** [comment]
+1

**Comment by yaway** [comment]
+1

**Comment by shankiesan** [comment]
I'm going to follow everyone else and give this a +1

**Comment by SteveLTN** [comment]
+1

**Comment by wbond** [comment]
Sorry this has taken so long. I've just needed to focus on some paying work recently. I'm hoping to get this resolved soon.

**Comment by jonathanmorgan** [comment]
Does this actually cause anything to fail?  If not, it would be nice to have it fixed, but you should put food on the table first.

**Comment by zhanghan177** [comment]
When I first encountered this issue, my sublime froze and I have to force quit. I haven't been using sublime since then. But I just checked my sublime again, and it seems working well. I don't know if my issue still exist though...

**Comment by qbein** [comment]
+1

**Comment by davidhq** [comment]
Maybe there has been enough of +1s on this thread :) The message got accross :D

**Comment by imcom** [comment]
+1 Appears after upgrading to os x 10.11

**Comment by inopinatus** [comment]
+1 and mostly I want to know if this breaks anything.

**Comment by urda** [comment]
I'm going to echo what @davidhq said, we've got enough +1's for now, and @wbond has recognized this issue.

**Comment by tatygrassini** [comment]
+1

**Comment by badabam** [comment]
+1

**Comment by goiwai** [comment]
+1

**Comment by cfc4n** [comment]
+1
```
Package Control

Error executing: /usr/bin/security dump-trust-settings -d

SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
Number of trusted certs = 6
Cert 0: GDB
   Number of trust settings : 12
   Trust Setting 0:
      Policy OID            : SSL
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 1:
      Policy OID            : SSL
      Allowed Error         : Host name mismatch
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 2:
      Policy OID            : SMIME
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 3:
      Policy OID            : SMIME
      Allowed Error         : S/MIME Email address mismatch
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 4:
      Policy OID            : EAP
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 5:
      Policy OID            : IPSec
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 6:
      Policy OID            : iChat
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 7:
      Policy OID            : PKINIT Client
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 8:
      Policy OID            : PKINIT Server
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 9:
      Policy OID            : Code Signing
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 10:
      Policy OID            : Unknown OID length 9, value { 2A 86 48 86 F7 63 64 01 14  }
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
   Trust Setting 11:
      Policy OID            : Apple X509 Basic
      Allowed Error         : CSSMERR_TP_CERT_EXPIRED
      Result Type           : kSecTrustSettingsResultTrustRoot
Cert 1: Equifax Secure Certificate Authority
Cert 2: GTE CyberTrust Global Root
Cert 3: Thawte Premium Server CA
Cert 4: Thawte Server CA
Cert 5: Class 3 Public Primary Certification Authority

VCS-based packages can be ignored with the "ignore_vcs_packages" setting.
```

**Comment by marcjohlic** [comment]
+1 ST3, El Capitan etc

**Comment by manuelmeurer** [comment]
Seriously, guys, please stop it with the +1s! It gets really annoying for people like me who subscribed to updates from this ticket... @wbond already responded that he is working on this! :smile:

**Comment by wbond** [comment]
Here is the current work to be done: https://github.com/wbond/oscrypto/issues/15

**Comment by wbond** [comment]
be747b94c778cc8d9815746aa3bec1ad3eea247f replaces the old trust list export code with new code from oscrypto. There will be a new release in the near future that includes this.
