### ISSUE TITLE
ST3 Palette menu not showing Package Control commands

### ISSUE THREAD

**Issue by NickStees** [wbond/package_control#1003]
![st3_package](https://cloud.githubusercontent.com/assets/2799150/10120658/dd6abe8c-6494-11e5-9e98-773a3901fc39.jpg)

Tried looking around the forms, but could not find a solution. Tried uninstalling/reinstalling ST3. Tried deleting "/installed packages/Package Control.sublime-package" and reinstalling. 

When pasting in the "simple" install code into ST3 console nothing seems to happen and I always get a "186789" response in the command line.

**Comment by FichteFoll** [comment]
The numbers are expected, but it should also ask to to restart ST.

Please post a [debug log](https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log).

**Comment by wbond** [comment]
No, ST3 does not ask for a restart. That is a limitation of ST2.

The debug log is what is needed to figure out what is going on.

**Comment by NickStees** [comment]
Thank you both for you help so far. I followed the steps for a debug log but I don't have that menu option. I also checked the ST3 pref's to make sure package manager is not being ignored. 
![st3_debug](https://cloud.githubusercontent.com/assets/2799150/10127389/f058a3a8-656e-11e5-816b-9854d8e743fb.jpg)

**Comment by wbond** [comment]
@NickStees How about the contents of your Sublime Text console? My guess is that Package Control is in the `ignored_packages` list in Preferences > Settings - User.

**Comment by NickStees** [comment]
@wbond THAT WAS IT! Not sure how that got ignored. Thanks for the help. I removed it from my Presences > Setting - User

**Comment by LekisS** [comment]
I had the exact same issue, thanks @wbond. But I never put _Package Control_ in the `ignored packages`, and it worked like a charm until a few days.

Any idea why the `ignored_packages` got updated ?

**Comment by wbond** [comment]
Packages have to be disabled to be upgraded. It is possible an error during an upgrade caused PC to become disabled.
