### ISSUE TITLE
Inspect package-metadata.json before removing orphaned package

### ISSUE THREAD

**Issue by wbond** [wbond/package_control#1005]
It seems more people are extracting packages to alternate names, and PC is cleaning them up as orphans.

Perhaps we should add the name of the package to the package-metadata.json and then only clean it up as an orphaned package if the name matches. If the name does not match, delete the package-metadata.json file and let the user mess around all they want.

**Comment by FichteFoll** [comment]
That should solve this specific issue. I wonder how you determine which `package-metadata.json` needs to be updated initially though and do not do it for those added later. Check if the package name is already in place for Package Control's?

This seems like the perfect issue to ask about the concern I've been having for a while but didn't investigate further:

What does PC do when you extract the whole package's contents into an override package, most notably also `package-metadata.json`?

**Comment by deathaxe** [comment]
> What does PC do when you extract the whole package's contents into an override package

If a whole package is extracted...

1. the originating sublime-package file is augmented in the first place.
2. `remove_package` command would remove both the sublime-package file and extracted package the same way as it would do for unmanaged or partial overrides.
3. the extracted package directory is deleted by package updates.
 
   If a package without .no-sublime-package file is updated and a package-metadata.json exists in an extracted package, PC treats it as conversion from unpacked to packed package.
