### ISSUE TITLE
Install Package not show

### ISSUE THREAD

**Issue by srhnyldz** [wbond/package_control#1009]
hi,
I install Sublime Text 2. I install package control. but not show install package
![package control](https://cloud.githubusercontent.com/assets/1523648/10456070/d107e832-71c7-11e5-9059-49a55aec5f75.png)

**Comment by FichteFoll** [comment]
Please provide a [debug log](https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log).

**Comment by srhnyldz** [comment]
i enable it.
http://paste.ubuntu.com/12773745/

**Comment by FichteFoll** [comment]
This is weird, everything seems to function properly, including the check for updates on startup, but the install command is not in the palette. I'm a bit clueless here, but maybe reinstalling helps: https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling

**Comment by srhnyldz** [comment]
I did what you said. After installation has the following errors

Package Control

Package Control just installed or upgraded the missing Python _ssl module for Linux since Sublime Text does not include it.

Please restart Sublime Text to make SSL available to all packages.

--------

Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

**Comment by wbond** [comment]
If you type "Install" at the prompt, does it show? It may be that there are too many entries for Install to show in the initial list.

**Comment by srhnyldz** [comment]
What should I do?

**Comment by wbond** [comment]
Did you try typing "install" into the command palette?

**Comment by srhnyldz** [comment]
yes. i try typing "install" into the command palette. Bu
![ekran goruntusu_2015-10-13_21-45-21](https://cloud.githubusercontent.com/assets/1523648/10464708/dd3bcf3e-71f3-11e5-8493-10395ab29bed.png)
t not show.

**Comment by wbond** [comment]
What is the result when you type "package i"?

**Comment by srhnyldz** [comment]
![ekran goruntusu_2015-10-13_21-45-21](https://cloud.githubusercontent.com/assets/1523648/10464939/006bf00a-71f5-11e5-8bc0-b8ad4881c56b.png)

**Comment by srhnyldz** [comment]
I've install sublime text 2. I removed it. I install sublime text 3.
now working the package install.

**Comment by wbond** [comment]
For Sublime Text 2 can you try the following?

 1. Delete `Packages/Package Control/`
 2. Delete `Packages/0_package_control_loader/`
 3. Reinstall via https://packagecontrol.io/installation

**Comment by srhnyldz** [comment]
I did try it. It is not for me.
