### ISSUE TITLE
Invisible package

### ISSUE THREAD

**Issue by davidhq** [wbond/package_control#1018]
I'm trying to install https://packagecontrol.io/packages/Sublime%20Bookmarks

but it doesn't show up -

![screen shot 2015-10-23 at 22 13 59](https://cloud.githubusercontent.com/assets/3899/10703903/65a5cb7c-79d3-11e5-8fe8-f701349ab00d.png)

GIF: http://cl.ly/image/2a441g0K3W3j

**Comment by wbond** [comment]
Do you already have it installed? Maybe see if it is disabled?

I can see it in the list.

**Comment by davidhq** [comment]
yes! thank you
