### ISSUE TITLE
Website doesn't show release date on search results

### ISSUE THREAD

**Issue by pcgeek86** [wbond/package_control#1022]
The Package Control website doesn't show the release date of a package on the search results. Since many packages are outdated, it is important to be able to sort the search results by date, to find recently updated packages.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by FichteFoll** [comment]
There is three timestamps available, modified, first seen and last seen. I imagine you are referring to modified here, correct?

Also, I have to say that last modified day does not always point to packages being outdated - some packages "just work" and don't need updates. Take https://packagecontrol.io/packages/Insert%20Nums for example, which was last modified two years ago.

The repo for the website is located at https://github.com/wbond/packagecontrol.io.

**Comment by pcgeek86** [comment]
Hello @FichteFoll, I was referring specifically to the search results page. Here is a screenshot. From a user perspective, it isn't very efficient to click on each search result, to open the detailed view, just to observe the release date.

![screen shot 2015-11-02 at 3 46 11 pm](https://cloud.githubusercontent.com/assets/466713/10897748/e1823896-8178-11e5-8337-5b0bd46947b9.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by FichteFoll** [comment]
I understand that very well. I meant that this is the wrong repository for this issue because there is a dedicated one for the website code.

**Comment by pcgeek86** [comment]
@FichteFoll Oh, sorry about that. I'll look for the repository for the website itself.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by wbond** [comment]
Issues for the website can be posted at https://github.com/wbond/packagecontrol.io/issues.
