### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by onlineth** [wbond/package_control#1023]
It looks like the actual website is down,
![Website Down](http://s8.postimg.org/cldllhmpx/2015_11_01_12_43_43_Start.png)

http://downforeveryoneorjustme.com/packagecontrol.io/installation

**Comment by hemendra619** [comment]
And I was looking of the there is some proxy or firewall blocked it. So dump.

**Comment by wbond** [comment]
The site is hosted at Linode in Atlanta http://status.linode.com

**Comment by wbond** [comment]
Came back online recently

**Comment by jakebian** [comment]
Looks like site is down again due to another Lincode incident
