### ISSUE TITLE
i can't install package for Sublime Text 3

### ISSUE THREAD

**Issue by marginyu** [wbond/package_control#1029]
console information:

Package Control: Fetching list of available packages
  Platform: windows-x32
  Sublime Text Version: 3083
  Package Control Version: 2.0.0
Package Control: Download Debug
  URL: https://sublime.wbond.net/channel.json
  Resolved IP: 50.116.34.243
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: f42O34HKwvQTRlRAsXiRPvAWUUwbo22p, GT52951423, See www.rapidssl.com/resources/cps (c)15, Domain Control Validated - RapidSSL(R), sublime.wbond.net
    issuer: US, "GeoTrust, Inc.", RapidSSL CA
    common name: sublime.wbond.net
    issue date: Tue, 24 Feb 2015 14:47:53 GMT
    expire date: Tue, 29 Mar 2016 10:42:51 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel.json HTTP/1.1
  If-Modified-Since: Wed, 18 Nov 2015 02:05:03 GMT
  Accept-Encoding: gzip,deflate
  User-Agent: Sublime Package Control v2.0.0
  Host: sublime.wbond.net
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Wed, 18 Nov 2015 02:55:50 GMT
  Last-Modified: Wed, 18 Nov 2015 02:05:03 GMT
  Connection: keep-alive
  ETag: "564bdccf-371"
Package Control: Using cached content for https://sublime.wbond.net/channel.json
error: Package Control

There are no packages available for installation

**Comment by wbond** [comment]
You are using a very old, unsupported version of Package Control.

Follow the directions at https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling to upgrade.

**Comment by marginyu** [comment]
thank you very much
