### ISSUE TITLE
Making Package Control a standard part of Sublime Text

### ISSUE THREAD

**Issue by nathany** [wbond/package_control#1031]
Hi Will,
I'm currently writing a book for new/early programmers and trying to decide which text editor and plugins to recommend for Go development if they don't already have one.

Right now I'm worried that the Package Control [installation](https://packagecontrol.io/installation) might scare people off.

If @jskinner of @sublimehq were willing to include Package Control in https://github.com/sublimehq/Packages and future releases, I'm wondering if this would be feasible and of interest to you?

Obviously I wouldn't want to tie Package Control development to the Sublime Text release cycle, but rather have it continue to update independently.

Thanks,
Nathan.

**Comment by wbond** [comment]
As of [dev build 3121](https://www.sublimetext.com/3dev) we now ship a command (available in the command pallets and menu) to download, verify and install Package Control.

**Comment by nathany** [comment]
Awesome. Thanks Will!

**Comment by FichteFoll** [comment]
It doesn't shot if it's already installed, yes.

**Comment by nathany** [comment]
Now that Build 3124 is generally available, might it make sense to update https://packagecontrol.io/installation -- at least for Sublime Text 3?

**Comment by wbond** [comment]
Probably next week I will. Going to let the beta roll out to some more users.
