### ISSUE TITLE
why <!-- comment --> is ignored and not displayed inside README.md file ?

### ISSUE THREAD

**Issue by ismnoiet** [wbond/package_control#1032]
This is a problem just with [package control](packagecontrol.io/packages/BowerInjector) inside code block
example 
```html
<!-- bower:js -->
<!-- endbower -->
```
otherwise with Github it is not a problem and html comments are displayed properly.
Please can you tell what am i doing wrong or it is just a packagecontrol way of interpreting markdown files

**Comment by FichteFoll** [comment]
https://github.com/wbond/packagecontrol.io uses a different markdown parser than github, because github's is not open source and using it would require lots of API requests.
