### ISSUE TITLE
Installed Package

### ISSUE THREAD

**Issue by ZeyadMounir** [wbond/package_control#1033]
I have already installed a Package for Laravel and It's included in "List Package" option. But I can't use it and I can't find it in Snippets..

**Comment by FichteFoll** [comment]
Check if it's disabled (use *Package Control: Enable Package* command).

**Comment by ZeyadMounir** [comment]
It gives me "There is no disabled packages to enable"!

**Comment by FichteFoll** [comment]
Please post your entire console log then.

**Comment by ZeyadMounir** [comment]
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Zeyad/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Zeyad/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Zeyad/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: []
pre session restore time: 0.140202
startup time: 0.171202
first paint time: 0.171202
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Laravel-5-Artisan-master.Laravel 5 Artisan
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-11-29 18:05:01, next run at 2015-11-29 19:05:01 or after

**Comment by ZeyadMounir** [comment]
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Laravel-5-Artisan-master.Laravel 5 Artisan
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-11-29 18:05:01, next run at 2015-11-29 19:05:01 or after

**Comment by ZeyadMounir** [comment]
Thank you for your concern!)
It doesn't include the mentioned Package, I don't know the reason!
Laravel-5-Snippets!

**Comment by FichteFoll** [comment]
This is not the full console. Do you perhaps have multiple windows in a session? If so, please close them all one by one and paste the console log after restarting ST.

What is the exact name of the package?

Did you try reinstalling?

**Comment by wbond** [comment]
Stale
