### ISSUE TITLE
Can't find local repositories

### ISSUE THREAD

**Issue by daniele-niero** [wbond/package_control#1034]
Hello, 

This is more of a question than an issue report...
Is there any way to add a local repository to Package Control?

in my User preferences I have put:

``` JSON
"repositories":
[
    "C:/Users/daniele.niero/Documents/repos.json"
],
"channels":[] // this to be sure to see only my repos
```

the repos.json file looks like:

``` JSON
{
    "schema_version": "3.0.0",
    "repositories": [
        "file:///path/to_my/repo"
    ]
}
```

the above doesn't seem to work.

Many thanks,
   Dan

**Comment by wbond** [comment]
In the case of a local repo, normally most users just check the repo out into the `Packages/` folder.

I use filesystem paths in some of the repository/channel code for the channel server, but I have never tried using a local `repositories.json` from within Sublime Text. You may be able to accomplish the same sort of thing via adding GitHub/BitBucket URLs as repositories. If the names don't match up, you can use the [`package_name_map`](https://packagecontrol.io/docs/settings#setting-package_name_map).

**Comment by FichteFoll** [comment]
Firstly, your repos.json file looks like channel rather than a repository. 

Other than that I can say that you can certainly point to local repository files in the settings, but I don't know about includes in that file. I also don't know about channels. 

What I attempted in the past but didn't get to work was specifying a file path to a local file in a package's URL.

**Comment by daniele-niero** [comment]
Hi wbond,
I agree that this is a sort of weird case but I'm trying to share packaged tools in an internal network with some collegues. there isn't any mercurial, git or any other server running we just access repositories directly through file://.
We could certainly clone every package we did in the packages folder and don't use package control at all, but we will lose the automatic upadate. Plus I was hoping to set a main package with dependencies (both internal and external) so that every sublime user here could have a minimal required setup with a very small effort.

Really I don't need to use a repository.json, any other method that works will be fine to me, I just thought that that was THE method.

**Comment by wbond** [comment]
As @FichteFoll mentioned, you are currently setting up a channel. Channels contains repositories. Repositories contain packages. It kind of sounds like you want to set up a repository, which you can find more info about at https://github.com/wbond/package_control/blob/master/example-repository.json.

At this point you are exploring uncharted territory! :-) I've never dealt with this kind of a situation before, so Package Control currently does not handle it. If you are keen with Python, feel free to dig around. Currently the `PackageManager.list_available_packages()` method gets the list of packages that can be installed:

https://github.com/wbond/package_control/blob/master/package_control/package_manager.py#L490-L542

It uses a `BackgroundDownloader`, which is a thread so as not to block the UI, to grab data via one of the `REPOSITORY_PROVIDERS`:

https://github.com/wbond/package_control/blob/master/package_control/providers/__init__.py#L9-L10

It seems to me that a simple repository provider would need to be implemented that recognized the `file://` scheme.

I can tell you that dependencies probably don't work the way you think they do, based on your comment. They only allow you to require Python modules, not other ST packages.

**Comment by daniele-niero** [comment]
Thanks Will,

I'm quite experienced with python, the problem is finding the time.
I have looked around a little bit and as soon as I have a moment to spare I
will try to implement a new provider.

Thanks for the clarifications.

**Comment by deathaxe** [comment]
Local channels and repositories work fine in Package Control 4.

A todo would be to support representation by URL (`file://`), but normal "C:\folder\repo.json" on Windows or "/folder/repo.json" on Unix work fine.
