### ISSUE TITLE
How to make sure that my plugin is synchronized with the github repo ?

### ISSUE THREAD

**Issue by ismnoiet** [wbond/package_control#1035]
I changed some code in my plugin(github repo),
when i try to install my plugin from the offical registry(meaning the package control menu)
i get the previous version of the plugin without the latest updates,
How to tell package control to pick the recent modifications ?
or i have to create a new release, knowing that i'm just adding and correcting some simple things

**Comment by FichteFoll** [comment]
Push a higher [semantic version](http://semver.org) tag from the commit of your choice (usually lates) to your repo. Package Control will pick up the new version within an hour.

**Comment by ismnoiet** [comment]
If i add a PATCH number, will it be considered ?
