### ISSUE TITLE
Error "The following incompatible dependency was found installed" pops up on Linux for my local package

### ISSUE THREAD

**Issue by GrayFace** [wbond/package_control#1037]
I'm trying out Linux now and when I copied "Packages" and "Installed Packages" folders there I got this error, referring to my theme package. Full message is below. The package is unmanaged, only present in Packages folder of my profile. Sublime loads the theme just fine, only Package Control complains and only on Linux.

Here's the full error message:

Package Control

The following incompatible dependency was found installed:

Theme - GrayFace

This is usually due to syncing packages across different machines in a way that does not check package metadata for compatibility.

Please visit https://packagecontrol.io/docs/syncing for information about how to properly sync configuration and packages across machines.

To restore package functionality, please remove each listed package and reinstall it.

**Comment by FichteFoll** [comment]
Is there a `.package-metadata` or `.dependency-metadata` file in it? If yes, please paste its contents.

**Comment by GrayFace** [comment]
No, there's nothing starting with a dot there. Strangely, Package Control doesn't say anything about an old version of the theme in a folder right next to it.
Here's the theme: https://dl.dropboxusercontent.com/u/44735333/tmp/Theme%20-%20GrayFace.zip
Here's the old version: https://dl.dropboxusercontent.com/u/44735333/tmp/Theme%20-%20Mine.zip

**Comment by wbond** [comment]
@GrayFace The filenames @FichteFoll meant to mention are `package-metadata.json` and `dependency-metadata.json`.

Is it possible you referenced the `Theme - GrayFace` package as a dependency of another package?

**Comment by GrayFace** [comment]
No jsons either. I've learned the lesson well about them :)
No other package depends on it, I didn't tinker with package dependencies.

**Comment by wbond** [comment]
Closing this since in favor of #1116 – that will report to the user what package is causing the issue.
