### ISSUE TITLE
OSError: exception: access violation reading 0x00007530

### ISSUE THREAD

**Issue by wrokred** [wbond/package_control#1042]
Using package control with user setting
[
"remember_open_files": false
]
Creates this error.
OSError: exception: access violation reading 0x00007530

**Comment by FichteFoll** [comment]
Pretty sure this is actually a duplicate of https://github.com/wbond/package_control/issues/1039 and you just didn't include the full traceback, as you always should.

**Comment by wbond** [comment]
Yes, appears to be a duplicate.
