### ISSUE TITLE
packagecontrol.io: search box says no match while there should be some

### ISSUE THREAD

**Issue by Hibou57** [wbond/package_control#1044]
(I'm not sure it's the place to submit a bug in the Package Control web site)

In [packagecontrol.io](https://packagecontrol.io) search box, if I start typing the two letters “AT”, I can see “ATS2 Build System” and “ATS Syntax Highlight”. Surprisingly, if I type the three letters “ATS”, it says no match was found.

The Sublime Text plugin does not suffer from the same issue.

**Comment by FichteFoll** [comment]
The packagecontrol.io has its own repository: https://github.com/wbond/packagecontrol.io

**Comment by Hibou57** [comment]
Thanks. I'm closing this issue and reopening it there.
