### ISSUE TITLE
Package Control Down?

### ISSUE THREAD

**Issue by askl56** [wbond/package_control#1046]
What's happened with Package Control? Has the domain expired?

**Comment by juanpmd** [comment]
I cant acces either the package control in sublime or the web page, @askl56 does the same thing happen to you?

**Comment by askl56** [comment]
Yep. I think it's down.

**Comment by askl56** [comment]
I'm switching to Atom for the time being.

**Comment by FichteFoll** [comment]
I suggest checking out existing issues before opening your own. Hint: #1045

**Comment by Robot5** [comment]
me too, from china!
Should be Package Control down!
