### ISSUE TITLE
Can't use Package Control in Archlinux

### ISSUE THREAD

**Issue by ericramirez** [wbond/package_control#1047]
After typing *Install Package* and pressing *Enter* I get the following message: **There are no available for installation.**

**Comment by victorhaggqvist** [comment]
https://packagecontrol.io/ seems to be down atm, http://isup.me/packagecontrol.io agrees too.

**Comment by ericramirez** [comment]
Thanks @victorhaggqvist

**Comment by ericramirez** [comment]
It's up now, I'm still getting the same message.

**Comment by akgnosis** [comment]
I'm getting the same error and I'm on Arch also. Although, I think https://packagecontrol.io could be suffering intermittent problems atm.

**Comment by ericramirez** [comment]
Yes, I think the same. 

Package Control: Error downloading channel. URL error 101 downloading https://packagecontrol.io/channel_v3.json.

**Comment by wbond** [comment]
At this point, Linode has indicated Atlanta should be back online. I've refreshed the data, so users should see normal Package Control behavior now.

**Comment by ericramirez** [comment]
Still getting: **There are no available for installation.**

:(

**Comment by ericramirez** [comment]
Now is working! :)
