### ISSUE TITLE
Package control cannot be installed correctly. Sublime 3083, Both OSX and Windows 10

### ISSUE THREAD

**Issue by oxygenbilly** [wbond/package_control#1048]
Message below - tried with both Mac and Windows

186789
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading Packages/Package Control/Package Control.sublime-settings
reloading plugin 0_package_control_loader.00-package_control
reloading Packages/User/Package Control.sublime-settings
Package Control: Installing 1 missing dependency
Package Control: The dependency specified, bz2, is not available
Package Control: No updated packages

**Comment by tobiajo** [comment]
I have the same issue. After the installation I get "There are no packages available for installation".

**Comment by dmorrill10** [comment]
Same here, with Windows 10.

**Comment by dargue3** [comment]
Looks like the site where Will is hosting package controller has been getting DDoS'd this weekend. I'd expect normal functionality to pick back up when this blows over. 

https://twitter.com/wbond/status/683059802533195776

**Comment by suvosem** [comment]
Same issue, Win 10.
Contents of:
https://packagecontrol.io/channel_v3.json
seem to be:
{"packages_cache": {}, "repositories": [], "schema_version": "3.0.0", "dependencies_cache": {}}

I am assuming that's why Package Control: Install package yields:
"There are no packages available for installation"

**Comment by Meuss** [comment]
Same issue, Win 7. After the installation I also get "There are no packages available for installation" when trying to install packages.

**Comment by ddahan** [comment]
Same Issue with OS X 10.11.2

```
plugins loaded
reloading plugin 0_package_control_loader.00-package_control
Package Control: Installing 1 missing dependency
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2016-01-03 02:37:38, next run at 2016-01-03 03:37:38 or after
```

**Comment by mcpengelly** [comment]
Same issue on both OSX and Linux Ubuntu

**Comment by heyitsguay** [comment]
Same issue on Ubuntu 15.04 using Sublime Text 3. Key log element seems to be
```
Package Control: The dependency specified, bz2, is not available
```
In addition to which, packagecontrol.io has been down like 66% of the times that I've tried to access it in the past two days. Very frustrating, as a new user of Sublime Text. I've verified that both my python 2.7.9 and python 3.4.3 versions can find and import the bz2 module, if that makes any difference.

**Comment by Meuss** [comment]
temporary fix until DDoS stops: https://source.ind.ie/snippets/11

**Comment by dave-caputo** [comment]
The solution by Meuss works! Thanks! I had wasted all day searching for a fix.

**Comment by wbond** [comment]
At this point, Linode has indicated Atlanta should be back online. I've refreshed the data, so any users with the https://web.archive.org/web/20150905194312/https://packagecontrol.io/channel_v3.json channel should remove it now.
