### ISSUE TITLE
"There are no packages available for installation", All packages on packagecontrol.io say "removed"

### ISSUE THREAD

**Issue by Eptis** [wbond/package_control#1049]
You are probably aware of this, just to have it here for people looking into issues.

<img width="742" alt="screen shot 2016-01-03 at 02 15 16" src="https://cloud.githubusercontent.com/assets/88688/12076878/5418ada0-b1c0-11e5-8077-587d080d6668.png">

<img width="753" alt="screen shot 2016-01-03 at 02 15 25" src="https://cloud.githubusercontent.com/assets/88688/12076879/541a2536-b1c0-11e5-8db1-c3b754d5fe21.png">

<img width="749" alt="screen shot 2016-01-03 at 02 15 59" src="https://cloud.githubusercontent.com/assets/88688/12076877/54161e50-b1c0-11e5-84e3-e0e79e1e06fa.png">

**Comment by Meuss** [comment]
Yeah, he knows.. https://twitter.com/wbond/status/683059802533195776

**Comment by wbond** [comment]
This is a side effect of the crawler being unable to update package info for the past couple of days. It will resolve once the DDoS is mitigated/ends.

**Comment by aral** [comment]
For a temporary workaround, see https://source.ind.ie/snippets/11

**Comment by wbond** [comment]
At this point, Linode has indicated Atlanta should be back online. I've refreshed the data, so any users with the https://web.archive.org/web/20150905194312/https://packagecontrol.io/channel_v3.json channel should remove it now.
