### ISSUE TITLE
Error message: There are no packages available for installation

### ISSUE THREAD

**Issue by Lidofernandez** [wbond/package_control#1052]
I'm getting this error on mac osx:
Package Control: Error submitting usage information. URL error [Errno 65] No route to host downloading https://packagecontrol.io/submit?operation=install&package_control_version=3.1.2&sublime_version=3083&version=3.1.2&package=Package+Control&sublime_platform=osx.
Package Control: Installing 1 missing dependency
Package Control: Error downloading channel. URL error [Errno 65] No route to host downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error [Errno 65] No route to host downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2016-01-03 11:39:09, next run at 2016-01-03 12:39:09 or after
Package Control: Error downloading channel. URL error [Errno 65] No route to host downloading https://packagecontrol.io/channel_v3.json.

somebody can help me please?

**Comment by Merovex** [comment]
I am getting the same error...maybe different cause...

the https://packagecontrol.io/channel_v3.json for me reads:

`{"schema_version": "3.0.0", "packages_cache": {}, "repositories": [], "dependencies_cache": {}}`

**Comment by Merovex** [comment]
Looks like the same as #1051, #1049, etc.

**Comment by seoplay** [comment]
Yup, I have the same issue as @Merovex 

On OS X I go to install a package and I get "There are no packages available for installation".

Nothing shows up in my debug console though which is odd.

When I go to  [https://packagecontrol.io/channel_v3.json](https://packagecontrol.io/channel_v3.json) I get the same json response as @Merovex 

I realise thought that linode and sublime are having ddos issues at the moment so this is probably related?

**Comment by aral** [comment]
See https://source.ind.ie/snippets/11 for a temporary workaround. Please do not open duplicate issues — the devs are aware of the problem (see @Merovex’s post).

**Comment by wbond** [comment]
At this point, Linode has indicated Atlanta should be back online. I've refreshed the data, so any users with the https://web.archive.org/web/20150905194312/https://packagecontrol.io/channel_v3.json channel should remove it now.

**Comment by Merovex** [comment]
Just to comment on @aral's comment, the snippet links to an archive snapshot of the site... should be safe.

@wbond, any chance of cloud-y-ing the repository via CDN, AZN, etc. to avoid again? :-)

And, great product. Thanks for all the attention through the years.

**Comment by wbond** [comment]
@Merovex See #1057 for more info
