### ISSUE TITLE
Package Controler

### ISSUE THREAD

**Issue by AhsanAliKhan** [wbond/package_control#1053]
Hy.... I am having problem in installing packages
Whenever I try to run the Install Package option I get an error message "There are no packages available for installation"

**Comment by TheAwesomeGem** [comment]
I am having the same issue. Probably DDOS related.

**Comment by aral** [comment]
See https://source.ind.ie/snippets/11 for a temporary workaround.

**Comment by AhsanAliKhan** [comment]
Aral Thanx for your answer it is working thank you soo much....

**Comment by wbond** [comment]
@aral Thanks for your help in this.

At this point, Linode has indicated Atlanta should be back online. I've refreshed the data, so any users with the https://web.archive.org/web/20150905194312/https://packagecontrol.io/channel_v3.json channel should remove it now.
