### ISSUE TITLE
Offline cache for package lists

### ISSUE THREAD

**Issue by aral** [wbond/package_control#1054]
To avoid a situation like the one we’re experiencing at the moment, Package Control could cache the last list downloaded from the official channel (or, alternatively, this feature could be expanded to include any specified channel).

(In the meanwhile, here’s a workaround — https://source.ind.ie/snippets/11)

Thoughts, @wbond?

**Comment by FichteFoll** [comment]
https://github.com/wbond/package_control/issues/1045#issuecomment-168352243

https://github.com/wbond/package_control/issues/1024

**Comment by aral** [comment]
Sorry, @FichteFoll, was just telling folks to search first and I didn’t myself :) Thanks for the links, closing.

**Comment by wbond** [comment]
For anyone who sees this issue in the future, please reference #1057 for more info
