### ISSUE TITLE
"There are no packages available for installation" Package Control of Sublime Text 3

### ISSUE THREAD

**Issue by liquidlotus** [wbond/package_control#1056]
I recently received this message when attempting to install a package via Package Control. 

edit* I apologize for not reading the guidelines, I found out how to get the debug log.

**Comment by liquidlotus** [comment]
I apologize for not reading the guidelines, I found the solution.

**Comment by liquidlotus** [comment]
I now added debug to my setting and I get nothing in console. Still have the same issue as well.

**Comment by cfrank** [comment]
There was a DDOS attack against the hosting provider of packagecontrol.io

For the last two days this has been a reoccurring problem. From my understanding it's caused by this outage.

**Comment by liquidlotus** [comment]
So everyones having this issue right now? I noticed for about 5 minutes it started working again. Also wouldn't that mean I shouldn't be able to Package Control: List Packages?

**Comment by dogrizz** [comment]
https://packagecontrol.io/channel_v3.json is empty for some reason?
Also i don't see any packages on the main page.

**Comment by cfrank** [comment]
@liquidlotus Yes everyone is having issues. If there is nothing in the channel.json then the package control can't work

**Comment by liquidlotus** [comment]
alright cool, I was kinda freaking out. I installed 2 packages during the 5 minutes it did work and those plugins refused to work so I figured something was up.

**Comment by wbond** [comment]
Please see #1057
