### ISSUE TITLE
There are no packages available for installation

### ISSUE THREAD

**Issue by mmdeww** [wbond/package_control#1058]
Hi, recently I met with this issue often. My system is OS X 10.11.2 and I'm using sublime text 3 build 3083. I reinstalled ST3 once and I was able to install packages for about 4 times. Then the problem shows again. 
Below are the debug info.
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/liangwang/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/liangwang/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher DHE-RSA-AES128-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
    subject alt name: codexns.com, packagecontrol.io, wbond.net, rc.codexns.io, codexns.io, www.codexns.io
    expire date: Nov 27 23:59:59 2016 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: gzip,deflate
  Connection: Keep-Alive
  Host: packagecontrol.io
  User-Agent: Package Control v3.1.2
  If-Modified-Since: Sun, 03 Jan 2016 21:50:01 GMT
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sun, 03 Jan 2016 22:02:26 GMT
  Content-Type: application/json
  Last-Modified: Sun, 03 Jan 2016 22:00:01 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Caching https://packagecontrol.io/channel_v3.json in /Users/liangwang/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request

Sometimes the debug info only shows:
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
I don't know which part goes wrong.

**Comment by wbond** [comment]
This is related to #1057 and should be fixed for now.
