### ISSUE TITLE
Unable to show package list by chrome And I Can't install by packageControl

### ISSUE THREAD

**Issue by wedojava** [wbond/package_control#1060]
![fireshot capture 1 - package control - the sublime text package manager - https___packagecontrol io_](https://cloud.githubusercontent.com/assets/9837993/12087827/246655e2-b311-11e5-9622-6568c681ad63.png)

![2016-01-04 18-34-31](https://cloud.githubusercontent.com/assets/9837993/12087936/05d80df4-b312-11e5-8df3-f15c31c171c6.png)

**Comment by Reewr** [comment]
There are currently some outage issues ( #1057 ) which may be causing you issues. If you need to install packages through Sublime Text and you're getting the "No packages available for installation" message, have a look at #1059 and the above link to see temporary fixes.

**Comment by wedojava** [comment]
i got it !!!

thank you very much!!!!!!!!!!!!!!!!!!!!!!
