### ISSUE TITLE
ST3: Unable install or remove packages

### ISSUE THREAD

**Issue by jayasimha3000** [wbond/package_control#1062]
Hitting the below exception, when I try to install/remove packages. Following is the backtrace from the ST3 console (running ST3 build 3083, Package Control v3.1.2 on Windows 7).

```
Package Control: Skipping automatic upgrade, last run at 2016-01-07 11:46:20, next run at 2016-01-07 12:46:20 or after
Traceback (most recent call last):
  File "package_control.package_installer in C:\Users\<user>\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 159, in on_done
  File "package_control.package_disabler in C:\Users\<user>\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 105, in disable_packages
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by wbond** [comment]
Can you provide a full debug log, as specified here: https://github.com/wbond/package_control/blob/master/contributing.md

**Comment by jayasimha3000** [comment]
I got it working after a reboot. Closing this, will add more details if I hit it again.

**Comment by FichteFoll** [comment]
Apparently, you can erase the "syntax" setting in a view's settings object. There will still be syntax highlighting though:

```python
>>> view.settings().get("syntax")
'Packages/PythonImproved/PythonImproved.tmLanguage'
>>> view.settings().erase("syntax")
>>> view.settings().get("syntax")
```

I do not think this can happen without plugin interference however.
