### ISSUE TITLE
ignore_vcs_packages

### ISSUE THREAD

**Issue by alecthomas** [wbond/package_control#1068]
I have a package that has some local changes and updates fail with:

![image](https://cloud.githubusercontent.com/assets/41767/12436524/3a832ff2-bf6a-11e5-9b4f-f8a79b26b6d4.png)

It would be really great if this error indiciated *which* package was failing.

**Comment by wbond** [comment]
This should be resolved by 1a9db4a4286530d2ba24045f807c4a67df321137
