### ISSUE TITLE
Add ability to set backup channel

### ISSUE THREAD

**Issue by groteworld** [wbond/package_control#1073]
This may be a question more about how Package Control works, but if Github (or any git repo) went down for an extended period of time, would PC fail to find my channel and mark its repos as missing? If so, I would like to make the feature request of a backup channel repo url. If there isn't already that feature, that is.

Thanks for the amazing platform, SublimeLinter would be nearly nothing without it!

**Comment by wbond** [comment]
Yes, if your package disappear for an extended period of time, they are marked as "removed". If they are missing for a short while, they are marked as "missing".

I'm not sure exactly what you mean by a backup channel repo url? In PC terms, a channel is one thing and repository is another. Are you wishing to provide multiple repository URLs to place in the main channel?

**Comment by groteworld** [comment]
Yeah, so best case scenerio would be to have PC check for `https://raw.githubusercontent.com/SublimeLinter/package_control_channel/master/packages.json` and if it didn't exist, look for `https://gitlab.com/SublimeLinter/package_control_channel/raw/master/packages.json`

not sure best way to facilitate this, but that's the idea at least

**Comment by wbond** [comment]
There would need to be new functionality added to the channel schema, and the providers would need to be updated to handle the situation also.

**Comment by groteworld** [comment]
Question: If another channel was added and one of its projects had the same name as another found project, what would happen?

**Comment by wbond** [comment]
A presume you mean a second repository was added to the channel that contained the same packages as the first repository? In that case I believe that both would always be checked, and the second one would overwrite the first.

When a repository is fetched and package information retrieved, the repository URL is saved in as the "source" of a package in the packagecontrol.io database, and when that source could not be downloaded, the package would be marked as missing. Thus, if you added multiple sources, only the last would be used, and saved as the source, and would be the source checked for failures.

It is possible that upon a subsequent run of the crawler that the first repository would then overwrite the package information and source, however I have not tested such a failure scenario.

In the grand scheme of things, when GitHub goes down, the crawler grinds to a halt and things get funky. Currently there are not enough resources available to support development of improved robustness in the face of various failures (GitHub outage or packagecontrol.io outage).

**Comment by groteworld** [comment]
No problem! Yeah, I agree that if GitHub were to really go down, this project would need bigger fixes than feature requests.

Closing because it's unnecessary.
