### ISSUE TITLE
No Instructions

### ISSUE THREAD

**Issue by jeremykenedy** [wbond/package_control#1077]
Hi there,

It would be super helpful and intuitive if you added the installation instructions. I understand you link to them, however, in instances such as today the website containing the installation instructions is down thus leaving this REPO with no instructions and virtually useless.

Thanks,

Jeremy

**Comment by zerowaitstate** [comment]
The problem is that the packages themselves (or at least, the package list) appear to be hosted from the same address, so you're probably not going to have much luck until that's resolved.

**Comment by FichteFoll** [comment]
Installing packages is really easy: http://docs.sublimetext.info/en/latest/extensibility/packages.html#installing-packages

**Comment by wbond** [comment]
@jeremykenedy Installation instructions are hosted at https://packagecontrol.io/installation. If you can't get there, you can't reasonably use Package Control anyway.

**Comment by jeremykenedy** [comment]
Thank you for the response, the URL was not working about 30 minutes ago, it would just time out.

**Comment by wbond** [comment]
@jeremykenedy Yes, the site was unavailable due to a Linode networking outage.

**Comment by jeremykenedy** [comment]
Ouch, Linode has been under serious attack, I was on Linode but switched to Vultr after the attack on 12/25/2015 that left us in the dark for 5 days.
