### ISSUE TITLE
Can't Load Packages

### ISSUE THREAD

**Issue by IsaiahJTurner** [wbond/package_control#1078]
I'm thinking it has to do with http://isup.me/packagecontrol.io "It's not just you! http://packagecontrol.io looks down from here."?

**Comment by zerowaitstate** [comment]
Yes.  I can confirm.  
"Package Control: Error downloading channel. URL error [Errno 101] Network is unreachable downloading https://packagecontrol.io/channel_v3.json."

**Comment by DiMFail** [comment]
Same problem. Packagecontrol.io doesn't work :(

**Comment by jbreneman** [comment]
packagecontrol.io is down because of a linode outage according to twitter.

**Comment by wbond** [comment]
Yes, https://packagecontrol.io was down due to a Linode networking outage.
