### ISSUE TITLE
Has there been a fix for/to Error executing: /usr/bin/security dump-trust-settings ?

### ISSUE THREAD

**Issue by ashishtibrewal** [wbond/package_control#1079]
This issue started a fair while ago and haven't received an update/notice on how to fix this.

**It was first reported [here](https://github.com/wbond/package_control/issues/1002).**

Your response would be appreciated. Thank you. :)

**Comment by wbond** [comment]
No, not yet. I haven't had much time for Package Control recently, and much of the time I did have went to outage issues.

The (proper) solution is to switch from launching a subprocess to using an API via [oscrypto.trust_list](https://github.com/wbond/oscrypto/blob/master/docs/trust_list.md).

**Comment by tkeriduN** [comment]
@wbond : While you're at it, maybe a good idea would be to make error dialogs come with a slider, so that whenever an error like this one is thrown, it doesn't look like this:
![capture d ecran 2016-02-12 06 19 09](https://cloud.githubusercontent.com/assets/7006826/12999571/10eb00d6-d151-11e5-90a9-f9f1eb2d1e2f.png)

The okay button is outside the screen, there's no quit button in the dialog header, and the only option I have when this error occurs is to actually force quit sublime, and remove package control manually through terminal with: rm -R.

It _might_ deserve a thread of its own, but I'm not sure so I'm posting it here for now.

Best

**Comment by donCarlosOne** [comment]
I get the error, too.  You don't need to click the Ok button to close the popup (or shut down ST).  Just click the popup and hit Enter.

**Comment by ashishtibrewal** [comment]
@tkeriduN - I second @donCarlosOne's comment. Clicking the pop-up window and hitting Enter closes it.

**Comment by FichteFoll** [comment]
@tkeriduN this is controlled by Sublime Text.

**Comment by polyclick** [comment]
@FichteFoll : Length of the message too?

**Comment by FichteFoll** [comment]
Yes and no. The message is provided by PC, but ST or more likely the OS are responsible for the rendering, so they should take care of providing access to the "OK" button.

PC can shorten the message by not including the error message, but then it would have to go to the console.

**Comment by jrnewell** [comment]
I put in a PR to workaround this issue by simply ignoring this error message (https://github.com/wbond/package_control/pull/1081).

If anyone want to use it before it gets approved, just download the master zip of my fork (https://github.com/jrnewell/package_control/archive/master.zip), rename the zip file to ``Package Control.sublime-package`` and move that file to ``~/Library/Application Support/Sublime Text 3/Installed Packages``.  Hope this helps someone...

**Comment by tkeriduN** [comment]
LOL! Never thought of trying enter... Thanks @donCarlosOne

**Comment by gazazello** [comment]
@jrnewell thanks that worked!

**Comment by ccharlton** [comment]
Can't wait to see this bug quashed.

**Comment by zachfeldman** [comment]
This bug is making me finally consider switching to Atom...I know it's outside of Sublime's control/unrelated, but just putting it out there.

**Comment by ashishtibrewal** [comment]
@zachfeldman I've done the same -- moved to Vim instead.

**Comment by ashishtibrewal** [comment]
@zachfeldman I've done the same - moved to Vim instead.

**Comment by wbond** [comment]
@zachfeldman I've spent well over 30 hours working on preparatory work that goes into a proper fix. How about you offer pitching in to help?

The function `extract_from_system()` needs to be augmented to accept a standardized OID to filter trust roots by the purpose for which certificates are trusted. In the case of Package Control, we need to filter by SSL usage, however note that different vendors use different OIDs, which is where we have to translate/standardize. You can find the source for the functions at:

 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/trust_list.py
 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_win/trust_list.py
 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_linux_bsd/trust_list.py

My recent work includes adding extra OID to `asn1crypto.x509.KeyPurposeId` for various purposes, including those for Windows:

 - https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L1531

That list needs to be augmented with the OIDs from https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/trust_list.py#L93-L111, and we need to check and make sure there aren't others that should be supported.

Then these functions need to be tested to ensure that everything works on OS X 10.7 to 10.11, and Windows XP to 10.

Then finally we can move forward with a new release.

**Comment by wbond** [comment]
Here is an issue outlining exactly what needs to happen: https://github.com/wbond/oscrypto/issues/15

**Comment by wbond** [comment]
This should be resolved by be747b94c778cc8d9815746aa3bec1ad3eea247f. There will be some testing on the various platforms and a few other bug fixes before I do a prerelease version, then a regular release.
