### ISSUE TITLE
Package Control is not working in linux

### ISSUE THREAD

**Issue by SarjuHansaliya** [wbond/package_control#1083]
- packagecontrol.io is not being opened in any browser.
- I tried to do `curl https://packagecontrol.io` but below is the output.
```
curl: (7) Failed to connect to packagecontrol.io port 443: Connection timed out
```
- I tried `wget https://packagecontrol.io/channel_v3.json` but no luck.
- Then I tried to install package directly from Sublime using `Install Package` but below is the dialog.
```
There are no packages available for installation.
```
**But**
When I tried to open packagecontrol.io with some proxy site then it is working fine.

So,

I have doubt that there is some problem with my ssl certificates.
So anybody knows or face this type of issue

**Comment by wbond** [comment]
Please provide a debug log.

**Comment by SarjuHansaliya** [comment]
@wbond From where I can get the debug log. Can you guide me in this matter ?
It would be really helpful.

**Comment by wbond** [comment]
The instructions to obtain a debug log can be found at https://github.com/wbond/package_control/blob/master/contributing.md

**Comment by wbond** [comment]
Feel free to open a new issue with a debug log if you are still have trouble with recent versions of ST3.
