### ISSUE TITLE
Install from command gives error -- subl 3

### ISSUE THREAD

**Issue by coscho** [wbond/package_control#1085]
Install from command gives error -- subl 3

IndentationError: unexpected indent 

???

**Comment by wbond** [comment]
You must open Sublime Text and run the install command from the Console window.

**Comment by coscho** [comment]
You can't get an error if you don’t open console and run the command ... (smirk) ... The issue is: 1) when you double click on textarea then copy... gives error ... 2) WHEN select just the text from the start to the end ... works OK ... SO ... I think some html is copied in first scenario.
