### ISSUE TITLE
Package “LineEndings” listed on packagecontrol.io isn’t available for installation

### ISSUE THREAD

**Issue by Kiyos** [wbond/package_control#1086]
The “LineEndings” package is [listed](https://packagecontrol.io/packages/LineEndings) on packagecontrol.io, but it is not available for installation from within Sublime Text. All I can see on the list is some other irrelevant package.

<img src='http://rghost.net/74vqy5SF6/image.png' />

There are no errors or warnings in the console:

```
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3103
  Package Control Version: 3.1.2
```

**Comment by FichteFoll** [comment]
![2016-02-20_13 40 36](https://cloud.githubusercontent.com/assets/931051/13196747/a3a5417a-d7d7-11e5-93fc-4fd2493bff18.png)



You probably have it installed already. Check if it's ignored.

**Comment by Kiyos** [comment]
> You probably have it installed already.

That is true. Sorry for bringing this not-an-issue up :-(.
