### ISSUE TITLE
Refine error message about $LANG/UTF-8?

### ISSUE THREAD

**Issue by jwhendy** [wbond/package_control#1087]
I just ran into the same issue in #532  and got it fixed (eventually) based on the comments there. I think I may have stumbled on a slight twist, however, so I'm opening a new issue. Just to summarize the solutions mentioned in the closed issue:

- add `LANG=en_US.UTF-8` to `/etc/locale.conf` ([comment](https://github.com/wbond/package_control/issues/532#issuecomment-38231276))
- uncomment all lines except `LANG=en_US.UTF-8` in `/etc/locale.conf` ([comment](https://github.com/wbond/package_control/issues/532#issuecomment-44789830))
- explicitly unset `LC_ALL` ([comment](https://github.com/wbond/package_control/issues/532#issuecomment-59430511))

For me, all of the above were already in play. I'm on Arch Arch (x86_64), and for me `LANG` was already set to `en_US.UTF-8` like many of the commenters, and `LC_ALL` was also unset...

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE=C
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES=C
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I think in my unfamiliarity with `/etc/locale.conf`, I'd set some variables to `C` instead of `en_US.UTF-8` at some point:
```
$ cat /etc/locale.conf 
LANG=en_US.UTF-8
LC_CTYPE=C
LC_MESSAGES=C
LC_COLLATE=C
```

When I set `LC_MESSAGES` and `LC_CTYPE` to `en_US.UTF_8` instead of `C`, ST3 didn't complain anymore. I was able to leave `LC_COLLATE` set to `C`, which I prefer for sorting when using `ls`. Rather than post the block again, this change updated the output of `locale` to `en_US.UTF-8` to all variables except `LC_COLLATE`.

Also, jut want to confirm that @benslice 's hint in the comment above was correct: `LC_ALL` overrides `LANG` ([source](http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html)):

> LC_ALL
> This variable determines the values for all locale categories. The value of the LC_ALL environment variable has precedence over any of the other environment variables starting with LC_ (LC_COLLATE, LC_CTYPE, LC_MESSAGES, LC_MONETARY, LC_NUMERIC, LC_TIME) and the LANG environment variable.

**Request**: could you confirm that the error message shown by Package Control is absolutely accurate? In other words, is my experience correct that `LANG` can be set as the error message suggests, but *other* environment variables can cause an issue?

Starting ST3 with `LANG=en_US.UTF-8 sublime_text` did not work for me. I *think* this is because it was related to either `LC_MESSAGES` or `LC_CTYPE`, not `LANG`. Could the two variables mentioned also cause issues?

If so, updating the error message could assist users in finding the source of the issue sooner.

**Comment by wbond** [comment]
I am not expert in this, so I can not confirm that `LANG` is correct.

From what you've said, I searched for `LC_ALL` and `LANG`. http://comments.gmane.org/gmane.comp.internationalization.linux/4820 seems to indicate we should be recommending `LC_ALL=en_US.UTF-8`.

**Comment by jwhendy** [comment]
Thanks for taking a look! I'm not an environment variable expert myself, so I really have no idea what the various effects are (not to mention why at some point I apparently set some to `C` instead of `UTF-8`).

The only concern I have with `LC_ALL` is that I definitely prefer `LC_COLLATE` set to `C` for ordering the results of the `ls` command. The docs for `LC_ALL` (linked in my post above) make it sound like this would dominate `LC_COLLATE` settings.

If you want, I can try various incantations of `LC_MESSAGES`, `LANG` and `LC_CTYPE` to see if I can pin down which one[s] seem to prompt for the message. Here's the code that creates the error (from my searching):

*Package Control.py*
```
def plugin_loaded():
 
# comments snipped #
        try:
            os.path.exists(os.path.join(sublime.packages_path(), u"fran\u00e7ais"))
```

I'm not a `python` expert, but I take it this is seeing if the system can spit out "francais" (with [this](http://www.fileformat.info/info/unicode/char/00E7/index.htm) character as the "c")? I can definitively say that even with `LANG` set to `UTF-8`, it fails.

**Comment by wbond** [comment]
@jwhendy Try launching Sublime Text via:

```bash
LC_ALL=en_US.UTF-8 sublime_text
```

and let me know if you still get the error.

My intention is not to have you change your system to use this locale, but rather to use a `.desktop` file or script to launch Sublime Text with the env var set.

**Comment by jwhendy** [comment]
@wbond Understood. Give me a little to futz with this as it seems that changes don't work unless I reboot. At the moment I have everything but `LC_COLLATE` set to `en_US.UTF-8` so there's no complaints. I'm inclined to think that would work, though (as long as setting the command overrides what a user might have in `/etc/locale.conf`.

**Comment by mikeshultz** [comment]
@jwhendy After 3 years or so, your tip on `LC_CTYPE` and `LC_MESSAGES` have finally let me use Package Control.  Thank you.

**Comment by jwhendy** [comment]
Glad I could help @mikeshultz !

Finally got around to running some more tests... My `/etc/locale.conf` is currently:
```
LANG=en_US.UTF-8
#LC_CTYPE=en_US.UTF-8
#LC_MESSAGES=en_US.UTF-8
LC_COLLATE=C
LC_CTYPE=C
LC_MESSAGES=C
```

This yields the startup error about `LANG`. Then I did the following three tests:

**works**
`LC_CTYPE=en_US.UTF-8 subl3`
`LC_CTYPE=en_US.UTF-8 LANG=C subl3`

**doesn't work**
`LC_MESSAGES=en_US.UTF_8 subl3`

So, I think the key variable is `LC_CTYPE`. That said, it looks like the check you're running for this error is:
`os.path.exists(os.path.join(sublime.packages_path(), u"fran\u00e7ais"))`

I don't know if that test is sufficient to make sure whatever else depends on locale variables works properly. If it is, with `LC_CTYPE` set, it apparently succeeds.

I can run more tests if you'd like, but I think it'd be sufficient to just change the error message to suggest checking the value of `LC_CTYPE` (in addition to `LANG` if you're sure that matters as well).

**Comment by jwhendy** [comment]
For example, what about something like this?
```
diff --git a/Package Control.py b/Package Control.py
index 9add277..6e66817 100644
--- a/Package Control.py        
+++ b/Package Control.py        
@@ -117,11 +117,11 @@ else:
                 unless this is fixed.
 
                 On Linux, please reference your distribution's docs for
-                information on properly setting the LANG environmental variable.
+                information on properly setting the LANG and LC_CTYPE environment variables.
                 As a temporary work-around, you can launch Sublime Text from the
                 terminal with:
 
-                LANG=en_US.UTF-8 sublime_text
+                LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 sublime_text
                 '''
             )
             sublime.error_message(message)
```

If you prefer `LC_ALL`, that's cool. The above just targets the minimal variable set in case others are not `en_US.UTF-8` for a reason. I wanted to avoid `LC_ALL` since the docs indicate it overrides just about everything. I'm no `env` expert, so I really have no idea what the effects of the various settings are!

**Comment by wbond** [comment]
Thanks for all of the digging on this. I updated the help text as suggested with 6243fc699b1756916772b85434ae440519748107.
