### ISSUE TITLE
Package control doesn't see last releases

### ISSUE THREAD

**Issue by equinusocio** [wbond/package_control#1090]
I've made a new release tag of my [Material Theme Appbar](https://github.com/equinusocio/material-theme-appbar/releases/tag/v1.1.0) a day ago and PC doesn't see it. It say `LAST SEEN	5 days ago`

**Comment by FichteFoll** [comment]
See also https://github.com/wbond/package_control_channel/issues/5283

**Comment by markbirbeck** [comment]
I made an update a couple of days ago, and it too, hasn't come through:

https://github.com/markbirbeck/sublime-text-shell-command

**Comment by spgennard** [comment]
Me too the.. any idea what is going on?

ref: https://bitbucket.org/bitlang/sublime_cobol

**Comment by equinusocio** [comment]
Check the @FichteFoll link wbond/package_control_channel#5283.

**Comment by shian48263** [comment]
[mdegoo/sublime-bootstrap4#9](https://github.com/mdegoo/sublime-bootstrap4/issues/9) is facing this problem too.

**Comment by markbirbeck** [comment]
@equinusocio: unfortunately that doesn't tell us what is going on, only that lots of other packages haven't been updated. :(

**Comment by markbirbeck** [comment]
(or rather *no* other packages have been updated...)

**Comment by wbond** [comment]
I just wanted to let you know that there is a bug with the crawler. One of the recently channel changes has caused it to stop functioning. Haven't finished debugging it yet. Sorry for the delay!

**Comment by wbond** [comment]
This is resolved now.

**Comment by markbirbeck** [comment]
Nice work...thanks @wbond!
