### ISSUE TITLE
ImportError: No module named 'package_control' [FIXED]

### ISSUE THREAD

**Issue by kostrovart** [wbond/package_control#1091]
Hello!
I'd read all topics about this issue, but couldn't fix it. It happens when I try to install a new package.

Package Control: Fetching list of available packages
  Platform: linux-x32
  Sublime Text Version: 3103
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Found system CA bundle at /usr/lib/ssl/certs/ca-certificates.crt
Package Control: Curl Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Trying to execute command /usr/bin/curl --connect-timeout 30 -sSL --tlsv1 --dump-header /tmp/tmpx16dlt --user-agent 'Package Control v3.1.2' --header 'If-Modified-Since: Mon, 29 Feb 2016 10:20:07 GMT' --header 'Accept-Encoding: gzip,deflate' --cacert '/home/art/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle' -v https://packagecontrol.io/channel_v3.json
Package Control: Curl HTTP Debug Write
  Hostname was NOT found in DNS cache
    Trying 50.116.33.29...
  Connected to packagecontrol.io (50.116.33.29) port 443 (#0)
  successfully set certificate verify locations:
    CAfile: /home/art/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle
    CApath: /etc/ssl/certs
  SSLv3, TLS handshake, Client hello (1):
  SSLv3, TLS handshake, Server hello (2):
  SSLv3, TLS handshake, CERT (11):
  SSLv3, TLS handshake, Server key exchange (12):
  SSLv3, TLS handshake, Server finished (14):
  SSLv3, TLS handshake, Client key exchange (16):
  SSLv3, TLS change cipher, Client hello (1):
  SSLv3, TLS handshake, Finished (20):
  SSLv3, TLS change cipher, Client hello (1):
  SSLv3, TLS handshake, Finished (20):
  SSL connection using ECDHE-RSA-AES128-GCM-SHA256
  Server certificate:
  	 subject: 1.3.6.1.4.1.311.60.2.1.3=US; 1.3.6.1.4.1.311.60.2.1.2=Massachusetts; businessCategory=Private Organization; serialNumber=471714639; C=US; ST=Massachusetts; L=Newbury; O=Codex Non Sufficit LC; CN=codexns.io
  	 start date: 2015-10-29 00:00:00 GMT
  	 expire date: 2016-11-27 23:59:59 GMT
  	 subjectAltName: packagecontrol.io matched
  	 issuer: C=US; O=GeoTrust Inc.; CN=GeoTrust EV SSL CA - G4
  	 SSL certificate verify ok.
Package Control: Curl HTTP Debug Read
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.1.2
  Host: packagecontrol.io
  Accept: */*
  If-Modified-Since: Mon, 29 Feb 2016 10:20:07 GMT
  Accept-Encoding: gzip,deflate
Package Control: Curl HTTP Debug General
  HTTP/1.1 200 OK
Package Control: Curl HTTP Debug Read
  Server nginx is not blacklisted
Package Control: Curl HTTP Debug General
  Server: nginx
  Date: Mon, 29 Feb 2016 10:40:42 GMT
  Content-Type: application/json
  Last-Modified: Mon, 29 Feb 2016 10:40:07 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Curl HTTP Debug General
  Connection #0 to host packagecontrol.io left intact
Package Control: Caching https://packagecontrol.io/channel_v3.json in /home/art/.config/sublime-text-3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Traceback (most recent call last):
  File "package_control.package_installer in /home/art/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 159, in on_done
  File "package_control.package_disabler in /home/art/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 74, in disable_packages
ImportError: No module named 'package_control'

**Comment by kostrovart** [comment]
Thanks @wbond, his [suggestion](https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling) is helpful! 
But, I just removed "Package Control" from the "ignored_packages" and reload Sublime. And it helped! "Purging and Reinstalling" weren't needed at this time!

**Comment by shohoku3** [comment]
https://www.rrosetta.com/computers-programming/sublime-text-3-importerror-no-module-named-package_control#comment-13388
click it i think it is helpful
