### ISSUE TITLE
ComputerCraft repository unmaintained? Switch to forked version?

### ISSUE THREAD

**Issue by michthom** [wbond/package_control#1095]
The original GravityScore project hasn't had an update in a couple of years, but I recently had a pull request merged by the most recent fork, here: https://github.com/Cyb3rWarri0r8/ComputerCraft-Support

Would it be acceptable to switch to using that as the repo for the ComputerCraft syntax highlighting module?

**Comment by FichteFoll** [comment]
Yes. If the original author is AWOL and does not reply to a mention of a package control channel maintainer (such as myself) within a certain timestamp, we can replace the url reference of a package to a fork that is still maintained.

**Comment by wbond** [comment]
This should be opened at https://github.com/wbond/package_control_channel/issues
