### ISSUE TITLE
2 Dialog boxes pop up whenever I start ST3  (SideBar?)

### ISSUE THREAD

**Issue by RickyS** [wbond/package_control#1096]
I have added the
             "ignore_vcs_packages": true,
as instructed, to the file
      /home/ricky/Dropbox/Apps/SublimeText/Packages/User/Package Control.sublime-settings
but it does not make a difference.

Attached is the text of the dialog boxes:
[packagecontrol.txt]
(https://github.com/wbond/package_control/files/172255/packagecontrol.txt)

And the full contents of the Console:
[PackageControlConsole.txt]
(https://github.com/wbond/package_control/files/172261/PackageControlConsole.txt)

**Comment by wbond** [comment]
Can you execute the following in the console and provide the output?

```python
sublime.load_settings('Package Control.sublime-settings').get('ignore_vcs_packages')
```

**Comment by RickyS** [comment]
>>> sublime.load_settings('Package Control.sublime-settings').get('ignore_vcs_packages')
[]

------------
I seem to have fixed the problem.  And now I get:
>>> sublime.load_settings('Package Control.sublime-settings').get('ignore_vcs_packages')
True
---
I don't know what I did to fix it except move the setting to the first line:
{
	"ignore_vcs_packages": true,
	"auto_upgrade_last_run": null,
	"bootstrapped": true,
	"in_process_packages":
	[
	],
        ...

In any case, thank you very much, this has been bothering me for weeks.
  Ricky
