### ISSUE TITLE
Cannot import ssl

### ISSUE THREAD

**Issue by sindrig** [wbond/package_control#1097]
On Manjaro 15.12, sublime build 3103.

The ssl-linux package does not work as SSLv3 methods have been disabled in the newest openssl release (https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/openssl&id=4b82ed4285c7cb76caf6d75a015c5a7542c625d1).

I filed a technical support on the sublime forum but I'm really unsure on who could be able to fix this (and where this could be fixed): https://forum.sublimetext.com/t/st-3-cannot-import-ssl/18506

Originally I posted an issue on the package GitSavvy's page: https://github.com/divmain/GitSavvy/issues/370

I could not find the ssl-linux package here on GitHub, please let me know if it's located somewhere else and I should maybe be posting there.

**Comment by FichteFoll** [comment]
It's a dependency, not a package, and referenced [here](https://github.com/wbond/package_control_channel/blob/cce02139fdfe526beba7dae92b931cb0ffece998/repository/dependencies.json#L473-L487).

**Comment by sindrig** [comment]
Thanks for the pointer. Seems there's already an issue posted there (https://github.com/codexns/sublime-ssl-linux/issues/4). Since this issue has is not directly related to package_control I'm closing this issue.

**Comment by sindrig** [comment]
For anyone wandering in here, this has been resolved in ST3 build 3109
