### ISSUE TITLE
Package Control is missing

### ISSUE THREAD

**Issue by Fatbat** [wbond/package_control#1098]
Sublime Text 3, most recent version on Windows 10. I installed and previously had a great experience using Package Control. However, now I cannot find Package Control under the preferences menu, nor though the usual keys to open it. I tried reinstalling it, but to no avail.

Any ideas on how to fix this?

Thanks.

**Comment by FichteFoll** [comment]
Check if it is in your `ignored_packages` setting in the User Preferences file.

**Comment by Fatbat** [comment]
Sorry, I should have mentioned that I already tried that. The only thing in there is...

"ignored_packages": ["Vintage"]

**Comment by FichteFoll** [comment]
Please post the entire console contents then.

**Comment by Fatbat** [comment]
This is what I have...

DPI scale: 1.5
startup, version: 3109 windows x64 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Brad/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Brad/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Brad/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "Package Control"]
pre session restore time: 0.0855852
startup time: 0.113585
first paint time: 0.114585
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin CSS Color Converter.colorconvert
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin Hex to HSL Color Converter.Hex-to-HSL-color
reloading plugin Hex to HSL Color Converter.RGB-to-HSL-color
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin ScopeHunter.scope_hunter
reloading plugin ScopeHunter.scope_hunter_notify
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Sync View Scroll.syncscroll
reloading plugin Tag.Edit
reloading plugin Tag.Tag
reloading plugin Tag.tag_classes
reloading plugin Tag.tag_close_tag
reloading plugin Tag.tag_close_tag_on_slash
reloading plugin Tag.tag_indent
reloading plugin Tag.tag_insert_as_tag
reloading plugin Tag.tag_lint
reloading plugin Tag.tag_remove
reloading plugin Tag.tag_remove_attributes
plugins loaded
syncScroll starting

I had an error with one package, LiveReload, but I removed it. Unfortunately Package Control still isn't showing up.

**Comment by FichteFoll** [comment]
>ignored_packages: ["Vintage", "Package Control"]

So it seems package control actually is disabled. Did you perhaps look in the wrong settings file? You should be looking into the user preferences, not default.

**Comment by Fatbat** [comment]
Weird, I could have sworn I looked in both places. Thanks for the help!
