### ISSUE TITLE
version OPENSSL_1.0.0 not defined

### ISSUE THREAD

**Issue by ZeTomate** [wbond/package_control#1099]
I've got this error while starting sublime :
"Package Control: Linux SSL: _ssl module import error - /home/zetomate/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0/_ssl.cpython-33m.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
Package Control: Linux SSL: _ssl module import error - **libssl.so.10**: cannot open shared object file: No such file or directory
Package Control: Linux SSL: _ssl module import error - **libssl.so.0.9.8**: cannot open shared object file: No such file or directory"

For information, I'm using : 
- "archlinuxfr/**sublime-text-dev 3.3103-1**"
- OpenSSL> version
      ** OpenSSL 1.0.2g**  1 Mar 2016
and I've got thouse:
.config]$ ls -a sublime-text-3/Packages/ssl-linux/st3_linux_x64/
.  ..  **libssl-0.9.8  libssl-1.0.0  libssl-10**

Thank you for your answers...

**Comment by wbond** [comment]
This is fixed in Sublime Text dev build 3109 and newer by Sublime Text statically linking a version of OpenSSL 1.0.2g.

As it has been fixed upstream, I don't currently plan on shipping new versions of the Linux SSL shim any longer.
