### ISSUE TITLE
No package in package-setting

### ISSUE THREAD

**Issue by EasonWang01** [wbond/package_control#1101]
I have try the ignore option but still.

the eslint tutorial say that setting like pic below
![01](https://cloud.githubusercontent.com/assets/11001914/14065907/9727c040-f46e-11e5-8b7b-6b07a722f195.png)

But mine is
![02](https://cloud.githubusercontent.com/assets/11001914/14065909/9a070244-f46e-11e5-80b3-a04cbff07047.png)

**Comment by wbond** [comment]
Unfortunately, I am not sure what issue you are reporting.

Could you try explaining it again, a slightly different way?

**Comment by EasonWang01** [comment]
Thanks for reply,finally I found that some package will not appear in package control.
