### ISSUE TITLE
Package Control not installed when not root

### ISSUE THREAD

**Issue by khaosdoctor** [wbond/package_control#1102]
When I open Sublime Text 3 as a normal user (without using sudo) on Ubuntu 15, it doesn't show package control as one of the installed packages, it seems I never installed it.

When I try to install manually through the website, it shows me "Permission Denied". I've tried to open the .desktop as `gksu` but then the launcher does not recognize the program.

**Comment by wbond** [comment]
It sounds like you ran Sublime Text as root, so it installed your settings in the root user's folder?

Either way, without a debug log, there isn't much I can do to help. If you are still having trouble, open a new issue and include the debug log.
