### ISSUE TITLE
Installing on Fresh ST3

### ISSUE THREAD

**Issue by hozza** [wbond/package_control#1106]
I always have the same problem when installing Package Control for the first time on a new Sublime Text 3 installation.

When you go to the installation website (https://packagecontrol.io/installation) to get the install code, if you triple click to select the code to copy/pate into Sublime it also includes a space or tab at the beginning of the code, when this is pasted into ST3 it errors, obviously the solution is to remove the extra space/tab at the beginning of the code, but it could stump some new users.

Maybe the website source could be tweaked to remove this space/tab?

**Comment by FichteFoll** [comment]
I tried removing any whitespace after the `<code>` tag and before the first non-whitespace character, but FireFox was still copying a space using the select method you suggested.

Anyway, the homepage has its own repository: https://github.com/wbond/packagecontrol.io/issues.

**Comment by wbond** [comment]
Closing this in favor of: https://github.com/wbond/packagecontrol.io/issues/71
