### ISSUE TITLE
Possible to ship the install code for package_control as a default command in Tools > Command Palette?

### ISSUE THREAD

**Issue by kevinSuttle** [wbond/package_control#1107]
Or better yet, just ship package control with Sublime? 

Genuinely curious what that would entail or if it's even possible.

**Comment by wbond** [comment]
This is something I will likely discuss with Jon at some point.

As of the next beta, the install code should be simplified since all platforms will have SSL support built in.

Additionally at some point I will likely drop ST2 support to simplify the codebase.

**Comment by wbond** [comment]
As of [dev build 3121](https://www.sublimetext.com/3dev) we now ship a command (command palette and menu item) that downloads, verifies and installs Package Control.

**Comment by FichteFoll** [comment]
So, does `sublime_api.verify_pc_signature` just do an RSA signature check against any data using any signature and a public key?

**Comment by wbond** [comment]
It does a secp256r1 ECC sha256 signature check on data using a SubjectPublicKeyInfo DER-encoded public key. It is not meant as a public API, per se, hence no documentation was added for it.

**Comment by FichteFoll** [comment]
Ah, you know, just curious.

**Comment by ihodev** [comment]
@wbond Is there any reason why not install it by default? IMO most users run the command right after fresh install :wink:

**Comment by wbond** [comment]
I think there are two reasons:

 - It makes the support expectations clear - Sublime HQ isn't going to directly support Package Control
 - Rather than trying to add functionality to disable network requests out of the box until first use, those that want it can easily install, and those that don't won't be pulling down 300KB of package info every day that they won't use

These are my current thoughts, but they may change in the future.

**Comment by kevinSuttle** [comment]
Thanks @wbond. However, I'm going to disagree with this one: 

> Sublime HQ isn't going to directly support Package Control

I would be willing to gamble that there are very few installations of Sublime Text that are stock builds without plugins.

**Comment by FichteFoll** [comment]
You can't disagree with it, since it's a fact. Besides providing an easy download button, Sublime Hq does not provide *support* for package control. At least for the time being.
