### ISSUE TITLE
There are no packages available for installation

### ISSUE THREAD

**Issue by Pineapple86** [wbond/package_control#1108]
Hi, when i install package in sublime text 3, i got failed messages as below.
`Package Control
There are no packages available for installation`

My PC is win 10 64-bits. Thanks for any replies.
-------------------------------------------------------------------------------------------
The debug mode shows:
`Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3103
  Package Control Version: 2.0.0
Package Control: Download Debug
  URL: https://sublime.wbond.net/channel.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Mon, 28 Mar 2016 08:00:00 GMT
    expire date: Mon, 28 Nov 2016 07:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel.json HTTP/1.1
  If-Modified-Since: Thu, 14 Apr 2016 09:05:03 GMT
  Accept-Encoding: gzip,deflate
  User-Agent: Sublime Package Control v2.0.0
  Host: sublime.wbond.net
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Thu, 14 Apr 2016 10:03:50 GMT
  Last-Modified: Thu, 14 Apr 2016 09:05:03 GMT
  Connection: keep-alive
  ETag: "570f5d3f-371"
Package Control: Using cached content for https://sublime.wbond.net/channel.json
error: Package Control

There are no packages available for installation
Package Control: WinINet HTTPS Debug General
  Closing connection to sublime.wbond.net on port 443 after 1 request`

**Comment by Pineapple86** [comment]
Well, i fixed this problem.
Just remove the "package control", and reinstall it.

**Comment by wbond** [comment]
You were using an old channel URL in your settings (https://packagecontrol.io/channel.json). The current one is https://packagecontrol.io/channel_v3.json.

**Comment by Pineapple86** [comment]
thanks! 
i got this problem
