### ISSUE TITLE
Mediawiker ssl error after certificate update

### ISSUE THREAD

**Issue by Silberling** [wbond/package_control#1111]
I use letsencrypt certificates for my personal wiki and use Mediawiker to edit it.

After I refreshed the certificate I got

> Connection failed for ('https', 'my.mediawiki.url'): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

I read through possibly causes and found:
[#957](https://github.com/wbond/package_control/issues/957)

which was linked from the mediawiker issues page.

I tried removing the bundles and installed a random package. I understood this would regenerate those files and might fix my issue. But it didn't. The files are still missing. I also tried removing the "bootstrapped": true line in the config. As far as I remember I asked what this line is for in the forum and remember some relationship.

I assume there might be a problem with ssl when a certificate got replaced / updated.

**Comment by wbond** [comment]
What platform are you using?

Can you provide the certificate chain from your site and the Package Control.merged-ca-bundle?

**Comment by Silberling** [comment]
Certificate is from letsencrypt. The old bundle files are gone now, i clean up my desktop regularly :-) But the prolem disppeared after several days. I can't remember if thats the consequence of any action. @work I installed a mod, but the sublime configuration is deployed via git. I havent committed any new settings so i don't thinks thats why my home pcs work again, too.

all PCs are Windows 10 64bit.

**Comment by wbond** [comment]
It sounds like the issue was resolved for you. I am hoping to add some functionality eventually to provide some debugging information for TLS issues.
