### ISSUE TITLE
Package Control  Error executing: /usr/bin/security dump-trust-settings -d

### ISSUE THREAD

**Issue by edarioq** [wbond/package_control#1118]
After installing package control I get this (and whenever I open sublime text 3 as well):

SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
SecTrustSettingsCopyTrustSettings: The specified item could not be found in the keychain.
Number of trusted certs = 6
Cert 0: VeriSign Class 3 Secure Server CA - G3
   Number of trust settings : 1
   Trust Setting 0:
      Result Type           : kSecTrustSettingsResultTrustAsRoot
Cert 1: Equifax Secure Certificate Authority
Cert 2: GTE CyberTrust Global Root
Cert 3: Thawte Premium Server CA
Cert 4: Thawte Server CA
Cert 5: Class 3 Public Primary Certification Authority

VCS-based packages can be ignored with the "ignore_vcs_packages" setting.

**Comment by MattiSG** [comment]
I also got this. Could you explain how you solved it?
