### ISSUE TITLE
Can't reinstall Package Control

### ISSUE THREAD

**Issue by jaylevitt** [wbond/package_control#112]
My ST install got a little hosed and ST would crash at startup, so I started moving packages out of the Packages directory to see which package it was.  In the process, I moved Package Control out - and then back in - but still didn't have any Package Control menu items.

I then reinstalled Package Control and saw TWO copies of the menu items.. so I used Package Control to uninstall Package Control.  Now the menu items were gone; I reinstalled via the cut-and-paste into the Python console, and it doesn't show any errors - but I still get no Package Control menu items.

I do see Package Control in the Packages dir, and in the Installed and Pristine Packages dirs.. how can I fix this?

**Comment by meoso** [comment]
had this issue Apr 2018; had to remove from ignored packages also.
