### ISSUE TITLE
Markdown caches build status images

### ISSUE THREAD

**Issue by niosus** [wbond/package_control#1120]
Hello! It seems that markdown implementation caches the images which means that if the build failed during the generation of markdown preview in the package control, the build status badge will always stay red even though the new build is passing (and the actual image under the link is a green one). For an example see https://packagecontrol.io/packages/EasyClangComplete (as of now)

Note that when clicking on a failing build badge you see that it is actually passing.

This is the how it looks in package control.
![image](https://cloud.githubusercontent.com/assets/1893598/15885285/7a18acdc-2d56-11e6-935b-bbe123ea9e7c.png)

The link to the image is a link to a cached version here: https://packagecontrol.io/readmes/img/1deb0a0e609f82da92819e8fb1f149f885fb50f5.svg which is indeed a red one.

While the [original link](https://camo.githubusercontent.com/53faf75d5cea66ff8d8d60bbfa5c5fae812a7797/68747470733a2f2f7472617669732d63692e6f72672f6e696f7375732f45617379436c616e67436f6d706c6574652e7376673f6272616e63683d6d6173746572) points to a passing image. This link is just a mangled link to an svg for the master branch: https://travis-ci.org/niosus/EasyClangComplete.svg?branch=master

Why not pointing it to the original location? This is annoying because it creates the illusion that the plugin fails the tests even though it doesn't. This hinders new installations.

**Comment by FichteFoll** [comment]
This is an issue for https://github.com/wbond/packagecontrol.io. And yes, this is intentional, because particularly shields.to is usually very slow to respond and load. I don't know how long the caching is done though.

**Comment by niosus** [comment]
Sorry for misplacing this. I will move it there.
