### ISSUE TITLE
Cmd+Shift+P behaves differently on some browsers for search bar on website

### ISSUE THREAD

**Issue by zaynv** [wbond/package_control#1126]
Referring to this:

![screen shot 2016-07-08 at 4 58 52 pm](https://cloud.githubusercontent.com/assets/8627403/16704557/4838df22-452d-11e6-9874-8f41b9bfc30d.png)

It says to press <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> to select the search bar. However, on Firefox this is the shortcut to open a new private browser. Just fyi.

**Comment by FichteFoll** [comment]
https://github.com/wbond/packagecontrol.io/issues/28

**Comment by zaynv** [comment]
Oh sorry, I'll close this.
