### ISSUE TITLE
Debug information

### ISSUE THREAD

**Issue by ssonnenwald** [wbond/package_control#1136]
I have set the "debug": true setting so as to view the debug information in the console window, but I'm not seeing any information being reported for package control.   I have sublime text 3 installed and believe my company is blocking things.   Also what I am seeing is when you bring package control up it doesn't have any packages in the list to install along with not displaying the install packages item.  Why is this happening?  Is something being blocked?  Also what would cause the package control not to display debug information.   And a side not here I do have the "debug": true flag set in the right place I have checked the documentation a couple of times.   Any help would be appreciated.

What I see
![image](https://cloud.githubusercontent.com/assets/4144058/17810444/20278f7c-65eb-11e6-9b7b-080422fb1771.png)

as aposed to

![image](https://cloud.githubusercontent.com/assets/4144058/17810483/60f05ed0-65eb-11e6-8b21-962a740b8277.png)

Console display
DPI scale: 1
startup, version: 3114 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/x/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/x/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/x/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
ignoring deprecated syntax definition: Packages/HTML/HTML.tmLanguage
ignoring deprecated syntax definition: Packages/Rails/HTML (Rails).tmLanguage
Unable to decode Packages/Theme - Default/icons/folder.png
Unable to decode Packages/Theme - Default/icons/spinner7.png
Unable to decode Packages/Theme - Default/icons/spinner6.png
Unable to decode Packages/Theme - Default/icons/spinner5.png
Unable to decode Packages/Theme - Default/icons/spinner4.png
Unable to decode Packages/Theme - Default/icons/spinner3.png
Unable to decode Packages/Theme - Default/icons/spinner2.png
Unable to decode Packages/Theme - Default/icons/spinner1.png
Unable to decode Packages/Theme - Default/icons/spinner.png
Unable to decode Packages/Theme - Default/icons/folder_dup.png
Unable to decode Packages/Theme - Default/panels.png
pre session restore time: 0.530099
warning: mnemonic w not found in menu caption Word Wrap
warning: mnemonic b not found in menu caption Bookmarks
warning: mnemonic r not found in menu caption SublimeREPL
warning: mnemonic r not found in menu caption Ruby
warning: mnemonic p not found in menu caption Python
warning: mnemonic d not found in menu caption Python - PDB current file
warning: mnemonic d not found in menu caption Python - RUN current file
warning: mnemonic p not found in menu caption Python - IPython
warning: mnemonic f not found in menu caption F#
warning: mnemonic d not found in menu caption GDB
warning: mnemonic g not found in menu caption Groovy
warning: mnemonic h not found in menu caption Haskell
warning: mnemonic i not found in menu caption Io
warning: mnemonic l not found in menu caption Lua
warning: mnemonic m not found in menu caption Matlab
warning: mnemonic m not found in menu caption MozRepl
warning: mnemonic n not found in menu caption Node
warning: mnemonic o not found in menu caption Octave
warning: mnemonic p not found in menu caption Perl
warning: mnemonic s not found in menu caption PHP
warning: mnemonic p not found in menu caption PowerShell
warning: mnemonic r not found in menu caption R
warning: mnemonic n not found in menu caption Racket
warning: mnemonic r not found in menu caption Rails
warning: mnemonic b not found in menu caption SBT for opened folder
warning: mnemonic r not found in menu caption Scheme
warning: mnemonic r not found in menu caption Gauche
warning: mnemonic r not found in menu caption Petite Chez Scheme
warning: mnemonic scs not found in menu caption ScriptCS
warning: mnemonic s not found in menu caption Shell
warning: mnemonic p not found in menu caption Project
startup time: 0.561099
first paint time: 0.561099
first paint time: 0.561099
unable to launch plugin_host
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted

Thanks,
    Scott

**Comment by FichteFoll** [comment]
Your problem is that, for some reason, ST is unable to launch the container  process for plugins, which is required for PC and many other packages to work. 

A ST reset could help in this case. https://www.sublimetext.com/docs/3/revert.html

**Comment by ssonnenwald** [comment]
I followed your instruction from the link you provided and it didn't fix the problem.  The console output was the same.  Could it be that virus software or a policy is blocking the plugin_host process from starting?

**Comment by wbond** [comment]
@ssonnenwald Yes, it certainly is possible. Since this is a general Sublime Text question, I would post at https://forum.sublimetext.com/ if you are still having trouble.

**Comment by ssonnenwald** [comment]
After running the repair install on it, I have found that it updated the plugin_host.exe and now things seem to function correctly.  Thanks for the feedback Scott
