### ISSUE TITLE
There are no packages available for installation  win10 32bit

### ISSUE THREAD

**Issue by MoguG** [wbond/package_control#1138]
Package Control: Settings change detected, clearing cache
Package Control: Fetching list of available packages
  Platform: windows-x32
  Sublime Text Version: 3114
  Package Control Version: 2.0.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Mon, 28 Mar 2016 08:00:00 GMT
    expire date: Mon, 28 Nov 2016 07:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-Modified-Since: Wed, 24 Aug 2016 07:40:04 GMT
  Accept-Encoding: gzip,deflate
  User-Agent: Package Control v{1.3.0}
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Wed, 24 Aug 2016 07:45:36 GMT
  Last-Modified: Wed, 24 Aug 2016 07:40:04 GMT
  Connection: keep-alive
  ETag: "57bd4f54-28a7f3"
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json
Package Control: Channel https://packagecontrol.io/channel_v3.json does not appear to be a valid channel file because  the "schema_version" is not a valid number.
error: Package Control

There are no packages available for installation
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request

**Comment by ClericPy** [comment]
me too, check “ping sublime.wbond.net” ， 
https://packagecontrol.io/ and https://sublime.wbond.net/Package%20Control.sublime-package 
failed too.........

**Comment by wbond** [comment]
@MoguG You are using a very, very old version of Package Control. This should guide you through the process of installing a recent version: https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling

**Comment by wbond** [comment]
@ClericPy There was a DDoS affecting Linode a few days ago that explains the issues you were seeing.
