### ISSUE TITLE
Package control does not install manually or through the script in sublime. 

### ISSUE THREAD

**Issue by nojvek** [wbond/package_control#1142]
I'm using Build 3114.

Sublime doesn't seem to recognize the package even though its there in `Installed Packages` folder.

**Comment by FichteFoll** [comment]
Check if it's ignored. If it's not, post the console log.

**Comment by nojvek** [comment]
I uninstalled sublime, deleted it from program files and re-installed it. It worked with package control there after.

I'm going to close this since I didn't copy the old console messages. Was something about files exceeding sanity limit.
