### ISSUE TITLE
Website outage

### ISSUE THREAD

**Issue by shakeelmohamed** [wbond/package_control#1143]
I tried to search for a package (request times out eventually) and going to the website directly (it is down). So, here's a curl request for proof 😃 

```bash
$ curl -v https://packagecontrol.io/
*   Trying 2600:3c02::f03c:91ff:fedf:6883...
*   Trying 50.116.33.29...
* connect to 2600:3c02::f03c:91ff:fedf:6883 port 443 failed: Operation timed out
* connect to 50.116.33.29 port 443 failed: Operation timed out
* Failed to connect to packagecontrol.io port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to packagecontrol.io port 443: Operation timed out
```

**Comment by wbond** [comment]
Linode is undergoing a DDoS. This happens occasionally, and the upsides of Linode vs other providers currently outweighs the inconvenience of very infrequent network issues.

**Comment by Kevin-Prichard** [comment]
What about mirroring packagecontrol.io, would you consider that as an option?

**Comment by Kristinita** [comment]
Alternative channel — <https://raw.githubusercontent.com/Kristinita/Kristinita.github.io/master/technical_texts/channel_v3.json>. I was able to install [new packages](https://twitter.com/packagectrl) for me. Thanks.

**Comment by cheshrkat** [comment]
Still down - Linode are advising some sites might need to contact support for IP migration (_If you are still experiencing connectivity issues or have a Linode in one of the affected ranges, please reach out to our Customer Support Team for assistance in obtaining a new IP address._  https://status.linode.com Sep 4, 07:30 UTC)

**Comment by TheGP** [comment]
> currently outweighs the inconvenience of very infrequent network issues.
So if you not able to quickly fix issues with your hosting, I will never pay for sublime :/

**Comment by wbond** [comment]
@TheGP Just to be clear - this service is provided for free, and is not connected to SublimeHQ in any way. All of the code to run it is open source and you are welcome to fork and run it yourself.

I'm currently on vacation, and it is a holiday weekend here in the US. I won't be working on this on my vacation - my paying work gives me time off, and I'm not going to use that to work on a service I give away for free.

**Comment by idleberg** [comment]
Seems like since DDoS attack, the Updated Packages is no longer updating. I pushed some updates yesterday and they're still not available.

**Comment by wbond** [comment]
For the record, I've done work to determine what "mirroring" packagecontrol.io would take. By this, I mean a redundant hosting setup where one machine outage would be transparent to users. A second machine would be located on a different provider in a different geographic area. Likely it would take around $80-100 more per month and a few weeks of development work, which is the expensive part. At some point I may start a campaign to raise money to fund that, but currently I don't even have time for that.

An alternative would be to just mirror a stale version of the packages list, and let all of the crawling, install metrics and everything else that comprises Package Control fail. This would take less development time (although probably still around a week), mostly focused on doing different things (fallback channel settings, testing of DNS resolution and connections failures for the various downloaders, allowing "soft" HTTP failures for certain requests, using the local HTTP cache, etc).

I'm back from vacation now, so I'll be figuring out why the crawler is having trouble. My guess is that Linode changed their local nameservers and I need to refresh the resolv.conf on the server. I'll update this issue once that is solved.

**Comment by wbond** [comment]
Alright, the crawler is back online. Somehow the Python process literally got stuck and never bailed out. I'll make an update to ensure that the crawler is killed if it is more than the max crawl age old.

**Comment by wbond** [comment]
Ok, I've made the crawler more robust with https://github.com/wbond/packagecontrol.io/commit/29754d05031aa0616cdc03a5ce4aed018a03f211.

Eventually I found that is was `git` on the command line had hung trying to fetch the latest copy of the channel from GitHub.

**Comment by Kristinita** [comment]
@wbond , may be better paid $0 per all time, if write [**similar script**](https://forum.sublimetext.com/t/who-may-edit-webcite-archive-script/24314)? Thanks.
