### ISSUE TITLE
Package control website not working

### ISSUE THREAD

**Issue by mr-woot** [wbond/package_control#1146]
I am unable to open packagecontrol.io

**Comment by wbond** [comment]
Can you provide more details, such as:

 1. what error you receive
 2. what browser you are using
 3. if you are in a country that blocks some websites

**Comment by iiandrade** [comment]
Perhaps the mistake he is receiving is the same as mine, **ERR_CONNECTION_TIMED_OUT**.

I use Google Chrome in Fedora 24 in Brazil.
