### ISSUE TITLE
How can i solve this problem about sublime text that there are no package available for installation?

### ISSUE THREAD

**Issue by hudacse6** [wbond/package_control#1147]
m using windows 10 enterprise . when i install sublime text 3 there are no problem ,but when i copy and paste the this

```
import urllib.request,os,hashlib; h = '2915d1851351e5ee549c20394736b442' + '8bc59f460fa1548d1514676163dafc88'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
```

in last line it occurs that `urllib.error.URLError: <urlopen error [Errno 11003] getaddrinfo failed>`. and if m trying to install package it also tells that there are no package for installation . so what can i do now ?

**Comment by wbond** [comment]
It appears your local DNS is not resolving `packagecontrol.io` for `plugin_host.exe`. Perhaps check if you have security software that is blocking the request?
