### ISSUE TITLE
Permission Denied when installing on ElementaryOS

### ISSUE THREAD

**Issue by flannelJesus** [wbond/package_control#1148]
I was following installation instructions here: https://packagecontrol.io/installation

It wasn't working, the console was telling me [Errno 13] Permission denied: `'~/.config/sublime-text-3/Packages/ssl-linux/dependency-metadata.json'`

I closed sublime text and reopened it from command line with `sudo subl` and then it worked. I think it might be helpful to add that to the instructions.

**Comment by wbond** [comment]
`sudo` should definitely not be required to write to `~/.config/`. It sounds like you have permissions issue.

**Comment by wbond** [comment]
You should check and make sure that `~/.config/sublime-text-3/` and all child directories are writable by your user.
