### ISSUE TITLE
Regression: urllib.parse

### ISSUE THREAD

**Issue by ferhtgoldaraz** [wbond/package_control#1150]
I'm on ElmentaryOS Loki, based on Ubuntu 16.04 x64.

In build 3120, clean install plus Package Control, I can import `urllib` and it contains `parse`.

In build 3121 and 3122, without Package Control (clean install), I can import `urllib` and it contains `parse`. But if I install Package control, `urllib` does no longer contain `parse`. This breaks some packages (at least DoxyDoxygen).

**Comment by wbond** [comment]
I can not reproduce with build 3121 and Package Control 3.2.0-beta2.

**Comment by ferhtgoldaraz** [comment]
I can confirm everything is working with 3.2.0-beta2. Thanks! Closing....
