### ISSUE TITLE
Missing dependency loop

### ISSUE THREAD

**Issue by idleberg** [wbond/package_control#1152]
As of 3122, every time I launch Sublime Text, the same missing dependency is installed. I haven't installed any packages I'd suspect causing this.

```
Package Control: Installing 1 missing dependencies
/Users/jan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/loader.py:197: UserWarning: Duplicate name: '02-bz2.py'
Package Control: Installed missing dependency bz2
```

I would love to provide more useful information. Is there a way to determine which package causes this (other than trial and error?)

Mac OS X 10.11.6 (15G1004)
Sublime Text 3 (3122)

**Comment by wbond** [comment]
This means either the `0_package_control_loader.sublime-package` has somehow become corrupted, or there is an error extracting the bz2 module onto disk.

Could you try running the 3.2.0-beta2 to see if that helps? I've done work recently on trying to resolve issues with dependencies and loaders. https://forum.sublimetext.com/t/package-control-3-2-0-testing/22834

**Comment by idleberg** [comment]
That seems to have fixed it. Doesn't happen on launch or when I manually run “Satisfy Dependencies”.
