### ISSUE TITLE
"Package Control.merged-ca-bundle" should be ignored?

### ISSUE THREAD

**Issue by mshibanami** [wbond/package_control#1153]
I manage settings of Sublime Text 3 by Git.
Should I add `Package Control.merged-ca-bundle` to my .gitignore?

Probably it's true because that file has only certificates.
But I couldn't make sure because [Github's gitignore](https://github.com/github/gitignore/blob/master/Global/SublimeText.gitignore) doesn't have it.

Sorry for my silly question, But I just want to make it clear.

**Comment by wbond** [comment]
Yes, it can be ignored. It is generated on the fly if it does not exist.
