### ISSUE TITLE
Occasional Mac "freezes"

### ISSUE THREAD

**Issue by rhc54** [wbond/package_control#1156]
My apologies - I know there were prior issues filed about this problem, and they appear to be gone (and so I assume the problem was fixed). I still occasionally see Sublime "freeze" on startup due to a Mac trust issue. I assume therefore that I need to update Package Control.

When I attempted to do so before, I wound up deleting all my existing packages. No major problem as I simply reinstalled them. However, the update didn't include the solution to the problem, so no gain.

Would you mind just letting me know if it is time to update, or how I might best track that situation? Also appreciate any guidance on a better method for updating than just remove/reinstall.

Thanks - I really appreciate what you have done with Package Control!

**Comment by wbond** [comment]
I don't know of any freezing issues. There was an issue where a popup would be shown because El Capitan changes the `security` CLI tool to output errors when no trust records existed for certain certificates.

Version 3.2.0 was released yesterday and uses a different method for exporting trust roots. What trouble are you having exactly? Can you provide a debug log?

**Comment by rhc54** [comment]
I'm not sure I can get a debug log, though I can try. What happens is that ST starts up, and then a giant pane appears that declares there is a certificate issue - and ST "freezes". The only way to resolve it is to "force quit" the application.

It doesn't happen every time, and I haven't been able to correlate it to some circumstance. So my ability to report on it will be limited.

Let me update to the latest version and keep an eye on things. Can you point me to the best way to do the update, and how to turn on the debug log? My apologies for ignorance.

**Comment by wbond** [comment]
If you press the 'Enter' key it will dismiss the dialog. Version 3.2.0 uses a different method, so that dialog will no longer be shown.

**Comment by wbond** [comment]
Sorry, to update, run the "Upgrade Package" command from the command palette.

**Comment by rhc54** [comment]
Thanks! Got it. Will reopen if I hit the problem again.

**Comment by wbond** [comment]
You won't hit that issue again since the code was completely changed from starting a command line process to using OS X's Security APIs.

If you do have trouble, open a new issue and be sure to include a debug log. That can help identify where in the process the issue is happening.

**Comment by rhc54** [comment]
Kewl - thanks so much!
