### ISSUE TITLE
Cannot open Controll Package: Install package

### ISSUE THREAD

**Issue by zabojpetr** [wbond/package_control#1159]
Hi,
I use Windows 10 Version 1607 x64 and after start ST3, in console is error

`DPI scale: 1`
`startup, version: 3114 windows x64 channel: stable`
`executable: /C/Program Files/Sublime Text 3/sublime_text.exe`
`working dir: /C/Program Files/Sublime Text 3`
`packages path: /C/Users/Petr/AppData/Roaming/Sublime Text 3/Packages`
`state path: /C/Users/Petr/AppData/Roaming/Sublime Text 3/Local`
`zip path: /C/Program Files/Sublime Text 3/Packages`
`zip path: /C/Users/Petr/AppData/Roaming/Sublime Text 3/Installed Packages`
`ignored_packages: ["Vintage"]`
`pre session restore time: 0.164182`
`startup time: 0.207182`
`first paint time: 0.208182`
`first paint time: 0.209182`
`reloading plugin Default.auto_indent_tag`
`reloading plugin Default.block`
`reloading plugin Default.comment`
`reloading plugin Default.convert_syntax`
`reloading plugin Default.copy_path`
`reloading plugin Default.delete_word`
`reloading plugin Default.detect_indentation`
`reloading plugin Default.duplicate_line`
`reloading plugin Default.echo`
`reloading plugin Default.exec`
`reloading plugin Default.fold`
`reloading plugin Default.font`
`reloading plugin Default.goto_line`
`reloading plugin Default.history_list`
`reloading plugin Default.indentation`
`reloading plugin Default.kill_ring`
`reloading plugin Default.mark`
`reloading plugin Default.new_templates`
`reloading plugin Default.open_context_url`
`reloading plugin Default.open_file_settings`
`reloading plugin Default.open_in_browser`
`reloading plugin Default.pane`
`reloading plugin Default.paragraph`
`reloading plugin Default.paste_from_history`
`reloading plugin Default.profile`
`reloading plugin Default.quick_panel`
`reloading plugin Default.run_syntax_tests`
`reloading plugin Default.save_on_focus_lost`
`reloading plugin Default.scroll`
`reloading plugin Default.set_unsaved_view_name`
`reloading plugin Default.show_scope_name`
`reloading plugin Default.side_bar`
`reloading plugin Default.sort`
`reloading plugin Default.swap_line`
`reloading plugin Default.switch_file`
`reloading plugin Default.symbol`
`reloading plugin Default.transform`
`reloading plugin Default.transpose`
`reloading plugin Default.trim_trailing_white_space`
`reloading plugin CSS.css_completions`
`reloading plugin Diff.diff`
`reloading plugin HTML.encode_html_entities`
`reloading plugin HTML.html_completions`
`reloading plugin 0_package_control_loader.00-package_control`
`reloading plugin Package Control.1_reloader`
`reloading plugin Package Control.2_bootstrap`
`reloading plugin Package Control.Package Control`
`plugins loaded`
`Package Control: Download Debug`
`URL: https://packagecontrol.io/submit?sublime_platform=windows&package=Package+Control&package_control_version=3.2.0&version=3.2.0&sublime_version=3114&operation=install`
`Timeout: 30`
`Resolved IP: 50.116.33.29`
`Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883`
`Exception in thread Thread-2:`
`Traceback (most recent call last):`
`File "./python3.3/threading.py", line 901, in _bootstrap_inner`
`File "package_control.package_cleanup in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 55, in run`
`File "package_control.package_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 1996, in record_usage`
`File "package_control.download_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch`
`File "package_control.downloaders.wininet_downloader in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 338, in download`
`OSError: exception: access violation reading 0x0000024000007530`
` `
`Exception in thread Thread-3:`
`Traceback (most recent call last):`
`  File "./python3.3/threading.py", line 901, in _bootstrap_inner`
`  File "./python3.3/threading.py", line 1142, in run`
`  File "package_control.download_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 124, in close_all_connections`
`  File "package_control.download_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 187, in close`
`  File "package_control.downloaders.wininet_downloader in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 208, in close`
`AttributeError: 'NoneType' object has no attribute 'upper'`

When I try Ctrl+Shift+P -> Controll Package: Install package
show next error and not show list of packages
`Package Control: Fetching list of available packages and dependencies`
`Platform: windows-x64`
`Sublime Text Version: 3114`
`Package Control Version: 3.2.0`
`Package Control: Download Debug`
`URL: https://packagecontrol.io/channel_v3.json`
`Timeout: 30`
`Resolved IP: 50.116.33.29`
`Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883`
`Exception in thread Thread-4:`
`Traceback (most recent call last):`
`File "./python3.3/threading.py", line 901, in _bootstrap_inner`
`File "package_control.commands.install_package_command in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 45, in run`
`File "package_control.package_installer in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in make_package_list`
`File "package_control.package_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 687, in list_available_packages`
`File "package_control.package_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 551, in _list_available`
`File "package_control.package_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 450, in list_repositories`
`File "package_control.providers.channel_provider in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 201, in get_repositories`
`File "package_control.providers.channel_provider in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 87, in fetch`
`File "package_control.download_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch`
`File "package_control.downloaders.wininet_downloader in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 338, in download`
`OSError: exception: access violation reading 0x0000024000007530`
` `
`Exception in thread Thread-5:`
`Traceback (most recent call last):`
`  File "./python3.3/threading.py", line 901, in _bootstrap_inner`
`  File "./python3.3/threading.py", line 1142, in run`
`  File "package_control.download_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 124, in close_all_connections`
`  File "package_control.download_manager in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 187, in close`
`  File "package_control.downloaders.wininet_downloader in C:\Users\Petr\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 208, in close`
`AttributeError: 'NoneType' object has no attribute 'upper'`

**Comment by wbond** [comment]
I'm not sure why some Windows 10 installs get all fussy about functions that work fine everywhere else.

Are you running an antivirus program, or network security program? Does Package Control work if you temporarily disable it?

**Comment by zabojpetr** [comment]
I use ESET Smart Security, but if I disable it, it still doesn't work.
In safe mode works everything fine.

**Comment by Shababsoft** [comment]
@wbond Any progress on this bug? I am not able to install or update a package.

**Comment by wbond** [comment]
No, I can't reproduce the error so I'm not really sure what to do. It may have to be wait until someone has the problem that is comfortable writing and debugging Python.

**Comment by MarkoN95** [comment]
I'm currently experiencing a very similiar issue with the package manager. Im also on Window 10 version 1607 (64-bit). I'm on Sublime Text 2 though. When I type ctrl+shift+p to open up the small console window and start typing "package" I only get the following options:

<img width="412" alt="package_control_broken" src="https://cloud.githubusercontent.com/assets/16439305/18946310/9a6dee26-862e-11e6-8cce-8f91dc10eb90.PNG">

I'm not able to install any packages or browse them etc. All these options are gone.
I first experienced this issue yesterday. I was able to solve it temporarily only after doing the following steps:

1. Uninstall Sublime Text 2 and all it's packages (not just via the system settings but also delete the Sublime Text 2 folder from the /AppData/Roaming Folder)

2. (optional, worked without it) Restart System

3. Reinstall Sublime Text 2 and the [package manager](https://packagecontrol.io/installation)

After those steps the package manager worked agin but this only persisted until I restarted my computer again and then I'm back to square one. Maybe it has something to do with the Windows 10 anniversary update (bothe me and @zabojpetr run version 1607) but that is just pure speculation.

This is the SublimeText log I get after starting the editor:

startup, version: 2221 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Users/Marko/Desktop
packages path: /C/Users/Marko/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/Marko/AppData/Roaming/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 7 files for base name Main.sublime-menu
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\00-package_control.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\01-ssl-windows.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\02-bz2.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\02-select-windows.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\1Self\1self.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\1self.py", line 21
SyntaxError: Non-ASCII character '\xe2' in file .\1self.py on line 21, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\1Self\1selfOpenDashboardCommand.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\2pdf\2pdf.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\2pdf.py", line 65, in <module>
    import rst2pdf.createpdf
  File "C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\rst2pdf-0.93.dev\rst2pdf\createpdf.py", line 45, in <module>
    from opt_imports import psyco
  File "C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\rst2pdf-0.93.dev\rst2pdf\opt_imports.py", line 50, in <module>
    from reportlab.platypus.paragraph import Paragraph
  File "C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\reportlab-2.6\reportlab\platypus\__init__.py", line 10, in <module>
    from reportlab.platypus.paragraph import Paragraph, cleanBlockQuotedText, ParaLines
  File "C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\reportlab-2.6\reportlab\platypus\paragraph.py", line 9, in <module>
    from unicodedata import category
ImportError: 
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Emmet\emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\JSHint\JSHint.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Package Control\1_reloader.py
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Package Control\2_bootstrap.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\2_bootstrap.py", line 22, in <module>
    from package_control.bootstrap import bootstrap_dependency, mark_bootstrapped
  File ".\package_control\bootstrap.py", line 20, in <module>
    from .download_manager import downloader
  File ".\package_control\download_manager.py", line 24, in <module>
    from .downloaders import DOWNLOADERS
  File ".\package_control\downloaders\__init__.py", line 3, in <module>
    from .urllib_downloader import UrlLibDownloader
  File ".\package_control\downloaders\urllib_downloader.py", line 46, in <module>
    from ..ca_certs import get_ca_bundle_path
  File ".\package_control\ca_certs.py", line 7, in <module>
    from .deps.oscrypto import trust_list
  File ".\package_control\deps\oscrypto\trust_list.py", line 11, in <module>
    from ..asn1crypto.x509 import Certificate, TrustedCertificate, CertificateAux
  File ".\package_control\deps\asn1crypto\x509.py", line 18, in <module>
    from encodings import idna  # noqa
  File ".\encodings\idna.py", line 3, in <module>
  File "<string>", line 27, in load_module
  File ".\stringprep.py", line 8, in <module>
ImportError: 
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\Package Control.py", line 95, in <module>
    from package_control.commands import *  # noqa
  File ".\package_control\commands\__init__.py", line 3, in <module>
    from .advanced_install_package_command import AdvancedInstallPackageCommand
  File ".\package_control\commands\advanced_install_package_command.py", line 10, in <module>
    from ..package_manager import PackageManager
  File ".\package_control\package_manager.py", line 34, in <module>
    from .downloaders.background_downloader import BackgroundDownloader
  File ".\package_control\downloaders\__init__.py", line 3, in <module>
    from .urllib_downloader import UrlLibDownloader
  File ".\package_control\downloaders\urllib_downloader.py", line 46, in <module>
    from ..ca_certs import get_ca_bundle_path
  File ".\package_control\ca_certs.py", line 7, in <module>
    from .deps.oscrypto import trust_list
  File ".\package_control\deps\oscrypto\trust_list.py", line 11, in <module>
    from ..asn1crypto.x509 import Certificate, TrustedCertificate, CertificateAux
  File ".\package_control\deps\asn1crypto\x509.py", line 18, in <module>
    from encodings import idna  # noqa
  File ".\encodings\idna.py", line 3, in <module>
  File "<string>", line 27, in load_module
  File ".\stringprep.py", line 8, in <module>
ImportError: 
Reloading plugin C:\Users\Marko\AppData\Roaming\Sublime Text 2\Packages\SublimeOnSaveBuild\SublimeOnSaveBuild.py
plugin init time: 0.322472
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.438673
startup cache, total files: 110 cache hits: 110
startup time: 0.508897 (package setup was not run)
loaded 837 snippets

**Comment by smcgee31** [comment]
I am having the exact same problem and wouldn't you know it... I'm also using the same version of Windows 10... 1607
My Sublime Text log:
DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/solod/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/solod/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/solod/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.363377
startup time: 0.420377
first paint time: 0.421377
first paint time: 0.422377
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin BracketHighlighter.bh_core
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_core in C:\Users\solod\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 16, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_rules in C:\Users\solod\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 7, in <module>
ImportError: cannot import name bre
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_rules in C:\Users\solod\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 7, in <module>
ImportError: cannot import name bre
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.changes
reloading plugin BracketHighlighter.support
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin Emmet.emmet-plugin
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MarkdownPreview in C:\Users\solod\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 14, in <module>
ImportError: No module named 'yaml'
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin Babel.Babel
reloading plugin CodeComplice.CodeComplice
reloading plugin ColorPicker.sublimecp
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin LiveReload.__init__
reloading plugin LiveReload.CoffeescriptPlugin
reloading plugin LiveReload.CommandAPI
reloading plugin LiveReload.CompassPlugin
reloading plugin LiveReload.LESSPlugin
reloading plugin LiveReload.LiveReload
reloading plugin LiveReload.SimpleReloadCallback
reloading plugin LiveReload.SimpleReloadPlugin
reloading plugin LiveReload.SimpleReloadPluginDelay
reloading plugin LiveReload.SimpleWSCallback
reloading plugin LiveStyle.livestyle-plugin
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
thread finalize
number of files to index exceeds sanity limit, bailing out

**Comment by LekoWhite** [comment]
Hi, i've got the exact same problem: I'm working on a windows 10 desktop and nothing show up when using package control: install package (but for example when i run remove package it works perfectly)

I've got this error in the console:
`Exception in thread Thread-6:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 687, in list_available_packages
  File "package_control.package_manager in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 551, in _list_available
  File "package_control.package_manager in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 450, in list_repositories
  File "package_control.providers.channel_provider in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Loucas\Desktop\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 338, in download
OSError: exception: access violation reading 0x0000000000007530`

**Comment by zabojpetr** [comment]
Hi, I try it today again and it seems that everything works OK.
Maybe Microsoft fixed same bugs.

**Comment by smcgee31** [comment]
I've got mine fixed it seems, and I think it was because I had both packages CodeComplice and SublimeCodeIntel installed. When I went back through my packages I read on the ReadMe for CodeComplice that it was a fork of SublimeCodeIntel with changes that he thought worked better... So I thought that maybe those two packages were "crashing" each other or something.

**Comment by dolphin8** [comment]
just use urllib instead of wininet :)

Preferences>Package Settings>Package Control>Settings-User
```
	"downloader_precedence": {
		"linux": ["urllib", "curl", "wget"],
		"osx": ["urllib"],
		"windows": ["urllib"]
	}
```

**Comment by chrisonline** [comment]
Thanks @dolphin8 !
This worked for me.

**Comment by jguerin** [comment]
@dolphin8's workaround fixes the issue.
