### ISSUE TITLE
Self Signed Certificate SSL Trust-Store

### ISSUE THREAD

**Issue by jeeftor** [wbond/package_control#1161]
I'm behind a firewall with self signed certificates.  Things were working recently but our certs expired and things have stopped working.

I'm on OS X.

Could somebody point me to where i need to put a copy of our cert so it can be trusted or let me know if there is an option in the settings to use a custom cert trust store thing?

Thanks

**Comment by jeeftor** [comment]
Ok so it looks like its pulling things from the keychain?
```

def extract_from_system():
    """
    Extracts trusted CA certificates from the OS X trusted root keychain.
    :raises:
        OSError - when an error is returned by the OS crypto library
    :return:
        A list of 3-element tuples:
         - 0: a byte string of a DER-encoded certificate
         - 1: a set of unicode strings that are OIDs of purposes to trust the
              certificate for
         - 2: a set of unicode strings that are OIDs of purposes to reject the
              certificate for
```

So i guess i'll have to check my keychain?

**Comment by wbond** [comment]
You can stick it in the keychain, or put a PEM-formatted version in a file named `Packages/User/Package Control.user-ca-bundle`. This file is merged with the certs from the OS trust store into `Packages/User/Package Control.merged-ca-bundle` and used by the Python `ssl` module.

**Comment by sammcj** [comment]
This is quite annoying, I have many custom certs as I work as a systems engineer, surely there must be a better way to handle this?

**Comment by wbond** [comment]
@sammcj I don't understand your comment. You have custom certs that you don't put it your OS trust store and can't place in a file, but are required to make a connection to the Internet?
