### ISSUE TITLE
Create a dummy package that can re-enable Package Control if ST was restarted during a Package Control update

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#1164]
ST updates happening at roughly the same time as a PC update can end up fatally for inexperienced users because they will respond "yes" to the ST update prompt while a PC update is still in progress, meaning that PC will remain in `ignored_packages` and cannot re-enable itself. 

The only way around this appears to be a temporary plugin in a different package that can take care of re-enabling PC if it ends up being in both `in_progress_packages` and `ignored_packages` on startup.

**Comment by wbond** [comment]
This seems like a good idea, albeit a little messy. Perhaps I will add it to Sublime Text itself.

**Comment by megadr01d** [comment]
@wbond 

Maybe PC itself should be built-in ST.

**Comment by wbond** [comment]
That would prevent me from handling things like #1334. Right now since it is de-coupled I can roll out a new updater to everyone. It it was built-in, users on the stable build would have to install a dev build, and you can only do that if you have a license.

**Comment by wbond** [comment]
Additionally, many users are not keen on having their editor communicate with the internet, so we'd need a way to disable PC, thus meaning something like this would be possible.

**Comment by deathaxe** [comment]
If Package Control is scheduled for update, all other packages are ignored.

Recent upgrades have been pretty reliable and never left Package Control behind in disabled state.

Thus closing as no longer required.
