### ISSUE TITLE
Error executing git config --get branch.XXXX.merge

### ISSUE THREAD

**Issue by joaoe** [wbond/package_control#1167]
I have a local package which is controlled by git. That package's currently checked out branch is not a remote branch, it is just my local branch. As such there are no keys in `git config` for `branch.XXXX` and `git config` fails with exit status 1.

The code that calls `git config` should just silently fail if that `git config` call fails.

```
Error executing: /usr/bin/git config --get branch.XXXX.merge

Working directory: /home/jce/.config/sublime-text-3/Packages/EditorConfig

VCS-based packages can be ignored by changing the "ignore_vcs_packages" setting to true.

Sublime Text will need to be restarted once the setting is changed.
```

**Comment by davebrny** [comment]
im having the same problem. setting "ignore_vcs_packages" to true doesnt seem to be helping
