### ISSUE TITLE
The package control sometimes forget to remove 1 or 2 packages from the ignored list, after installing them

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1168]
### The package control sometimes forget to remove 1 or 2 packages from the ignored list, after installing them

Sometimes everything works ok, other times, 1 or 2 packages end up at the `ignored packages list`, when installing something like 65 missing packages.

My ignored packages list is just this 

```
    "ignored_packages":
    [
        "ApplySyntax",
        "BracketHighlighter",
        "Color Highlighter",
        "DictionaryAutoComplete",
        "SublimeCodeIntel",
        "Vintage",
        "WordHighlight"
    ],
```

Here we may see, it installed the package `DocBlockr` and right after it was kept on the ignored list. Whille the other 63 packges when ok, getting out from the ignored list, at the process end.

```
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin CopyWithLineNumbersReloaded.copy_with_line_numbers
reloading plugin DistractionFreeWindow.distraction_free_window
Package Control: Installed missing package DocBlockr
ignored packages updated to: ["AdvancedNewFile", "Alignment", "All Autocomplete", "ApplySyntax", "Auto Refresh", "AutoFileName", "BracketHighlighter", "C++ Completions", "C++ Snippets", "C++ Starting Kit", "C++11", "Clickable URLs", "Color Highlighter", "ColorHelper", "Column Select", "Compare Side-By-Side", "Copy Filepath With Line Numbers", "Delete Current File", "DictionaryAutoComplete", "DocBlockr", "Emmet", "ExportHtml", "ExtendedTabSwitcher", "File Rename", "FileDiffs", "Find++", "FindKeyConflicts", "FuzzyFileNav", "Gist", "Git", "GitGutter", "GitHub Markdown Snippets", "Google Spell Check", "Highlight Build Errors", "HighlightWords", "Hungry Backspace", "Invert Selection", "Line Endings Unify", "Local History", "Markdown Preview", "MarkdownEditing", "MarkdownLight", "Matlab Completions", "MatlabFilenameAutoComplete", "MaxPane", "PackageDev", "PackageResourceViewer", "Path Translator", "PostScript", "Preferences Editor", "Project Specific Syntax Settings", "Qt Completions for C++", "ScopeAlways", "ScopeHunter", "StickySearch", "sublime-text-2-buildview", "SublimeCodeIntel", "SyncedSideBar", "Trimmer", "Vintage", "Whitespace", "WordHighlight"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin Origami.origami
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

[full installation log.txt](https://github.com/wbond/package_control/files/493030/log.txt)

![image](https://cloud.githubusercontent.com/assets/5332158/18834061/43f44bdc-83ca-11e6-86ac-e0b1f6fc4d33.png)
### How to reproduce the issue

1) Install `Sublime Text` from [https://www.sublimetext.com/3](https://www.sublimetext.com/3)

2) Close your Sublime Text and delete/rename the folder below, if it exists: (the folder `sublime-text-3/` below contain all your current settings)

```
mv -v ~/.config/sublime-text-3/ ~/.config/sublime-text-3_Old/
```

3) While keeping your Sublime Text closed, clone this repository using this command: (Linux Only)

```
git clone --recursive https://github.com/evandrocoan/SublimeTextStudio.git ~/.config/sublime-text-3/Packages
```
- The packages will be automatically installed on the first `Sublime Text` run after the repository clone.
- If you are a Windows/Mac user, just figure out where are your settings folders. (the folder `Sublime Text 3\` below contain all your current settings)

```
~/.config/sublime-text-3/ --> "C:\Users\YOUR_USER_NAME\AppData\Roaming\Sublime Text 3\"
~/.config/sublime-text-3/ --> "~/Library/Application Support/Sublime Text 3"
```

4) Open your Sublime Text and wait several minutes until it install all new packages and restart your Sublime Text.

5) You can open the Console on View -> Console (Ctrl+`) to view the download progress.
### Environment

Sublime Text Build 3126 x86 - Windows 10
Package control version 3.2.1

**Comment by wbond** [comment]
Can you provide a full debug log of the process you outlined for reproducing?

**Comment by evandrocoan** [comment]
I quite do not get what is this. Since from the beginning added this to the main post:

![image](https://cloud.githubusercontent.com/assets/5332158/18874539/83b1814e-8498-11e6-929c-bfa2f2faf384.png)


It is not that? How may I get this ` full debug log of the process`?

**Comment by wbond** [comment]
It is documented at https://github.com/wbond/package_control/issues/new.

**Comment by evandrocoan** [comment]
Sorry, I got that, I am now trying to reproduce it with debug enabled. Why do you think about this new message:
```
If you are running into a bug, please you should really read https://packagecontrol.io/docs/troubleshooting
before submitting an issue here.

Bug reports must include a debug log (the setting "debug": true, on Package Control.sublime-settings). The Troubleshooting page explains how to capture one.
```

**Comment by evandrocoan** [comment]
I cannot get the whole process, the sublime console window, cut it after several line. Do you now how to increase it? I going to search while it.

**Comment by FichteFoll** [comment]
Did you close a window in the current session? When a new window is created, it starts with an empty console. I don't think the console contents in a single window ever get cleared.

**Comment by evandrocoan** [comment]
No, just after 3000 lines outputting they got cut. See this logs:

[Compare Side-By-Side.txt](https://github.com/wbond/package_control/files/496059/Compare.Side-By-Side.txt)
[went_ok1.txt](https://github.com/wbond/package_control/files/496058/went_ok1.txt)

Both of them are cut before 3000 lines.

**Comment by evandrocoan** [comment]
For now I got these two files:

**Comment by evandrocoan** [comment]
Now I understando what is happening. It is not a problem on Package Control, but on Sublime Text. Then, it is already reported over there:
1. https://github.com/SublimeTextIssues/Core/issues/2132 Randomly reverting back the `ignored_packages` setting on batch operations
