### ISSUE TITLE
Package Control not showing up on Preferences menu

### ISSUE THREAD

**Issue by albertonieto** [wbond/package_control#1169]
Hi, weird issue here.

I am currently running Sublime Text 3 Build 3126 on Windows 8.1.

I have Package Control installed (I am guessing so), the package is located under the Sublime Text 3\Installed Packages folder.

However Package Control is not showing up on the Preferences > Package Settings > Package Control menu.

Any ideas?

**Comment by FichteFoll** [comment]
Remove it from the `ignored_packages` setting.

**Comment by albertonieto** [comment]
Hero!!

**Comment by dcondrey** [comment]
Why was this added to the ignored_packages setting?  That's rather frustrating.

**Comment by wbond** [comment]
@dcondrey Apparently there is a bug somewhere. If you can reproduce the issue to provide a debug log, that would help in tracking it down.

**Comment by flmm** [comment]
@FichteFoll Thanks :)

**Comment by pandalowry** [comment]
me this help too. I remove from settings, string PackageControl in section 'ignored_packages'. Thanx!

**Comment by VileTouch** [comment]
this happened with latest update to me as well. unfortunately at the time i didn't think of capturing the debug info (went straight to re-enabling it in user settings file)

however, this might be related (or not)

> [2016-09-29 00:05:23,868 - WARNING  - process] Could not import subprocess32 module, falling back to subprocess module
Unable to extract text from the clipboard, available formats: 
Unable to extract text from the clipboard, available formats: 
Unable to extract text from the clipboard, available formats: 
Unable to extract text from the clipboard, available formats: 
\+ Debug: Invalid language: Plain text. Available: RHTML, HTML, SCSS, Twig, Python, HTML5, Ruby, XML, CSS, Less, Sass, Node.js, JavaScript, Python3, PHP, Perl, TemplateToolkit, XUL, Mason, Smarty, Tcl, Go, XSLT, XBL, Django
Invalid language: Plain text. Available: RHTML, HTML, SCSS, Twig, Python, HTML5, Ruby, XML, CSS, Less, Sass, Node.js, JavaScript, Python3, PHP, Perl, TemplateToolkit, XUL, Mason, Smarty, Tcl, Go, XSLT, XBL, Django
Unable to open /C/Users/redacted/AppData/Roaming/Sublime Text 3/Packages/Default/Preferences.sublime-settings
Unable to open /C/Users/redacted/AppData/Roaming/Sublime Text 3/Packages/User/Plain text.sublime-settings

**Comment by cameronroe** [comment]
This happened to me too. How can I remove it from `ignored_packages` What's the path on that?

**Comment by FichteFoll** [comment]
@cameronroe *Preferences → Settings*

**Comment by cameronroe** [comment]
@FichteFoll Got it thanks.

**Comment by BoleLee** [comment]
Thans for the answer: Remove it from the ignored_packages setting. Open the setting file in Preferences → Settings; by the way, check the Settings-Default as well as the Settings-User file, cause for me, the setting is in the Settings-User file.

**Comment by FichteFoll** [comment]
@BoleLee it will never be in the default file. (Unless someone deliberately violated all package conventions.)
