### ISSUE TITLE
Error Message On Startup

### ISSUE THREAD

**Issue by Drllap** [wbond/package_control#1170]
This message is always printed to the console when I start Sublime Text:

```
plugins loaded
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_cleanup in C:\Users\<user>\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 81, in run
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<user>\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\Package Control.sublime-package'
```

I have tried purging and reinstalling package control but it still appears.
I also tested putting the plugins I have install one by one into ignored_packages, but I was still getting this message when all plugins where ignored except Package Control, but it stops when I ignore Package Control.

Is anyone else getting this? 

I'm running on Windows 10, Sublime build 3126

**Comment by wbond** [comment]
It seems odd that Package Control is trying to clean itself up.

Do you see this error with a fresh copy of Sublime Text? http://www.sublimetext.com/docs/3/revert.html

**Comment by Drllap** [comment]
No, the error doesn't appear with a fresh copy.

But I just noticed that none of the packages I have installed have been updated for a very long time. Wonder if it is related.

**Comment by marwan2** [comment]
Same error with me, till now can't solve it

**Comment by deathaxe** [comment]
Package Control 3.4 adds itself back to list of "installed_packages" to prevent it from trying to delete itself. Should therefore be resolved.
