### ISSUE TITLE
Without access to packagecontrol.io site or wbond.net

### ISSUE THREAD

**Issue by iiandrade** [wbond/package_control#1171]
I've tried several ways to access the site Package Control and wbond, but the most interesting is that this only happens in my network. Anyone have any idea what's going on?

**Comment by raxixor** [comment]
Same issue here. Hoping we get a response soon.

**Comment by wbond** [comment]
I can’t replicate the issue, so I don’t know how to help you. Most likely there is some sort of routing issue.

**Comment by iiandrade** [comment]
After a long time, I decided my problem. Talking a lot with my stubborn internet dealership, they changed some setting on his servers, and the problem was solved.
