### ISSUE TITLE
Command that disable all plugins

### ISSUE THREAD

**Issue by math2001** [wbond/package_control#1172]
Hi

On forums, when people have problem, the cause is often coming from a plugin. So, I thought that a command which disable all the plugin would be quite useful.

I tried to add this to my settings `"ingored_packages" [ ... "*"]`, but sublime crashed. 

Matt

**Comment by keith-hall** [comment]
I think that the quickest way to do this at the moment (without a command), is to open the Package Control settings, copy the contexts of `"installed_packages"` and paste into `"ignored_packages"` in your User settings. Maybe it's simple enough not to need a dedicated command?

**Comment by math2001** [comment]
Hi!

Yes, I guess this is easy enough. But, now that I think about it, **isn't it the kind of thing that you love in sublime text**? Little problem that takes you `30s` to solve, and st gives a solution that takes `2`? (i'm thinking about `open containing folder` right now).

And, for a very beginner, I think it could be good. But, it is indeed not as necessary as I thought it was.

Just a sample to copy/paste:

1. go to `Preferences -> Package Settings -> Package Control -> Settings - User`
2. Copy the list bellow `installed_packages`,
3. Open your settings
4. add/find the key `ignored_package` and set/replace the value with the list you just copied.

Thanks for you answer anyway,
Matt

**Comment by FichteFoll** [comment]
I intend to add functionality like this (and more) to the [Troubleshooting](https://packagecontrol.io/packages/Troubleshooting) package.

**Comment by math2001** [comment]
Hi!

Thanks for mentioning this package, didn't know about it.

That'd be cool to add it. Just had a look to implement it, how do you want to do it? Edit the

**Comment by FichteFoll** [comment]
The other primary feature would be a binary search algorithm for disabling packages and finding That One Package that causes issues for you much faster.

**Comment by math2001** [comment]
So, you want to do a package that

- disable a package
- test
- do it again if there is more packages

How do you want to test? Record a macro for text command could do it, but for others problem, except the user himself, no idea how you could do it.

**Comment by FichteFoll** [comment]
Don't worry, I know very well how I will do it. It's been in my head for years.

**Comment by math2001** [comment]
Ok. how?

**Comment by math2001** [comment]
Just something to take into account ( 😆 )

<http://stackoverflow.com/questions/30856557/sublime-disable-all-packages>

**Comment by Kristinita** [comment]
+1. @FichteFoll , it would be nice, if you add this functionality.

**Comment by deathaxe** [comment]
I guess that's obsolete with ST4's SAFE MODE feature.

**Comment by deathaxe** [comment]
This issue is part of #858
