### ISSUE TITLE
No packages available for installation - invalid certificate

### ISSUE THREAD

**Issue by rsperberg** [wbond/package_control#1173]
This may be a duplicate of #1334

When I click `Install Package,` I get a dialog that says:
"There are no packages available for installation."

I am able to reach https://packagecontrol.io/ in my browser

Here is the debug log:

Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/jcon876/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (306906 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/jcon876/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.

**Comment by FichteFoll** [comment]
Please see https://packagecontrol.io/docs/troubleshooting#There_are_no_packages_available_for_installation.

**Comment by rsperberg** [comment]
I'm unable to find the necessary information from this corporate location, but I solved my immediate problem by taking the laptop to another location, which did not use proxies.
So I'm closing this issue.
