### ISSUE TITLE
Missing `urllib.error` module on Linux installations

### ISSUE THREAD

**Issue by sergeche** [wbond/package_control#1174]
A number of users reported sudden issues with Emmet package installations on Linux: https://github.com/sergeche/emmet-sublime/issues/636

The problem caused by missing [`urllib.error` standard module](https://github.com/sergeche/emmet-sublime/blob/c28d0e834b55209807e9d697f1a129894a1f505c/emmet/pyv8loader.py#L20-L21). I did initial research and it looks like the cause is SSL module loaded specifically for Linux: https://github.com/wbond/package_control/blob/master/2_bootstrap.py#L118

The downloaded package deletes `urllib.*` symbols from modules and I guess it replaces them with SSL version. And this version is missing `errors` submodule which causes error.

Is it possible to include `errors` submodule into bootstrapped SSL version?

**Comment by wbond** [comment]
Thanks for figuring out what was going on. I had looked into it some, but was unable to figure it out.

There isn't really a great solution that I can think of here. I can update the SSL dependency to not clear the `urllib` module from `sys.modules`, however that will only work for newer versions of Package Control. That bootstrapped module is no longer downloaded for with recent versions of ST3 and Package Control, so this would only be a fix for people installed Package Control fresh with an old beta of ST3.

I suppose I could update the dependency version which should prompt older ST3 users to get the updated `loader.py`.

**Comment by wbond** [comment]
Alright, I've pushed up a new version of `ssl-linux` that no longer removes `urllib` from `sys.modules`. It really does seem fraught with peril to mess with modules.

The next release of Package Control will bootstrap that version.

**Comment by sergeche** [comment]
Thanks! Will wait for user response

**Comment by hardillb** [comment]
Is there a way to pull a head build of Package Control to test or do I have to wait for a release?

**Comment by wbond** [comment]
@hardillb Yes, you can use git to clone it to your `Packages/` folder after removing `Package Control.sublime-package` from `Installed Packages/`.

Is there a reason you aren't using one of the two beta builds (3114 and 3126) that no longer require this work-around?

**Comment by hardillb** [comment]
@wbond I am using 3126 and I'm seeing the issue

**Comment by wbond** [comment]
Do you have the `ssl-linux` package installed?

**Comment by wbond** [comment]
Rather, it is a "dependency", but it will be in the `Packages/` folder. If you don't can you post your ST console output from a fresh start so I can see all of the Python being loaded?

**Comment by hardillb** [comment]
No. I did upgrade previous ST 3 version to get to this one. But as a test for the emmet issue I removed and reinstalled PC once. I'll add a console output in a min, just got to finished this check-in

**Comment by hardillb** [comment]
DPI scale: 2
startup, version: 3126 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/hardillb/.config/sublime-text-3/Packages
state path: /home/hardillb/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/hardillb/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.082466
startup time: 0.146847
first paint time: 0.152575
first paint time: 0.228451
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
Package Control: Linux SSL: unloading http module so ssl will be available
Package Control: Linux SSL: unloading urllib module so ssl will be available
reloading plugin Emmet.emmet-plugin
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "emmet-plugin in /home/hardillb/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/hardillb/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/pyv8loader.py", line 20, in <module>
AttributeError: 'module' object has no attribute 'error'
reloading plugin JsFormat.js_formatter
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin OmniMarkupPreviewer.OmniMarkupPreviewer
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin sublime_diagram_plugin.diagram_plugin
plugins loaded
Viewer Setting: Preview
Loading processor class: <class 'sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor'>
Detected '/home/hardillb/.config/sublime-text-3/Packages/sublime_diagram_plugin/diagram/plantuml-8024.jar'
Version Detection:
b'PlantUML version 8024 (Sun May 03 16:05:11 BST 2015)\n(GPL source distribution)\nOpenJDK Runtime Environment\nOpenJDK 64-Bit Server VM\n1.7.0_111-b01\nLinux\n\nThe environment variable GRAPHVIZ_DOT has not been set\nDot executable is /usr/bin/dot\nDot version: dot - graphviz version 2.36.0 (20140111.2315)\nInstallation seems OK. File generation OK\n'
PlantUML Smoke Check:
b'The environment variable GRAPHVIZ_DOT has not been set\nDot executable is /usr/bin/dot\nDot version: dot - graphviz version 2.36.0 (20140111.2315)\nInstallation seems OK. File generation OK\n'
Loaded processor: <sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor object at 0x7f0745522510>
Loading viewer class from configuration: <class 'sublime_diagram_plugin.diagram.preview.PreviewViewer'>
Unable to load configured viewer, falling back to autodetection...
Traceback (most recent call last):
  File "/home/hardillb/.config/sublime-text-3/Packages/sublime_diagram_plugin/diagram/__init__.py", line 58, in setup
    vwr.load()
  File "/home/hardillb/.config/sublime-text-3/Packages/sublime_diagram_plugin/diagram/preview.py", line 9, in load
    raise Exception("Currently only supported on MacOS")
Exception: Currently only supported on MacOS
Trying Viewer Sublime3Viewer
Loading viewer class: <class 'sublime_diagram_plugin.diagram.sublime3.Sublime3Viewer'>
Loaded viewer: <sublime_diagram_plugin.diagram.sublime3.Sublime3Viewer object at 0x7f0745522990>
Processors: [<sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor object at 0x7f0745522510>]
Viewer: <sublime_diagram_plugin.diagram.sublime3.Sublime3Viewer object at 0x7f0745522990>
OmniMarkupPreviewer: [INFO] Bottle v0.11.6 server starting up...
OmniMarkupPreviewer: [INFO] Listening on http://127.0.0.1:51004/
OmniMarkupPreviewer: [INFO] Loaded renderer: TextileRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: AsciiDocRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: OrgRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: PodRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: RstRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: MediaWikiRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: CreoleRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: RDocRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: MarkdownRenderer
Package Control: Skipping automatic upgrade, last run at 2016-10-11 20:13:57, next run at 2016-10-11 21:13:57 or after

**Comment by wbond** [comment]
What version of Package Control do you have installed?

**Comment by hardillb** [comment]
v3.2.1

**Comment by wbond** [comment]
The `ssl-linux` dependency should not be installed for ST3 3126 if you are running PC 3.2.0 or newer.

**Comment by wbond** [comment]
I wonder if another package you have installed is causing this.

If you delete `Packages/ssl-linux/` and restart Sublime Text, it should only reinstall if needed by another package. And that should pull in version 1.0.2 of ssl-linux, which doesn't clobber `sys.modules` and doesn't even apply itself on build 3109 or newer.

**Comment by hardillb** [comment]
I don't have ssl-linux in ~/.config/sublime-text-3/Packages

**Comment by wbond** [comment]
Hmm, very odd. Try nuking `Installed Packages/0_package_control_loader.sublime-package` and restarting Sublime Text.

It seems as though PC should be updated to audit `0_package_control_loader` and wipe any loaders without a corresponding folder.

My plan moving forward it to get rid of this disaster of trying to inject Python modules into `sys.path` and instead have a folder for Python modules built into ST's data folder itself. Then ST can just add that modules folder to `sys.path` before loading any packages and `0_package_control_loader` can just be deleted.

**Comment by hardillb** [comment]
Thanks, removing `Installed Packages/0_package_control_loader.sublime-package` seams to have done the trick.

I can only assume it was a left over from upgrading from earlier ST 3 builds
