### ISSUE TITLE
No packages available for installation and debug issue

### ISSUE THREAD

**Issue by Rhyngoh** [wbond/package_control#1176]
I installed Sublime Text Build 3126 x64 Setup last night but when I was trying to install package control, it says no packages available for installation. 
I've already gone to https://packagecontrol.io/docs/troubleshooting and attempted to fix the package control issue with no results. I've purged and reinstalled the package control via both ways, copying the text into the console and downloading the Package Control.sublime-package file and putting that into the installed packages folder. 
I tried to add a debug log but when I added the line "debug": true into my user settings, it gives me an error: Error trying to parse settings: Unexpected trailing characters in Packages\User\Package Control.sublime-settings:4:1
Here is the code for user settings. I'm very new to coding and am not sure if I did this correctly. I tried both versions but both gave errors. 
{
	"bootstrapped": true
}
{	
	"debug": true
}

and 

{
	"bootstrapped": true
	"debug": true
}

Here is my textlog:
DPI scale: 1.25
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Ryan/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Ryan/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Ryan/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.200079
startup time: 0.247079
first paint time: 0.247079
first paint time: 0.247079
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
error: Error trying to parse settings: Unexpected trailing characters in Packages\User\Package Control.sublime-settings:4:1
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
error: Error trying to parse settings: Unexpected trailing characters in Packages\User\Package Control.sublime-settings:4:1
Unable to fetch update url contents
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Operation timed out (errno 12002) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Unable to download https://packagecontrol.io/channel_v3.json after 3 attempts

**Comment by FichteFoll** [comment]
```
{
"bootstrapped": true, 
"debug": true
}
```

**Comment by Rhyngoh** [comment]
Here is the debug log:

Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at C:\Users\Ryan\AppData\Roaming\Sublime Text 3\Packages\User\oscrypto-ca-bundle.crt (72161 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Downloading https://packagecontrol.io/channel_v3.json timed out, trying again
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Downloading https://packagecontrol.io/channel_v3.json timed out, trying again
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Unable to download https://packagecontrol.io/channel_v3.json after 3 attempts
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

**Comment by Rhyngoh** [comment]
I realize I just had to turn off my firewall to let it install. Closing thread now.
