### ISSUE TITLE
My package appears missing from time to time

### ISSUE THREAD

**Issue by TheClams** [wbond/package_control#1178]
I wrote the package SystemVerilog, and for the last two month I got some report that the package is sometimes not available in packageControl.
When going to the page https://packagecontrol.io/packages/SystemVerilog , I sometime have the "Missing" flag with the message "Package info was unavailable last time crawler ran. Error downloading repository. HTTP error 503 downloading https://api.bitbucket.org/1.0/repositories/Clams/sublimesystemverilog/changesets/1.1.0"
Note that the changeset is not always the same for the 4-5 times I checked on the error. And if go the address, I do not have any issue seeing the file.
I also checked other repository hosted on bitbucket to know if this related to this site, but the few I checked looked fine ... 
The problem can go on for hours or days, and then it's back to normal. Any idea what could cause this and is there anything I can do on my side to fix it ?

**Comment by wbond** [comment]
That's crummy, sorry you've been experiencing that.

Historically BitBucket has had an very unreliable API. A decent number of requests to the API result in 503s. In fact, all of the downloaders have special retry mechanisms to try and counter this.

However, it seems that there may be some other issue going on if it goes on for days. The crawler should inspect each package approximately once an hour. So if there was an issue, it should be resolved in about an hour, unless the BitBucket API continues to have trouble.

**Comment by TheClams** [comment]
Ok thanks, I guess the best way for me is probably to setup a github mirror
then. (I checked again right now and the package still appears missing).

**Comment by TheClams** [comment]
The move to github seems to have fixed the issue.
