### ISSUE TITLE
Package control not pulling the latest release from TypeScript sublime plugin repo

### ISSUE THREAD

**Issue by zhengbli** [wbond/package_control#1179]
The latest released version is 2.0:
https://github.com/Microsoft/TypeScript-Sublime-Plugin/releases/tag/2.0
Which was drafted yesterday.

But the latest available on packagecontrol.io is still 0.1.16:
https://packagecontrol.io/packages/TypeScript

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by zhengbli** [comment]
Thanks for pointing out. I've drafted another release with the correct format to see if it can be fixed.

**Comment by zhengbli** [comment]
It was updated as expected. Thanks @FichteFoll !
