### ISSUE TITLE
Prettifying adds space after ending quote

### ISSUE THREAD

**Issue by ShudhPandit** [wbond/package_control#1181]
In HTML file, prettifying creates **extra gap between class added in tag** and the ending quote, resulting in distorted page on browser.
![capture](https://cloud.githubusercontent.com/assets/8871502/19798020/3d359110-9d0c-11e6-82e5-492ba6cc1efd.PNG)

**Comment by wbond** [comment]
Package Control does not provide pretty-printer/formatting functionality. This is a bug with another package you must have installed via Package Control.
