### ISSUE TITLE
Error downloading channel. URL error [Errno -3]

### ISSUE THREAD

**Issue by mubaris** [wbond/package_control#1182]
I am getting following message.

"Package Control: Error downloading channel. URL error [Errno -3] Temporary failure in name resolution downloading https://packagecontrol.io/channel_v3.json."

**Comment by wbond** [comment]
Sounds like your DNS is broken.

**Comment by mubaris** [comment]
How do I fix it???

**Comment by chshouyu** [comment]
#1187

**Comment by Cliff2016** [comment]
Did you solve the problem? I met the same error too,but i don't know how to solve it.

**Comment by deathaxe** [comment]
I've seen that issue only if debug mode is enabled and many DNS requests are made. It appears windows API gives up at some point.
