### ISSUE TITLE
TypeError: unorderable types: dict() < str()

### ISSUE THREAD

**Issue by eladiomanvia** [wbond/package_control#1186]
Hello i have a problem when i try to use Packages Control, i can't enable any package. When i click in "Enable Package" the console show me  this erro

LOG:

startup, version: 3126 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/eladio/.config/sublime-text-3/Packages
state path: /home/eladio/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/eladio/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.085631
startup time: 0.189528
first paint time: 0.227559
first paint time: 0.297401
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Traceback (most recent call last):
  File "package_control.package_cleanup in /home/eladio/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 320, in <lambda>
  File "package_control.package_cleanup in /home/eladio/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 458, in finish
  File "package_control.settings in /home/eladio/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 72, in save_list_setting
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 797, in run_
    return self.run()
  File "package_control.commands.enable_package_command in /home/eladio/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 19, in run
TypeError: unorderable types: dict() < str()

**Comment by wbond** [comment]
This is fixed by ffe26e7
