### ISSUE TITLE
I found a very good method to solve the "channel error" problem

### ISSUE THREAD

**Issue by chshouyu** [wbond/package_control#1187]
in some case, you may find it is fail to download repositories from `https://packagecontrol.io/channel_v3.json`, maybe the DNS problem, maybe the ssl problem

here is my method:
to be short: place the `channel_v3.json` file on your own site.

1. first, download the `channel_v3.json` file from `https://packagecontrol.io/channel_v3.json`
2. place this file on your site, make it can visit
3. in sublime text, `cmd + shift + p`, find `remove channel`, and remove the default `https://packagecontrol.io/channel_v3.json` channel
4. `cmd + shift + p`, find `add channel`, add your own site url, for example: `http://example.com/channel_v3.json`
5. restart your sublime text

now, everything ok. no matter install new package or upgrade package.

you can keep the `channel_v3.json` update to date manually, or use the crontab

for example:
```
* 8-23/2 * * * wget -q https://packagecontrol.io/channel_v3.json -O /path/to/your/site/channel_v3.json
```
the example above will update the `channel_v3.json` file every 2 hours on 8.am to 23.pm

Hope this can help you.

**Comment by wbond** [comment]
Don't host it over a non-secure connection, unless you are ok with attackers installing random code on your machine.

**Comment by FichteFoll** [comment]
Furthermore, if you can't connect to packagecontrol.io via TLS, chances are high you can't connect to github.com either.
