### ISSUE TITLE
[Feature request] Enable/Disable local plugins

### ISSUE THREAD

**Issue by Kristinita** [wbond/package_control#1190]
### Request

It would be nice, if will be add function enable/disable local plugins, not only Package Control packages. I also don't find other plugin with this function.

### Justification

I have some plugins in my `Data/Packages/Plugins` directory, for example, plugin `show_commands_in_console.py`.

Total 100+ Package Control packages and other plugins installed for me. I have many conflicts between plugins and I need debugging. For Package Control packages I can <kbd>Ctrl+Shift+P</kbd> → `Package Control: Disable Package` → select package and `Package Control: Enable Package`. But for local plugins I can do it, I need remove and insert my plugins manually, it takes a lot of time.

### Extended behavior

<kbd>Ctrl+Shift+P</kbd> → `Package Control: Disable Package` → I select `show_commands_in_console` → `show_commands_in_console` plugin was disabled. Then <kbd>Ctrl+Shift+P</kbd> → `Package Control: Enable Package` → I select `show_commands_in_console` → `show_commands_in_console` plugin was enabled.

Thanks.

**Comment by FichteFoll** [comment]
ST only has functionality to ignore Packages. For `Data/Packages/Plugins/show_commands_in_console.py`, that means you can only ignore the "Plugins" package, which will ignore the entire package with all plugins within (and consequently all commands). Anything beyond that is out of PC's scope.

**Comment by Kristinita** [comment]
@FichteFoll, thank you very much!

But in `User/Package Control.sublime-settings` in `installed_packages` parameter I have not value `Plugins`.

**Comment by FichteFoll** [comment]
Yes, since that only contains packages installed with Package Control.
