### ISSUE TITLE
[Question] BetterBuffer package not installed

### ISSUE THREAD

**Issue by Kristinita** [wbond/package_control#1192]
### Summary

I can not install BufferScroll package. titoBouzout not answered on a [similar question](https://github.com/titoBouzout/BufferScroll/issues/37#issue-186873786), therefore I write issue here.

### Steps to reproduce

<kbd>Ctrl+Shift+P</kbd> → ``Package Control: Add Repository`` → https://github.com/titoBouzout/BufferScroll.git → Enter → <kbd>Ctrl+Shift+P</kbd> → ``Package Control: Install Package`` → I not find BufferScroll in results → I see in console:

```
Package Control: Error downloading repository. HTTP error 404 downloading https://api.github.com/repos/titoBouzout/BufferScroll/commits?per_page=1&sha=master.
```

If in Package Control `"debug": true`, I not see another messages about BufferScroll.

<https://api.github.com/repos/titoBouzout/BufferScroll/commits?per_page=1&sha=master> page:

```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

Thanks.

**Comment by wbond** [comment]
Well, technically you added the `master` branch of that git repo as a PC repository, but it doesn't exist. The repo only has an `st3` branch. I believe if you add a repository using the URL https://github.com/titoBouzout/BufferScroll/tree/st3 you should be good.
