### ISSUE TITLE
sublime text 3 package control not working 

### ISSUE THREAD

**Issue by KheMak** [wbond/package_control#1195]
DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Khema/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Khema/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Khema/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.25565
startup time: 0.33465
first paint time: 0.33465
first paint time: 0.33465
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
>>> import urllib.request,os,hashlib; h = 'df21e130d211cfc94d9b0905775a7c0f' + '1e3d39e33b79698005270310898eea76'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
275309
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading settings Packages/Package Control/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading plugin 0_package_control_loader.00-package_control
Unable to open /C/Users/Khema/AppData/Roaming/Sublime Text 3/Packages/Default/Preferences.sublime-settings
Unable to open /C/Users/Khema/AppData/Roaming/Sublime Text 3/Packages/User/Preferences.sublime-settings

Please  help me !!

**Comment by FichteFoll** [comment]
What is the error?

**Comment by KheMak** [comment]
I tired everything but nothing works T_T It's allaways the same, the installation of package control doesn't works


DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Khema/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Khema/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Khema/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.541056
startup time: 0.619056
first paint time: 0.619056
first paint time: 0.619056
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: No updated packages
>>> import urllib.request,os,hashlib; h = 'df21e130d211cfc94d9b0905775a7c0f' + '1e3d39e33b79698005270310898eea76'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
275309

**Comment by shockerli** [comment]
I have the same problem in Mac, also echo 275309

**Comment by crisefd** [comment]
Same problem with me in Ubuntu 14. The  console and manual installation don't work

**Comment by wbond** [comment]
I see no indication @KheMak that the installation failed. The fact that "Package Control: No updated packages" was printed in the console demonstrates that Package Control, is in fact installed. The number (275309) that was printed after pasting the install code shows that the `Package Control.sublime-package` was written to disk, with a filesize of 275,309 bytes.

@shockerli and @crisefd: Please provide a debug log if you are having trouble with something.

**Comment by crisefd** [comment]
`DPI scale: 1
startup, version: 3126 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/crisefd
packages path: /home/crisefd/.config/sublime-text-3/Packages
state path: /home/crisefd/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/crisefd/.config/sublime-text-3/Installed Packages
ignored_packages: ["Package Control", "Vintage"]
pre session restore time: 2.0831
startup time: 3.14395
first paint time: 3.27139
first paint time: 4.71254
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Pylinter.multiconf
reloading plugin Pylinter.pylinter
reloading plugin SublimePythonIDE.__init__
reloading plugin SublimePythonIDE.pep8
reloading plugin SublimePythonIDE.sublime_python
reloading plugin SublimePythonIDE.sublime_python_colors
reloading plugin SublimePythonIDE.sublime_python_commands
reloading plugin SublimePythonIDE.sublime_python_errors
reloading plugin SublimePythonIDE.sublime_python_linting
reloading plugin SublimePythonIDE.sublime_python_refactorings
plugins loaded
 - PyLinter: Pylint executable found
 - PyLinter: Pylint version (1, 1, 0) found
>>> import urllib.request,os,hashlib; h = 'df21e130d211cfc94d9b0905775a7c0f' + '1e3d39e33b79698005270310898eea76'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
275309`

After pasting the python code for the installation nothing happens.

**Comment by wbond** [comment]
@crisefd That all looks correct. Nothing else is supposed to happen. Now the Install Package command is in the command palette.

**Comment by FichteFoll** [comment]
@crisefd Package Control is being ignored on machine (for some reason). Go to user settings and remove it from the `ignored_packages` list.

> ignored_packages: ["Package Control", "Vintage"]

**Comment by crisefd** [comment]
@FichteFoll You were right my friend, that was problem. It's working fine now

**Comment by akansharaut** [comment]
I am facing same issue while installing package control from console in sublime text. 
Error is-
Unable to open /C/Users/akansha.bhopale/AppData/Roaming/Sublime Text 3/Packages/Default/Preferences.sublime-settings
>>> import urllib.request,os,hashlib; h = 'df21e130d211cfc94d9b0905775a7c0f' + '1e3d39e33b79698005270310898eea76'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
Traceback (most recent call last):
  File "./python3.3/urllib/request.py", line 1248, in do_open
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1103, in _send_request
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 417, in create_connection
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 469, in open
  File "./python3.3/urllib/request.py", line 487, in _open
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 1274, in http_open
  File "./python3.3/urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

and I don't have package control in ignored packages-

 // List any packages to ignore here. When removing entries from this list,
  // a restart may be required if the package contains plugins.
   "ignored_packages": ["Vintage"]

What is the issue? Can anyone help me to get out of this issue?

**Comment by Klemart3D** [comment]
> "Go to user settings and remove it from the `ignored_packages` list."

@FichteFoll  Thanks, can you add your comment to the official installation page ?
https://packagecontrol.io/installation#ST3

(And for users like me having found this issue before the first : https://github.com/wbond/package_control/issues/874)

**Comment by NoEMP33** [comment]
what should in be deleting exaclty? im at the settings screen  with the ignored_packages: ["vintage"]

what am i deleting

**Comment by FichteFoll** [comment]
@NoEMP33 since you don't have Package Control in the ignored packages list, you can't remove it from there either. Your problem is different.

Open a new issue with your entire ST console content.

**Comment by deathaxe** [comment]
As the original error was Package Control being in ignored_packages, I close it as resolved.
