### ISSUE TITLE
Add post_install event

### ISSUE THREAD

**Issue by idleberg** [wbond/package_control#1196]
The current `events.install` does not take installed dependencies into account, so it would be nice to have an event that waits for all dependencies to be installed before it's fired.

> `events.install("Package Name")` - package was just installed

It could be argued that `events.install` should do that (judging by the description), but that's not for me to decide. It be be desirable to differentiate between the two.

**Comment by deathaxe** [comment]
Package Control 4.0 installs all required libraries before a package install/upgrade finishs
