### ISSUE TITLE
[Stats]: how many user are using St2/3

### ISSUE THREAD

**Issue by math2001** [wbond/package_control#1198]
Hello!

Thank you so much for package control, I don't know how I would manage my st packages without it. :+1:

In the [stats](https://packagecontrol.io/stats) page, I've seen that you're able to say if a user is using `window`, `linux`, or `osx`, so I guess you could tell us if they're using `st2` or `st3`. It would be quite helpful to see if it's worth supporting `st2`. Would it be hard to do?

Thank you again,

Matt

**Comment by FichteFoll** [comment]
I also wanted to propose this. It should probably go to https://github.com/wbond/packagecontrol.io, however.

**Comment by math2001** [comment]
Ok. Do you want me to close this issue and reopen it to `packagecontrol.io`?

**Comment by FichteFoll** [comment]
I suggest doing that, yes.

**Comment by math2001** [comment]
Ok
