### ISSUE TITLE
Markdown2Clipboard & Clipboard2Markdown

### ISSUE THREAD

**Issue by hginzel** [wbond/package_control#1199]
Thank you for [Markdown to Clipboard](https://packagecontrol.io/packages/Markdown%20to%20Clipboard).

What about the opposite “Clipboard to Markdown” or “Paste as Markdown” respectively?

Thank you in advance, H.

**Comment by wbond** [comment]
This issue tracker is for Package Control itself. Click on the Issues link on https://packagecontrol.io/packages/Markdown%20to%20Clipboard to find the issue tracker for the package you would like to discuss.
