### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED - how to debug?

### ISSUE THREAD

**Issue by unilynx** [wbond/package_control#1201]
I'm trying to add our repository `https://files.b-lex.com/sublime/repository.json` but keep getting stuck on 

```
Package Control: Error downloading repository. HTTP exception InvalidCertificateException (Host files.b-lex.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://files.b-lex.com/sublime/repository.json.
```

We're using a certbot certificate over SNI hosted by nginx - I first had the name in a long list of altnames but now I've created a separate certificate for just `files.b-lex.com`, but no luck. 

https://www.ssllabs.com/ssltest/analyze.html?d=files.b-lex.com&s=46.101.235.123 appears to be happy with the certificate.

Is there any way to extract more debug information? 

More log lines:
```
Package Control: Download Debug
  URL: https://files.b-lex.com/sublime/repository.json
  Timeout: 30
  Resolved IP: 46.101.147.18
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/arnold/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (275093 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to files.b-lex.com on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/arnold/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading repository. HTTP exception InvalidCertificateException (Host files.b-lex.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://files.b-lex.com/sublime/repository.json.
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
```

**Comment by wbond** [comment]
My guess is that the certificate being used doesn't chain back to a root on your machine.

It may have to do with not serving an intermediate, or the LE root not being in your root repository.

At some point once I have some free time, I'm intending to try and improve the debug output from the cert export to help identifying issues like this.

**Comment by Nicd** [comment]
My guess is that Package Control is not using SNI when sending the request. Due to that sites that host many domains send the certificate for the wrong domain. You can see that if you add https://codestats.net/dev/packages.json you will get certificate for ahlroth.fi (another domain on my system). So it seems PC does not support SNI that is required for multiple domains on the same machine.

**Comment by Nicd** [comment]
Btw requests sent from a plugin using the requests library (installed as PC dependency) work fine with SNI, so maybe the repository adding code uses some other method?

**Comment by wbond** [comment]
Can you check and see if Package Control 3.3.0 fixes this? I think it very likely will.

**Comment by deathaxe** [comment]
Closing a stale
