### ISSUE TITLE
packagecontrol.io is down

### ISSUE THREAD

**Issue by ryan-w-moore** [wbond/package_control#1203]
Just wanted to point out that Packageccontrol.io is down, seems march 7th of 2015 was the last time anyone else experienced this but I was wondering if anything regarding the site can be posted so we can get an idea of the current situation and when it might be resolved. Thanks.

**Comment by wbond** [comment]
Yeah, the website is having issues. Some funky issue with uwsgi and nginx. I've been working on it.

**Comment by wbond** [comment]
Duplicate of #1202
