### ISSUE TITLE
[Feature request] Package installation time

### ISSUE THREAD

**Issue by Kristinita** [wbond/package_control#1210]
### 1. Request

It would be nice, if I can see time, when I install my packages.

### 2. Justification

I use 200+ Sublime Text packages. Often I get conflicts between packages. I need to make debugging, but often I forgot, which packages I install lately. Often the best disable last installed packages to fix my problems.

### 3. Desirable behavior

<kbd>Ctrl+Shift+P</kbd> → `Package Control: Package Installation Time` → my installed packages will be sorted by installation time, from last to first. Example of command palette items:

```
Package Resource Viewer
<small>2017.04.14</small>
SashaSublime
<small>2017.04.07</small>
```

Thanks.

**Comment by FichteFoll** [comment]
For now, I suppose you could sort the Installed Packages dir by MTIME, which will also consider package updates but that might be useful by itself as well. For the Packages folder, this would be less straight forward.
