### ISSUE TITLE
Can't find "Emmet" or any other package. Build 3126

### ISSUE THREAD

**Issue by malakhkelevra** [wbond/package_control#1212]
As by title, I can't install any package. 
http://prntscr.com/e28fge

There is no package already installed (exception for Package Control of course) because it's a fresh new installation.

I tought it was a problem with the package repository but it seems not, this is what I got when I force the upgrade:

> Package Control: Skipping automatic upgrade, last run at 2017-01-30 14:42:21, next run at 2017-01-30 15:42:21 or after
> Package Control: Fetching list of available packages and dependencies
>   Platform: windows-x64
>   Sublime Text Version: 3126
>   Package Control Version: 3.2.1
> Package Control: Download Debug
>   URL: https://packagecontrol.io/channel_v3.json
>   Timeout: 30
>   Resolved IP: 50.116.34.243
>   Resolved IPv6: 2600:3c02:e000:42::1
> Package Control: WinINet Debug Proxy
>   proxy: 
>   proxy bypass: 
>   proxy username: 
>   proxy password: 
> Package Control: WinINet HTTPS Debug General
>   Server SSL Certificate:
>     subject: packagecontrol.io
>     issuer: US, GeoTrust Inc., RapidSSL SHA256 CA
>     common name: packagecontrol.io
>     issue date: Sun, 27 Nov 2016 01:00:00 GMT
>     expire date: Thu, 28 Nov 2019 00:59:59 GMT
> Package Control: WinINet HTTPS Debug Write
>   GET /channel_v3.json HTTP/1.1
>   User-Agent: Package Control v3.2.1
>   Host: packagecontrol.io
>   Connection: Keep-Alive
>   Cache-Control: no-cache
>   If-None-Match: "588f448f-4566a"
>   Accept-Encoding: bzip2,gzip,deflate
>   If-Modified-Since: Mon, 30 Jan 2017 13:50:07 GMT
> Package Control: WinINet HTTPS Debug Read
>   HTTP/1.1 200 OK
>   Server: nginx
>   Date: Mon, 30 Jan 2017 14:08:26 GMT
>   Content-Type: application/json
>   Content-Length: 283557
>   Last-Modified: Mon, 30 Jan 2017 14:00:07 GMT
>   Connection: keep-alive
>   ETag: "588f46e7-453a5"
>   Content-Encoding: bzip2
>   Vary: Accept-Encoding
>   Strict-Transport-Security: max-age=15552000
>   Accept-Ranges: bytes
> Package Control: Caching https://packagecontrol.io/channel_v3.json in C:\Users\MalakhKelevra\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
> Package Control: Fetching list of available packages and dependencies
>   Platform: windows-x64
>   Sublime Text Version: 3126
>   Package Control Version: 3.2.1
> reloading settings Packages/User/Package Control.sublime-settings
> reloading settings Packages/User/Preferences.sublime-settings
> Package Control: WinINet HTTPS Debug General
>   Closing connection to packagecontrol.io on port 443 after 1 request

I don't know what to do :\

**Comment by geeky-gurl** [comment]
I had the same problem. Here is what fixed it for me. Go to user settings and see if it Package Control has appeared in your "ignored_packages" list. If so, remove it from the ignored_packages list. 

    ignored_packages: ["Package Control", "Vintage"]

**Comment by malakhkelevra** [comment]
I already did, I have only "Vintage" as ignored_packages
Thank you anyway, I hope someone else could help me :\
