### ISSUE TITLE
[Question] Package Reloader and PackageReloader 

### ISSUE THREAD

**Issue by Kristinita** [wbond/package_control#1214]
Now we have 2 packages with similar names: [**Package Reloader**](https://packagecontrol.io/packages/Package%20Reloader) and [**PackageReloader**](https://packagecontrol.io/packages/PackageReloader). [**2.2 item Submitting a Package**](https://packagecontrol.io/docs/submitting_a_package) — «Don‘t use a name too similar to another».

I think, it would be better to rename one of packages. @csch0, @randy3k, what you think?

Thanks.

**Comment by FichteFoll** [comment]
Agree. That was a mistake on my side, probably.

**Comment by csch0** [comment]
@randy have not checked your package but if you are open to it and if they do the same we can also merge it to keep it clean for everybody else.

**Comment by randy3k** [comment]
I think both packages are doing similar jobs. My approach is more automatic and doesn't require to specify the order of loading. I certainly want to keep my package, though I don't mind renaming it (since my package is a late comer). Any good alternative name? How about "Package Module Reloader"?

**Comment by FichteFoll** [comment]
"Automatic Package Reloader" \*boom\*

**Comment by randy3k** [comment]
renamed [Automatic Package Reloader][1]

[1]: https://github.com/randy3k/AutomaticPackageReloader

**Comment by FichteFoll** [comment]
Ah well, seems I was right and didn't make a mistake here, since the package wasn't directly added to this repository but is rather referenced [here](https://raw.githubusercontent.com/randy3k/sublime_packages/master/packages.json).

Case closed.

**Comment by randy3k** [comment]
@FichteFoll, you are right, I am using my own repository file.
