### ISSUE TITLE
"There are no packages available for installation"

### ISSUE THREAD

**Issue by saatomic** [wbond/package_control#1215]
I'm having issues with package control, which appears to be an older/known problem.
`There are no packages available for installation`.

![1](https://cloud.githubusercontent.com/assets/22639652/22728761/f12cda1a-eddf-11e6-8d46-707e14019918.png)

After enabling the debugging messages the only thing the console logs is:
`Package Control: Error downloading channel. URL error unknown error (_ssl.c:2229) downloading https://packagecontrol.io/channel_v3.json.`

If i go to https://packagecontrol.io/ it seems to work fine. No proxies or anything.

![2](https://cloud.githubusercontent.com/assets/22639652/22728779/0aca7694-ede0-11e6-9768-ec88fe326d7e.png)

I'm on Xubuntu 16.04.1 LTS, Sublime Text Build 3126

**Comment by wbond** [comment]
If all you got was `Package Control: Error downloading channel. URL error unknown error (_ssl.c:2229) downloading https://packagecontrol.io/channel_v3.json.`, then debugging was not properly enabled.

Once you've got debugging enabled, you should check out the debug info and crab the path to the CA certs being used for the connection. You can then test and see if curl or wget can connect using that CA bundle.

**Comment by saatomic** [comment]
Then there seems to be a different fundamental problem. I was able to install it just fine on my other notebook.
