### ISSUE TITLE
setting locale from terminal does not clear the warning of the package manager

### ISSUE THREAD

**Issue by flip111** [wbond/package_control#1216]
When starting sublime text like

```
[ myPC: ~/ ] 
bash> LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /home/flip111/programs/sublime_text_3/sublime_text
```

I still get

![image](https://cloud.githubusercontent.com/assets/2244480/22940059/f3d5d9aa-f2e0-11e6-8dd5-2461588642de.png)

System:
CentOS 7.3.1611
terminator 0.98
bash 4.2.46
kernel: 3.10.0-514.6.1.el7.x86_64

**Comment by wbond** [comment]
Do you have en_US.UTF-8 installed on your machine?

**Comment by flip111** [comment]
How do i check?

**Comment by wbond** [comment]
I would try that locale in the command instead and see if it works for you.

BTW, what distro are you using?

**Comment by flip111** [comment]
I tried now `LANG=en_US.utf8 LC_CTYPE=en_US.utf8 /home/flip111/programs/sublime_text_3/sublime_text` and i still get the same dialog

**Comment by wbond** [comment]
I'm not really use why your machine won't properly handle UTF-8 in filenames.

You can play around with different locales until you can get the following code to run in your Sublime Text Console without an error:

```python
os.path.join(sublime.packages_path(), u"fran\u00e7ais")
```

**Comment by flip111** [comment]
with play around, do you mean try all possible combinations? There are like 15 different locale settings and lots and lots of different locales that can be used. Do you have any specific suggestions of this direction?

**Comment by wbond** [comment]
Not really – this error indicates your machine can't properly handle UTF-8 filenames and is instead using a single-byte character encoding. There are packages and files in packages that use non-ASCII characters. If this test doesn't pass, then your machine could fail in all sorts of different places.

Honestly, as long as you are using a locale that supports UTF-8, you should be good.

**Comment by deathaxe** [comment]
Nothing we can do on our end.
