### ISSUE TITLE
[Question] Valid tags

### ISSUE THREAD

**Issue by Kristinita** [wbond/package_control#1217]
### 1. Summary

Users of my package don't can read Package Control Messages of versions of my package. Perhaps, the problem is in my `st3-` tags.

### 2. Expected behavior

Successfully get messages of each version.

### 3. Actual behavior

When package upgrade, I see in Sublime Text console:

```
Package Control: Error sorting versions - 'st3-1.1.0' is not a valid SemVer string
Package Control: Upgraded SashaSublime to 1.5.0
```

### 4. Settings

[**`messages.json`**](https://github.com/Kristinita/SashaSublime/blob/master/messages.json) file of my package:

```json
{
    "st3-1.1.0": "messages/1.1.0.txt",
    "st3-1.2.0": "messages/1.2.0.txt",
    "st3-1.3.0": "messages/1.3.0.txt",
    "st3-1.4.0": "messages/1.4.0.txt",
    "st3-1.5.0": "messages/1.5.0.txt",
    "1.5.1": "messages/1.5.1.txt",
    "install": "messages/install.txt"
}
```

SashaSublime package only for Sublime Text 3, [**from Build 3114**](https://github.com/wbond/package_control_channel/pull/5723/files#diff-c8d235d61468c406b65f0f42dd314140R96).

[**SashaSublime releases page**](https://github.com/Kristinita/SashaSublime/releases).

### 5. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

When my package upgrade, users, who install my package, get `install.txt` message, but don't get messages of versions, and get actual behavior.

Perhaps, I need name my tags, for example, simply `1.5.1`, not `st3-1.5.1`, but @wbond [**say**](https://github.com/wbond/package_control_channel/pull/5723#issuecomment-246348096):

> You'll need to create a semver tag on your repo that begins with st3- (since you specified that in your PR).

Maybe I misunderstood the words @wbond? Or it a Package Control bug?

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by wbond** [comment]
> Perhaps, I need name my tags, for example, simply 1.5.1, not st3-1.5.1

No, you do need the `st3-` prefix for your tags. However, the *version* numbers in your `messages.json` need to be version numbers and *not* tag names.

In short, remove the `st3-` text from the keys in your `messages.json` file and you should be all set.

**Comment by FichteFoll** [comment]
Note that the package_reviewer utility would have spotted this :wink:

**Comment by Kristinita** [comment]
@FichteFoll , yes

```shell
D:\package_reviewer>python -m package_reviewer "D:\Sublime Text 3 x64\Data\Packages\SashaSublime" Package path: D:\Sublime Text 3 x64\Data\Packages\SashaSublime

## Report for SashaSublime ############################

Reporting 5 failures:
- Key 'st3-1.1.0' is not 'install' or a valid semantic version
    File: messages.json
- Key 'st3-1.2.0' is not 'install' or a valid semantic version
    File: messages.json
- Key 'st3-1.3.0' is not 'install' or a valid semantic version
    File: messages.json
- Key 'st3-1.4.0' is not 'install' or a valid semantic version
    File: messages.json
- Key 'st3-1.5.0' is not 'install' or a valid semantic version
    File: messages.json

No warnings or more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki
```

Thanks for package_reviewer!
