### ISSUE TITLE
Package Control: Error parsing JSON from repository http://download.eclipse.org/vjet/updates-0.10.

### ISSUE THREAD

**Issue by WeijianXu** [wbond/package_control#1222]
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Package Control: Error parsing JSON from channel https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error EOF occurred in violation of protocol (_ssl.c:548) downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error parsing JSON from repository http://download.eclipse.org/vjet/updates-0.10.
Package Control: Error parsing JSON from repository http://download.eclipse.org/vjet/updates-0.10.
Package Control: Error parsing JSON from channel https://packagecontrol.io/channel_v3.json.

**Comment by WeijianXu** [comment]
Sometimes I can't install any packages because of the packages list panel can't be displayed by this problem. Sometimes I can open the the packages list panel. I don't know how to cause that.

**Comment by FichteFoll** [comment]
Sounds like a network issue.

**Comment by wbond** [comment]
http://download.eclipse.org/vjet/updates-0.10 is not a valid channel server for Package Control.

As @FichteFoll mentioned, the issue seems to be that something in your network connection is breaking the connection to packagecontrol.io.
