### ISSUE TITLE
HTTP exception InvalidCertificateException when installing new packages

### ISSUE THREAD

**Issue by jonmrich** [wbond/package_control#1223]
Having issues installing new packages. Ran the debug and got the following.

I've tried reinstalling everything several times, but nothing seems to be working.

Any help would be appreciated.

Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.1
ignored packages updated to: ["Cobalt2 Flat Theme", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.1
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Download Debug
  URL: https://codeload.github.com/r3volution11/cobalt2-flat-theme/zip/1.0.4
  Timeout: 30
  Resolved IP: 192.30.253.121
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/richman/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (302566 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/richman/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://codeload.github.com/r3volution11/cobalt2-flat-theme/zip/1.0.4.
error: Package Control

Unable to download Cobalt2 Flat Theme. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

**Comment by jonmrich** [comment]
Fixed with
https://github.com/wbond/package_control/issues/1220

**Comment by jzatarain** [comment]
Added CURL in osx mojave, and now I get this error:
`curl: (60) SSL certificate problem: self signed certificate in certificate chain `
