### ISSUE TITLE
Confusing url source while installing a forked package

### ISSUE THREAD

**Issue by Starli0n** [wbond/package_control#1225]
Hi,

I faced an issue while installing a forked package `PHPUnit`.

On the screenshot, the first entry `PHPUnit` is the original one from `stuartherbert`.
The last one `PHPUnit_Patched` is mime, the package I forked from the original one.

![image](https://cloud.githubusercontent.com/assets/3925813/23703294/837913a4-03ff-11e7-9d14-4c320da0c0ba.png)

But as you can see on the picture, they both have the same url source.
On `PHPUnit_Patched`, I expect to have my url `https://github.com/Starli0n/f_sublime-phpunit` instead of this one `https://github.com/stuartherbert/sublime-phpunit`.

To reproduce, add [this repository](https://raw.githubusercontent.com/Starli0n/SublimePackages/master/patched_repository.json) to Package Control.

It was confusing as I had to rename my package to see the two entries.
I confirmed that the downloaded package is mine. Tested on st3 on Windows.

Thanks

**Comment by FichteFoll** [comment]
Change the "repo url" of your fork (here: https://github.com/Starli0n/f_sublime-phpunit). It points to the origin. Removing it entirely will make PC default to the actual repo url.

**Comment by Starli0n** [comment]
I removed the `Website` url beside the `Description` of my repo and it works fine now.

I will be able to renamed it from `PHPUnit_Patched` to `PHPUnit`

Thanks!
