### ISSUE TITLE
Package control freezes on package removal

### ISSUE THREAD

**Issue by kaba2** [wbond/package_control#1226]
0. Delete all files in `C:\Users\Kaba\AppData\Roaming\Sublime Text 3\Packages\User` and `C:\Users\Kaba\AppData\Roaming\Sublime Text 3\Installed Packages`. Reboot the computer.
1. Install latest `Sublime Text Build 3126 x64 Setup.exe` on Windows 10.
2. Install Package Control from the Sublime Text menu.
3. Install "LatexTools" package.
4. Remove "LatexTools" package.

This freezes Sublime Text, so I cannot access the debug log. But here is a screenshot of the last moments:

![package-control-debug](https://cloud.githubusercontent.com/assets/2399754/23812364/f0ae8b9a-05e2-11e7-861b-b79c25e5ddc4.png)

This indeed reveals a Windows PermissionError, where the package control cannot access its file.

**Comment by evandrocoan** [comment]
Probably related to:

1. https://github.com/SublimeText/LaTeXTools/issues/1226 Autocompletion is slow and sometimes it is blocking Sublime Text for ever with 0% CPU usage

Sublime Text has a bug which causes it to enter on a deadlock state when reloading/unloading settings or packages files:

1. https://github.com/SublimeTextIssues/Core/issues/1966 Deadlock/hang when batch deleting/creating settings files

**Comment by megadr01d** [comment]
Just FYI, I get this hang when removing GitGutter (and a couple of few more I don't remember, in the past), on OS X.

**Comment by deathaxe** [comment]
Package Control 4 resolves this issue.

1. Depedencies don't need a 00_package_control_loader which was involved here
2. Several changes were made to reduce the risk of hitting locked files or folders during package operations.
3. Several race conditions which could be the root cause of most of the trouble are fixed.
