### ISSUE TITLE
API for packagecontrol.io

### ISSUE THREAD

**Issue by zeeshanu** [wbond/package_control#1229]
Is there any API for Sublime text's package manager? I tried to find it but couldn't find any mention of it anywhere.

http://stackoverflow.com/questions/43556525/is-there-any-api-for-sublime-texts-packages-site

**Comment by wbond** [comment]
I've provided an answer at http://stackoverflow.com/questions/43556525/is-there-any-api-for-sublime-texts-packages-site.
