### ISSUE TITLE
Cannot open Package Control

### ISSUE THREAD

**Issue by muhammedMoussa** [wbond/package_control#1232]
i faced some problems with installing Package Control at first about environment variables dialog was appear to me, then it fixed and hidden now i try to open command ballet and type 
```
Package Control: List Packages
```
then hit enter no response, and console clear !

**Comment by wbond** [comment]
Look in your other Sublime Text window for the console contents

**Comment by muhammedMoussa** [comment]
@wbond it never appear at command ballet, i'm using linux mint 17.. here is some output from console 
```
reloading plugin package_control.semver
reloading plugin package_control.settings
reloading plugin package_control.show_error
reloading plugin package_control.show_quick_panel
reloading plugin package_control.sys_path
reloading plugin package_control.text
reloading plugin package_control.thread_progress
reloading plugin package_control.unicode
reloading plugin package_control.versions
plugins loaded
Unable to fetch update url contents
```

**Comment by cmdstewart** [comment]
I am having a similar issue. Sublime text 3 started to freeze so I restarted my computer and now package control will not show up. I manually reinstalled it (although it was still present) and nothing shows up when I Ctrl+Shift+P and type install or list. There are no errors in the console and, in addition, some keyboard shortcuts no longer work, such as Ctrl+Shift+/ (for comment blocks) or Ctrl+Shift+Up/Down Arrows to move lines up and down.

Console Log:

> DPI scale: 2
> startup, version: 3126 windows x64 channel: stable
> executable: /C/Program Files/Sublime Text 3/sublime_text.exe
> working dir: /C/Program Files/Sublime Text 3
> packages path: /C/Users/cstewart/AppData/Roaming/Sublime Text 3/Packages
> state path: /C/Users/cstewart/AppData/Roaming/Sublime Text 3/Local
> zip path: /C/Program Files/Sublime Text 3/Packages
> zip path: /C/Users/cstewart/AppData/Roaming/Sublime Text 3/Installed Packages
> ignored_packages: ["Color Highlighter", "TrailingSpaces", "Vintage"]
> pre session restore time: 0.420108
> startup time: 0.538108
> first paint time: 0.544108
> first paint time: 0.545108
> reloading plugin Default.auto_indent_tag
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.install_package_control
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.quick_panel
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.settings
> reloading plugin Default.show_scope_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin 0_package_control_loader.00-package_control
> reloading plugin 0_package_control_loader.01-pygments
> reloading plugin 0_package_control_loader.02-bz2
> reloading plugin 0_package_control_loader.50-backrefs
> reloading plugin 0_package_control_loader.50-dateutil
> reloading plugin 0_package_control_loader.50-markupsafe
> reloading plugin 0_package_control_loader.50-python-markdown
> reloading plugin 0_package_control_loader.51-python-jinja2
> reloading plugin 0_package_control_loader.55-mdpopups
> reloading plugin All Autocomplete.all_views_completions
> reloading plugin BracketHighlighter.bh_core
> reloading plugin BracketHighlighter.bh_logging
> reloading plugin BracketHighlighter.bh_plugin
> reloading plugin BracketHighlighter.bh_popup
> reloading plugin BracketHighlighter.bh_regions
> reloading plugin BracketHighlighter.bh_remove
> reloading plugin BracketHighlighter.bh_rules
> reloading plugin BracketHighlighter.bh_search
> reloading plugin BracketHighlighter.bh_swapping
> reloading plugin BracketHighlighter.bh_wrapping
> reloading plugin BracketHighlighter.support
> reloading plugin Colorsublime.colorsublime-plugin
> reloading plugin DocBlockr.jsdocs
> reloading plugin FTPSync.__init__
> reloading plugin FTPSync.FTPSync
> reloading plugin FTPSync.ftpsynccommon
> reloading plugin FTPSync.ftpsyncexceptions
> reloading plugin FTPSync.ftpsyncfiles
> reloading plugin FTPSync.ftpsyncfilewatcher
> reloading plugin FTPSync.ftpsyncprogress
> reloading plugin FTPSync.ftpsyncpubsub
> reloading plugin FTPSync.ftpsyncworker
> reloading plugin FTPSync.ftpsyncwrapper
> reloading plugin Function Name Display.FunctionNameStatus
> reloading plugin Google Spell Check.google-spell-check
> reloading plugin Package Control.1_reloader
> reloading plugin Package Control.2_bootstrap
> reloading plugin Package Control.Package Control
> reloading plugin PHP Codebeautifier.phpcbf
> reloading plugin PHP Syntax Checker.phpSyntaxChecker
> reloading plugin Phpcs.phpcs
> reloading plugin PhpDoc.CodeDoc
> reloading plugin SideBarEnhancements.SideBar
> reloading plugin SideBarEnhancements.SideBarAPI
> reloading plugin SideBarEnhancements.SideBarDefaultDisable
> reloading plugin SideBarEnhancements.Stats
> reloading plugin sublime-github.commandline
> reloading plugin sublime-github.github
> reloading plugin sublime-github.sublime_github
> reloading plugin sublime-github.sublime_requests
> reloading plugin SublimeLinter-csslint.linter
> SublimeLinter: csslint linter loaded 
> reloading plugin SublimeLinter-jshint.linter
> SublimeLinter: jshint linter loaded 
> reloading plugin SublimeLinter-json.linter
> SublimeLinter: json linter loaded 
> reloading plugin SublimeLinter-php.linter
> SublimeLinter: php linter loaded 
> reloading plugin VCS Gutter.gutter_handlers
> reloading plugin VCS Gutter.vcs_gutter
> reloading plugin VCS Gutter.vcs_gutter_change
> reloading plugin VCS Gutter.vcs_gutter_events
> reloading plugin VCS Gutter.vcs_helpers
> reloading plugin VCS Gutter.view_collection
> reloading plugin WebFont.WebFont
> reloading plugin Xdebug Client.main
> reloading plugin AutoSpell.AutoSpell
> reloading plugin CodeComplice.CodeComplice
> reloading plugin PlainTasks.APlainTasksCommon
> reloading plugin PlainTasks.PlainTasks
> reloading plugin PlainTasks.PlainTasksDates
> reloading plugin PlainTasks.PlainTasksToHTML
> reloading plugin PlainTasks.plist_parser
> reloading plugin Pretty JSON.PrettyJson
> reloading plugin Pretty JSON.PrettyJsonListeners
> reloading plugin SublimeCodeIntel.ordereddict
> reloading plugin SublimeCodeIntel.SublimeCodeIntel
> thread finalize

**Comment by boomshadow** [comment]
@cmdstewart I was having the exact same issue as you. I went through the "Purging and Reinstalling" guided here, and it solved my problem:

https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling
