### ISSUE TITLE
How to reload the package control files after Sublime Text start?

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1234]
I just created a new command on `Package Control\package_control\commands\list_packages_command.py`, however Sublime Text only reloads automatically packages after saving them if they are on the package root folder first level.

So how to reload that file, or just reload all `Package Control` files?

**Comment by FichteFoll** [comment]
Reload the "reloaded.py" file or a file that includes it.

**Comment by evandrocoan** [comment]
Thanks. Initially I opened `Package Control\Package Control.py` and resaved (force reload), then later I did the same process with `Package Control\1_reloader.py`.

I also added my class on `Package Control\package_control\commands\__init__.py`:
```python
from .list_packages_command import ListPackagesOnViewCommand
...
    'ListPackagesOnViewCommand',
```

I also put `print( "Reloading Package Control\package_control\commands\list_packages_command.py" )` on the beginning of the file to know when it is being reloaded.
