### ISSUE TITLE
Package Control: Skipping due to hitting rate limit for api.github.com

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1239]
How to pass this limitation?
```
Package Control: Download Debug
  URL: https://api.github.com/repos/math2001/FileManager
  Timeout: 30
  Resolved IP: 192.30.253.116
  Skipping due to hitting rate limit for api.github.com
Package Control: Rate limit of 60 exceeded for api.github.com
Package Control: Skipping due to hitting rate limit for api.github.com
Package Control: Skipping due to hitting rate limit for api.github.com
Package Control: Skipping due to hitting rate limit for api.github.com
Package Control: Skipping due to hitting rate limit for api.github.com
```
Is it hourly? If so, on the next hour the skipped packages are going to be updated, or they will never update?

Here is the full log within these messages on debug mode:

1. [Package Control: Debug for AttributeError: 'bool' object has no attribute 'replace'](https://gist.github.com/evandrocoan/757da5a3c7083b26c6069dc3f85f5980)

**Comment by wbond** [comment]
To pass this limitation you have to create an OAuth application and then provide the client id and client secret via query string parameters.
