### ISSUE TITLE
Should messages.json contain the tags in github or the raw version number ?

### ISSUE THREAD

**Issue by Wramberg** [wbond/package_control#1247]
Package control prints

```
Error parsing messages.json...
```

for this https://github.com/Wramberg/TerminalView/blob/master/messages.json
Is it due to the fact that my tags are named "v0.4.0" etc. or ?
On the package control homepage the version number is a clean "0.4.0".

Is there anyway to test this except with a new release ?

**Comment by Wramberg** [comment]
Upon inspection of the package control source i see that the trailing comma was causing problems so i removed that. I would like to know how to format the keys in the json file though.

**Comment by wbond** [comment]
The raw version number is what should be used. The extra prefix allowed in the tag name is just for the purpose of selecting tags that represent real releases.

**Comment by Wramberg** [comment]
Great - thanks for the clarification :-)
