### ISSUE TITLE
Sublime 3 Opening google.com instead of html code

### ISSUE THREAD

**Issue by arsovskidario** [wbond/package_control#1248]
**I downloaded sublime 3 to switch from codepen.io and the build functino isnt worknig.I typed in basic html code and it opens a google.com website not the website it's supposed to open.
http://prntscr.com/ftoh49 code
https://prnt.sc/ftoh78 after CTRL+B**
**Need help urgent getting aggressive**

**Comment by wbond** [comment]
This has nothing to do with Package Control. I recommend posting on https://forum.sublimetext.com/.
