### ISSUE TITLE
This is my problem, Help me please

### ISSUE THREAD

**Issue by tsuneska** [wbond/package_control#1249]
DPI scale: 1
startup, version: 3126 windows x32 channel: stable
executable: /C/Program Files (x86)/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files (x86)/Sublime Text 3
packages path: /C/Users/yorgenis/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/yorgenis/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files (x86)/Sublime Text 3/Packages
zip path: /C/Users/yorgenis/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0745537
startup time: 0.0995537
first paint time: 0.100554
first paint time: 0.100554
Unable to fetch update url contents
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Not running package cleanup since bootstrapping is not yet complete
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "2_bootstrap in C:\Program Files (x86)\Sublime Text 3\Packages\Package Control.sublime-package", line 114, in _background_bootstrap
  File "package_control.loader in C:\Program Files (x86)\Sublime Text 3\Packages\Package Control.sublime-package", line 209, in add_or_update
  File "package_control.loader in C:\Program Files (x86)\Sublime Text 3\Packages\Package Control.sublime-package", line 293, in add
  File "./python3.3/zipfile.py", line 921, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Sublime Text 3\\Installed Packages\\0_package_control_loader.sublime-package'

**Comment by wbond** [comment]
Delete the file `C:\Program Files (x86)\Sublime Text 3\Packages\Package Control.sublime-package` and install package control following the directions on the website, or use the `Install Package Control` command palette entry.
