### ISSUE TITLE
Should be able to use proxy configuration from the system's settings in Unix systems

### ISSUE THREAD

**Issue by rafaelbco** [wbond/package_control#1252]
I think Package Control should be able to use proxy configuration from the system settings in Unix systems. It seems it already does this for windows. For Unix I'm talking about the `http_proxy` and `https_proxy` environment variables.

The main reasons are:

1. It's a source of frustration for users when Package Control does not work when behind a proxy. They'll have to google to discover they must add the proxy information to the settings. And maintain them up to date.
2. Sharing configuration with colleagues with different proxy configurations (or publicly) is hard.

**Comment by rafaelbco** [comment]
I'm thinking about writing a pull request about this. 

It seems the best place to handle this would be here: https://github.com/wbond/package_control/blob/5b35f88fe2d748af15d9d6079d50629f2bf82ad0/package_control/download_manager.py#L369

What do you think?

**Comment by wbond** [comment]
If you want to support env vars on Linux, then changing the Windows-only WinInet provider exception handling code won't help.

The default provider on Linux is `UrllibDownloader`. If proxy info isn't present in settings, it constructs a default `urllib.request.ProxyProvider()`, which pulls proxy info from the env:

 - https://github.com/wbond/package_control/blob/master/package_control/downloaders/urllib_downloader.py#L273-L284
 - https://docs.python.org/3.3/library/urllib.request.html#urllib.request.ProxyHandler

The `CurlDownloader` uses curl, which grabs from the env: https://stackoverflow.com/a/7559180/230074.

The `WgetDownloader` uses wget, which grabs from the env: https://www.gnu.org/software/wget/manual/html_node/Proxies.html.

My guess is that perhaps you are launching Sublime Text in such a way that your env vars aren't being sent to the `sublime_text` process. If you open the console, you can execute the following to see what is present:

```python
import os; dict(os.environ)
```

If your proxy vars aren't there, then the urllib proxy code won't find them, and curl and wget won't either.

**Comment by rafaelbco** [comment]
> My guess is that perhaps you are launching Sublime Text in such a way that your env vars aren't being sent to the sublime_text process. If you open the console, you can execute the following to see what is present:

You're right. I was able to solve the problem. Thank you!
