### ISSUE TITLE
Package Pandoc doesn't contain latest master of the package on the corresponding github page

### ISSUE THREAD

**Issue by dahanbn** [wbond/package_control#1255]
If I install Pandoc via PackageControl I won't get the latest master from the package.

PackageControl says the latest version is 12 months old and from 2016.08.23.12.01.10. 

If I go to the github page of the [Pandoc package](https://github.com/tbfisher/sublimetext-Pandoc) than it says the latest commit is from January 16. 

I noticed the difference only because the latest merge contains a new setting that I was looking for.

PS: I am new to ST and Packagecontrol and I hope this is the right place to mention that problem. If not, please point me in the right direction.

**Comment by FichteFoll** [comment]
That's because the author of the package specified two releases that point to the `1.x` and `2.x` branches respectively.

https://raw.githubusercontent.com/tbfisher/sublimetext-Pandoc/master/packages.json

```js
{// …
      "releases": [
        {
          "sublime_text": "<3000",
          "details": "https://github.com/tbfisher/sublimetext-Pandoc/tree/1.x"
        },
        {
          "sublime_text": ">=3000",
          "details": "https://github.com/tbfisher/sublimetext-Pandoc/tree/2.x"
        }
      ]
}
```

**Comment by dahanbn** [comment]
Thanks, for the clarification. As a newbie I still have two questions.

Is it possible to download the master release via PackageControl?

To fix this I must contact the maintainer of Pandoc?

**Comment by FichteFoll** [comment]
You can still add the repository manually with the *Package Control: Add Repository* command from the palette. If you paste the link to the github repo, it will automatically use the master branch. Note that the name of the package is inherited from the repo name, so it will be `sublimetext-Pandoc`.

The better way would be to contact the author, however.
