### ISSUE TITLE
So what's the problem here? 

### ISSUE THREAD

**Issue by stefan41** [wbond/package_control#1259]
If you are running into a bug, please read https://packagecontrol.io/docs/troubleshooting
before submitting an issue here.
![sublime-error](https://user-images.githubusercontent.com/9367873/29740518-8c976ac8-8a58-11e7-95be-cf3341110c60.jpg)

Bug reports must include a debug log. The Troubleshooting page explains how to capture one.

**Comment by ihodev** [comment]
Add `,` after `"installed_packages": []`
