### ISSUE TITLE
github package with a git submodule dependency?

### ISSUE THREAD

**Issue by quarnster** [wbond/package_control#126]
I recently broke some common code from an experimental branch of SublimeClang and the master branch of [SublimeJava](https://github.com/quarnster/SublimeJava/) into its own repository, and added that repository as a submodule to these two projects. However, when installing SublimeJava using package control it does not also install the common git submodule. Is this some configuration setting I have not done or is it not supported yet?

It seem the zipball doesn't contain the submodule data, but it does have a ".gitmodules" which could be used. That file does not specify which revision to use of the submodule though...

**Comment by smac89** [comment]
I was able to find a workaround for this, by creating a tag which points to a ref containing the contents of the submodule. See https://github.com/smac89/autodark-sublime-plugin. The workaround is embodied in the [`release.sh`](https://github.com/smac89/autodark-sublime-plugin/blob/20629887788e65b11f286e872ddc0153a38ea641/release.sh) script found in that repository.
