### ISSUE TITLE
Unable to load a simple csv file using Python 3.5 in Windows 10 

### ISSUE THREAD

**Issue by datatales2017** [wbond/package_control#1260]
import pandas as pd
data = pd.read_csv('‪‪‪M:\\test.csv')

error: UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

I did search github and tried some solutions like giving forward slashes and double slashes in the path of the file but  nothing seems to work. I recently migrated from Windows 7 to windows 10.This is very frustrating. Please help.

**Comment by FichteFoll** [comment]
This has no relevance to this repository whatsoever, but try with `r'M:\test.csv`.

**Comment by datatales2017** [comment]
got it.Thanks.
