### ISSUE TITLE
http://packagecontrol.io down

### ISSUE THREAD

**Issue by sparr** [wbond/package_control#1265]
I am seeing timeouts when trying to connect.

http://downforeveryoneorjustme.com/packagecontrol.io also indicates the site is not responding.

**Comment by jonluca** [comment]
Same as well. Might be a DNS issue

`
; <<>> DiG 9.9.7-P3 <<>> http://packagecontrol.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 37595
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;http://packagecontrol.io.	IN	A

;; AUTHORITY SECTION:
io.			676	IN	SOA	a0.nic.io. noc.afilias-nst.info. 1497251335 10800 3600 2764800 900

;; Query time: 58 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Sep 11 13:58:10 PDT 2017
;; MSG SIZE  rcvd: 116`

[y tho](https://ih1.redbubble.net/image.164229979.6542/flat,1000x1000,075,f.u3.jpg)

**Comment by jonluca** [comment]
It's definitely a DNS issue - the old cached IP works (if you ignore the SSL errors due to going straight to IP)

https://50.116.34.243/

**Comment by zachdixon** [comment]
Looks like it's back up

**Comment by jonluca** [comment]
Yup, working for me as well. Feel free to close the issue
