### ISSUE TITLE
Package Control not working on ST3

### ISSUE THREAD

**Issue by dlo** [wbond/package_control#1275]
After installing Package Control and restarting, none of the commands appear to be available under ST3. It's appropriately installed to the correct directory using the automatic installation script, but none of the commands appear in the command palette.

<img width="819" alt="screen shot 2017-09-29 at 11 42 55 am" src="https://user-images.githubusercontent.com/38447/31026287-7e73543e-a50b-11e7-9c8a-335b9bcee160.png">
<img width="629" alt="screen shot 2017-09-29 at 11 43 05 am" src="https://user-images.githubusercontent.com/38447/31026286-7e5e0d72-a50b-11e7-9fe2-2300754d75be.png">

**Comment by rosilva** [comment]
Hi, just as commented here: https://github.com/wbond/package_control/issues/1271#issuecomment-331626458

Open "Preferences" > "Settings" and see if the "Package Control" is listed in "ignored_packages", if it's listed, just remove it and it will get working again.

**Comment by dlo** [comment]
Wow, yes it was, and I never remembered ever disabling it. Thank you!
