### ISSUE TITLE
[Feature Request]: Advanced Remove Package

### ISSUE THREAD

**Issue by thecodechef** [wbond/package_control#1279]
Since using the advance install package command lately i have acquired a ton of packages that i hardly use anymore so it would be really great to have a command  to get rid of a list of packages the in the same fashion instead of removing them individually 

What are your thoughts

Sicerely Jeremy,

@wbond

**Comment by FichteFoll** [comment]
You should be able to remove them from the `installed_packages` list in PC user settings and force upgrade.

**Comment by thecodechef** [comment]
What i mean is doing a batch advance remove command just like the batch advance install command

Example:

givin that you have these in your packages dir
```
Pug, Twig, Jinja
```
you should be able to type this list when u run a command like advance remove package
and when its done u know longer have them

**Comment by FichteFoll** [comment]
I know; I was merely providing a workaround.

**Comment by deathaxe** [comment]
Fixed by PC 4.0
