### ISSUE TITLE
Package control keeps reinstalling bz2

### ISSUE THREAD

**Issue by Seraphli** [wbond/package_control#1283]
After I tried the method described in  #989 . The problem still exists. I already upgrade package control to the latest version. Removing folder doesn't work. And there is no `0_package_control_loader.sublime-package` in `Installed Packages`. Here is the output log. 
```
Package Control: Installing 2 missing dependencies
Package Control: The dependency '0_package_control_loader' is not available
Package Control: Installed missing dependency bz2
Package Control: No updated packages
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
```
Even though there is a folder named `bz2` in `Packages` folder, package control just keeps reinstalling this package.

**Comment by FichteFoll** [comment]
Are you perhaps using ST2 and/or an old version of package control?

**Comment by Seraphli** [comment]
I'm using ST3, and like what I said, I already update to the latest version. I just deleted the old package and downloaded the new version and manually installed on my PC.

**Comment by wbond** [comment]
@Seraphli You are probably using a very old version of Sublime Text 3. You should upgrade to 3.0.

**Comment by Seraphli** [comment]
Yeah, I'm using Build 3065. Maybe that is the cause.

**Comment by thesandbender** [comment]
@wbond I'm running into the same issue with Build 3083.  Unfortunately I don't have the option to upgrade, we have a tightly managed environment and 3083 is the most "recent" build that's been packaged.  Any suggestions for how I might hack around it (understanding it voids the warranty)?

**Comment by wbond** [comment]
@thesandbender No, I don't have any idea why it isn't working on old builds, and unfortunately I don't have the time or desire to support such an old build. You are going to have to dive into the Python and try to figure out what exactly is happening. All recent versions of Sublime Text 3 come with the bz2 and _ssl modules, so the bootstrapping of Package Control is no longer required.

I highly recommend you push your IT staff to bring you up to version 3.0 (build 3143). I'm sure they'd be happy to have a build with security fixes.

**Comment by thesandbender** [comment]
@wbond Understood and thank you for the response.  Already submitted the request, IT just has it queued up behind a hundred other production reviews.  They'll get to it, just can't be sure when.

**Comment by Seraphli** [comment]
@thesandbender Actually, I just delete package control, because every package I need is installed and I really don't need to use package control recently. So this might be the easiest way to solve this problem.
