### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by Festum** [wbond/package_control#1284]
![](https://i.imgur.com/UpqnoZP.png)

**Comment by carsonkk** [comment]
Getting the same result, can't install package control either

**Comment by ihodev** [comment]
Will's probably sleeping now :sleeping:  We have to wait :wink:

**Comment by ihodev** [comment]
@Festum It's working now. You can close the issue :wink:

**Comment by wbond** [comment]
Yes, the server was down last night while I was sleeping.
