### ISSUE TITLE
Unable to save config file to add Debug option

### ISSUE THREAD

**Issue by GardenerMatt** [wbond/package_control#1295]
I am having an issue with getting Anaconda added to my Sublime Test 3 install, but I can't get the debug log to file an issue for that, because I get the following error when I save the user settings:

Error trying to parse settings: Unexpected character, expected a comma or closing bracket in Packages\User\Package Control. sublime-settings:3:2.

I'm running Package Control v3.3.0, on Sublime Text 3.0 Build 3143.

![sublime text1](https://user-images.githubusercontent.com/6304018/32675715-7982d2f4-c632-11e7-8fa4-a8a2c8ed11e5.JPG)
![sublime text2](https://user-images.githubusercontent.com/6304018/32675716-7999f7d6-c632-11e7-9061-61a2a253ff51.JPG)

**Comment by FichteFoll** [comment]
>expected a comma or closing bracket

Uhm, try adding a comma after the first key-value pair?

**Comment by GardenerMatt** [comment]
Thanks! Sorry for the PEBKAC.
