### ISSUE TITLE
Cannot install new packages on MacOS/Sublime Text 3: error when checking root CAs

### ISSUE THREAD

**Issue by svitebskiy** [wbond/package_control#1297]
I have tried dis-trusting some of the problem root CAs, but there was always another CA with the same error. I have also completely re-installed Sublime Text, also erasing the ~/Library/Application Support/Sublime Text 3 directory to get a clean reset, but the same error would re-appear after the Package Control is installed and Sublime Text app is re-started.
Below is the console output that shows up after the Sublime Text 3 start.

Package Control: Download Debug
  URL: https://packagecontrol.io/submit?package=Package+Control&sublime_platform=osx&operation=install&version=3.3.0&package_control_version=3.3.0&sublime_version=3143
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Package Control: Skipped certificate: Common Name: Actalis Authentication Root CA, Organization: Actalis S.p.A./03358520967, Locality: Milan, Country: IT - reason explicitly distrusted
Package Control: Skipped certificate: Organization: Government Root Certification Authority, Country: TW - reason explicitly distrusted
Package Control: Skipped certificate: Organizational Unit: I.CA - Accredited Provider of Certification Services; Organization: První certifikační autorita, a.s.; Common Name: I.CA - Qualified Certification Authority, 09/2009; Country: CZ - reason explicitly distrusted
Package Control: Exported certificate: Common Name: Izenpe.com, Organization: IZENPE S.A., Country: ES
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: OISTE WISeKey Global Root GA CA; Organizational Unit: OISTE Foundation Endorsed, Copyright (c) 2005; Organization: WISeKey; Country: CH
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root G3, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Symantec Class 2 Public Primary Certification Authority - G4, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: Class 2 Primary CA, Organization: Certplus, Country: FR
Package Control: Exported certificate: Organization: TÜRKTRUST Bilgi İletişim ve Bilişim Güvenliği Hizmetleri A.Ş. (c) Aralık 2007, Locality: Ankara, Country: TR, Common Name: TÜRKTRUST Elektronik Sertifika Hizmet Sağlayıcısı
Package Control: Exported certificate: Common Name: StartCom Certification Authority G2, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Common Name: GlobalSign Root CA, Organizational Unit: Root CA, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: Echoworx Root CA2, Organizational Unit: Certification Services, Organization: Echoworx Corporation, Locality: Toronto, State/Province: Ontario, Country: CA
Package Control: Exported certificate: Common Name: COMODO Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: DigiCert Global Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: SwissSign Platinum CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Organizational Unit: ePKI Root Certification Authority; Organization: Chunghwa Telecom Co., Ltd.; Country: TW
Package Control: Exported certificate: Common Name: ComSign Global Root CA, Organization: ComSign Ltd., Country: IL
Package Control: Exported certificate: Common Name: Chambers of Commerce Root, Organizational Unit: http://www.chambersign.org, Organization: AC Camerfirma SA CIF A82743287, Country: EU
Package Control: Exported certificate: Common Name: USERTrust RSA Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: Swisscom Root EV CA 2, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: Visa Information Delivery Root CA, Organizational Unit: Visa International Service Association, Organization: VISA, Country: US
Package Control: Exported certificate: Common Name: UTN-USERFirst-Client Authentication and Email, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: SwissSign Gold Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: QuoVadis Root CA 2 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: Swisscom Root CA 2, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: Apple Root CA, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: Certigna, Organization: Dhimyotis, Country: FR
Package Control: Exported certificate: Common Name: COMODO ECC Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: TÜBİTAK UEKAE Kök Sertifika Hizmet Sağlayıcısı - Sürüm 3; Organizational Unit: Kamu Sertifikasyon Merkezi, Ulusal Elektronik ve Kriptoloji Araştırma Enstitüsü - UEKAE; Organization: Türkiye Bilimsel ve Teknolojik Araştırma Kurumu - TÜBİTAK; Locality: Gebze - Kocaeli; Country: TR
Package Control: Exported certificate: Common Name: ComSign CA, Organization: ComSign, Country: IL
Package Control: Exported certificate: Common Name: Swisscom Root CA 1, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: SecureTrust CA, Organization: SecureTrust Corporation, Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Commercial, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Email Address: pki@sk.ee, Common Name: EE Certification Centre Root CA, Organization: AS Sertifitseerimiskeskus, Country: EE
Package Control: Exported certificate: Common Name: thawte Primary Root CA - G3; Organizational Unit: (c) 2008 thawte, Inc. - For authorized use only, Certification Services Division; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: DST Root CA X3, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: IdenTrust Public Sector Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: DigiCert Global Root G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Certum Trusted Network CA, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Common Name: Deutsche Telekom Root CA 2, Organizational Unit: T-TeleSec Trust Center, Organization: Deutsche Telekom AG, Country: DE
Package Control: Exported certificate: Common Name: Amazon Root CA 2, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: TRUST2408 OCES Primary CA, Organization: TRUST2408, Country: DK
Package Control: Exported certificate: Common Name: Autoridad de Certificacion Firmaprofesional CIF A62634068, Country: ES
Package Control: Exported certificate: Common Name: SwissSign Silver CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: E-Tugra Certification Authority, Organizational Unit: E-Tugra Sertifikasyon Merkezi, Organization: E-Tuğra EBG Bilişim Teknolojileri ve Hizmetleri A.Ş., Locality: Ankara, Country: TR
Package Control: Exported certificate: Common Name: TWCA Global Root CA, Organizational Unit: Root CA, Organization: TAIWAN-CA, Country: TW
Package Control: Exported certificate: Common Name: IdenTrust Commercial Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: Global Chambersign Root, Organizational Unit: http://www.chambersign.org, Organization: AC Camerfirma SA CIF A82743287, Country: EU
Package Control: Exported certificate: Common Name: D-TRUST Root Class 3 CA 2 EV 2009, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G3, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - EC1; Organizational Unit: (c) 2012 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: StartCom Certification Authority, Organizational Unit: Secure Digital Certificate Signing, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Common Name: TWCA Root Certification Authority, Organizational Unit: Root CA, Organization: TAIWAN-CA, Country: TW
Package Control: Exported certificate: Common Name: Symantec Class 3 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: Certinomis - Root CA, Organizational Unit: 0002 433998903, Organization: Certinomis, Country: FR
Package Control: Exported certificate: Common Name: Starfield Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Email Address: Info@izenpe.com, Common Name: Izenpe.com, Locality: Avda del Mediterraneo Etorbidea 3 - 01010 Vitoria-Gasteiz, Organization: IZENPE S.A. - CIF A-01337260-RMerc.Vitoria-Gasteiz T1055 F62 S8, Country: ES
Package Control: Exported certificate: Common Name: DigiCert Trusted Root G4, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: SwissSign Platinum Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: TeliaSonera Root CA v1, Organization: TeliaSonera
Package Control: Exported certificate: Common Name: UCA Global Root, Organization: UniTrust, Country: CN
Package Control: Exported certificate: Common Name: D-TRUST Root Class 3 CA 2 2009, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: AffirmTrust Premium, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: Certplus Root CA G1, Organization: Certplus, Country: FR
Package Control: Exported certificate: Common Name: SZAFIR ROOT CA, Organization: Krajowa Izba Rozliczeniowa S.A., Country: PL
Package Control: Exported certificate: Common Name: DigiCert Global Root G3, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: SwissSign Gold CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: T-TeleSec GlobalRoot Class 3, Organizational Unit: T-Systems Trust Center, Organization: T-Systems Enterprise Services GmbH, Country: DE
Package Control: Exported certificate: Common Name: GeoTrust Global CA, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: XRamp Global Certification Authority, Organization: XRamp Security Services Inc, Organizational Unit: www.xrampsecurity.com, Country: US
Package Control: Exported certificate: Common Name: DST Root CA X4, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Common Name: QuoVadis Root CA 1 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Organizational Unit: Go Daddy Class 2 Certification Authority; Organization: The Go Daddy Group, Inc.; Country: US
Package Control: Exported certificate: Common Name: Hongkong Post Root CA 1, Organization: Hongkong Post, Country: HK
Package Control: Exported certificate: Common Name: StartCom Certification Authority, Organizational Unit: Secure Digital Certificate Signing, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Email Address: acraiz@suscerte.gob.ve, Organizational Unit: Superintendencia de Servicios de Certificacion Electronica, Organization: Sistema Nacional de Certificacion Electronica, State/Province: Distrito Capital, Locality: Caracas, Country: VE, Common Name: Autoridad de Certificacion Raiz del Estado Venezolano
Package Control: Exported certificate: Common Name: Symantec Class 1 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Belgium Root CA2, Country: BE
Package Control: Exported certificate: Common Name: T-TeleSec GlobalRoot Class 2, Organizational Unit: T-Systems Trust Center, Organization: T-Systems Enterprise Services GmbH, Country: DE
Package Control: Exported certificate: Common Name: QuoVadis Root Certification Authority, Organizational Unit: Root Certification Authority, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: Amazon Root CA 1, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: AAA Certificate Services, Organization: Comodo CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: Buypass Class 2 Root CA, Organization: Buypass AS-983163327, Country: NO
Package Control: Exported certificate: Common Name: AddTrust Class 1 CA Root, Organizational Unit: AddTrust TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority; Organizational Unit: (c) 2006 Entrust, Inc., www.entrust.net/CPS is incorporated by reference; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - G2; Organizational Unit: (c) 2009 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: KISA RootCA 1, Organizational Unit: Korea Certification Authority Central, Organization: KISA, Country: KR
Package Control: Exported certificate: Common Name: Certinomis - Autorité Racine, Organizational Unit: 0002 433998903, Organization: Certinomis, Country: FR
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R2
Package Control: Exported certificate: Common Name: ComSign Secured CA, Organization: ComSign, Country: IL
Package Control: Exported certificate: Common Name: D-TRUST Root CA 3 2013, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: Starfield Services Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: ISRG Root X1, Organization: Internet Security Research Group, Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: Staat der Nederlanden EV Root CA, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: AddTrust External CA Root, Organizational Unit: AddTrust External TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: Symantec Class 1 Public Primary Certification Authority - G4, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: Izenpe.com, Organization: IZENPE S.A., Country: ES
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R3
Package Control: Exported certificate: Common Name: SwissSign Silver Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: thawte Primary Root CA; Organizational Unit: (c) 2006 thawte, Inc. - For authorized use only, Certification Services Division; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: Certum Trusted Network CA 2, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Common Name: thawte Primary Root CA - G2; Organizational Unit: (c) 2007 thawte, Inc. - For authorized use only; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: Symantec Class 2 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: Common Policy, Organizational Unit: FBCA, Organization: U.S. Government, Country: us
Package Control: Exported certificate: Common Name: Visa eCommerce Root, Organizational Unit: Visa International Service Association, Organization: VISA, Country: US
Package Control: Exported certificate: Organizational Unit: certSIGN ROOT CA, Organization: certSIGN, Country: RO
Package Control: Exported certificate: Common Name: Buypass Class 3 Root CA, Organization: Buypass AS-983163327, Country: NO
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: CFCA EV ROOT, Organization: China Financial Certification Authority, Country: CN
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G5; Organizational Unit: (c) 2006 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Organizational Unit: Trustis FPS Root CA, Organization: Trustis Limited, Country: GB
Package Control: Exported certificate: Common Name: Sonera Class2 CA, Organization: Sonera, Country: FI
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G4; Organizational Unit: (c) 2007 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G2, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: Apple Root Certificate Authority; Organizational Unit: Apple Computer Certificate Authority; Organization: Apple Computer, Inc.; Country: US
Package Control: Exported certificate: Common Name: Apple Root CA - G3, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: Federal Common Policy CA, Organizational Unit: FPKI, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Premium ECC, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Organizational Unit: Security Communication RootCA2; Organization: SECOM Trust Systems CO.,LTD.; Country: JP
Package Control: Exported certificate: Common Name: ANF Global Root CA, Serial Number: G63287510, Email Address: info@anf.es, Organizational Unit: ANF Clase 1 CA, Organization: ANF Autoridad de Certificacion, Locality: Barcelona (see current address at http://www.anf.es/es/address-direccion.html ), State/Province: Barcelona, Country: ES
Package Control: Exported certificate: Common Name: Admin-Root-CA; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: ch
Package Control: Exported certificate: Common Name: CA Disig Root R2, Organization: Disig a.s., Locality: Bratislava, Country: SK
Package Control: Exported certificate: Common Name: UTN - DATACorp SGC, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: OpenTrust Root CA G1, Organization: OpenTrust, Country: FR
Package Control: Exported certificate: Common Name: CA Disig Root R1, Organization: Disig a.s., Locality: Bratislava, Country: SK
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign ECC Root CA - R4
Package Control: Exported certificate: Common Name: Hellenic Academic and Research Institutions RootCA 2011, Organization: Hellenic Academic and Research Institutions Cert. Authority, Country: GR
Package Control: Exported certificate: Common Name: Network Solutions Certificate Authority, Organization: Network Solutions L.L.C., Country: US
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Organizational Unit: Security Communication RootCA1, Organization: SECOM Trust.net, Country: JP
Package Control: Exported certificate: Common Name: ApplicationCA2 Root, Organizational Unit: GPKI, Organization: Japanese Government, Country: JP
Package Control: Exported certificate: Common Name: Amazon Root CA 3, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: USERTrust ECC Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Organizational Unit: Starfield Class 2 Certification Authority; Organization: Starfield Technologies, Inc.; Country: US
Package Control: Exported certificate: Common Name: Certum CA, Organization: Unizeto Sp. z o.o., Country: PL
Package Control: Exported certificate: Common Name: NetLock Arany (Class Gold) Főtanúsítvány, Organizational Unit: Tanúsítványkiadók (Certification Services), Organization: NetLock Kft., Locality: Budapest, Country: HU
Package Control: Exported certificate: Common Name: Cisco Root CA 2048, Organization: Cisco Systems
Package Control: Exported certificate: Common Name: Certplus Root CA G2, Organization: Certplus, Country: FR
Package Control: Exported certificate: Common Name: Secure Global CA, Organization: SecureTrust Corporation, Country: US
Package Control: Exported certificate: Common Name: VeriSign Class 2 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign ECC Root CA - R5
Package Control: Exported certificate: Common Name: Symantec Class 3 Public Primary Certification Authority - G4, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Common Name: AffirmTrust Networking, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: Apple Root CA - G2, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Organizational Unit: Security Communication EV RootCA1; Organization: SECOM Trust Systems CO.,LTD.; Country: JP
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_cleanup in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 55, in run
  File "package_control.package_manager in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 2005, in record_usage
  File "package_control.download_manager in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 166, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 122, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 153, in extract_from_system
  File "package_control.deps.oscrypto._osx.trust_list in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 177, in _cert_callback
  File "package_control.ca_certs in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 108, in print_cert_subject
  File "package_control.deps.asn1crypto.x509 in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1035, in human_friendly
  File "package_control.deps.asn1crypto.core in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 3205, in __getitem__
  File "package_control.deps.asn1crypto.core in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 3200, in __getitem__
  File "package_control.deps.asn1crypto.core in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 3147, in _lazy_child
  File "package_control.deps.asn1crypto.core in /Users/stan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 5008, in _build
ValueError: Error parsing Package Control.package_control.deps.asn1crypto.x509.EmailAddress - tag should have been 22, but 19 was found
    while parsing Package Control.package_control.deps.asn1crypto.x509.NameTypeAndValue

**Comment by wbond** [comment]
Any change you can follow the instructions at https://github.com/wbond/package_control/issues/1302#issuecomment-352076439 to see if 3.3.1-beta4 fixes the issue for you?

**Comment by svitebskiy** [comment]
The version 3.3.1-beta4 seem has fixed it for me. Thank you very much!

**Comment by wbond** [comment]
Excellent. I should have 3.3.1 released soon.
