### ISSUE TITLE
Using Package Control shown as below:AttributeError: ValidatingHTTPSConnection instance has no attribute '_set_tunnel'

### ISSUE THREAD

**Issue by Uni-lovenix** [wbond/package_control#1299]
startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/newstart/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/newstart/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/0_package_control_loader/00-package_control.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/0_package_control_loader/02-bz2.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Emmet/emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Package Control/1_reloader.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Package Control/2_bootstrap.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/newstart/Library/Application Support/Sublime Text 2/Packages/SublimeLinter/SublimeLinter.py
imported capp_lint
imported pep8
imported pyflakes
imported pyflakes.api
imported pyflakes.checker
imported pyflakes.messages
imported pyflakes.reporter
SublimeLinter: Lua loaded
SublimeLinter: Squirrel loaded
SublimeLinter: Java loaded
SublimeLinter: Perl loaded
SublimeLinter: Ruby Haml loaded
SublimeLinter: HTML loaded
SublimeLinter: Git Commit Message loaded
SublimeLinter: XML loaded
SublimeLinter: puppet-lint loaded
SublimeLinter: Ruby loaded
SublimeLinter: Annotations loaded
SublimeLinter: CoffeeScript loaded
SublimeLinter: CSS loaded
SublimeLinter: Objective-J loaded
SublimeLinter: C loaded
SublimeLinter: Puppet loaded
SublimeLinter: Python loaded
SublimeLinter: ruby-lint loaded
SublimeLinter: PHP loaded
SublimeLinter: haskell loaded
SublimeLinter: JavaScript loaded
SublimeLinter: c_cpplint loaded
SublimeLinter: pylint loaded
plugin init time: 0.589695
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 1.21183
using gamma: 1.9 (err: 99.6544)
wrote startup cache, added files: 2 orphaned files: 3 total files: 103 cache hits: 101
startup time: 1.33652 (package setup was not run)
SublimeLinter: python enabled (built in)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2017-12-04 00:04:42, next run at 2017-12-04 01:04:42 or after
reloading /Users/newstart/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
Reloading /Users/newstart/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 2221
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/newstart/Library/Application Support/Sublime Text 2/Packages/User/oscrypto-ca-bundle.crt (275132 bytes)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "./package_control/commands/install_package_command.py", line 45, in run
  File "./package_control/package_installer.py", line 58, in make_package_list
  File "./package_control/package_manager.py", line 694, in list_available_packages
  File "./package_control/package_manager.py", line 554, in _list_available
  File "./package_control/package_manager.py", line 453, in list_repositories
  File "./package_control/providers/channel_provider.py", line 201, in get_repositories
  File "./package_control/providers/channel_provider.py", line 87, in fetch
  File "./package_control/download_manager.py", line 340, in fetch
  File "./package_control/downloaders/urllib_downloader.py", line 139, in download
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "./package_control/http/validating_https_handler.py", line 45, in https_open
  File "./package_control/http/persistent_handler.py", line 94, in do_open
AttributeError: ValidatingHTTPSConnection instance has no attribute '_set_tunnel'

**Comment by wbond** [comment]
It appears you are using Sublime Text 2 on macOS High Sierra. Unfortunately Apple swapped out Python 2.6 for 2.7, and thus a bunch of things with ST2 are broken. I highly recommend upgrading to ST3. We bundle our own build of Python 3 with that, and there have been hundreds of bug fixes and feature enhancements since ST2.

The next release of Package Control will be dropping support for ST2, mostly because very few users use ST2 (less than 5% of Package Control users), and things like High Sierra making ST2 unusable.
