### ISSUE TITLE
Issue with Restart package, won't restart after Package Control Install

### ISSUE THREAD

**Issue by wattry** [wbond/package_control#1303]
Repo: https://github.com/yedderson/SublimeRestart
Dev: yedderson on Github

I have been trying to reach the developer of the sublime Restart package, as the current version is not working on Sublime Text 3 for Windows. Looking at his activity he has been inactive on the issue board for over two years. There have been several other issues logged but no contact from dev or team.

The issue seems to be that when a package is installed, via Package Control, python's os.getcwd() method returns the Sublime Texts package install directory. I'm not sure if this was a change by Package Control's or Sublime's side.

I have written a working windows version and have requested a pull. Baring this I don't know what else to do. This package is a great supporting package for Package Control.

**Comment by FichteFoll** [comment]
https://github.com/wbond/package_control/blob/607b235946759e26c5907b1617b4c3b1793c7562/package_control/package_manager.py#L1524

I do not know why it does that.
