### ISSUE TITLE
New `next` branch for backward-incompatible work for 4.0.0.

### ISSUE THREAD

**Issue by Thom1729** [wbond/package_control#1310]
Per @deathaxe's suggestion [on the forums](https://forum.sublimetext.com/t/general-method-to-add-a-pypi-package-as-st-dependency/34081/5): create a new branch for changes planned for the ST3-only 4.0.0 release.

Low-hanging fruit for the new branch might be ripping out ST2 support and merging #1289.

**Comment by FichteFoll** [comment]
The API becoming thread-safe will probably be one of the most significant changes upstream with regard to stripping out ST2 cruft. Will also improve testability *significantly*.

**Comment by deathaxe** [comment]
I already got most (obvious) ST2 stuff ripped out. Digging into detail a bit to prepare a safe working PR as starting point for the `next` branch.

**Comment by wbond** [comment]
I see no reason to support anything older than build 3143 for 4.0.0. Everyone else can continue to use 3.3.1 until we decide to stop publishing channel schema_version 3.0.0.

**Comment by FichteFoll** [comment]
We have `four-point-oh` now.
