### ISSUE TITLE
Manual Installation of package control doesn't work

### ISSUE THREAD

**Issue by bgajjela** [wbond/package_control#1316]
Hello,

Iam following below link for manual installation of package control , it seems like it doesn't work for me. Please let me know if Iam missing anything

https://packagecontrol.io/Package%20Control.sublime-package

Error message:

DPI scale: 1
startup, version: 3103 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/bgajjel/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/bgajjel/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/bgajjel/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.342165
startup time: 0.411165
first paint time: 0.423165
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Trimmer.Trimmer
plugins loaded
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "2_bootstrap in C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 123, in _background_bootstrap
  File "package_control.loader in C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 207, in add_or_update
  File "package_control.loader in C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 291, in add
  File "./zipfile.py", line 919, in __init__
PermissionError: [Errno 13] Permission denied: '0_package_control_loader.sublime-package'

Package Control: Installing 2 missing dependencies
Package Control: Installed missing dependency bz2
Package Control: The dependency '0_package_control_loader' is not available
Package Control: Skipping automatic upgrade, last run at 2017-12-30 20:54:48, next run at 2017-12-30 21:54:48 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

**Comment by FichteFoll** [comment]
Delete the file `C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\0_package_control_loader.sublime-package`, then restart ST.

**Comment by bgajjela** [comment]
Thanks for the response @FichteFoll . I don't have "C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\0_package_control_loader.sublime-package" file. 

Although I have "C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\package_control_loader.sublime-package", which is downloaded  part of manual installation of Package Control.

**Comment by FichteFoll** [comment]
If you don't have the file, it's a permissions problem. The best way seems to revert your configuration and then try to install PC again. Refer to https://www.sublimetext.com/docs/3/revert.html.

**Comment by bgajjela** [comment]
Tried below steps to Revert Configuration:

1) Closed Sublime

2) Copied All dirs under "C:\Users\bgajjel\AppData\Roaming\Sublime Text 3" to different location

3) Started Sublime

4) Followed Manual Installation procedure for package control , still have the error. Below is the error

DPI scale: 1
startup, version: 3103 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/bgajjel/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/bgajjel/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/bgajjel/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.23006
startup time: 0.25006
first paint time: 0.25006
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
plugins loaded
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading Packages/Package Control/Package Control.sublime-settings
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "2_bootstrap in C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 123, in _background_bootstrap
  File "package_control.loader in C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 207, in add_or_update
  File "package_control.loader in C:\Users\bgajjel\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 291, in add
  File "./zipfile.py", line 919, in __init__
PermissionError: [Errno 13] Permission denied: '0_package_control_loader.sublime-package'

**Comment by evandrocoan** [comment]
> startup, version: 3103 windows x64 channel: stable

Try updating your Sublime Text to the latest version build 3143: https://www.sublimetext.com/3

**Comment by jzatarain** [comment]
I have the same problem, and also after updating, searching no longer work. I get something like "10 of 10 matches. Unable to find " + my search text.
I was going to try the revert thing, but it mentions a data folder, which I don't have; should I create one?

**Comment by bgajjela** [comment]
thanks @evandrocoan 

Fresh Install of  Sublime Text to the latest version build 3143: https://www.sublimetext.com/3 solved the problem
