### ISSUE TITLE
How to setup CI (Continuous Integration) for GitHub URL accesses?

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1319]
From:

1. https://github.com/wbond/package_control/issues/1317 Ran 60 tests, FAILED (failures=3, errors=7) 

We notice that all the failures are related to the accesses to the GitHub URLs, then there is no way to setup CI if we need a `client_id` and `client_secret` from GitHub.

1. https://developer.github.com/v3/guides/basics-of-authentication/

I have setup/implemented:

1. https://github.com/wbond/package_control/issues/1318 Replace the builtin tests runner by UnitTesting

On my fork of Package Control and added CL integration with Travis and AppVeyor:

[![Build Status](https://travis-ci.org/evandrocoan/PackagesManager.svg?branch=master)](https://travis-ci.org/evandrocoan/PackagesManager)
[![Build status](https://ci.appveyor.com/api/projects/status/lih43dhp29257fvv/branch/master?svg=true)](https://ci.appveyor.com/project/evandrocoan/packagesmanager/branch/master)
[![codecov](https://codecov.io/gh/evandrocoan/PackagesManager/branch/master/graph/badge.svg)](https://codecov.io/gh/evandrocoan/PackagesManager)
[![Coverage Status](https://coveralls.io/repos/github/evandrocoan/PackagesManager/badge.svg?branch=master)](https://coveralls.io/github/evandrocoan/PackagesManager?branch=master)
https://github.com/evandrocoan/PackagesManager

However, Coverage is not working due:

1. https://github.com/SublimeText/UnitTesting/issues/77 Not uploading coverage reports when there are tests failures/errors

Anyways, after solving how to pass `client_id` and `client_secret` for GitHub tests, everything should be working.

**Comment by evandrocoan** [comment]
I do now know how, but Travis just ran all the units on Ubuntu successfully:

1. https://travis-ci.org/evandrocoan/PackagesManager/jobs/325856632#L500

```
Start to read output...
............................................................
----------------------------------------------------------------------
Ran 60 tests in 8.037s

OK
```
But not is not always. It is apparently only one in three in a row.

However, AppVeyor (Windows) still failing the same tests:
```
Ran 60 tests in 19.462s
FAILED (failures=3, errors=7)
```

**Comment by deathaxe** [comment]
PC's unittests may perform a lot of API calls to various code hosters and thus may cause API limits to be hit.

To reduce the risk of doing so, proper authentication information need to be provided via environment variables.

The following lines are from https://github.com/wbond/package_control/blob/four-point-oh/package_control/tests/_config.py:

```
GH_USER = os.environ.get('GH_USER', 'packagecontrol-bot')
GH_PASS = os.environ.get('GH_PASS', '')

GL_USER = os.environ.get('GL_USER', 'wbond')
GL_PASS = os.environ.get('GL_PASS', '')

BB_USER = os.environ.get('BB_USER', 'wbond')
BB_PASS = os.environ.get('BB_PASS', '')
```

They are used to perform basic auth, which pushes the limits from 60 to 5000 API calls.
