### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by revolter** [wbond/package_control#1322]
Running `Package Control: Upgrade/Overwrite All Packages` prints this error in the console:

> Package Control: Using cached content for https://api.github.com/repos/sublime-ycmd/sublime-ycmd/commits?per_page=1&sha=master from /Users/revolt/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/6ce62bf9776109038b97c5024d839a98
Package Control: Repository http://sublime.wbond.net/repositories.json does not appear to be a valid repository file because  the "packages" key is an object, not an array. This indicates it is a channel not a repository.
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

It looks like it might be caused by the https://github.com/sublime-ycmd/sublime-ycmd package and related to https://github.com/sublime-ycmd/sublime-ycmd/issues/1.

Also,

> 6. Make sure you have the latest version of Package Control installed: 3.3.0

How?

> 4. Delete the folder named Package Control

There is no folder named `Package Control` in macOS at the location specified by the instructions.

**Comment by FichteFoll** [comment]
What are the contents of your `Packages/User/Package Control.sublime-settings` file?

**Comment by revolter** [comment]
```
{
	"bootstrapped": true,
	"debug": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"ANSIescape",
		"ApacheConf",
		"ApplySyntax",
		"BinaryPlist",
		"BracketHighlighter",
		"CSS Completions",
		"DashDoc",
		"Diffy",
		"Dotfiles Syntax Highlighting",
		"DuplicateSelections",
		"EML (E-Mail)",
		"Emmet",
		"Evaluate",
		"EZWebSequenceDiagrams",
		"FileSystem Autocompletion",
		"fish",
		"GhostText",
		"Git",
		"GitGutter",
		"GitSavvy",
		"Google Spell Check",
		"HexViewer",
		"Highlight",
		"HTML-CSS-JS Prettify",
		"HTMLBeautify",
		"INI",
		"Insert Nums",
		"JSLint",
		"JSON Reindent",
		"JsonTree",
		"JSX",
		"Keymaps",
		"Leaf",
		"Log Highlight",
		"MagicPython",
		"Markdown Preview",
		"MarkdownEditing",
		"Open URL",
		"Package Control",
		"Plist Binary",
		"Preferences Editor",
		"Python Breakpoints",
		"Python Checker",
		"Python Completions",
		"Random Everything",
		"Sass",
		"Schemr",
		"SerializedDataConverter",
		"Seti_UI",
		"Seti_UX",
		"SideBarEnhancements",
		"Smarty",
		"SortBy",
		"Status Bar File Size",
		"Statusbar Path",
		"Swift",
		"Sync View Scroll",
		"SyncedSideBar",
		"Text Pastry",
		"Themr"
	],
	"repositories":
	[
		"https://sublime.wbond.net/repositories.json",
		"http://sublime.wbond.net/repositories.json",
		"https://github.com/sublime-ycmd/sublime-ycmd"
	]
}
```

**Comment by FichteFoll** [comment]
You should remove the `repositories` key with all its entries.

[YouCompleteMe is available directly on Package Control](https://packagecontrol.io/packages/YouCompleteMe), so you shouldn't need to add it as a repository manually. The other two urls are deprecated since the release of PC 2.0, I think.

**Comment by revolter** [comment]
Shouldn't Package Control have removed that key when it was updated?

Also, I still can't find `YouCompleteMe`:

![screen shot 2018-01-14 at 20 09 38](https://user-images.githubusercontent.com/5748627/34919084-dece7a20-f966-11e7-88ae-a2ef7bd603f1.png)

**Comment by FichteFoll** [comment]
The key itself isn't redundant, but the `sublime.wbond.net` urls are. The setting shouldn't be within your user settings unless you edited it manually, so PC decided to not mess with the user setup here. It could have removed the URLs, but I believe it decided to go after the "if you changed it, you should know what you changed" principle.

For ycmd, I added an explanation at the dedicated issue. You can remove the two redudant URLs for now and keep the ycmd URL until that is resolved.

**Comment by revolter** [comment]
I completely removed the `repositories` key and added:

```json
"install_prereleases":
[
	"YouCompleteMe"
]
```

and it works. Thank you.
