### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by aspin** [wbond/package_control#1323]
Can't access packagecontrol.io

**Comment by jzgdev** [comment]
+1 for this issue

**Comment by ArcherFMY** [comment]
+1

**Comment by dave4jr** [comment]
+1

**Comment by wbyc816** [comment]
+1

**Comment by tjuyy** [comment]
+1

**Comment by MrZaphod** [comment]
+1

**Comment by stevechen** [comment]
+1

**Comment by RyoIshizawa** [comment]
+1

**Comment by Kochiya-Yoru** [comment]
+1

**Comment by kojisato2002** [comment]
+1

**Comment by zeeshanu** [comment]
+1

**Comment by 422563261** [comment]
+1

**Comment by HoiweCheng** [comment]
+1

**Comment by wbond** [comment]
We are back now. nginx didn't properly come back online after Linode moved the VM to a new host for the sake of Spectre/Meltdown mitigation. It didn't come back online sooner because I was asleep and didn't get the monitoring email. 🙂

**Comment by faraazahmad** [comment]
Aaaand its down again

**Comment by kadomcevi** [comment]
server down

**Comment by wbond** [comment]
@kadomcevi Details at https://forum.sublimetext.com/t/packagecontrol-io-not-working/47063/18?u=wbond

**Comment by kadomcevi** [comment]
still not works for me, when I try open link: 
https://packagecontrol.io/installation
browser got error
ERR_CONNECTION_REFUSED

$ curl  packagecontrol.io/unstallation
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>
