### ISSUE TITLE
https://packagecontrol.io is down?

### ISSUE THREAD

**Issue by dusmant** [wbond/package_control#1324]
Not able to access https://packagecontrol.io from any browser and ping to the url is also failing.

Webpage says 
"This site can’t be reached
packagecontrol.io refused to connect.

ERR_CONNECTION_REFUSED"

Even the ping also failed...
ping packagecontrol.io

Pinging packagecontrol.io [50.116.34.243] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 50.116.34.243:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

**Comment by kojisato2002** [comment]
I've been also occurred this problem.

**Comment by jacekbogdanski** [comment]
Me too, could someone paste package control installation script? I'm in need )

**Comment by 422563261** [comment]
Mark

**Comment by ondObno** [comment]
Same here: "Package Control: Error downloading channel. URL error [Errno 65] No route to host downloading https://packagecontrol.io/channel_v3.json.'

**Comment by arispati** [comment]
I've this problem too

**Comment by DocteurNo** [comment]
Moi aussi

**Comment by AkitakiKou** [comment]
Same here, both website and ping failed.

**Comment by nei** [comment]
+1

**Comment by Helfull** [comment]
+1

**Comment by sadgazm** [comment]
+1

**Comment by miquelmassot** [comment]
+1

**Comment by adummy832** [comment]
Oh god, thought twas my ISP. Btw, site can be pinged but still unable to access. 
+1 for this

**Comment by psykzz** [comment]
This is working for me now in Dublin, IE

**Comment by miquelmassot** [comment]
Working too from Spain

**Comment by wbond** [comment]
Back now. See https://github.com/wbond/package_control/issues/1323#issuecomment-357670341.

**Comment by dusmant** [comment]
Yes, it's working from India now. Thanks Wbond !!!
