### ISSUE TITLE
Upgrading package does not reload nested Python packages.

### ISSUE THREAD

**Issue by ehuss** [wbond/package_control#1325]
If I have a plugin with the following layout:

    MyPlugin/stuff/__init__.py
    MyPlugin/stuff/sub.py
    MyPlugin/plug.py

when the plugin is updated by Package Control, it does not seem to reload any nested Python packages, like `stuff` in this example, and will continue using the old code.  The top-level Python modules do get reloaded (`plug.py`).

Is there something my package should do to ensure that everything gets reloaded when it is upgraded?

If I am reading [this code](https://github.com/wbond/package_control/blob/1f551cc92afb95ba5ca4cd17270060de4f796ea1/package_control/automatic_upgrader.py#L238-L318) correctly, it looks like Package Control simply places the package into `ignored_packages`, updates it, and then takes it back out of the ignored packages.  I'm guessing this is not sufficient to completely reload the package.  Placing a package into `ignored_packages` does not unload any of the modules from `sys.modules`.  I'm wondering if simply removing all of the plugin's entries from `sys.modules` would work.

During development I use [AutomaticPackageReloader](https://github.com/randy3k/AutomaticPackageReloader), which seems to do the right thing.  However, it seems to be much more elaborate, and I'm uncertain if that is necessary.

Does anyone have any insight to this?

**Comment by FichteFoll** [comment]
Unsure if this is something that PC should handle, although it technically *could*. The thing is that Sublime Text itself does not reload sub-modules and -packages automatically when they change, nor when a package is changed/updated as done by Package Control. PC could work around this and do `sys.modules` pruning manually, although I wonder whether this would be better suited to happen directly inside ST's plugin handling code instead. It should be noted that this is separate from simple plugin loading, as plugins (Python files in the package root) need to share the same environment.

The reloading behavior *might* break plugins in unpredictable ways if they relied on the property of *not* being reloaded under any circumstances, but I'm not aware of any such plugin. It should be noted that any other package importing something from the updated package will result in references to the old version still being held and that in return could lead to unpredictable results. The most popular example for this would be SublimeLinter and its linter plugins, which all import from the core linter to interface with its API. SublimeLinter itself demands a restart of ST in its update message anyway, but this is just an example.

**Comment by ehuss** [comment]
I have opened an issue on SublimeTextIssues since I agree this is probably not Package Control-specific.  There is already some code in `sublime_plugin.py` to delete modules from `sys.modules`, but doesn't clean up everything.  Leaving this open since I'm uncertain if this is something that Package Control should do anything about, but feel free to close this if you agree it should be fixed in Sublime.

**Comment by evandrocoan** [comment]
> The reloading behavior might break plugins in unpredictable ways if they relied on the property of not being reloaded under any circumstances, but I'm not aware of any such plugin.

My dependency https://github.com/evandrocoan/debugtools/blob/1f033f6b9dacf03a9bde670bec84e9634a4d54b3/all/debug_tools/stderr_replacement.py#L205-L208 can be reloaded, it just cannot be completely deleted from memory, otherwise `sys.stderr` and `sys.stdout` are set to `None` and the Sublime Text console dies:
1. https://github.com/randy3k/AutomaticPackageReloader/issues/26 Reload first dependency's dependencies when reloading a dependency

**Comment by evandrocoan** [comment]
After reading more about the complications this will bring upon Package Control code, the best solution should be just show a big pop up asking for the User to restart Sublime Text when some package is upgraded.

**Comment by wbond** [comment]
Closing as this is would be solved by ST core, if we decide to try and solve it "automagically".
