### ISSUE TITLE
when i am trying to open my sublime 3. this error appears on my screen. Error trying to parse setting:Unexpected trailing characters in Packages/User/Emmet.sublime-setting:1:30

### ISSUE THREAD

**Issue by bhupesh-IVIN** [wbond/package_control#1326]

**Comment by FichteFoll** [comment]
This has absolutely nothing to do with Package Control.

I suggest looking at the file and position that the error suggest and fix the invalid JSON there.

**Comment by evandrocoan** [comment]
You should open an issue on https://github.com/sergeche/emmet-sublime/issues if you just installed the emmet package and did nothing else. 

Also, post the contents of your file on `Packages/User/Emmet.sublime-setting`. You can open the `Packages` folder by going on the Sublime Text menu `Preferences -> Browse Packages...`: 

![image](https://user-images.githubusercontent.com/5332158/35684003-b569dd70-074c-11e8-97c0-a4053bd73758.png)
