### ISSUE TITLE
Check output panels for used syntaxes when updating

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#1331]
In addition to checking all views, PC needs to check all output panels for potentially used syntaxes before disabling and updating a package.

Possibly related: #964

**Comment by keith-hall** [comment]
It'd also be cool if it'd check `Packages/Default/Regex Replace Widget.sublime-settings` etc.

**Comment by deathaxe** [comment]
Output panels will be backedup/reset by PC4.0

As a syntax is assigned to all major widgets (Console Input, Regexp, Location, Regexp Replace) I am uncertain, whether backup/restore is still relevant. Maybe got uncommon enough for them to be customized.
