### ISSUE TITLE
HexViewer and RegReplace cannot be installed

### ISSUE THREAD

**Issue by neremin** [wbond/package_control#1341]
I could not install HexViewer and RegReplace packages using the latest Sublime Text 3 build for x86. Package Control tries to connect the server and just does nothing after that. Could you help me with this issue?

**Comment by neremin** [comment]
Seems to be Package Control issue. Posted issues to their page.

**Comment by wbond** [comment]
You should follow the guidelines at https://github.com/wbond/package_control/issues/new and include a debug log.
