### ISSUE TITLE
There are no packages availables for installation 

### ISSUE THREAD

**Issue by seotkd** [wbond/package_control#1347]
DPI scale: 1
startup, version: 3047 windows x32 channel: stable
executable: /E/Sublime Text/SublimeText.exe
working dir: /E/Sublime Text
packages path: /E/Sublime Text/Data/Packages
state path: /E/Sublime Text/Data/Local
hardware concurrency: 2
zip path: /E/Sublime Text/Packages
zip path: /E/Sublime Text/Data/Installed Packages
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 5 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 158 cache hits: 158
pre session restore time: 0.827322
startup time: 1.03032
first paint time: 1.04632
launching: /E/Sublime Text/plugin_host.exe
loaded 837 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.Encoding
reloading plugin Default.EncodingHelper
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin GBK Support.sublime_gbk
reloading plugin Emmet.emmet-plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Emmet: No need to update PyV8
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x32
  Sublime Text Version: 3047
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: packagecontrol.io
    issuer: US, GeoTrust Inc., RapidSSL SHA256 CA
    common name: packagecontrol.io
    issue date: Sun, 27 Nov 2016 08:00:00 GMT
    expire date: Thu, 28 Nov 2019 07:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  If-Modified-Since: Sat, 10 Mar 2018 01:20:05 GMT
  If-None-Match: W/"5aa332c5-317263"
  Accept-Encoding: gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sun, 11 Mar 2018 10:01:38 GMT
  Content-Type: application/json
  Last-Modified: Sun, 11 Mar 2018 10:00:05 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  ETag: W/"5aa4fe25-317265"
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Exception in thread Thread-3:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 111, in run
    self.install_missing()
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 143, in install_missing
    if self.installer.manager.install_package(dependency, is_dependency=True):
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\package_manager.py", line 1009, in install_package
    packages = self.list_available_dependencies()
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\package_manager.py", line 678, in list_available_dependencies
    return self._list_available()[1]
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\package_manager.py", line 554, in _list_available
    repositories = self.list_repositories()
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\package_manager.py", line 453, in list_repositories
    channel_repositories = provider.get_repositories()
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\providers\channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\providers\channel_provider.py", line 87, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\download_manager.py", line 340, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\downloaders\wininet_downloader.py", line 648, in download
    result = self.decode_response(encoding, result)
  File "E:\Sublime Text\Data\Packages\Package Control\package_control\downloaders\decoding_downloader.py", line 60, in decode_response
    return gzip.GzipFile(fileobj=StringIO(response)).read()
  File "X/gzip.py", line 358, in read
  File "X/gzip.py", line 454, in _read
  File "X/gzip.py", line 486, in _read_eof
  File "X/gzip.py", line 69, in read32
struct.error: unpack requires a bytes object of length 4

Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request

**Comment by SEOTKD** [comment]
Sorry, I don't konw what happend，I get a cache ，today is ok! **but unsteadiness**

> Package Control: Caching https://packagecontrol.io/channel_v3.json in E:\Sublime Text\Data\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414

**Comment by SEOTKD** [comment]
I get that. The cause of unseadiness，because of request and return does not   match. @wbond 
**compare diffs:** _If-Modified-Since / If-None-Match_ and  _Last-Modified / E-tag_，Update every ten minutes，It causes me to keep cache

> Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: bzip2,gzip,deflate
  If-Modified-Since: Mon, 12 Mar 2018 03:00:06 GMT
  If-None-Match: "5aa5ed36-4fa39"
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Mon, 12 Mar 2018 03:13:14 GMT
  Content-Type: application/json
  Content-Length: 323785
  Last-Modified: Mon, 12 Mar 2018 03:10:07 GMT
  Connection: keep-alive
  ETag: "5aa5ef8f-4f0c9"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Accept-Ranges: bytes
