### ISSUE TITLE
Inconsistent permissions for installed package

### ISSUE THREAD

**Issue by twolfson** [wbond/package_control#1348]
In https://github.com/wbond/sublime_terminal/issues/171#issuecomment-372095756, OS X users were reporting that some of our scripts which have the executable flag set were not receiving said flag when being installed:

https://github.com/wbond/sublime_terminal/issues/171#issuecomment-372095756

Unfortunately, I don't have time at the moment to fully look into this but it sounds like something that would be relatively easy to reproduce if you have a Package Control channel already set up

The reporters are also saying that the permissions can change on reinstall

Any idea what might be causing this?

**Comment by chenzeZzz** [comment]
![image](https://user-images.githubusercontent.com/24696566/45858361-9f933d80-bd8f-11e8-95b6-52a97f9d1883.png)

**Comment by deathaxe** [comment]
Fixed by PC 4.0.0-beta9
