### ISSUE TITLE
Personal access token

### ISSUE THREAD

**Issue by arsham** [wbond/package_control#1355]
Hi,

I was wondering if incorporating a personal `access_token` would help eliminate the `Rate limit of 60 exceeded for api.github.com` problem?

Thanks.

**Comment by deathaxe** [comment]
Package Control 4 supports HTTP basic auth.

```
	"http_basic_auth": 	{
	    "api.github.com": ["username", "personal access token"],
	    "gitlab.com": ["username", "personal access token"],
	    "api.bitbucket.org": ["username", "app password"],
	}
```
