### ISSUE TITLE
Invalid Certificate and Package Control.merged-ca-bundle - partial solution on OS X

### ISSUE THREAD

**Issue by hfreville** [wbond/package_control#1358]
Hello,

I was unable to install new packages due to "Invalid Certificate" error
After trying several solution, i'm pretty sure problem is that file " Package Control.merged-ca-bundle" is not correctly generated (maybe related to #1302 )

I found a solution replacing this file by cert bundle provided by curl from MacPorts (https://www.macports.org/) and changing file permission to be sure file is not overwritten

If you have curl installed :
```
cp /opt/local/share/curl/curl-ca-bundle.crt "/Users/<USERNAME>/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle"
chmod u-w "/Users/<USERNAME>/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle"
```

Hope it will help

**Comment by dwasss** [comment]
I don't have MacPorts but I have curl also installed with homebrew, though I couldn't figure out how to make that work.

I can confirm following the steps in https://github.com/wbond/package_control/issues/1302#issuecomment-352076439 (basically deleting anything Package Control related and installing the prerelease version) I was able to finally get it to work and install packages.

**Comment by deathaxe** [comment]
Closing with regards to #1302 as this error was most likely caused by encoding issues in asn1crypto.
