### ISSUE TITLE
Sublime Semver Support

### ISSUE THREAD

**Issue by Thom1729** [wbond/package_control#1362]
It would be easier for package authors to declare sublime version support using semantic version numbers instead of build numbers, such as `">=3.0"` rather than `">=3000"`. I think that this would significantly reduce the number of package submissions that declare the wrong version (e.g. 3000 when the package includes a sublime-syntax). Developers targeting dev builds could still declare them.

**Comment by FichteFoll** [comment]
The downside is that we'd require a lookup table for all previous and future release versions to translate them back to build numbers because you don't get the semantic number from the API. 

I don't think this is necessary tbh.

**Comment by deathaxe** [comment]
With ST~~4~~ dropping versioning, that change doesn't make sense anymore.
