### ISSUE TITLE
python error on plugin execution/build

### ISSUE THREAD

**Issue by SeerKan** [wbond/package_control#1364]
Hi,

I installed the package manager and installed some docker build plugin. Everything seemed ok but when I try to build something I dies with:

`Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 1034, in run_
    return self.run(**args)
  File "/opt/sublime_text_3/Packages/Default.sublime-package/exec.py", line 271, in run
FileNotFoundError: [Errno 2] No such file or directory: 'file_path'`

I have sublime 3 build 3176 on archlinux.

Thanks.

**Comment by FichteFoll** [comment]
This definitely doesn't look like an issue with Package Control, but rather that the external docker build plugin specifies an incorred `working_dir` in its build system (or however it invokes the `exec` command).
