### ISSUE TITLE
Package Control: Error downloading channel. curl: (35) SSL: CA certificate set, but certificate verification is disabled downloading https://packagecontrol.io/channel_v3.json.

### ISSUE THREAD

**Issue by michelleowen** [wbond/package_control#1365]
When I tried to do Package Control: Install Package, I got no packages available for installation error. Please find the detailed log below:

Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3126
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 10.124.7.14
Package Control: Found previously exported CA bundle at /Users/louyang11/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (326177 bytes)
Package Control: Curl Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Trying to execute command /usr/bin/curl --connect-timeout 30 -sSL --tlsv1 --dump-header /var/folders/87/3f0js3zj5yq37mkm_40gt9mj0wdr27/T/tmprlsgvu --user-agent 'Package Control v3.3.0' --header 'Accept-Encoding: bzip2,gzip,deflate' --cacert '/Users/louyang11/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle' -v https://packagecontrol.io/channel_v3.json
Package Control: Curl HTTP Debug Write
    Trying 69.191.241.9...
  Connected to proxy.bloomberg.com (69.191.241.9) port 81 (#0)
  Establish HTTP proxy tunnel to packagecontrol.io:443
Package Control: Curl HTTP Debug Read
  CONNECT packagecontrol.io:443 HTTP/1.1
  Host: packagecontrol.io:443
  User-Agent: Package Control v3.3.0
  Proxy-Connection: Keep-Alive
Package Control: Curl HTTP Debug General
  HTTP/1.1 200 Connection established
Package Control: Curl HTTP Debug General
  Proxy replied OK to CONNECT request
  SSL: CA certificate set, but certificate verification is disabled
  Closing connection 0
Package Control: Error downloading channel. curl: (35) SSL: CA certificate set, but certificate verification is disabled downloading https://packagecontrol.io/channel_v3.json.

**Comment by mmaithani** [comment]
go for official documention of package install website

**Comment by Gilbert-Changky** [comment]
Facing the same error...How's your problem?

**Comment by deathaxe** [comment]
Has been fixed by 3.4.1
