### ISSUE TITLE
package control - install

### ISSUE THREAD

**Issue by pitarf** [wbond/package_control#1369]
Done!
(node:10092) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:10092) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
(node:10092) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by wbond** [comment]
Package Control does not use node.
