### ISSUE TITLE
packagecontrol.io certificate untrusted starting with Chrome 70

### ISSUE THREAD

**Issue by silverwind** [wbond/package_control#1374]
Using Chrome Canary 70, one gets this error when opening https://packagecontrol.io

````
NET::ERR_CERT_SYMANTEC_LEGACY
Subject: packagecontrol.io
Issuer: RapidSSL SHA256 CA
Expires on: Nov 28, 2019
````

Also see https://security.googleblog.com/2018/03/distrust-of-symantec-pki-immediate.html.

**Comment by wbond** [comment]
Yeah, I have a new certificate. Should be getting this installed in the next month or so.

**Comment by wbond** [comment]
The certificate has been updated to one issued by DigiCert
