### ISSUE TITLE
Package control doesnt install new packages like sublimepuppet

### ISSUE THREAD

**Issue by Altanaib** [wbond/package_control#1377]
Observing the following bug from console 

```
indexing: Unable to write to index, index is likely corrupted, and will be recreated after restarting.
Package Control: Error parsing JSON from channel https://packagecontrol.io/channel_v3.json.
Package Control: Error parsing JSON from URL https://api.github.com/repos/russCloak/SublimePuppet.
```

tried accessing the above mentioned repos directly they are up and valid . For exmaple one of them is for SublimePuppet , which can be found under 
https://github.com/russCloak/SublimePuppet

**Comment by deathaxe** [comment]
PC got a broken channel_v3.json and therefore wasn't able to perform any other action.
