### ISSUE TITLE
Package control: error 

### ISSUE THREAD

**Issue by MLHFOX** [wbond/package_control#1388]
Package Control: Installing 1 missing dependency
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate (_ssl.c:493: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version)) downloading https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0.
error: Package Control

Où je peux installer les fichiers de "https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0." ? Que puis-je faire ? Je n'arrive toujours pas à utiliser Emmet à cause de ça. D'avance merci. 
Je suis sur: 
OS X: Yosmite 
Version 10.10.2

**Comment by reber0** [comment]
I have the same problem


startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/reber/Library/Application Support/Sublime Text 3/Packages
state path: /Users/reber/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/reber/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.196383
using gpu buffer for window
first paint time: 0.298826
startup time: 0.300075
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin Emmet.emmet-plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin Codecs33.Codecs33
reloading plugin ConvertToUTF8.ConvertToUTF8
plugins loaded
Detected ASCII vs UTF-8 with 100% confidence
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: You have the most recent PyV8 binary
Package Control: No updated packages
ignored packages updated to: ["GitHubinator", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/ehamiter/GitHubinator/zip/master.
error: Package Control

Unable to download GitHubinator. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["GitGutter", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/jisaacks/GitGutter/zip/1.9.5.
error: Package Control

Unable to download GitGutter. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings


macOS Sierra 10.12.6

**Comment by reber0** [comment]
I have the same problem

startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/xxx/Library/Application Support/Sublime Text 3/Packages
state path: /Users/xxx/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.196383
using gpu buffer for window
first paint time: 0.298826
startup time: 0.300075
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin Emmet.emmet-plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin Codecs33.Codecs33
reloading plugin ConvertToUTF8.ConvertToUTF8
plugins loaded
Detected ASCII vs UTF-8 with 100% confidence
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: You have the most recent PyV8 binary
Package Control: No updated packages
ignored packages updated to: ["GitHubinator", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/ehamiter/GitHubinator/zip/master.
error: Package Control

Unable to download GitHubinator. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["GitGutter", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/jisaacks/GitGutter/zip/1.9.5.
error: Package Control

Unable to download GitGutter. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

macOS Sierra 10.12.6

**Comment by FichteFoll** [comment]
It seems you're using an old version of Sublime Text 2. Update to Sublime Text 3.

**Comment by frankfarm** [comment]
I encountered the same problem that @MLHFOX had. I am using Sublime Text 2 and a new installation of macOS Mojave. I encountered "Unable to download bz2" every time upon starting or launching Sublime Text 2 after installing Package Control. I resolved it like this:

Press Cmd+Shift+P to open the Command Palette then type 'package' then select 'Preferences: Package Control Settings - User' then add "downloader_precedence": { "osx": ["curl"] }, to the first line of the settings file after the opening curly brace (checking that the syntax is correct if other settings were present). Here's what the entire Package Control.sublime-settings file now looks like (although github has stripped out my tabs and line breaks):

`{
	"downloader_precedence": { "osx": ["curl"] },
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Package Control"
	]
}
`

Save, then after a few seconds you should see a dialog: 'Package Control: 1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.'

![Screen Shot 2019-03-26 at 12 51 40](https://user-images.githubusercontent.com/11372252/55030339-6bf8d080-4fc9-11e9-9967-5a8184be416d.png)

Restart Sublime Text 2 and the problem should be gone.

This answer comes by way of @fabritw at #1134 even though that's not exactly the same problem and even though that issue mentions Sublime Text 3 instead of ST2.

**Comment by wbond** [comment]
@frankfarm Sublime Text 2 does not properly work on Mojave, nor High Sierra. Some of it will work, but other things are broken and can't be fixed since Apple changed Python 2.6 to 2.7 behind the scenes.

Beyond that, Sublime Text 2 is unsupported by Sublime HQ, and Sublime Text 3 is leaps and bounds beyond ST2 in almost every regard.

The next release of Package Control will likely be dropping ST2 support.
