### ISSUE TITLE
Dependency dependencies

### ISSUE THREAD

**Issue by Thom1729** [wbond/package_control#1391]
Currently, packages may have dependencies, but dependencies may not themselves have dependencies. This means that dependencies must either vendor the code they depend on (partly defeating the purpose of having dependencies) or advise packages to declare extra dependencies. In the latter case, the dependency author must also declare the correct loading order.

Instead, dependencies could declare other dependencies in the same way as packages. Then, load order can be determined by a topological sort. (To ensure backward compatibility, PC should load dependencies with a declared loading order in that order, then load all other dependencies in topological order.)

The advantages of this approach are:

- Dependencies never have to vendor code that's already available as another dependency.
- A dependency adding code that relies on another dependency is no longer a breaking change.
- Dependency authors no longer have to manually determine load order. A change in load order is no longer breaking.
- Packages only have to declare dependencies that they use directly, not dependencies of dependencies.
- It should be safe to load dependencies as soon as they are installed (without restarting Sublime).

**Comment by Thom1729** [comment]
I should mention that I'm willing to implement this myself; I'd just like to get some feedback before spending the time to do so.

**Comment by FichteFoll** [comment]
I believe there is some more important stuff to do first, like moving dependencies to the Lib folder and extracting them properly or getting rid of st2 code paths, but this is generally much appreciated from my side.

**Comment by Thom1729** [comment]
I think that these things are orthogonal. This would be a fairly small code change; much, much smaller than the ST2 deprecation (#1313) and likely smaller than moving dependencies (although I'm not clear on exactly how that would work). I don't think there's any need to do one before the others.

**Comment by FichteFoll** [comment]
True enough.

PC does need some work, but implementing dependency dependencies is probably an easy addition on top of the current features and imo definitely worthwhile to implement *and* support.
