### ISSUE TITLE
Package control does not install new package

### ISSUE THREAD

**Issue by nickriches** [wbond/package_control#1394]
Hi. Package control seems to have broken. When I select install "Package Control: Install Package" and then the name of the package, nothing happens. I sync my user folder via DropBox (NB I am careful to follow instructions, and do not sync the packages themselves). Below is the full log. thanks

startup, version: 3176 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/nickriches/Library/Application Support/Sublime Text 3/Packages
state path: /Users/nickriches/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/nickriches/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["0_package_control_loader", "Markdown", "Vintage"]
Error loading commands: Error trying to parse file: Expected value in Packages/User/Default.sublime-commands:1:2
"Packages/Color Scheme - Default/Espresso Libre.tmTheme" is no longer maintained and is now part of "Color Scheme - Legacy"
pre session restore time: 0.538998
startup time: 0.729908
environment variables loaded using: /bin/bash -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin BracketHighlighter.bh_core
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/nickriches/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 16, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/nickriches/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package/bh_rules.py", line 7, in <module>
ImportError: cannot import name bre
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/nickriches/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package/bh_rules.py", line 7, in <module>
ImportError: cannot import name bre
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Fix Mac Path.FixPath
reloading plugin Glue.__init__
reloading plugin Glue.Glue
reloading plugin Glue.GlueBrowser
reloading plugin Glue.GlueCmds
reloading plugin Glue.GlueIO
reloading plugin Glue.GlueSidebarOpener
reloading plugin LaTeXTab.latextab
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.folding
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.list_back_links
reloading plugin MarkdownEditing.make_page_reference
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.open_home_page
reloading plugin MarkdownEditing.open_journal
reloading plugin MarkdownEditing.open_page
reloading plugin MarkdownEditing.prepare_from_template
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.replace_selected_command
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin MarkdownEditing.wiki_page
reloading plugin MarkdownPreview.markdown_preview
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/nickriches/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 14, in <module>
ImportError: No module named 'yaml'
reloading plugin MarkdownPreview.markdown_settings
reloading plugin MarkdownPreview.markdown_wrapper
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/nickriches/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownPreview.sublime-package/markdown_wrapper.py", line 4, in <module>
ImportError: No module named 'markdown'
reloading plugin MarkdownTOC.__init__
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin R-Box.rbox
reloading plugin SendCode.commands
reloading plugin SendCode.settings
reloading plugin SendCode.textgetter
reloading plugin SendCode.textsender
reloading plugin SendCode.update_resources
reloading plugin SendText.SendText
reloading plugin SnippetMaker.SnippetMaker
reloading plugin Sublime Bookmarks.bookmark
reloading plugin Sublime Bookmarks.bookmarkWatcher
reloading plugin Sublime Bookmarks.common
reloading plugin Sublime Bookmarks.sublimebookmark
reloading plugin Sublime Bookmarks.ui
reloading plugin Sublime Bookmarks.visibilityHandler
reloading plugin View In Browser.ViewInBrowserCommand
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin LaTeXTools.01_reload_submodules
reloading plugin LaTeXTools.02_temp_file_cleanup
reloading plugin LaTeXTools.03_reset_phantoms
reloading plugin LaTeXTools.biblatex_crossref_completions
reloading plugin LaTeXTools.biblatex_field_name_completions
reloading plugin LaTeXTools.biblatex_name_completions
reloading plugin LaTeXTools.biblatex_snippet_completions
reloading plugin LaTeXTools.biblatex_syntax_listener
reloading plugin LaTeXTools.change_environment
reloading plugin LaTeXTools.create_mousemap
reloading plugin LaTeXTools.delete_temp_files
reloading plugin LaTeXTools.detect_spellcheck
reloading plugin LaTeXTools.getRegion
reloading plugin LaTeXTools.getTeXRoot
reloading plugin LaTeXTools.jumpto_anywhere
reloading plugin LaTeXTools.jumpto_tex_file
reloading plugin LaTeXTools.jumpToPDF
reloading plugin LaTeXTools.kpsewhich
reloading plugin LaTeXTools.latex_cite_completions
reloading plugin LaTeXTools.latex_cwl_completions
reloading plugin LaTeXTools.latex_directive_completions
reloading plugin LaTeXTools.latex_env_completions
reloading plugin LaTeXTools.latex_fill_all
reloading plugin LaTeXTools.latex_glossary_completions
reloading plugin LaTeXTools.latex_input_completions
reloading plugin LaTeXTools.latex_installed_packages
reloading plugin LaTeXTools.latex_own_command_completions
reloading plugin LaTeXTools.latex_ref_completions
reloading plugin LaTeXTools.latexCommand
reloading plugin LaTeXTools.latexDocumentationViewer
reloading plugin LaTeXTools.latexEnvCloser
reloading plugin LaTeXTools.latexEnvironment
reloading plugin LaTeXTools.latextools_cache_listener
reloading plugin LaTeXTools.latextools_default_settings
reloading plugin LaTeXTools.latextools_plugin
reloading plugin LaTeXTools.latextools_sublime_version_listener
reloading plugin LaTeXTools.makePDF
reloading plugin LaTeXTools.migrate
reloading plugin LaTeXTools.open_detexify
reloading plugin LaTeXTools.parseTeXlog
reloading plugin LaTeXTools.search_commands
reloading plugin LaTeXTools.system_check
reloading plugin LaTeXTools.texcount
reloading plugin LaTeXTools.texMacro
reloading plugin LaTeXTools.texSections
reloading plugin LaTeXTools.texSyntaxListener
reloading plugin LaTeXTools.toc_quickpanel
reloading plugin LaTeXTools.toggle_auto
reloading plugin LaTeXTools.toggle_focus
reloading plugin LaTeXTools.toggle_fwdsync
reloading plugin LaTeXTools.toggle_show
reloading plugin LaTeXTools.toggle_view_on_build
reloading plugin LiveReload.__init__
reloading plugin LiveReload.CoffeescriptPlugin
reloading plugin LiveReload.CommandAPI
reloading plugin LiveReload.CompassPlugin
reloading plugin LiveReload.LESSPlugin
reloading plugin LiveReload.LiveReload
reloading plugin LiveReload.SimpleReloadCallback
reloading plugin LiveReload.SimpleReloadPlugin
reloading plugin LiveReload.SimpleReloadPluginDelay
reloading plugin LiveReload.SimpleWSCallback
reloading plugin PlainTasks.APlainTasksCommon
reloading plugin PlainTasks.PlainTasks
reloading plugin PlainTasks.PlainTasksDates
reloading plugin PlainTasks.PlainTasksToHTML
reloading plugin PlainTasks.plist_parser
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin SublimeSnippetMaker.SnippetMaker
reloading plugin TodoReview.TodoReview
plugins loaded
Loaded LaTeXTools plugins ['base_viewer'] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers/base_viewer.py
Loaded LaTeXTools plugins ['skim_viewer', 'sumatra_viewer', 'okular_viewer', 'command_viewer', 'evince_viewer', 'preview_viewer', 'zathura_viewer'] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers
Loaded LaTeXTools plugins ['pdf_builder'] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/pdfBuilder.py
Loaded LaTeXTools plugins ['basic_builder', 'simple_builder', 'script_builder', 'traditional_builder'] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders
LiveReload: added file /livereload.js with content-type: text/javascript
Loading LaTeXTools plugins...
INFO:WebSocketClient:Starting server
Running "/usr/local/bin/gs -version"
Loaded LaTeXTools plugins ['new_bibliography', 'traditional_bibliography'] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins
Loaded LaTeXTools plugins [] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers/base_viewer.py
Loaded LaTeXTools plugins [] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers
/Users/nickriches/Library/Application Support/Sublime Text 3
LOADING BOOKMARKS
Loaded LaTeXTools plugins [] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/pdfBuilder.py
Loaded LaTeXTools plugins [] from path /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders
Package Control: Skipping automatic upgrade, last run at 2018-12-21 08:33:31, next run at 2018-12-21 09:33:31 or after
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3176
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: ::ffff:50.116.34.243
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (278588 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Using hostname "packagecontrol.io" for TLS SNI extension
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher ECDHE-RSA-AES128-GCM-SHA256
  Server SSL certificate:
    subject: CN=packagecontrol.io
    subject alt name: packagecontrol.io, www.packagecontrol.io
    expire date: Nov 27 12:00:00 2019 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-None-Match: "5c1ca93f-53dd9"
  Connection: Keep-Alive
  Accept-Encoding: bzip2,gzip,deflate
  If-Modified-Since: Fri, 21 Dec 2018 08:50:07 GMT
  Host: packagecontrol.io
  User-Agent: Package Control v3.3.0
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Fri, 21 Dec 2018 08:59:08 GMT
  Content-Type: application/json
  Last-Modified: Fri, 21 Dec 2018 08:50:07 GMT
  Connection: keep-alive
  ETag: "5c1ca93f-53dd9"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/nickriches/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Traceback (most recent call last):
  File "/Users/nickriches/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 154, in on_done
  File "/Users/nickriches/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_disabler.py", line 76, in disable_packages
ImportError: No module named 'package_control'

**Comment by FichteFoll** [comment]
It seems that `"0_package_control_loader"` ended up in your `ignored_packages` list. Removing that should solve all your issues.

**Comment by nickriches** [comment]
Brill. Thanks. That works. I am not sure how that ended up under "ignored packages"

**Comment by k0pch4** [comment]
DPI scale (detected): 1
startup, version: 3176 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/apoorv/.config/sublime-text-3/Packages
state path: /home/apoorv/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/apoorv/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
unable to write startup cache to /home/apoorv/.config/sublime-text-3/Cache/Default/Startup.cache
pre session restore time: 0.761901
startup time: 0.828367
first paint time: 0.834825
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/opt/sublime_text/Packages/Package Control.sublime-package/2_bootstrap.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/opt/sublime_text/Packages/Package Control.sublime-package/package_control/bootstrap.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/opt/sublime_text/Packages/Package Control.sublime-package/package_control/loader.py", line 57, in <module>
  File "./python3.3/posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/opt/sublime_text/Packages/Package Control.sublime-package/Package Control.py", line 14, in <module>
  File "./python3.3/posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
reloading plugin ShellScript.ShellScript
plugins loaded
Error installing Package Control: HTTPS error encountered, falling back to HTTP - <urlopen error [Errno -2] Name or service not known>
Error installing Package Control: HTTP error encountered, giving up - <urlopen error [Errno -2] Name or service not known>
error: An error occurred installing Package Control

Please check the Console for details

Visit https://packagecontrol.io/installation for manual instructions
Unable to open /home/apoorv/.config/sublime-text-3/Packages/Package Control/Package Control.sublime-settings
Error installing Package Control: [Errno 13] Permission denied: '/home/apoorv/.config/sublime-text-3/Installed Packages/Package Control.sublime-package'
error: An error occurred installing Package Control

Please check the Console for details

Visit https://packagecontrol.io/installation for manual instructions
Unable to write session file: /home/apoorv/.config/sublime-text-3/Local/Auto Save Temp Session.sublime_session



I am haing similar issues too.

**Comment by john-cj** [comment]
Same issue here today. For some reason `0_package_control_loader` was listed under ignored packages. What could be a reason?
