### ISSUE TITLE
Package Control: There are no packages available for installation/Server Error

### ISSUE THREAD

**Issue by laidbackwebsage** [wbond/package_control#1397]
None of the other issues have the same underlying symptoms as mine, hence, new issue.

Here is  the output from ST3 Console (replaced actual home directory path with "$HOME"):

```
DPI scale (detected): 1
startup, version: 3176 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: $HOME
packages path: $HOME/.config/sublime-text-3/Packages
state path: $HOME/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: $HOME/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0417539
startup time: 0.10296
first paint time: 0.10454
scan: $HOME/.config/menus/gnome-applications-merged has been seen before, skipping (using inode) previous path: $HOME/.config/menus/applications-merged inode: 19272774
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
reloading plugin 0_package_control_loader.00-package_control
Package Control: Skipping automatic upgrade, last run at 2019-01-10 22:40:04, next run at 2019-01-10 23:40:04 or after
Unable to open $HOME/.config/sublime-text-3/Packages/Package Control/Package Control.sublime-settings
Unable to open $HOME/.config/sublime-text-3/Packages/Default/Preferences.sublime-settings
Unable to open $HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
Package Control: Error downloading channel. HTTP error 404 downloading https://packagecontrol.io/channel_v3.json.
```
The final files listed as "Unable to open" do not exist.
I am NOT using a proxy of any kind.
I AM able to open "https://packagecontrol.io/channel_v3.json" in my browser.
I grepped for "downloader_precedence"  in all of "$HOME/.config/sublime-text-3", but it was not found.
I have completely removed the "sublime-text-3" directory tree under "~/.config" and reinstalled Package Control.

Please advise, and thank you for any assistance.

**Comment by mloweris** [comment]
Watching this thread for the same reason. 
Thanks as well for Package Control. Couldn't live without it.

**Comment by meunal** [comment]
Meanwhile, you can add
`"channels":
	[
		"https://erhan.in/channel_v3.json"
	],`
to Preferences > Package Settings > Package Control > Settings - User file.

This is the latest snapshot of the original JSON file from web.archive.org.

**Comment by AnggiWaSa** [comment]
> Meanwhile, you can add
> `"channels": [ "https://erhan.in/channel_v3.json" ],`
> to Preferences > Package Settings > Package Control > Settings - User file.
> 
> This is the latest snapshot of the original JSON file from web.archive.org.

Thank @meunal, this is very helpful for me

**Comment by goranskular** [comment]
Thanks meunal. I was going crazy over it until I saw this ticket and your json backup.

**Comment by badursun** [comment]
@meunal ya shukran :) for an hour, I wondered what the problem was. I've formatted the machine, I've re-installed everything, I wonder where I've been wrong but i didn't have the problem :D You saved me.

**Comment by thetutlage** [comment]
Same here. I did a fresh re-install of Sublime and then saw the pinned issue

**Comment by meunal** [comment]
Hey @AnggiWaSa, @goranskular, @badursun,
Glad to hear that it worked out. As a gentle reminder, please make sure you delete the entry once everything gets normal on packagecontrol.io.

**Comment by lichtamberg** [comment]
Ouch, looks like https://packagecontrol.io/channel_v3.json is also outputting a lot of IPs from users which downloaded packages? :O

<img width="1440" alt="bildschirmfoto 2019-01-11 um 23 03 12" src="https://user-images.githubusercontent.com/10075/51061921-301eb380-15f5-11e9-81aa-32cda474ff28.png">

**Comment by wbond** [comment]
@lichtamberg Thanks for the heads up. I've removed the JSON files to prevent inadvertent disclosure of information from the corrupt filesystem. I also removed your comment history to prevent spreading info.

**Comment by davewallace** [comment]
I'm about to chuck in that channels solution, if it does work is it possible at all to throw a prompt to remind people that they have alternate channel entries?

**Comment by bryanlopezcodes** [comment]
> Meanwhile, you can add
> `"channels": [ "https://erhan.in/channel_v3.json" ],`
> to Preferences > Package Settings > Package Control > Settings - User file.
> 
> This is the latest snapshot of the original JSON file from web.archive.org.

Thanks!

**Comment by marcosdipaolo** [comment]
> Meanwhile, you can add
> `"channels": [ "https://erhan.in/channel_v3.json" ],`
> to Preferences > Package Settings > Package Control > Settings - User file.
> 
> This is the latest snapshot of the original JSON file from web.archive.org.

thanks!!!

**Comment by wbond** [comment]
We should be back online now. Don't forget to remove alternate URLs from your channel configuration.

**Comment by lichtamberg** [comment]
For me it works without errors 🤷‍♂️

**Comment by wbond** [comment]
@kaiser101 Please open a new issue, and be sure to include info like what IP your DNS is resolving `packagecontrol.io` to.

**Comment by marsws** [comment]
> Meanwhile, you can add
> `"channels": [ "https://erhan.in/channel_v3.json" ],`
> to Preferences > Package Settings > Package Control > Settings - User file.
> 
> This is the latest snapshot of the original JSON file from web.archive.org.

Very helpful!

**Comment by pharrellyhy** [comment]
> Meanwhile, you can add
> `"channels": [ "https://erhan.in/channel_v3.json" ],`
> to Preferences > Package Settings > Package Control > Settings - User file.
> 
> This is the latest snapshot of the original JSON file from web.archive.org.

Works like a charm!

**Comment by kanekko** [comment]
> 
> 
> Meanwhile, you can add
> `"channels": [ "https://erhan.in/channel_v3.json" ],`
> to Preferences > Package Settings > Package Control > Settings - User file.
> 
> This is the latest snapshot of the original JSON file from web.archive.org.

I too solved this issue leaved blank node of "channels" in Package Control settings file:
` "channels": [  ] `

The output of @meunal with `"channels": [ "https://erhan.in/channel_v3.json" ]` is:
`Package Control: Installing 2 missing dependencies
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://erhan.in/channel_v3.json.
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host erhan.in returned an invalid certificate (_ssl.c:493: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure)) downloading https://erhan.in/channel_v3.json.
Package Control: The dependency 'select-windows' is not available
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host erhan.in returned an invalid certificate (_ssl.c:493: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure)) downloading https://erhan.in/channel_v3.json.
Package Control: The dependency 'bz2' is not available
Package Control: Skipping automatic upgrade, last run at 2020-04-10 13:14:59, next run at 2020-04-10 14:14:59 or after`

The output with `"channels": [  ]` is:
`Package Control: Installing 2 missing dependencies
Package Control: The dependency 'select-windows' is not available
Package Control: The dependency 'bz2' is not available
Package Control: Skipping automatic upgrade, last run at 2020-04-10 13:14:59, next run at 2020-04-10 14:14:59 or after`

My Environment is:
* Win XP 32 bits (I know, my OS is very old =/)
* ST2
