### ISSUE TITLE
Unable to update packages

### ISSUE THREAD

**Issue by kaiser101** [wbond/package_control#1401]
I am sorry I cannot refer to the trouble shooting guide or follow the guidelines because I cannot open packagecontrol.io

Accessing packagecontrol.io in my browser gives me a connection refused error.

However a ping command produces the following.

Pinging packagecontrol.io [2600:3c02::f03c:91ff:fec5:4fd5] with 32 bytes of data
:
Reply from 2600:3c02::f03c:91ff:fec5:4fd5: time=281ms
Reply from 2600:3c02::f03c:91ff:fec5:4fd5: time=289ms
Reply from 2600:3c02::f03c:91ff:fec5:4fd5: time=547ms
Reply from 2600:3c02::f03c:91ff:fec5:4fd5: time=507ms

Ping statistics for 2600:3c02::f03c:91ff:fec5:4fd5:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 281ms, Maximum = 547ms, Average = 406ms

**Comment by wbond** [comment]
Okay - great info! I am going to assume that ipv6 causing issues. Unfortunately when I initially set up ipv6 my provider had it so I could easily test. Since then I've moved and don't have ipv6.

I'll have to find a machine to test from.

**Comment by kaiser101** [comment]
Thanks for looking into it. Let me know if I can be of any further help.

**Comment by wbond** [comment]
Can you verify now?

**Comment by kaiser101** [comment]
Works now, many thanks.
