### ISSUE TITLE
cannot open the site packagecontrol.io 

### ISSUE THREAD

**Issue by CalanceHao** [wbond/package_control#1403]
I know two install way, one uses the command, and the other one is put the .zip to 'Installed Package' manually. These two all base on your website, and the packagecontrol.io and http://sublime.wbond.net are all cannot be ping.
Could I get the zip in GitHub??? How could I do?
Would you consider adding the manual way into the readme.md?

**Comment by isGalaxy** [comment]
The same question as you say

**Comment by CalanceHao** [comment]
❗️ I have already installed it by https://jingyan.baidu.com/article/a378c960bf2e2db329283065.html It offers another address to download. But still cannot install package😂. 
`There are no packages available for installation`
I guess it still because of the unreachable server😱

**Comment by wbond** [comment]
Unfortunately you can't get the zip from GitHub, and even if you could, you wouldn't be able to fetch the channel list.

My hunch is that you are in China and the great firewall is blocking access to the new server I am on. Hopefully in the next few weeks I'll be able to migrate the last few sites off of the old server then rebuild it for hosting packagecontrol.io again. Until then, I am afraid you are most likely out of luck unless there is some way to bypass the firewall.

**Comment by CalanceHao** [comment]
TOT So sad for the annoying firework...

I am using the VPN base on Vultr, my instance's location is in New Jersey. I'm using Shadowsocks, and usually in the 'PAC auto schema'. I just change to 'global schema' and try the website and `Install Package`. The situation has not been improved.
I'm not good at the firework part. Will it be helpful if I use the other server or configure another DNS or something?

**Comment by isGalaxy** [comment]
Maybe network or server down! @CalanceHao

**Comment by qijimrc** [comment]
I have the same situation, and hope that this problem will be solved as soon as possible... Thx.

**Comment by wbond** [comment]
Yes, I am migrating the site back to the old server (with a fresh image) since it has an IP address that can be accessed from within the great firewall of China. Hopefully it will be back up and running in 30 to 60 minutes.

**Comment by wbond** [comment]
The site is back online now, on and old IP address. Hopefully this fixes connectivity issues for users in China.

**Comment by wing-kai** [comment]
> The site is back online now, on and old IP address. Hopefully this fixes connectivity issues for users in China.

it works, thank you!

**Comment by danish-kamal** [comment]
Not working for me. Location: India, tried connecting through VPN from Canada and US servers.

**Comment by midboh** [comment]
Its been unavailable for me too for the past 4 hours for me (Sydney)

**Comment by JeffNucleusT** [comment]
Even today,  [packagecontrol.io](https://packagecontrol.io) is unavailable, through sublime or browsers

**Comment by James-Bovis** [comment]
Unavailable in the UK at the moment too.

**Comment by wbond** [comment]
The server is back online

**Comment by danish-kamal** [comment]
Thanks Mr. @wbond . Now I can download my favorite plugins 👍
