### ISSUE TITLE
Default keybinding for control panel not working

### ISSUE THREAD

**Issue by colbyfayock** [wbond/package_control#1404]
hey there,

Recently my default key bind stopped working for bringing up the command pallette:
```
{ "keys": ["super+shift+p"], "command": "show_overlay", "args": {"overlay": "command_palette"} },
```

I've verified it's still in the Key Bindings settings. I've tried:
 - Additionally adding the default in the user settings
 - Running the FindKeyConflict plugin, nothing but my user-defined one showed
 - Removing / reinstalling with while purging packages cache
 - A few other random things just trying to play with it

What DID work, was adding a different shortcut for it:
```
{ "keys": ["super+shift+/"], "command": "show_overlay", "args": {"overlay": "command_palette"} },
```

Any ideas aside from completely reinstalling Sublime?

Thanks

**Comment by FichteFoll** [comment]
You can debug this by enabling input logging via `sublime.log_input(True); sublime.log_commands(True)` in the console and then monitoring that as you attempt to use the key bindings.

**Comment by colbyfayock** [comment]
yeah you're right - funny enough, it doesn't even log the command with that particular shortcut so somethings messed up. thanks for the help though

**Comment by FichteFoll** [comment]
If not even input is logged, something else must be grabbing the key before it reaches ST.

I've also had this with the recent change to honor input methods on Linux where ctrl+shift+s doesn't register in ST anymore but haven't been able to debug if further until now.

**Comment by colbyfayock** [comment]
If it's a common / known problem, anything I can do (without not knowing too much of how ST works) to help debug? some kind of logs?

**Comment by FichteFoll** [comment]
It slightly varies from system to system, but generally you try to eliminate as many outer factors (i.e. other processes running) as possible until you find that it works again and thus know the culprit.
