### ISSUE TITLE
Sorry, visit packagecontrol.io in chrome is timeout

### ISSUE THREAD

**Issue by OceanicKang** [wbond/package_control#1405]
Sorry, I try to ping packagecontrol.io, but is request timeout for icmp_seq. And i visit the site in chrome, it can’t be reached.  However i try to ping wbond.net, www.google.com or www.facebook.com, it's ok. How can i solve the problem?

**Comment by 81218wbh** [comment]
![image](https://user-images.githubusercontent.com/11773012/52515863-3045b980-2c5c-11e9-9208-ba47f148018f.png)

**Comment by 81218wbh** [comment]
https://github.com/wbond/package_control/issues/1403#issuecomment-456815110

**Comment by wbond** [comment]
This should be fixed now since I've migrated the site back to an old IP address that should work in China
