### ISSUE TITLE
Package Control：There are no packages available for installation (how to solve?)

### ISSUE THREAD

**Issue by SeriStyle** [wbond/package_control#1408]
How to solve? 
the console dispay:
      Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 downloading https://packagecontrol.io/channel_v3.json.

**Comment by slf1991** [comment]
1. 下载Package Control手动安装
2. 网上下载channel_v3.json，记事本打开，找到"schema_version": "3.0.0".把3.0.0改成2.0，保存
3. 把channel_v3.json放到一个安全不会被删除的目录下。
4. subline菜单栏中的prefrences->package setting->Package control->setting-user。在{}中加入
"channels":
    	[
		"D:\\channel_v3的存放目录\\channel_v3.json"
	],
5. 保存后，ctrl+shift+p,正常安装就成了。
之前安装失败原因：channel_v3.json被墙了，无法下载下来。

**Comment by wbond** [comment]
I've just migrated packagecontrol.io back to an old IP address, so it should be accessible again from China.
