### ISSUE TITLE
Linux : Packages directory location

### ISSUE THREAD

**Issue by Auze** [wbond/package_control#1417]
Hello ! 
A small issue opened for documentation : 

The "Packages" directory is located at:
Linux : ~/.config/sublime-text-3/Packages

At least, on GNU/Linux Debian :) 

Thank you :+1:

**Comment by FichteFoll** [comment]
Hi, where can the current "incorrect" location be found and what does it say instead?

**Comment by deathaxe** [comment]
Closing as stale.
