### ISSUE TITLE
Package Control: Remove fails when SublimeText and SublimeMerge are both running.

### ISSUE THREAD

**Issue by aroberge** [wbond/package_control#1418]
### Description

I tried to remove some packages from SublimeText while I had SublimeMerge running and it failed silently.  This was trying to remove some linters.

### Steps to reproduce

1. Start SublimeText
2. Start SublimeMerge
3. Try removing some package using Package control

### Expected behavior

Either the package should be removed (ideally) or a message indicating that the removal failed should be given.

### Actual behavior

No package removed, no failure.

I found out about SublimeMerge preventing uninstalling when, after closing SublimeText, I navigated to the folder where the packages were located and tried to delete them.

### Environment

* Build: 3200
* Windows 10
* SublimeMerge build 1107
= = =
When trying to remove from SublimeText, here's the content of the console

## Immediately after removing

ignored packages updated to: ["SublimeLinter-annotations", "Vintage"]
unloading plugin SublimeLinter-annotations.linter
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The package SublimeLinter-annotations has been removed and will be cleaned up on the next restart
reloading settings Packages/User/Package Control.sublime-settings

## After restarting SublimeText 

DPI mode: per-monitor v2
startup, version: 3200 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/andre/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/andre/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/andre/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["SublimeLinter-annotations", "Vintage"]
pre session restore time: 0.431288
startup time: 0.525288
first paint time: 0.527288
git: tracking working dir C:\Users\andre\github\avantpy
reloading plugin Default.arithmetic

**Many similar lines about reloading plugins removed**

reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
plugins loaded
[sublack:main.py](INFO) Loglevel set to INFO
ignored packages updated to: ["SublimeLinter-annotations", "SublimeLinter-flake8", "Vintage"]
unloading plugin SublimeLinter-flake8.linter
ignored packages updated to: ["SublimeLinter", "SublimeLinter-annotations", "SublimeLinter-flake8", "Vintage"]
unloading plugin SublimeLinter.__init__
unloading plugin SublimeLinter.active_linters_view
unloading plugin SublimeLinter.busy_indicator_view
unloading plugin SublimeLinter.goto_commands
unloading plugin SublimeLinter.highlight_view
unloading plugin SublimeLinter.log_handler
unloading plugin SublimeLinter.message_view
reloading settings Packages/SublimeLinter/panel/message_view.sublime-settings
reloading settings Packages/SublimeLinter/panel/panel.sublime-settings
unloading plugin SublimeLinter.panel_view
unloading plugin SublimeLinter.status_bar_view
unloading plugin SublimeLinter.sublime_linter
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Unable to remove orphaned package SublimeLinter-annotations - deferring until next start: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\andre\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\SublimeLinter-annotations.sublime-package'
ignored packages updated to: ["SublimeLinter", "SublimeLinter-flake8", "Vintage"]
ignored packages updated to: ["SublimeLinter", "SublimeLinter-annotations", "SublimeLinter-flake8", "Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Removed orphaned package SublimeLinter-flake8
ignored packages updated to: ["SublimeLinter", "SublimeLinter-annotations", "Vintage"]
Error loading C:\Users\andre\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-flake8.sublime-package: [Errno 2] No such file or directory: 'C:\\Users\\andre\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\SublimeLinter-flake8.sublime-package'
ignored packages updated to: ["SublimeLinter", "SublimeLinter-flake8", "Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin SublimeLinter-annotations.linter
ignored packages updated to: ["SublimeLinter", "SublimeLinter-annotations", "Vintage"]
unloading plugin SublimeLinter-annotations.linter
reloading settings Packages/User/Preferences.sublime-settings
Error loading C:\Users\andre\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-flake8.sublime-package: [Errno 2] No such file or directory: 'C:\\Users\\andre\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\SublimeLinter-flake8.sublime-package'
Package Control: The package SublimeLinter-annotations is being re-enabled after a Package Control operation was interrupted
ignored packages updated to: ["SublimeLinter", "Vintage"]
Error loading C:\Users\andre\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-flake8.sublime-package: [Errno 2] No such file or directory: 'C:\\Users\\andre\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\SublimeLinter-flake8.sublime-package'
reloading plugin SublimeLinter-annotations.linter
Package Control: Removed orphaned package SublimeLinter
ignored packages updated to: ["Vintage"]
Error loading C:\Users\andre\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-flake8.sublime-package: [Errno 2] No such file or directory: 'C:\\Users\\andre\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\SublimeLinter-flake8.sublime-package'
Error loading C:\Users\andre\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package: [Errno 2] No such file or directory: 'C:\\Users\\andre\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\SublimeLinter.sublime-package'
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: No updated packages

## Trying to restart again, still with SublimeMerge running

DPI mode: per-monitor v2

** many similar lines to previous removed **

reloading plugin Package Control.Package Control
reloading plugin sublack.main
reloading plugin SublimeLinter-annotations.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-annotations.sublime-package\linter.py", line 15, in <module>
ImportError: No module named 'SublimeLinter'
plugins loaded
C:\Users\andre\github\avantpy\avantpy
C:\Users\andre\github\avantpy
[sublack:main.py](INFO) Loglevel set to INFO
ignored packages updated to: ["SublimeLinter-annotations", "Vintage"]
unloading plugin SublimeLinter-annotations.linter
Package Control: Removed directory for unneeded dependency jsonschema
ignored packages updated to: ["0_package_control_loader", "SublimeLinter-annotations", "Vintage"]
unloading plugin 0_package_control_loader.00-package_control
unloading plugin 0_package_control_loader.01-python-toml
unloading plugin 0_package_control_loader.50-pathlib
unloading plugin 0_package_control_loader.50-pyyaml
unloading plugin 0_package_control_loader.50-requests
unloading plugin 0_package_control_loader.55-jsonschema
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["SublimeLinter-annotations", "Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-python-toml
reloading plugin 0_package_control_loader.50-pathlib
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.55-jsonschema
ignored packages updated to: ["0_package_control_loader", "SublimeLinter-annotations", "Vintage"]
unloading plugin 0_package_control_loader.00-package_control
unloading plugin 0_package_control_loader.01-python-toml
unloading plugin 0_package_control_loader.50-pathlib
unloading plugin 0_package_control_loader.50-pyyaml
unloading plugin 0_package_control_loader.50-requests
unloading plugin 0_package_control_loader.55-jsonschema
Package Control: The package 0_package_control_loader is being re-enabled after a Package Control operation was interrupted
ignored packages updated to: ["SublimeLinter-annotations", "Vintage"]
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-python-toml
reloading plugin 0_package_control_loader.50-pathlib
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.55-jsonschema
Package Control: Skipping automatic upgrade, last run at 2019-03-15 16:42:25, next run at 2019-03-15 17:42:25 or after
Package Control: Unable to remove orphaned package SublimeLinter-annotations - deferring until next start: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\andre\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\SublimeLinter-annotations.sublime-package'
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin SublimeLinter-annotations.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-annotations.sublime-package\linter.py", line 15, in <module>
ImportError: No module named 'SublimeLinter'
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/loader.py", line 442, in do_swap
PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\andre\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\0_package_control_loader.sublime-package'
reloading settings Packages/User/Preferences.sublime-settings

## after a while

I stopped SublimeMerge, restarted SublimeText, and re-installed the package I had removed for this experiment.

**Comment by FichteFoll** [comment]
Looks a lot like Sublime Merge is holding a file handle to that package and preventing PC from deleting it, which would make it a Sublime Merge issue. Those are tracked [on a different repo](https://github.com/sublimehq/sublime_merge/issues/).

**Comment by evandrocoan** [comment]
Shouldn't this be filled in SublimeMerge issue tracker?

**Comment by wbond** [comment]
This is a suitable place to come up with a solution

**Comment by evandrocoan** [comment]
I see. After looking at the log, Package Control should show some error somewhere, because it is saying everything went fine, while the package still there.

The problem seems that SublimeMerge is pocking around with another application's files, i.e., Sublime Text files. It seems more logical for SublimeMerge do not do such nasty things.

**Comment by wbond** [comment]
No @evandrocoan, Sublime Merge is supposed to load syntax definitions, syntax-specific settings and color schemes from Sublime Text. This is a feature.

**Comment by evandrocoan** [comment]
Thanks for the patience explaining it!

**Comment by wbond** [comment]
As of ST build 3202 and Merge build 1111, `.sublime-package` files are no longer locked on Windows and can be freely deleted.

**Comment by Adarma** [comment]
I just had `SublimeLinter-annotations' update fail. The message was to restart Sublime Text to complete the update. Restarting did not complete the update. The Console showed the problem file:
`...\AppData\Roaming\Sublime Text\Installed Packages\SublimeLinter-annotations.sublime-package'.
I saw the `SublimeLinter-annotations.sublime-package-new` file was in the folder, but i was unable to delete the other file.
Once I closed Sublime Merge and restarted Sublime text, the update completed.
Maybe add a message to close Sublime Merge and restart Sublime Text to complete the update??

**Comment by Adarma** [comment]
Sublime Merge 2074
Sublime Text 4126

Sorry, I didn't save the console messages before I resolved it.
Is there a way to install an old version of a package?
Then I can let it try to update again and see if the same thing happens.

**Comment by FichteFoll** [comment]
You can manually change the version recorded inside the package's `package-metadata.json` file (unzip and re-zip if it's an archived package) to cause PC to think it has an older version.

**Comment by Adarma** [comment]
Closed Sublime Merge
Closed Sublime Text

Edited version number in `package-metadata.json` of `SublimeLinter-annotations.sublime-package` from `1.5.3` to `1.5.0`

Started Sublime Merge
Started Sublime Text

Got a messagebox: An error occurred while trying to upgrade SublimeLinter-annotations. Please restart Sublime Text to finish the upgrade.

Sublime Text Console Output:

	reloading...
	...
	plugins loaded
	Package Control: Installing 1 upgrades
	ignored packages updated to: ["ActionScript", "AppleScript", "ASP", "C#", "Clojure", "D", "Erlang", "Go", "Groovy", "Haskell", "Lisp", "Objective-C", "OCaml", "Pascal", "Perl", "PHP", "R", "Rails", "Ruby", "Rust", "Scala", "SublimeLinter-annotations", "TCL", "Textile", "Vintage"]
	unloading python 3.3 plugin SublimeLinter-annotations.linter
	reloading settings Packages/User/Package Control.sublime-settings
	reloading settings Packages/User/Preferences.sublime-settings
	error: Package Control

	An error occurred while trying to upgrade SublimeLinter-annotations. Please restart Sublime Text to finish the upgrade.


Closed Sublime Text
Started Sublime Text

Sublime Text Console Output:

	reloading...
	...
	plugins loaded
	Exception in thread Thread-9:
	Traceback (most recent call last):
	  File "./python3.3/threading.py", line 901, in _bootstrap_inner
	  File "C:\Users\<?????>\AppData\Roaming\Sublime Text\Installed Packages\Package Control.sublime-package\package_control/package_cleanup.py", line 82, in run
	    os.rename(os.path.join(installed_path, file), package_file)
	FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\<?????>\\AppData\\Roaming\\Sublime Text\\Installed Packages\\SublimeLinter-annotations.sublime-package'


Closed Sublime Text
Started Sublime Text

Sublime Text Console has the same error

Closed Sublime Text
Closed Sublime Merge
Started Sublime Text

Sublime Text Console Output:

	reloading...
	...
	plugins loaded
	Package Control: Finished replacing SublimeLinter-annotations.sublime-package
	Package Control: The package SublimeLinter-annotations is being re-enabled after a Package Control operation was interrupted
	ignored packages updated to: ["ActionScript", "AppleScript", "ASP", "C#", "Clojure", "D", "Erlang", "Go", "Groovy", "Haskell", "Lisp", "Objective-C", "OCaml", "Pascal", "Perl", "PHP", "R", "Rails", "Ruby", "Rust", "Scala", "TCL", "Textile", "Vintage"]
	Package Control: Installing 1 missing package
	reloading python 3.3 plugin SublimeLinter-annotations.linter
	reloading settings Packages/User/Package Control.sublime-settings
	reloading settings Packages/User/Preferences.sublime-settings
	ignored packages updated to: ["ActionScript", "AppleScript", "ASP", "C#", "Clojure", "D", "Erlang", "Go", "Groovy", "Haskell", "Lisp", "Objective-C", "OCaml", "Pascal", "Perl", "PHP", "R", "Rails", "Ruby", "Rust", "Scala", "SublimeLinter-annotations", "TCL", "Textile", "Vintage"]
	unloading python 3.3 plugin SublimeLinter-annotations.linter
	reloading settings Packages/User/Package Control.sublime-settings
	reloading settings Packages/User/Preferences.sublime-settings
	Package Control: Installed missing package SublimeLinter-annotations
	Package Control: Skipping automatic upgrade, last run at 2022-07-21 14:46:31, next run at 2022-07-21 15:46:31 or after
	ignored packages updated to: ["ActionScript", "AppleScript", "ASP", "C#", "Clojure", "D", "Erlang", "Go", "Groovy", "Haskell", "Lisp", "Objective-C", "OCaml", "Pascal", "Perl", "PHP", "R", "Rails", "Ruby", "Rust", "Scala", "TCL", "Textile", "Vintage"]
	reloading python 3.3 plugin SublimeLinter-annotations.linter
	reloading settings Packages/User/Package Control.sublime-settings
	reloading settings Packages/User/Preferences.sublime-settings
	reloading settings Packages/User/Preferences.sublime-settings

Now it is ok again. `SublimeLinter-annotations` is `1.5.3`

**Comment by FichteFoll** [comment]
Thanks, this is a very detailed report that seems to confirm that SM does indeed still lock the file, though I would have hoped for PC to also print an exception with a traceback instead of only displaying the error modal.

Unfortunately, this is on SM to fix and there isn't anything PC can do outside of modifying SM's preferences file directly to also add the package to the `ignored_packages` list there, only to then also remove it once the package has indeed been removed, which is quite an elaborate workaround. Especially considering SM should supposedly not keep the file locked anymore according to https://github.com/wbond/package_control/issues/1418#issuecomment-477195176.

**Comment by deathaxe** [comment]
It's a general bug is sublimeqh's git library.

git tracked packages/folders can't be removed at all if even only open in ST.
see: https://github.com/sublimehq/sublime_text/issues/3124

**Comment by FichteFoll** [comment]
Hm, that's a good idea. @Adarma do you have your packages inside of a git repository (e.g. one that spans your home folder)?

**Comment by Adarma** [comment]
No they are not in a git repo
