### ISSUE TITLE
There are no packages available for installation

### ISSUE THREAD

**Issue by zhwangart** [wbond/package_control#1419]
动不动就出现这个！动不动就出现这个！用的好好的就出现这个！什么原因呢？

![error](https://pic3.zhimg.com/v2-c79c85988209822dd09a1e631cb89ad6_b.jpg)

**Comment by FichteFoll** [comment]
The great firewall of China blocks the up of the packagecontrol.io website.

**Comment by zhwangart** [comment]
> The great firewall of China blocks the ip of packagecontrol.io.

My network can access packagecontrol.io. What is the role of PyV8 in Packages? One time I was getting the above error because I remove PyV8 in `Package Control: Remove Package`.

**Comment by FichteFoll** [comment]
PyV8 is required and downloaded by Emmet. It is not managed by PC.
