### ISSUE TITLE
Package control does not install new package from github repo

### ISSUE THREAD

**Issue by maboloshi** [wbond/package_control#1420]
```
Package Control: Error downloading repository. HTTP error 404 downloading https://api.github.com/repos/maboloshi/LineEndings/commits?per_page=1&sha=master.
```

The link returns the content as
```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository"
}
```
Recently happened, no problem before

**Comment by FichteFoll** [comment]
There doesn't seem to be a package with that name: https://packagecontrol.io/search/lineendings.

Do you have a modified `channels` setting?

**Comment by maboloshi** [comment]
Sorry, my fork project is from github and `Add repository`, maybe there is a problem with this project. I have not tested

**Comment by maboloshi** [comment]
The problem has been found, the default branch of the project is not `master`.

**Comment by FichteFoll** [comment]
You'll need to add `<repourl>/tree/<branch>` as the repo URL instead, then.
