### ISSUE TITLE
ST3: ImportError: No module named 'package_control' 2019

### ISSUE THREAD

**Issue by SakisHous** [wbond/package_control#1424]
I have an issue with ST3 and package_control. I copied and pasted the script from **[https://packagecontrol.io/installation#st3](url)** . Although, when I try to install a package I get the errors
```
Traceback (most recent call last):
  File "C:\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_installer.py", line 154, in on_done
  File "C:\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_disabler.py", line 76, in disable_packages
ImportError: No module named 'package_control'
```
 There are many threads with the same issue but I have not understood the solution yet.

**Comment by FichteFoll** [comment]
Please post the entire contents of ST's console.

**Comment by SakisHous** [comment]
Sorry for the bad response. First, I try to install the package control from the [https://packagecontrol.io/installation](url) website. I open the console and paste the script. I receive  286331.

**Comment by deathaxe** [comment]
The only known reason for this issue to happen is removing 'Package Control' package from python's `sys.modules`. Maybe caused by earlier versions of AutmaticPackageReloader.
