### ISSUE TITLE
Exclude unpacked packages from Package Control menu

### ISSUE THREAD

**Issue by john-cj** [wbond/package_control#1429]
Is there a way to exclude packages in Packages directory from being visible in Package Control menu? I'm afraid of accidentally delete them.

**Comment by FichteFoll** [comment]
Which menu are you talking about and which packages do you intend to include?

**Comment by john-cj** [comment]
I'm talking about the menu which could be invoked by pressing *Ctrl+Shift+P* and then selecting *Package Control: Remove Package* item. This menu is shown on the screenshot below.

I have `My Package 1`, `My Package 2`, and other unpacked packages in this folder. These packages weren't installed from GitHub. They are just files on my PC. If I accidentally remove one of them by accidentally pressing "Enter" key in the above-mentioned menu, such package will be lost.

![st1](https://user-images.githubusercontent.com/18004961/58523334-c03c4e80-81cc-11e9-91dc-425303613822.png)

![st1](https://user-images.githubusercontent.com/18004961/58523395-fc6faf00-81cc-11e9-8662-c494d3433197.png)

**Comment by john-cj** [comment]
A possible solution to this issue is to add a new setting to the Package Control settings file. Something like this:

```
{
    // Ignore specific directories in the <Data>/Packages folder.
    // These directories will not be listed under Package Control menu,
    // updated, or overwritten.
    "ignore_specific_directories_in_the_packages_folder": [
        // This list is empty by default. We have added 2 packages manually:
        "My Package 1",
        "My Package 2"
    ]
}
```
