### ISSUE TITLE
Can't install package from bitbucket repo

### ISSUE THREAD

**Issue by typorian** [wbond/package_control#1430]
When adding the bitbucket repo of markupsafe to sublime text, sublime tries to download the package via the 1.0 api resulting in the following error:

Package Control: Error downloading repository. HTTP error 410 downloading https://api.bitbucket.org/1.0/repositories/teddy_beer_maniac/sublime-text-dependency-markupsafe/main-branch.
error: Package Control

**Comment by lpanebr** [comment]
any workaround?

**Comment by danillos** [comment]
@lpanebr It not too safe but it works.

A temporary fix for it https://github.com/tomv564/LSP/issues/643#issuecomment-509894664
(Remember to revert the Channel to the original after the installation)

**Comment by lpanebr** [comment]
> @lpanebr It not too safe but it works.
> 
> A temporary fix for it [tomv564/LSP#643 (comment)](https://github.com/tomv564/LSP/issues/643#issuecomment-509894664)
> (Remember to revert the Channel to the original after the installation)

It worked perfectly! Thanks!

**Comment by FichteFoll** [comment]
I replaced all bitbucket dependencies with github mirrors for now (and also updated them). This should allow people to install packages that depend on these in about an hour when the crawler fetches the updates.

https://github.com/wbond/package_control_channel/commit/b64ef4a46ffc76953204a6caffe4d5fb01a8e78c
