### ISSUE TITLE
the installation web https://packagecontrol.io/ down

### ISSUE THREAD

**Issue by wen-fei** [wbond/package_control#1437]
hello, the web https://packagecontrol.io/ is down and the codes also can't get and reponse and operation timed out.

**Comment by wbond** [comment]
Yes, I am in the middle of a server migration right now

**Comment by zacfdbf** [comment]
when it will be available?

**Comment by wbond** [comment]
Hopefully fairly soon - I've had to figure out a handful of issues during the migration

**Comment by wbond** [comment]
We are back online
