### ISSUE TITLE
404 Error when reading https://packagecontrol.io/repository.json

### ISSUE THREAD

**Issue by ig0774** [wbond/package_control#1440]
When I attempt to connect to the main repository at https://packagecontrol.io/repository.json, I get a 404 status.

More specifically this:
```
➜  ~ http GET https://packagecontrol.io/repository.json
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Thu, 18 Jul 2019 00:30:12 GMT
Server: nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding

{
    "__status_code__": 404
}
```

I'm guessing I'm not the only person affected by this.

If this is a known issue or related to maintenance, I apologise for opening a nuisance issue.

**Comment by wbond** [comment]
As @FichteFoll, the URL you were trying is not the main repository file.
