### ISSUE TITLE
Accidentally deleted my Package Control settings file

### ISSUE THREAD

**Issue by dreamcat4** [wbond/package_control#1442]
So while trying to count the number of installed packages, I edited this file. Then unfortunately it got auto-saved by some plugins.

Now my file looks like this:

```sh
{
	"bootstrapped": true
}
```

So all of the packages which were being managed by package control are no longer being tracked. It cannot remember them!

So I was just wondering if there is any location of a backup of the list of packages. Rather than just only in the manually editable user settings file. Thank you.

**Comment by FichteFoll** [comment]
If you haven't restarted ST yet, you can use this in the console to restore the list:
```py
[path.split('/', 2)[1] for path in sublime.find_resources("package-metadata.json")]
```
It won't catch ignored packages, but you can restore those from the `ignored_packages` list.

If you have closed ST and not yet restarted, add Package Control to the `ignored_packages` list with a different editor *before* starting as it would otherwise remove these managed packages.

**Comment by dreamcat4** [comment]
Thank you for the quick reply. It was very informative. Indeed very useful set of steps to follow for performing a recovery process. I hope that it can help out others in the future.

As for myself: Very fortunately it turned out that I actually had a syncing program running in the background at the time. Which had then versioned an automatic backup of this file. So was then able to restore it from an appropriate backup in my own case.

But before doing that I did not know I had the backup there. And was trying to do it by myself. I had noticed that there was a difference between the number of packages in the folder `Installed Packages` vs the total number of packages that had previously been recorded in my lost Package Control Settings file. Something like 240 vs 290. Which is an interesting point. - it may be possible to figure out a partial restoration by simply creating a listing from all the the current packages inside of that folder. And putting it back into the json setting file of Package Control's, to restore that list tracked packages. Clearly most of them were there, but not all of them. Perhaps the rest were unpacked in other nearby folder(s). Although I would not be aware of how to check up on those remaining ones. At least it's another more basic alternative should the method above also end up failing.

Thanks again @FichteFoll !

**Comment by FichteFoll** [comment]
As my command kind of indicated, PC marks packages it manages with the mentioned `package-metadata.json` file so that it can remove any left-over packages that result from external syncing of the `Package Control.sublime-settings` file but not the installed packages (which is the usuag behavior).
