### ISSUE TITLE
Packagecontrol.io offline

### ISSUE THREAD

**Issue by NicoAiko** [wbond/package_control#1443]
It seems https://packagecontrol.io is offline.

Package Control can't be used or installed which is pretty bad right now for me...

**Comment by genckaptan55** [comment]
Same for me

**Comment by oguzhanaksoy** [comment]
Same

**Comment by benbenbang** [comment]
Same here 😢

**Comment by wbond** [comment]
This has been fixed, sorry for the inconvenience
