### ISSUE TITLE
Package Control not working in OS Sierra

### ISSUE THREAD

**Issue by digitalnomads2019** [wbond/package_control#1449]
Hi there, just read all related issues but can't figure out why PC is not working in my Sublime Text 3 (no options in right click either in tab title or content).
Did a manual install and I can see the PC Settings in Preferences.
And no, is not listed under ignored packages, either in default or user settings.
Hope someone can help.
Bests,

**Comment by FichteFoll** [comment]
Try updating to the latest version of Sublime Text first. If that doesn't work, paste the contents of ST's console.

**Comment by wbond** [comment]
Closing since there has been no response in four months.
