### ISSUE TITLE
Prune the Backup directory

### ISSUE THREAD

**Issue by svenax** [wbond/package_control#145]
After using Sublime Text with Package Control for some months, the Backup directory is starting to get pretty big. Sure, it is easy to delete old stuff there manually, but maybe it would be good to have an option to automatically prune backups older that X number of days. Good idea?

**Comment by darkmorpher** [comment]
Status request @wbond

**Comment by wbond** [comment]
Nothing has been done here. I'd be happy to have a PR to review.
