### ISSUE TITLE
Package Control: Install SSL Certification Error

### ISSUE THREAD

**Issue by khainguyen24** [wbond/package_control#1454]
I was able to use Package Control: Install Package a couple of days ago. I ran into some issue where it would keep failing with error:

"Package Control
There are no packages available for installation
Please see https://packagecontrol.io......"

Things I've done since.. issue occured:
reverted sublime > https://www.sublimetext.com/docs/3/revert.html
uninstalled sublime > (using windows uninstall)
reinstalled
reinstalled Package Control from the Tools menu. (didn't work)
did the manual install > https://packagecontrol.io/installation (packagecontrol installs but unable to install Terminus I would get the same error above)

This is my debug log output:
`DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/nguyenkq/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/nguyenkq/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/nguyenkq/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 1.36575
startup time: 1.41175
first paint time: 1.41175
Unable to fetch update url contents
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
plugins loaded
Error installing Package Control: HTTPS error encountered, falling back to HTTP - <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>
Error installing Package Control: HTTP error encountered, giving up - <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>
error: An error occurred installing Package Control

Please check the Console for details

Visit https://packagecontrol.io/installation for manual instructions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading settings Packages/Package Control/Package Control.sublime-settings
reloading plugin 0_package_control_loader.00-package_control
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Exported certificate: Common Name: CA_01, Organizational Unit: Root, Organization: GRRRRR8
Package Control: Exported certificate: Common Name: Leidos Private Issuing CA 2013 01, Organizational Unit: PKI, Organization: Leidos, Country: US
Package Control: Exported certificate: Common Name: Lockheed Martin Root Certification Authority, Organizational Unit: Certification Authorities, Organization: Lockheed Martin Corporation, Locality: Denver, State/Province: Colorado, Country: US
Package Control: Exported certificate: Common Name: Federal Bridge CA 2016, Organizational Unit: FPKI, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Organization: Razer Inc, Organizational Unit: Chroma, Common Name: Razer Chroma SDK
Package Control: Exported certificate: Common Name: DoD Root CA 3; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: The Boeing Company Root Certificate Authority; Organizational Unit: netscape, certservers; Organization: Boeing; Country: US
Package Control: Exported certificate: Common Name: Microsoft Root Certificate Authority; Domain Component: microsoft, com
Package Control: Exported certificate: Common Name: ECA Root CA 2, Organizational Unit: ECA, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Common Name: Thawte Timestamping CA, Organizational Unit: Thawte Certification, Organization: Thawte, Locality: Durbanville, State/Province: Western Cape, Country: ZA
Package Control: Exported certificate: Common Name: Leidos Private Root CA 2013 01, Organizational Unit: PKI, Organization: Leidos, Country: US
Package Control: Exported certificate: Common Name: COMODO RSA Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: Leidos FBCA Cloud PKI CA-1, Organization: Leidos
Package Control: Exported certificate: Common Name: Microsoft Root Authority; Organizational Unit: Microsoft Corporation, Copyright (c) 1997 Microsoft Corp.
Package Control: Exported certificate: Common Name: Symantec Enterprise Mobile Root for Microsoft, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: Federal Common Policy CA, Organizational Unit: FPKI, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Common Name: Microsoft Root Certificate Authority 2011, Organization: Microsoft Corporation, Locality: Redmond, State/Province: Washington, Country: US
Package Control: Skipped certificate: Common Name: IdenTrust Global Common Root CA 1, Organization: IdenTrust, Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: DoD Root CA 2; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: ECA Root CA, Organizational Unit: ECA, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Organizational Unit: VeriSign Trust Network, (c) 1998 VeriSign, Inc. - For authorized use only, Class 3 Public Primary Certification Authority - G2; Organization: VeriSign, Inc.; Country: US
Package Control: Skipped certificate: Common Name: Microsoft Authenticode(tm) Root Authority, Organization: MSFT, Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: OpenTrust Root CA G1, Organization: OpenTrust, Country: FR
Package Control: Skipped certificate: Common Name: Class 2 Primary CA, Organization: Certplus, Country: FR - reason no longer valid
Package Control: Exported certificate: Common Name: Leidos Cloud PKI Root CA, Organization: Leidos
Package Control: Exported certificate: Common Name: Leidos Private Issuing CA 2016 01, Organizational Unit: PKI, Organization: Leidos, Country: US
Package Control: Exported certificate: Common Name: Leidos Private Issuing CA 2014 03, Organizational Unit: PKI, Organization: Leidos, Country: US
Package Control: Exported certificate: Common Name: Microsoft Root Certificate Authority 2010, Organization: Microsoft Corporation, Locality: Redmond, State/Province: Washington, Country: US
Package Control: Exported certificate: Common Name: H9ZJ182
Package Control: Exported certificate: Common Name: Northrop Grumman Root CA, Organizational Unit: Northrop Grumman Information Technology, Organization: Northrop Grumman Corporation, Locality: Century City, State/Province: California, Country: US, Email Address: NGpki@ngc.com
Package Control: Exported certificate: Common Name: Leidos Cloud PKI Issuing CA-Users, Organization: Leidos
Package Control: Skipped certificate: Organizational Unit: Copyright (c) 1997 Microsoft Corp., Microsoft Time Stamping Service Root, Microsoft Corporation; Organization: Microsoft Trust Network - reason no longer valid
Package Control: Skipped certificate: Common Name: Federal Bridge CA 2013, Organizational Unit: FPKI, Organization: U.S. Government, Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: Leidos Cloud PKI Issuing CA-Machines, Organization: Leidos
Package Control: Skipped certificate: Organizational Unit: NO LIABILITY ACCEPTED, (c)97 VeriSign, Inc., VeriSign Time Stamping Service Root, VeriSign, Inc.; Organization: VeriSign Trust Network - reason no longer valid
Package Control: Exported certificate: Common Name: Leidos Public Issuing CA 2013 01, Organizational Unit: PKI, Organization: Leidos, Country: US
Package Control: Exported certificate: Common Name: DoD CLASS 3 Root CA; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Organizational Unit: US Treasury Root CA, Certification Authorities, Department of the Treasury; Organization: U.S. Government; Country: US
Package Control: Skipped certificate: Common Name: UTN-USERFirst-Object, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: IdenTrust Commercial Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: DigiCert Global Root G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root Certification Authority, Organizational Unit: Root Certification Authority, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: GeoTrust Global CA, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: DST Root CA X3, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R3
Package Control: Exported certificate: Common Name: Baltimore CyberTrust Root, Organizational Unit: CyberTrust, Organization: Baltimore, Country: IE
Package Control: Skipped certificate: Organizational Unit: Equifax Secure Certificate Authority, Organization: Equifax, Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: USERTrust ECC Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 2, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: Starfield Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority; Organizational Unit: (c) 2006 Entrust, Inc., www.entrust.net/CPS is incorporated by reference; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: GlobalSign Root CA, Organizational Unit: Root CA, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Organizational Unit: Starfield Class 2 Certification Authority; Organization: Starfield Technologies, Inc.; Country: US
Package Control: Exported certificate: Common Name: DigiCert Global Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: CISRCA1, Organizational Unit: Certification Authorities, Organization: Carillon Information Security Inc., Country: CA
Package Control: Exported certificate: Common Name: thawte Primary Root CA; Organizational Unit: (c) 2006 thawte, Inc. - For authorized use only, Certification Services Division; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - G2; Organizational Unit: (c) 2009 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: SecureTrust CA, Organization: SecureTrust Corporation, Country: US
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R2
Package Control: Exported certificate: Organizational Unit: Class 3 Public Primary Certification Authority; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Certum CA, Organization: Unizeto Sp. z o.o., Country: PL
Package Control: Exported certificate: Common Name: DigiCert High Assurance EV Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Organizational Unit: Security Communication RootCA2; Organization: SECOM Trust Systems CO.,LTD.; Country: JP
Package Control: Exported certificate: Common Name: Starfield Services Root Certificate Authority; Organizational Unit: http://certificates.starfieldtech.com/repository/; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: Hotspot 2.0 Trust Root CA - 03, Organization: WFA Hotspot 2.0, Country: US
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G5; Organizational Unit: (c) 2006 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Go Daddy Root Certificate Authority - G2; Organization: GoDaddy.com, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: StartCom Certification Authority, Organizational Unit: Secure Digital Certificate Signing, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Common Name: VeriSign Universal Root Certification Authority; Organizational Unit: (c) 2008 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: USERTrust RSA Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Organizational Unit: Go Daddy Class 2 Certification Authority; Organization: The Go Daddy Group, Inc.; Country: US
Package Control: Exported certificate: Common Name: Certum Trusted Network CA, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Common Name: Microsoft ECC Product Root Certificate Authority 2018, Organization: Microsoft Corporation, Locality: Redmond, State/Province: Washington, Country: US
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: AddTrust External CA Root, Organizational Unit: AddTrust External TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: Lockheed Martin Root Certification Authority 2, Organizational Unit: Certification Authorities, Organization: Lockheed Martin Corporation, Locality: Denver, State/Province: Colorado, Country: US
Package Control: Exported certificate: Common Name: DoD Root CA 4; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: ECA Root CA 4, Organizational Unit: ECA, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Common Name: Lockheed Martin Root Certification Authority 3, Organizational Unit: Certification Authorities, Organization: Lockheed Martin Corporation, Locality: Denver, State/Province: Colorado, Country: US
Package Control: Exported certificate: Common Name: ECA Root CA, Organizational Unit: ECA, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Common Name: Symantec Class 3 Secure Server CA - G4, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: TrustID Server CA A52, Organizational Unit: TrustID Server, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: USERTrust RSA Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: Let's Encrypt Authority X3, Organization: Let's Encrypt, Country: US
Package Control: Exported certificate: Common Name: CertiPath Bridge CA - G2, Organizational Unit: Certification Authorities, Organization: CertiPath LLC, Country: US
Package Control: Exported certificate: Common Name: DigiCert Baltimore CA-2 G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: RapidSSL RSA CA 2018, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Skipped certificate: Common Name: DoD Interoperability Root CA 2; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: DigiCert SHA2 Assured ID Code Signing CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: GlobalSign Organization Validation CA - SHA256 - G2, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: DOD EMAIL CA-49; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID SW CA-38; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DigiCert SHA2 Extended Validation Server CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Skipped certificate: Common Name: CertiPath Bridge CA - G2, Organizational Unit: Certification Authorities, Organization: CertiPath LLC, Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: IdenTrust Commercial Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: GlobalSign Domain Validation CA - SHA256 - G2, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: DOD ID CA-49; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Skipped certificate: Common Name: Federal Bridge CA 2016, Organizational Unit: FPKI, Organization: U.S. Government, Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: CertiPath Bridge CA - G2, Organizational Unit: Certification Authorities, Organization: CertiPath LLC, Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: COMODO RSA Domain Validation Secure Server CA, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: DOD SW CA-54; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: Go Daddy Secure Certificate Authority - G2; Organizational Unit: http://certs.godaddy.com/repository/; Organization: GoDaddy.com, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: Gandi Standard SSL CA 2, Organization: Gandi, Locality: Paris, State/Province: Paris, Country: FR
Package Control: Exported certificate: Common Name: DigiCert SHA2 Secure Server CA, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: COMODO RSA Organization Validation Secure Server CA, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: IdenTrust Global Common Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: Oracle SSL CA - G2, Organizational Unit: Symantec Trust Network, Organization: Oracle Corporation, Country: US
Package Control: Exported certificate: Common Name: Root Agency
Package Control: Skipped certificate: Common Name: DOD CA-28; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD CA-25; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Organizational Unit: www.verisign.com/CPS Incorp.by Ref. LIABILITY LTD.(c)97 VeriSign, VeriSign International Server CA - Class 3, VeriSign, Inc.; Organization: VeriSign Trust Network - reason no longer valid
Package Control: Exported certificate: Common Name: Microsoft TPM Root Certificate Authority 2014, Organization: Microsoft Corporation, Locality: Redmond, State/Province: Washington, Country: US
Package Control: Skipped certificate: Common Name: DOD CA-27; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-19; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD CA-19; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD CA-30; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: COMODO High-Assurance Secure Server CA, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Skipped certificate: Common Name: Leidos Public Issuing CA 2013 01, Organizational Unit: PKI, Organization: Leidos, Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: COMODO RSA Code Signing CA, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Skipped certificate: Common Name: DOD CA-26; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-26; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-31; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: ORC ECA SW 3; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-29; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DoD Intermediate CA-2; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: ORC ECA SW 4; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-27; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-32; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DoD Intermediate CA-1; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD CA-29; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: ORC ECA HW 3; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: VeriSign Class 3 Code Signing 2010 CA; Organizational Unit: Terms of use at https://www.verisign.com/rpa (c)10, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-30; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: IdenTrust ECA 3; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: VeriSign Client External Certification Authority - G2; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: EUS-NTC-KEYID-23F4E22AD3BE374A449772954AA283AED752572E
Package Control: Skipped certificate: Common Name: VeriSign Client External Certification Authority - G3; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-28; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: ORC ECA HW 4; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD CA-32; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Exported certificate: Email Address: NGpki@ngc.com, Common Name: Northrop Grumman US Policy CA, Organizational Unit: Northrop Grumman Information Technology, Organization: Northrop Grumman Corporation, Locality: Century City, State/Province: California, Country: US
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-25; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: IdenTrust ECA 2; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD EMAIL CA-20; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD CA-20; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Skipped certificate: Common Name: Microsoft Windows Hardware Compatibility; Organizational Unit: Microsoft Corporation, Microsoft Windows Hardware Compatibility Intermediate CA, Copyright (c) 1997 Microsoft Corp. - reason no longer valid
Package Control: Skipped certificate: Common Name: DOD CA-31; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US - reason no longer valid
Package Control: Exported certificate: Common Name: Symantec Class 3 SHA256 Code Signing CA, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: DOD ID CA-41; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: ORC ECA HW 5; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: ORC ECA SW 5; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD EMAIL CA-39; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID CA-44; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD EMAIL CA-42; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID CA-33; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD EMAIL CA-43; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD EMAIL CA-33; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: IdenTrust ECA 5; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID SW CA-45; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID CA-43; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID CA-42; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD EMAIL CA-40; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: ORC ECA 6; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID SW CA-37; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID SW CA-36; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID CA-34; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: Symantec Client External Certification Authority - G4; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID CA-39; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD EMAIL CA-34; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD EMAIL CA-41; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID CA-40; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID SW CA-46; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD EMAIL CA-44; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: IdenTrust ECA 4; Organizational Unit: Certification Authorities, ECA; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID SW CA-47; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID SW CA-48; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Exported certificate: Common Name: DOD ID SW CA-35; Organizational Unit: PKI, DoD; Organization: U.S. Government; Country: US
Package Control: Error downloading channel. URL error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions downloading https://packagecontrol.io/channel_v3.json.
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3211
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at C:\Users\nguyenkq\AppData\Roaming\Sublime Text 3\Packages\User\oscrypto-ca-bundle.crt (229536 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Error downloading channel. URL error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions downloading https://packagecontrol.io/channel_v3.json.`

**Comment by sofiaringstrom** [comment]
I solved it by adding the following to the user settings to _Preferences > Package Settings > Package Control > Settings - User_

```
"downloader_precedence": {
  "osx": [
    "curl",
    "urllib",
    "wget"
  ],
}
```

**Comment by deathaxe** [comment]
WinError 10013 means permission denied and is most likely caused by a firewall blocking ST's plugin host from accessing internet.
