### ISSUE TITLE
Package Control: Error downloading channel. URL error [WinError 10013]

### ISSUE THREAD

**Issue by devnewbee** [wbond/package_control#1457]
_There are no packages available for installation_

I have followed the troubleshooting guide, https://packagecontrol.io/docs/troubleshooting, but I still can't seem to run package control.

I am getting these errors from the console...

_Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions downloading https://packagecontrol.io/channel_v3.json._

I made sure my firewall was not blocking ST3.
On my browser, I can access the https://packagecontrol.io/channel_v3.json page without any problems, I can also visit https://packagecontrol.io

I have also read some issues here concerning this type of problem, but none of their solutions worked for me.

**Comment by tywunon** [comment]
Same here :(

**Comment by wbond** [comment]
Try changing the `downloader_precedence` setting. See https://packagecontrol.io/docs/settings#setting-downloader_precedence. Since you are on Windows, you'll want to try something like:

```
"downloader_precedence": {
    "windows": ["urllib", "wininet"],
    "osx": ["urllib"],
    "linux": ["urllib", "curl", "wget"]
}
```

**Comment by tywunon** [comment]
for me it only happend on linux, and I already tried that, did not work

**Comment by wbond** [comment]
Oh, that would be somewhat different then. Please open new issue and be sure to include the error you are seeing. This issue is about a problem with WinInet not working.

**Comment by tywunon** [comment]
Okay sorry.

**Comment by Dafaq-lang** [comment]
> Try changing the `downloader_precedence` setting. See https://packagecontrol.io/docs/settings#setting-downloader_precedence. Since you are on Windows, you'll want to try something like:
> 
> ```
> "downloader_precedence": {
>     "windows": ["urllib", "wininet"],
>     "osx": ["urllib"],
>     "linux": ["urllib", "curl", "wget"]
> }
> ```
I'm having the same issues. Did try the above, still nothing. Have tried various ways nothing seems to work. However I can add packages with Package Control: Add Repository, this seems to be my only work around at the moment?

**Comment by wbond** [comment]
Can you provide a debug log? https://packagecontrol.io/docs/issues

**Comment by Dafaq-lang** [comment]
> Can you provide a debug log? https://packagecontrol.io/docs/issues

Thanks for your reply. Discovered some processes for sublime were not included by the firewall, sublime was added but for some reason ignored some of the processes, once those were added worked like a bomb.

**Comment by hailin84** [comment]
Same here. How did you  guys fix it ? Here is my versions:
  Platform: windows-x64
  Sublime Text Version: 4107
  Package Control Version: 3.4.1

**Comment by deathaxe** [comment]
By fixing firewall rules, I guess `[WinError 10013]` just means no connection was blocked.

**Comment by jiyinyiyong** [comment]
same here..

```
Package Control: Error downloading channel. URL error [Errno 61] Connection refused downloading https://packagecontrol.io/channel_v3.json.
```

also tried proxies, no help

```js
        "http_proxy": "http://127.0.0.1:7890",
	"https_proxy": "http://127.0.0.1:7890",
	"channels": "http://r.tiye.me/sublime/channel_v3.json",
```

**Comment by deathaxe** [comment]
Closing as being a firewall configuration issue.

see: https://github.com/wbond/package_control/issues/1346
