### ISSUE TITLE
My Package is not updated to most recent version/tag

### ISSUE THREAD

**Issue by daniele-niero** [wbond/package_control#1458]
Hi,

I've noticed this problem happened in the past for other users/developers.
Unfortunately this is happening again for me.

My package repository is https://bitbucket.org/daniele-niero/sublimeprojectenvironment

In the last two/three weeks I've updated to version 1.0.11 (from 1.0.10) and that was successful.
Yesterday I've updated to Version 2.0.0, but that was never been seen by PackageControl.
Not only, even if PackageControl still showing version 1.0.11, the readme is not picked up anymore.

Check the page https://packagecontrol.io/packages/Project Environment

The previous issues were caused by bugs in the crawler, but I suspect this time there is something wrong with my repository, although, I can't figure out what.

**Comment by wbond** [comment]
This appears to be a bug with the new BitBucket client not supporting pagination. Your readme isn't within the first ten entries of the dir listing, and your new version isn't within the first ten tags.

I'm in the process of testing changes to fix these issues.

**Comment by wbond** [comment]
This is fixed by 0323d89aa61d228eeb59a7ca6278b0ae8c339a59 and https://github.com/wbond/packagecontrol.io/commit/50fbfbed250502f4106f0a0616321456c1b36112. It will take up to 2 hours before the crawler looks at your package again.
