### ISSUE TITLE
Can't specify dependencies for the User package

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#1463]
Currently, Package Control pretty much completely ignores the User package for all management purposes (it's excluded in `PackageManager.list_packages`), but that also means it doesn't look into it when satisfying dependencies. I would like to be able to use dependencies in my simple one-off plugins in my User package.

**Comment by rchl** [comment]
`Package Control: Install Local Dependency` does install dependencies for locale packages and `Package Control: Satisfy Dependencies` updates them.

It does seem a bit weird though, I would hope those would just work without having to manually trigger those.

**Comment by MattDMo** [comment]
`Package Control: Install Local Dependency` doesn't seem to read `Packages/User/dependencies.json` to install new dependencies. `Package Control: Satisfy Dependencies` also doesn't read the file in `Packages/User`, but it *will* read `Packages/SomeRandomPlugin/dependencies.json`.

So, as a workaround, you'll just need to create a `Local Dependencies` (or similar) folder in `Packages` and put a `dependencies.json` file in it that you update whenever you need a new dependency for a one-off that you're working on. You'll then have to satisfy dependencies before you can use it.
