### ISSUE TITLE
Package Control keeps removing a manually installed package

### ISSUE THREAD

**Issue by dannftk** [wbond/package_control#1464]
Hi,

I have a [package](https://github.com/dannftk/cppAdvanced)
I am on linux OS and clone it to the directory `~/.config/sublime-text-3/Packages` so that there appears a directory `cppAdvanced`
Upon cloning I open a Sublime Text 3 and it says that it has removed an old orphaned directory `cppAdvanced`
Could you please tell me what is going on?

```
Package Control: Removed old directory cppAdvanced
reloading settings Packages/cppAdvanced/C++.sublime-settings
reloading settings Packages/cppAdvanced/C.sublime-settings
```

Thank you

**Comment by dannftk** [comment]
UPD: hardly surfing internet and trying different approaches I seem to have found out that `package-metadata.json` and `package-control.cleanup` may affect this. I removed them from the package before opening Sublime Text, also having appended `cppAdvanced` into the list of `intalled_packages` in `Package Control.sublime-settings` and it has come out

**Comment by wbond** [comment]
Yes, package-control.metadata indicates that Package Control is managing the package. If you put that into a package not managed by Package Control, you are messing with the internal state of PC.

The file is used by PC to track that the package has been installed and what version is present. If the file is present, but the package name is not in `installed_packages`, it can be determined the user uninstalled the package on another machine and synced their settings to the current machine. Hence the notice about removing the orphaned package.

**Comment by wbond** [comment]
If you are installing a package manually, just don’t create internal Package Control files and Package Control won’t touch the package unless you tell it to.

**Comment by dannftk** [comment]
Ok, thank you
Still, must I list a new manually installed package disposed in the  `~/.config/sublime-text-3/Packages` in `installed_packages`?

**Comment by FichteFoll** [comment]
No, that is also under PC authority. You only need to remove `package-metadata.json` from your local clone (and the repository, but it doesn't seem to have it in the first place).

**Comment by dannftk** [comment]
thank you so much, I am closing the issue
