### ISSUE TITLE
Settings: repositories

### ISSUE THREAD

**Issue by TerminalFi** [wbond/package_control#1469]
**What**
- Repositories `settings.get('repositories')`

Rather than a list/array like the following

```json
"repositories": ["REPO"]
```

it would likely benefit to have it be an list/array of dicts such as, which allows for the name to be the primary text in the quick_panel and the url to be the secondary text in thee quick_panel

```json
{
    "repositories": [
        {
            "name": "SnAPI Repo",
            "url": "https://raw.githubusercontent.com/STealthy-and-haSTy/SublimePackages/master/unreleased-packages.json"
        }
    ]
}
```

**Comment by FichteFoll** [comment]
I personally don't think this is needed. People modifying the repositories setting are much more likely to perform such changes in the settings file directly instead of using the command palette.

**Comment by TheSecEng** [comment]
Two things:

1. What would be the harm in supporting this format?
1. I actually use the command palette over editing the JSON file when modifying repositories, which is how I initial discovered that when removing repos, I am presented with a list of long URL's which may or may not be enough info for me to know which one to remove.

**Comment by FichteFoll** [comment]
> What would be the harm in supporting this format?
It's a new feature that needs to be implemented, maintained, and adds potetial for breaking backwards compatibility. Every feature that is added should be evaluated for its necessity and usefulness.

**Comment by deathaxe** [comment]
I don't think it makes sense to give json repositories, names.

As `"repositories": []` can also take normal github/gitlab/bitbucket repos it may probably make sense to provide InputHandlers to also enter a "Package Name", when adding new urls, very much like Sublime Merge's "Add Remote" command, but those package names would then be stored in `"package_name_map"`.
