### ISSUE TITLE
Plugin installation with package control in Sublime 3 is entirely Voodoo.

### ISSUE THREAD

**Issue by ukimpact** [wbond/package_control#1470]
I have a lightweight machine which can't run heavy IDEs. Thought going with Sublime3 package control. I honestly haven't seen worse experience to install plugin ever, for the last 10 years this is phenomenon. I don't understand anything about the process or the flow, it is non standard to other IDEs, no decent guides ...

My user journey:

Install Terminus with Sublime3. After 30 min fighting i give up on IDE and the plugin.

- Need to install package manager? Why does it not come preinstalled? 
- What is this tutorial? https://packagecontrol.io/installation for whom it is created? Install package manager and then?

Installed package manager how does this : 
https://packagecontrol.io/packages/Terminus

gets installed in package manager? I tried to put the url above to:
**Preferences->Package Control>Add Repository**

There is no "OK" button or anything :-D 

![Screenshot from 2020-05-23 12-53-51](https://user-images.githubusercontent.com/6765469/82730005-82490c00-9cf4-11ea-87ef-55eb1c5a89b5.png)

 I don't mean to rage, but people, it is 2020 for record, these problems are already solved everywhere else. And I am not even millennial , so my patience span is a bit longer :-).

**Comment by wbond** [comment]
The usage docs are separate from the installation docs. You can find them at https://packagecontrol.io/docs/usage.

Your feedback is helpful - we should make sure there is a clear next action button for people to more easily transition to searching for a package or installing one.
