### ISSUE TITLE
Use the "Edit Settings" side-by-side view

### ISSUE THREAD

**Issue by michaelblyons** [wbond/package_control#1474]
Can the "[Settings - Default / Settings - User](https://github.com/wbond/package_control/blob/master/Default.sublime-commands#L74-L87)" code be switched to that `edit_settings` one that opens both at once?

**Comment by TheSecEng** [comment]
Likely dependent on #1313 I think the `edit_settings` command came in ST3?

**Comment by wbond** [comment]
I've got a shim/workaround in SFTP that uses `edit_settings` when available. I'll probably port it over for the last ST2 release.

**Comment by wbond** [comment]
This was added in 3e673f22525ff272275fa85b5221144f970af872
