### ISSUE TITLE
Control package of sublime text 3 not working 

### ISSUE THREAD

**Issue by MostafaSalah4** [wbond/package_control#1479]
I have problem with control package after installed all list of package of the course , i get a problem with visited and hover (pseudo class selectors) .These not highlighted after installed the package also. so that i cant show the affect of them in browser .

**Comment by FichteFoll** [comment]
This doesn't appear to be related to Package Control. You need to find out which package you installad and is misbehaving. Then you can follow the package's issues link on https://packagecontrol.io/.

**Comment by wbond** [comment]
Closing as invalid
