### ISSUE TITLE
Support download of custom build artifacts

### ISSUE THREAD

**Issue by deathaxe** [wbond/package_control#1484]
Package Control downloads packages from `https://codeload.github.com/<user>/<repo>/zip/<tag>` which always downloads the whole exported repository of the given `<tag>`.

A plugin author might want to run a deploy workflow to create custom build artifacts, which may contain external libraries which are not part of the repository itself. Those build artifacts are available for download via `https://github.com/<user>/<repo>/releases/download/<tag>/<artifact>`. The `<artifact>` is file name such as _Emmet.zip_.

At the moment an `url` key needs to be specified in the _repository.json_ to download such custom files.

How about adding a `download` key, which if present is used to build the download url?

**Example:**

```
{
	"schema_version": "3.0.0",
	"packages": [
		{
			"name": "Alignment",
			"details": "https://github.com/wbond/sublime_alignment",
			"download": "https://github.com/${user}/${repo}/releases/download/${tag}/Emmet.zip"
			"releases": [
				{
					"sublime_text": "*",
					"tags": true
				}
			]
		},
	]
}
```

**Comment by rwols** [comment]
Maybe we can go a bit further with this? the github api has a wealth of info.

```js
{
	"schema_version": "4.0.0",
	"packages": [
		{
			"name": "Package",
			"github": "user/sublime-package"
		}
	]
}
```

Only problem seems to be the missing `"subime_text"` key. But, if we all agree upon the idea that tags can be of the form `BBBB-x.y.z`, where `BBBB` is the minimum supported ST build version, then this should all be possible to work out what the latest release is for a given sublime version.
