### ISSUE TITLE
Trigger update check on ST version change

### ISSUE THREAD

**Issue by rchl** [wbond/package_control#1486]
When ST is upgraded, I think it would make sense to trigger update check. Especially when upgrading to a new major version as that can require upgrading to completely new versions of packages (one case: https://github.com/sublimelsp/LSP/issues/1186).

Currently, it seems that even on upgrading to a new major ST version, the update check will follow the usual schedule and might not run until some time later.

**Comment by wbond** [comment]
This should be addressed by 21e6c3aa918e165ba8507b1bb892f062d6d7d187

**Comment by FichteFoll** [comment]
This setting introduced in https://github.com/wbond/package_control/commit/21e6c3aa918e165ba8507b1bb892f062d6d7d187 will cause the settings file to change for every ST update, which will be annoying for people who have this file in VCS and can even lead to conflicts. It will also not behave as expected when the file is synced to other machines over other means, such as Dropbox. I believe a file in the cache path will be appropriate.

**Comment by rchl** [comment]
Good points but maybe besides the one about the file always changing as I would presume that that already happens as PC is probably storing last update check time there also?

**Comment by wbond** [comment]
Yes, I am planning on moving all state data to the cache, but this should probably happen now so we don’t run into these issues.

**Comment by wbond** [comment]
As of 0115b17814e4c1e86011cce1e539e892e78a5e23 the ST version info is no longer stored in the User package. Subsequent commits moved the HTTP cache and CA bundles out of the User package also into the Cache dir.
