### ISSUE TITLE
Unhandled error when using bad credentials

### ISSUE THREAD

**Issue by PpChailley** [wbond/package_control#1496]
The plugin refuses to create a gist with "unknown error". I just installed the plugin on this computer, so I suppose it's a credentials issue.

However, the error should be handed with a little more explanations

Here's the log: https://gist.github.com/PpChailley/064e72e5578a3146d4568f4fb146d041
My public settings file (copied the default and just added the debug=true option): https://gist.github.com/PpChailley/5c0dc96d5b19117634f490efbab51b84
my private settings file: https://gist.github.com/PpChailley/6810828c0844b85846b35fc3524dd4b0
Running on sublime 3.2.2 build 3211 on Ubuntu Focal LTS

Cheers & thanks for the plugin !!

**Comment by wbond** [comment]
This appears to be a bug with the "Gist" package, and not Package Control.
