### ISSUE TITLE
Error during startup trying to import CoreFoundation, CFHelpers 

### ISSUE THREAD

**Issue by kallewangstedt** [wbond/package_control#1498]
During startup of SublimeText 3 (both latest and the recent beta), Package control will not load on macOS Big Sur 11.0-beta (20A5364e). This, according to the error message in consol (below), seems to be due to new API's for calling CorFoundation.
```
File "/Users/kalle/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 7, in <module>
ImportError: No module named 'Package Control.package_control.deps.oscrypto._osx._core_foundation_cffi'
```
How to reproduce:

1. Install macOS 11.0-beta
2. Install SublimeText 3
3. Install Package control
4. Restart SublimeText
5. Look in Console to see error

**Comment by siddartha87** [comment]
Same problem 

` File "/Users/lavoro/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation_ctypes.py", line 21, in <module>
Package Control.package_control.deps.oscrypto.errors.LibraryNotFoundError: The library CoreFoundation could not be found`

**Comment by wbond** [comment]
This has been fixed on master
