### ISSUE TITLE
package control not installing other packags

### ISSUE THREAD

**Issue by kumararjunk** [wbond/package_control#1512]
If you are running into a bug, please read https://packagecontrol.io/docs/troubleshooting
before submitting an issue here.

Bug reports must include a debug log. The Troubleshooting page explains how to capture one.

**Comment by kumararjunk** [comment]
I am using mac pro, MacOS Catalina 10.15.17, I was able to install the package control, but when try to install other package i get the error:

There are no packages available for installation

Please see https://packagecontrol.io/docs/troubleshooting for help

**Comment by wbond** [comment]
Please follow the directions at https://packagecontrol.io/docs/issues and submit a debug log here.
