### ISSUE TITLE
Provide alternative, easy way to manually download/install packages

### ISSUE THREAD

**Issue by jedis00** [wbond/package_control#1536]
Can you provide an alternative way to download packages that is easy to use?

Downloads from codeload.github.com are blocked by our corporate proxy. I can, however, clone git repos from GitHub.

Is there another mechanism to be able to have Package Control clone the repo and get what it needs that way, vs trying to download a zip file that is getting blocked?

**Comment by wbond** [comment]
Personally I don't think this is a project I'd be interested in tackling, and my time is severely limited for open source these days, the majority of which goes into maintaining the infrastructure and necessary code maintenance.

That said, it is possible someone would be keen on taking on such a project.

It would require each package be augmented with info about alternative methods of install, like VCS commands, if available. Then someone would have to write the code to checkout and update repos. There is already code to keep things up-to-date, but it isn't the most robust.
