### ISSUE TITLE
Check for updates before showing incompatible package warnings for packages incompatible with ST4

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#1560]
When an Data folder is shared, most notably now with ST4 starting off the existing ST3 Data folder, PC complains about incompatible package versions while a proper version is actually available but not installed. This leads to unnecessary confusion for some users, because the package is auto-updated shortly afterwards and fixes the problem.

![popup](https://cdn.discordapp.com/attachments/280102180189634562/835580358191349770/unknown.png)

While this is probably still a useful warning for people syncing their packages across different platforms, for the ST3->ST4 path this is mostly annoying. I suggest to perform a package upgrade first for packages that don't match the current ST build and where the upgrade is from ST3 to ST4.

**Comment by deathaxe** [comment]
Addressed by 6324889cd3971fa4eb9a454941003003e03048c8
