### ISSUE TITLE
Package Control failing to install dependencies

### ISSUE THREAD

**Issue by nihal-ramaswamy** [wbond/package_control#1564]
When I try to install packages, this is error I get.
Operating System: Mac osx Big Sur
Sublime Text Version: Dev Channel Build 4104
<img width="969" alt="Screenshot 2021-05-05 at 9 10 01 PM" src="https://user-images.githubusercontent.com/41371273/117168948-42d0de00-ade6-11eb-86d7-249b5f26e6a7.png">

**Comment by deathaxe** [comment]
see also https://github.com/wbond/package_control/issues/1558

It appears the dependency got into review state due to temporary unavailability of its source.

This is a mechanism to handle: https://packagecontrol.io/news#2021-02-24-Package_Takeover_Vulnerability_Notification
