### ISSUE TITLE
package control not wroking in window10 help please

### ISSUE THREAD

**Issue by mspeed-13** [wbond/package_control#1568]
startup, version: 2221 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/WINDOWS/System32
packages path: /C/Users/Acer/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/Acer/AppData/Roaming/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Package Control\1_reloader.py
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Package Control\2_bootstrap.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\2_bootstrap.py", line 22, in <module>
    from package_control.bootstrap import bootstrap_dependency, mark_bootstrapped
  File ".\package_control\bootstrap.py", line 20, in <module>
    from .download_manager import downloader
  File ".\package_control\download_manager.py", line 24, in <module>
    from .downloaders import DOWNLOADERS
  File ".\package_control\downloaders\__init__.py", line 20, in <module>
    from .oscrypto_downloader import OscryptoDownloader
  File ".\package_control\downloaders\oscrypto_downloader.py", line 44, in <module>
    from ..deps.oscrypto import tls  # noqa
  File ".\package_control\deps\oscrypto\tls.py", line 17, in <module>
    from ._win.tls import (
  File ".\package_control\deps\oscrypto\_win\tls.py", line 7, in <module>
    import select
ImportError: No module named select
Reloading plugin C:\Users\Acer\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\Package Control.py", line 96, in <module>
    from package_control.commands import *  # noqa
  File ".\package_control\commands\__init__.py", line 3, in <module>
    from .advanced_install_package_command import AdvancedInstallPackageCommand
  File ".\package_control\commands\advanced_install_package_command.py", line 10, in <module>
    from ..package_manager import PackageManager
  File ".\package_control\package_manager.py", line 34, in <module>
    from .downloaders.background_downloader import BackgroundDownloader
  File ".\package_control\downloaders\__init__.py", line 20, in <module>
    from .oscrypto_downloader import OscryptoDownloader
  File ".\package_control\downloaders\oscrypto_downloader.py", line 44, in <module>
    from ..deps.oscrypto import tls  # noqa
  File ".\package_control\deps\oscrypto\tls.py", line 17, in <module>
    from ._win.tls import (
  File ".\package_control\deps\oscrypto\_win\tls.py", line 7, in <module>
    import select
ImportError: No module named select
plugin init time: 8.60963
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 27.7503
startup cache, total files: 96 cache hits: 96
startup time: 28.1462 (package setup was not run)
loaded 837 snippets

**Comment by deathaxe** [comment]
Recent versions of oscrypto 

1. depend on a `select` module, which is not available for python 2.6.
2. are required to support more recent OS.

With ST2 being unmaintained for years and PC4.0 being in development dropping support for it, I close this issue as "won't fix".

Time for ST2 is over.
