### ISSUE TITLE
A package using dependencies.json as well as a module from Default is broken in ST4

### ISSUE THREAD

**Issue by rwols** [wbond/package_control#1570]
The following situation is somewhat tragic:

- If a package uses _only_ dependencies.json, then it will keep working in py33.
- If a package imports something from Default, but doesn't use dependencies.json, then it can easily fix this by adding a .python-version file.

However, the Default package is now running in py38. So if a package imports something from Default _and_ it uses dependencies.json, then there is currently no way to fix this.

Example: https://github.com/rwols/CMakeBuilder/blob/master/plugin.py uses Default.exec and the `tabulate` dependency.

**Comment by FichteFoll** [comment]
Nothing that PC can do about this in particular, outside of getting ~~dependencies~~libraries ready for Python 3.8, which we already have project for: https://github.com/wbond/package_control/projects/1

**Comment by rwols** [comment]
I'll see what I can do about https://github.com/wbond/package_control/issues/1517

**Comment by randy3k** [comment]
What about finding and importing the `Default` module to python 3.3?

```
loader = sublime_plugin.multi_importer.find_module("Default")
mod = loader.load_module("Default")
sys.modules["Default"] = mod
import Default.exec
```

**Comment by rwols** [comment]
@randy3k that's clever, but won't work anymore once the Default package starts using e.g. f-strings. I don't expect the Default to start using py38 features any time soon though :) good idea!

**Comment by deathaxe** [comment]
With that comment you drive your whole request useless.

The way to go for plugins ported to python 3.8 is to get rid of "Default" dependencies and do their job on their own.

**Comment by rwols** [comment]
@deathaxe I'm not planning on using that hack, but I still think it's clever :)

**Comment by deathaxe** [comment]
You might want to have a look how packa_control handles that, then. In injects itself into lib of both hosts.
