### ISSUE TITLE
Document ranges for the `sublime_text` build selector

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#1575]
We don't have an example for range selectors in our `example_repositoy.json` and definitely should add one. There's been some confusion about this in the past, most recently https://github.com/vuejs/vue-syntax-highlight/issues/208.

**Comment by deathaxe** [comment]
An example will be provided by PC4.0 (see https://github.com/wbond/package_control/blob/eea307ec74195f2589aa1d09d9f6bd08641d0b21/example-repository.json#L312-L314).

Furthermore PC4.0 ships a json schema so users of LSP-json, will get full intellisense support for writing repositories.

The only requirement is to add a schema entry to their json files.

see: https://github.com/wbond/package_control/blob/eea307ec74195f2589aa1d09d9f6bd08641d0b21/example-repository.json#L6
