### ISSUE TITLE
Packages missing from https://packagecontrol.io/channel_v3.json

### ISSUE THREAD

**Issue by johnathanz** [wbond/package_control#1576]
I've tried this on a clean / no package install of Sublime Text 3 and 4.

When I try to `Package Control: Install Package`. I can't find the following packages:
* [NeoVintageous](https://packagecontrol.io/packages/NeoVintageous)
* [Anaconda](https://packagecontrol.io/packages/Anaconda)
* [Jedi](https://packagecontrol.io/packages/Jedi%20-%20Python%20autocompletion)
* [ApplySyntax](https://packagecontrol.io/packages/ApplySyntax)

There is a `Missing` status against those on the Package Control URLs above - what does this mean?

![CleanShot 2021-06-10 at 11 44 06](https://user-images.githubusercontent.com/1593039/121451642-4b1dc980-c9e1-11eb-80e3-20a148a74104.png)

From the debug log, looks like package list is fetched from `https://packagecontrol.io/channel_v3.json`.  Had a look at the json, seems like these packages aren't in the file

I installed Jedi less than 2 hours ago via PC, and it was there. Has something changed the server version of `channel_v3.json` @wbond ?

Thanks!

Debug log content below

----

reloading settings Packages/User/Package Control.sublime-settings
Package Control: Settings change detected, clearing cache
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 4107
  Package Control Version: 3.4.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: ::ffff:50.116.34.243
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/johnathan/Library/Caches/Sublime Text/Cache/Package Control/oscrypto-ca-bundle.crt (288008 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/johnathan/Library/Caches/Sublime Text/Cache/Package Control/merged-ca-bundle.crt
  Using hostname "packagecontrol.io" for TLS SNI extension
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher ECDHE-RSA-AES128-GCM-SHA256
  Server SSL certificate:
    subject: CN=packagecontrol.io
    subject alt name: packagecontrol.io, www.packagecontrol.io
    expire date: Dec 21 12:00:00 2021 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-None-Match: "60c16b1a-2256a"
  Connection: Keep-Alive
  User-Agent: Package Control v3.4.1
  Host: packagecontrol.io
  Accept-Encoding: bzip2,gzip,deflate
  If-Modified-Since: Thu, 10 Jun 2021 01:30:02 GMT
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Thu, 10 Jun 2021 01:40:17 GMT
  Content-Type: application/json
  Content-Length: 165594
  Last-Modified: Thu, 10 Jun 2021 01:40:02 GMT
  Connection: keep-alive
  ETag: "60c16d72-286da"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Accept-Ranges: bytes
Package Control: Caching https://packagecontrol.io/channel_v3.json in /Users/johnathan/Library/Caches/Sublime Text/Cache/Package Control/http_cache/01524fae79697630d0454ba3fabd9414
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request

**Comment by personalcomputer** [comment]
I'm experiencing the same issue. This seems to be a package control repo crawler outage. Maybe it hit some anti-spam Github ratelimiting threshold and has now been effectively shut out of most repos?

For anyone who doesn't know: In the interim, as a workaround you can do Cmd+Shift+P, then "Package Control: Add Repository", then copy/paste in the Github Repository URL. The repository URL can be found on the package's Package Control webpage, e.g. `https://github.com/srusskih/SublimeJEDI` for [Jedi](https://packagecontrol.io/packages/Jedi%20-%20Python%20autocompletion).

**Comment by johnathanz** [comment]
cool, good workaround, thanks @personalcomputer !

**Comment by johnathanz** [comment]
Looks like the issue has been fixed. The packages I was missing are in `channel_v3.json` again
