### ISSUE TITLE
Cannot install package due to dependency not being available.

### ISSUE THREAD

**Issue by johanrosenson** [wbond/package_control#1581]
I originally posted this as a [bug on the LSP page](https://github.com/sublimelsp/LSP/issues/1819) but was sent here instead.

I am trying to install the LSP plugin, but i get the following error in the console, which i have no knowledge on how to fix, search online have not given much good answers either, so i turn here.

Is this an error that you have encountered before and have a way to fix/work around?

```
Package Control: The dependency 'backrefs' is not currently installed; installing...
Package Control: The dependency 'backrefs' is not available
Package Control: The dependency 'backrefs' could not be installed or updated
```

Things i have tried already:

* removing package control and reinstalling.

**Environment**

OS: MacOS 10.15.7 (19H2)
Sublime Text version: 4113

**Comment by randy3k** [comment]
I encountered the same issue.
It seems to be an issue of the crawler of package control not able to locate the dependencies: `dependencies_cache` in https://packagecontrol.io/channel_v3.json is empty.

A temparorily workaround is to use this backup channel https://github.com/irvingcode/channelV3

- Run `Package Control: Add Channel`
- Paste `https://raw.githubusercontent.com/irvingcode/channelV3/master/channel_v3.json`
- Remember to remove the added channel once the issue of pakcage control is fixed.

**Comment by randy3k** [comment]
Looks like packagecontrol.io/channel_v3.json has been updated. The workaround is no longer needed.

**Comment by rerorengine** [comment]
Yep, I just read this issue and tried installing LSP (which need backrefs) and it installed smoothly and I didn't do any changes (its just a fresh install of ST4 in my new OS, I'm setting up ST4 in that OS). 😃

**Comment by johanrosenson** [comment]
Looks like it's all working now, so closing this, thanks all!

One request would be for a better error message when this happens, it's not easy (without knowledge) to understand if it's the local installation that's having a problem or something else.
