### ISSUE TITLE
Disallow "Add Repository"

### ISSUE THREAD

**Issue by bostick** [wbond/package_control#1585]
I have a git repository that has source for building a package, but the repo is not the package itself.

If a user did "Add Repository" on the git repo and installed the package, then the resulting .sublime-package would be very strange and incorrect.

I would like a way to prevent users from doing "Add Repository".

Is this possible?

**Comment by deathaxe** [comment]
No, there is not. There's also no way for Package Control, which git repositories can be added or not.

**Comment by FichteFoll** [comment]
What we could talk about is adding a feature for the Add Repository command to 
1. Switch to an input handler
2. Add a second optional prompt for a name to give to the provided git url (if it is a git url instead of a link to a repository.json file).
