### ISSUE TITLE
[Bug report] Crash of Package Control at Sublime3 start

### ISSUE THREAD

**Issue by mdziczkowski** [wbond/package_control#1604]
### Environment

    OS type: Linux
    OS distro Debian (10)
    Sublime version: Build 4113

Description

After starting Sublime3, I recieve a Package Control error message about the inpropper locale and how to set the LANG and LC_LCTYPE variables, even if they are already correctly set

### Steps to reproduce

    Start Sublime Text
    See the error

### Notes

The above error started to appear from the moment after the update of Sublime has failed

**Comment by deathaxe** [comment]
PC does some explicit unicode encode/decode checks upon startup. If those fail, it is most likely caused by ST being executed in an isolated environment which doesn't use correct language settings and/or doesn't respect LC_LCTYPE etc. from user profile.

There's nothing PC can do to fix it.
