### ISSUE TITLE
Documentation note or Explicit Error for python3.8 dependency.json

### ISSUE THREAD

**Issue by necarlson97** [wbond/package_control#1606]
It seems the dependency.json is not supported (yet) for python3.8
However, this manifests as a strange error - e.g.:
```
requests.get(
AttributeError: 'module' object has no attribute 'get'
```

3.8 being currently unsupported is completely understandable.
However, in the meantime, perhaps it would be prudent to update the [documentation](https://packagecontrol.io/docs/dependencies) with a line about this?

And/or a line added to the 'comments' on [example-dependencies.json](https://github.com/wbond/package_control/blob/master/example-dependencies.json)?

Additionally, it might be even better to add an explicit error check for this

Perhaps something in `package_control/package_manager.py:168 get_dependencies(self, package)` that throws a `ValueError("dependency.json is not currently supported with python3.8, please use python3.3 or include the 3rd party libraries in your package")` or similar
(I'm afraid I don't currently have the time to grok this project enough for a competent PR, but hopefully this can be useful to someone more experienced.)

(related to the discussion in https://github.com/wbond/package_control/issues/1570)
(See [here ](https://forum.sublimetext.com/t/sublime-text-3-plugin-use-requests-module/49897/5) for the initial troubleshooting)
Thanks, and let me know if any extra info would be helpful!

**Comment by deathaxe** [comment]
PC 3.x won't receive any more updates and PC4.0 will support python 3.8.
