### ISSUE TITLE
Excuse me, how to install json

### ISSUE THREAD

**Issue by zhang12346** [wbond/package_control#1608]
Excuse me, how to install json

**Comment by runeimp** [comment]
What aspect of JSON support are you trying to achieve? Basic JSON support with syntax highlighting is installed by default with Sublime Text 3 and 4. I think ST2 had basic JSON support built in as well. But if not just install Package Control you can... do nothing? If I remember correctly Package Control was created while ST2 was the latest version. But all the package control instructions expect you're using ST3 or ST4 now which has easy install of Package Control built in. So hopefully you're not on Sublime Text 2 or 1.

**Comment by zhang12346** [comment]
Hello, is there any introduction document used?

**Comment by runeimp** [comment]
@zhang12346 Introduction to JSON or Sublime Text?

**Comment by zhang12346** [comment]
Hello, yes, mine is sublime 4

**Comment by zhang12346** [comment]
Excuse me, is there a plug-in that can format JSON? And installation steps

**Comment by runeimp** [comment]
@zhang12346  I use `Pretty JSON`

1. Install Package Control: see https://packagecontrol.io/installation
2. Open the Command Palette: `Cmd+Shift+P` (Mac) or `Ctrl+Shift+P` (Linux / Windows)
3. Type `install` you should see `Package Control: Install Package` highlighted in the dropdown list
4. Press `Enter`
5. Type `pretty` you should see `Pretty JSON` highlighted in the dropdown list
6. Press `Enter`
