### ISSUE TITLE
Unable to show the Install Package window

### ISSUE THREAD

**Issue by ralmeida** [wbond/package_control#1614]
Steps Taken
  `Open Sublime 2.0.2 build 2221`
  `Enter: Cmd + Shift + P`
  `Enter: 'install package'`
  `-- nothing happens --`

Checked here https://forum.sublimetext.com/t/package-control-not-working-at-all/29219 and this did not resolve the issue.

System
`Mac Big Sur 11.6.2`

This is the console output:

> 
> Exception in thread Thread-25:
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "./package_control/commands/install_package_command.py", line 45, in run
>   File "./package_control/package_installer.py", line 58, in make_package_list
>   File "./package_control/package_manager.py", line 694, in list_available_packages
>   File "./package_control/package_manager.py", line 554, in _list_available
>   File "./package_control/package_manager.py", line 453, in list_repositories
>   File "./package_control/providers/channel_provider.py", line 201, in get_repositories
>   File "./package_control/providers/channel_provider.py", line 87, in fetch
>   File "./package_control/download_manager.py", line 340, in fetch
>   File "./package_control/downloaders/urllib_downloader.py", line 117, in download
>   File "./package_control/downloaders/urllib_downloader.py", line 317, in setup_opener
>   File "./package_control/ca_certs.py", line 31, in get_ca_bundle_path
>   File "./package_control/ca_certs.py", line 166, in get_system_ca_bundle_path
>   File "./package_control/deps/oscrypto/trust_list.py", line 122, in get_path
>   File "./package_control/deps/oscrypto/_osx/trust_list.py", line 49, in extract_from_system
>   File "./package_control/deps/oscrypto/_ffi.py", line 121, in new
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/api.py", line 266, in new
>     cdecl = self._typeof(cdecl)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/api.py", line 186, in _typeof
>     result = self._typeof_locked(cdecl)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/api.py", line 171, in _typeof_locked
>     type = self._parser.parse_type(cdecl)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/cparser.py", line 552, in parse_type
>     return self.parse_type_and_quals(cdecl)[0]
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/cparser.py", line 555, in parse_type_and_quals
>     ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/cparser.py", line 338, in _parse
>     self.convert_pycparser_error(e, csource)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/cparser.py", line 367, in convert_pycparser_error
>     raise CDefError(msg)
> CDefError: cannot parse "CFArrayRef *"
> <cdef source string>:2:12: before: *
>

**Comment by mvilain** [comment]
I'm running MacOS 10.13.6 with Sublime 4126. I don't get a crash dump, just the message box saying 

  Package Control

  There are no packages available for installation

  Please see https://packagecontrol.io/docs/troubleshooting for help


This used to work as I still have packages before it stopped.

From Tools>Command Palette menu, enter Package Control: List Packages.   This works.

I went to that page and turned on debugging. It can't find the json file it expects but I can go to the URL and access the file with a browser or curl. I emailed the developer directly but he hasn't responded.

Installing Sublime 3211 and installed Package Control. Package Control: Install works on V3.

**Comment by deathaxe** [comment]
What I find very strange is the log referencing python 2.7 because ST2 uses python 2.6, but I am not even a Mac noob.

Which version of Package Control do you use? It seems out dated as the current 3.4.1 doesn't contain an `./package_control/deps/oscrypto/_osx/` folder. 

That said, the error looks like some os related APIs have changed on Mac, which cause this failure.

**Comment by mvilain** [comment]
It's definitely version related. I don't have this problem with Sublime 4 on MacOS 15.2. But on both my MacOS 10.13.6 systems, it stopped working.

**Comment by df-a** [comment]
> 

I have the same issue, and it used to work properly. I haven't had any MacOS updates ever since it was working, and I am on v. 12 Monterrey. I wonder why it just stopped working like that.

**Comment by mvilain** [comment]
On my 10.13.6 systems, it stopped working but on the 10.15.2 system I have, it's OK. I wonder if it's something to do with the encryption the site is using. I can access the json file just fine with my browser, wget, and curl, so something in V4 isn't working right. V3 is fine.

**Comment by df-a** [comment]
Which OpenSSL version do you have installed on your systems (as its oscrypto which affects it)? Mine is 3.0.1 14 Dec 2021

**Comment by mvilain** [comment]
My system is running Apple's version of OpenSSL 
`
$ openssl version
LibreSSL 2.2.7
$ which openssl
/usr/bin/openssl
`

**Comment by TheSecEng** [comment]
Are you still experiencing this

**Comment by FichteFoll** [comment]
> What I find very strange is the log referencing python 2.7 because ST2 uses python 2.6, but I am not even a Mac noob.

Iirc, ST2 on mac used the system Python instead of a bundled one, but since ST2 hasn't seen an update in a long time, I wouldn't put my money on that still working.

@ralmeida, please use a more up-to-date version of Sublime Text, e.g. build 4126.

**Comment by deathaxe** [comment]
ST2 doesn't work anymore since python 2 was removed from MacOS. There have already been several topics in forum about that. With EOL of py2, ST2 is out of order as well.

**Comment by FichteFoll** [comment]
Closing the issue since it's not a problem with Package Control.
