### ISSUE TITLE
Package Control: Missing dependency (plutil) for nodejs not able to be resolved

### ISSUE THREAD

**Issue by dhershhorn** [wbond/package_control#1619]
**Issue Description:**
Sublime complains of unresolved dependency on startup, attempts to install and asks to be restarted

**Steps to reproduce:**
Uninstalled Sublime and re-installed on: MacBook Air (M1, 2020), Chip: Apple M1, Memory: 16GB, OS: Monterey v12.3.1, installed Package Control, installed nodejs, quit and re-opened Sublime

**Debug Log:**
startup, version: 4126 osx arm64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/mwaddell/Library/Application Support/Sublime Text/Packages
state path: /Users/mwaddell/Library/Application Support/Sublime Text/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/mwaddell/Library/Application Support/Sublime Text/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.192038
OpenGL Context Information:
  GL API Version: 4.1 Metal - 76.3
  GLSL Version: 4.10
  Vendor: Apple
  Renderer: Apple M1
startup time: 0.243655
first paint time: 0.247768
environment variables loaded using: /bin/bash -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading python 3.3 plugin 0_package_control_loader.10-shellenv
reloading python 3.3 plugin 0_package_control_loader.20-newterm
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin Nodejs.__init__
reloading python 3.3 plugin Nodejs.Nodejs
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/mwaddell/Library/Application Support/Sublime Text/Packages/Nodejs/Nodejs.py", line 14, in <module>
    from .lib.nodejs_commands import *
  File "/Users/mwaddell/Library/Application Support/Sublime Text/Packages/Nodejs/lib/nodejs_commands.py", line 3, in <module>
    from .nodejs_base import *
  File "/Users/mwaddell/Library/Application Support/Sublime Text/Packages/Nodejs/lib/nodejs_base.py", line 7, in <module>
    import psutil
ImportError: No module named 'psutil'
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages and dependencies
  Platform: osx-arm64
  Sublime Text Version: 4126
  Package Control Version: 3.4.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: ::ffff:50.116.34.243
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/user/Library/Caches/Sublime Text/Cache/Package Control/oscrypto-ca-bundle.crt (247839 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/user/Library/Caches/Sublime Text/Cache/Package Control/merged-ca-bundle.crt
  Using hostname "packagecontrol.io" for TLS SNI extension
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher ECDHE-RSA-AES128-GCM-SHA256
  Server SSL certificate:
    subject: CN=packagecontrol.io
    subject alt name: packagecontrol.io, www.packagecontrol.io
    expire date: Dec 21 23:59:59 2022 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  If-None-Match: "625c6abd-61233"
  Connection: Keep-Alive
  If-Modified-Since: Sun, 17 Apr 2022 19:30:05 GMT
  User-Agent: Package Control v3.4.1
  Host: packagecontrol.io
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Sun, 17 Apr 2022 19:33:11 GMT
  Content-Type: application/json
  Last-Modified: Sun, 17 Apr 2022 19:30:05 GMT
  Connection: keep-alive
  ETag: "625c6abd-61233"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/mwaddell/Library/Caches/Sublime Text/Cache/Package Control/http_cache/01524fae79697630d0454ba3fabd9414
Package Control: Fixed URL from https://raw.github.com/darinmorrison/sublime-packages/master/packages.json to https://raw.githubusercontent.com/darinmorrison/sublime-packages/master/packages.json
Package Control: Fixed URL from https://raw.github.com/darinmorrison/sublime-packages/master/packages.json to https://raw.githubusercontent.com/darinmorrison/sublime-packages/master/packages.json
Package Control: The dependency "psutil" is either not available on this platform or for this version of Sublime Text
Package Control: Installed missing dependency psutil
Package Control: Skipping automatic upgrade, last run at 2022-04-17 15:20:39, next run at 2022-04-17 16:20:39 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Unable to open /Users/mwaddell/Library/Application Support/Sublime Text/Packages/Default/Preferences.sublime-settings

**Comment by deathaxe** [comment]
The [psutil](https://github.com/packagecontrol/psutil) dependency doesn't support `arm64` architecture.

That's nothing Package Control can fix.

**Comment by dhershhorn** [comment]
Got it - makes perfect sense.

Since you already have https://github.com/wbond/package_control/issues/1605 I think this issue/question can be closed.

Thank you for your time, review, and answer!
