### ISSUE TITLE
[four-point-oh?] Concept for a dependency resolver on package level

### ISSUE THREAD

**Issue by LDAP** [wbond/package_control#1631]
>2. There's also no concept for a dependency resolver on package level. 

>   `dependencies.json` would need to be extended so it can also contain package dependency definitions. It supports libraries only, atm. The repository.json scheme would need to be extended to enable packages to define dependencies upstream in the same way as it is possible for libraries.

>   Much effort was taken to disable and reenable all installed/updated/removed packages in one step to avoid possible race conditions. Adding package level dependencies would require a further (massive?) refactoring of the whole "job batching" strategy.

_Originally posted by @deathaxe in https://github.com/wbond/package_control/issues/1628#issuecomment-1428328790_

If we accept that package dependencies are installed after the fact and ST needs to be restarted in some cases (LSP-helpers that depend on LSP), the repository.json scheme must not be updated as far as I can see.
This would already suit many plugins since the package dependencies are mostly optional (e.g. providing extra functionality if Terminus or Debugger are available).

I could attempt to provide a PR in this case.

**Comment by deathaxe** [comment]
> the repository.json scheme must not be updated

Even though barely used, plugins can provide dependency/library specification upstream via `dependencies: {...}` aka. `libraries: {...}` as an alternative for dependencies.json. With the discussion about adding support to force unmaintained packages to run on python 3.8 via upstream setting in mind it would probably just make sense to also support upstream package level dependencies, optionally.

Libraries are installed/updated during package installation. The same would need to happen for packages with the difference that those need to be disabled before installing or upgrading. As dependencies are not known before a package has been downloaded and extracted, we again end up in disabling and enabling packages nearly one by one, which is the main cause of all the trouble with packages keeping disabled after upgrade or batch install/upgrade operations being rather unreliable. This should not be the outcome of any future change again.

**Comment by deathaxe** [comment]
see also: https://github.com/wbond/package_control/issues/1089
