### ISSUE TITLE
[ST2] Package Control not working at all?

### ISSUE THREAD

**Issue by TheShotte** [wbond/package_control#1634]
I have installed Package Control manually on Sublime Text 2. If I go to _Preferences_ menu, _Package Control_ shows up on the bottom. However, if I go to _Preferences > Package Settings > Package Control_, all 3 options are grayed out. If I hit Ctrl + Shift + P, none of the Package Control commands show up. I used to just start typing "Pa Ins" and I would get Package Control: Install Package right off the bat. Now, I would like to install Package Control so I could install the SFTP plugin (which I have actually paid for). I have no idea how to troubleshoot this at all.

I have checked and made sure that it's not listed in "Ignored Packages", here's what I got there:
"ignored_packages": ["Vintage"]

**Comment by FichteFoll** [comment]
What platform are you on? What errors do you see in the console and can you paste its contents here? (View → Show Console)

Generally, Sublime Text 2 is unsupported by both ST and PC and there can be various reasons for it not to work for you. I strongly suggest using the latest ST version instead.

**Comment by baumanj** [comment]
I'm getting a similar issue after using Sublime Text (Stable Channel, Build 4143) on a newly created (second) admin account. I haven't been through all the troubleshooting for Package Control, but I just thought I'd mention this doesn't seem to be limited to ST2.
