### ISSUE TITLE
Update Syncing instructions for Dropbox on macOS

### ISSUE THREAD

**Issue by dserodio** [wbond/package_control#1636]
https://packagecontrol.io/docs/syncing#dropbox-osx tells us to use `~/Dropbox/Sublime` for syncing,  but on the new Dropbox client for macOS the folder should be `~/Library/CloudStorage/Dropbox` instead, otherwise Sublime won't be able to properly read the synced files.

I'd submit a PR but I can't find the GIt repo for the documentation.

**Comment by deathaxe** [comment]
That issue belongs to https://github.com/wbond/packagecontrol.io server / webapp repository.
