### ISSUE TITLE
[four-point-oh] `"index_files": false` added to Preferences (and kept false)

### ISSUE THREAD

**Issue by themilkman** [wbond/package_control#1639]
(recently discussed on discord in the support channel, starting around https://discord.com/channels/280102180189634562/280157083356233728/1118897302959050772)

I cannot imagine (but also not completely rule out) that this setting came from somewhere else (and esp. not manually by me and plugins checked via `[res for res in sublime.find_resources("*.py") if "index_files" in sublime.load_resource(res)]`), but I had this twice now: `"index_files": false`  got added to my Sublime settings. I found that this was generally added in  a0cc97f3c3498fe55b2c6a1ded15f662f197a18e on `package_control/package_disabler.py`. 

I am not able to reproduce it currently by using the upgrade command or so. In case it happens again I'll try to provide more information (esp. updated packages).

**Comment by deathaxe** [comment]
Thank's for reporting. It turned out PackageDisabler may run `backup_and_reset_settings()` multiple times for different set of package operations. In that case it stores the temporary `False` state instead of the original user preferences value.

**Comment by deathaxe** [comment]
fixed by 4.0.0-beta2
