### ISSUE TITLE
GutterColor slows down opening Install command panel

### ISSUE THREAD

**Issue by eugenesvk** [wbond/package_control#1646]
While troubleshooting https://github.com/wbond/package_control/issues/1645 I've discovered another puzzling issue: installing and using (having it active in an opened file) https://github.com/ggordan/GutterColor increases the time to open the `Package Control: Install package` command panel:
  - ~0.7 sec with all packages disabled in the settings 
  - ~2.1 sec with ONLY GutterColor active (and highlighting the current file)

I realize it's an old plugin, but still believe it should not have these kidns of side effects on this core ST package

```
Package Control: Fetching list of available packages and libraries
  Platform: osx-x64
  Sublime Text Version: 4150
  Package Control Version: 4.0.0-beta4
```
nothing is going on in the log, same with and without the plugin (there is a bunch of network calls on the first Install command, )

(also checked within the safe mode with just two packages isntalled: package control and guttercolor and a custom theme, ignoring GutterColor restores performance)

**Comment by deathaxe** [comment]
I don't see any relations or reasons for such delays, nor can I reproduce them  with GuterColor installed on Windows 11.

Package Control already uses dedicated threads to run background tasks, instead of relying on ST's worker thread, to not be delayed by or delay other plugins.

And it runs on another plugin_host.

**Comment by eugenesvk** [comment]
I don't see the connect either, yet it's there, the safe mode test with a single packages proves it
Was Gutter Color active and showing gutter colors on the opened file when you tried to run the Install command?

**Comment by deathaxe** [comment]
Tried with its test.css open - no delay.

**Comment by deathaxe** [comment]
If a plugin gets slowed down by another one running on a separate plugin_host, the only possible reason may be related with inter-process-communication or with API thread safety mechanisms.

Package Control downloads and parses information in a dedicated background thread with little to no application of sublime API calls until the final step of creating the quick panel with the list of pre-built items.

There's nothing to do to run it more independently.
