### ISSUE TITLE
Does not pick up package updates on packagecontrol.io

### ISSUE THREAD

**Issue by rchl** [wbond/package_control#1647]
https://packagecontrol.io/packages/LSP had a 1.25.0 release week ago or so and Package Control is still not picking it up. https://packagecontrol.io/ still shows 1.24.0.

I've heard that this affects all packages and not just LSP but I haven't verified myself.

**Comment by deathaxe** [comment]
This is an issue of packagecontrol.io server, which does not publish new releases or just stopped crawling.

developed under https://github.com/wbond/packagecontrol.io
