### ISSUE TITLE
Package Control makes ST4 latest dev build to freeze

### ISSUE THREAD

**Issue by eblot** [wbond/package_control#1665]
See initial description here:

https://github.com/sublimehq/sublime_text/issues/6304

I removed all packages but Package Control from the Installed Packages directory.
I've tried to add `debug: true` to the configuration file (from another editor), but I see no related info in the Console:

Package Control re-installs all previously installed packages, then ST4 stalls with no warning message from Package Control past the last downloaded package.

**Comment by FichteFoll** [comment]
It sounds like one of the packages installed by PC is causing the freeze rather than PC itself. This should be handled by ST or by the affected packages.

More details are at https://github.com/sublimehq/sublime_text/issues/6304.
