### ISSUE TITLE
package control not able to download

### ISSUE THREAD

**Issue by samuelmusau** [wbond/package_control#1669]
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Host not found (errno 12007) during HTTP write phase of downloading https://packagecontrol.io/installation.
Package Control: Error downloading channel. URL error [Errno 11001] getaddrinfo failed downloading https://packagecontrol.io/installation.

kindly help

**Comment by deathaxe** [comment]
https://packagecontrol.io/installation is an instruction site with information how to install Package Control. Package Control would never attempt to download this page.

Please check your "channel" configuration.

1. Open Command Palette
2. Call `Preferences: Package Control Settings`
3. Check and ideally remove custom "channels" setting in your user settings.


_My hunch is, you added the link above to that "channels" setting, which can't work._
