### ISSUE TITLE
Sass package no longer respects "word_separators" setting

### ISSUE THREAD

**Issue by mathijsprovoost** [wbond/package_control#1671]
As of Sass v4.0.0 doubleclicking a CSS declaration in a scss file selects the whole word instead of the part in between the characters that are defined in the "word_separators" setting.

It's set to the default:
// Characters that are considered to separate words
	"word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?",

[package control.log](https://github.com/wbond/package_control/files/14663308/package.control.log)

**Comment by FichteFoll** [comment]
Please report this to the [Sass package's issue tracker](https://github.com/SublimeText/Sass/issues).
