### ISSUE TITLE
request for guides 

### ISSUE THREAD

**Issue by XispenX69** [wbond/package_control#1672]
If you are running into a bug, please read https://packagecontrol.io/docs/troubleshooting
before submitting an issue here.

Bug reports must include a debug log. The Troubleshooting page explains how to capture one.

 Bug fixes include:
  ------------------

    - abort package operation if backup fails (#1000)
    - fix long path support on Windows (#1020)
    - fix missing packages not being installed if an overriding unpacked package exists (#1155)
    - fix errors being displayed for git/hg tracked packages without remote (#1167)
    - fix not all git/hg tracked packages being upgraded
    - fix packages in auto_upgrade_ignore setting being renamed without upgrade (#1370)
    - fix corruption of installed_packages or ignored_packages settings
    - fix backup/restore of ST's "auto" color schemes and themes
    - fix manual package upgrades converting unmanaged packages to managed ones (#1272)
    - fix libraries not being upgraded by auto upgrader
    - fix prompt for ST restart before all operations are completed
    - fix SSL_CERT_FILE environment variable being ignored
    - fix repositories of channels without cache not being downloaded (#1354, #1601)
    - fix QuickPanelItem parse errors in URLs (#1580)
    - fix unavailable libraries being reported as successfully installed (#1605)
    - fix error message flooding
    - keep ingored_packages clean by removing non-existing packages

**Comment by predragnikolic** [comment]
Is this spam?
