### ISSUE TITLE
[error 2147942402 (0x80070002) when launching `Install Package Control']

### ISSUE THREAD

**Issue by aaaaaaaaahhhhh** [wbond/package_control#1687]
When I type "Install Package Control" into the command palette in Windows Terminal, it gives me the error in the title. If the command palette that gets invoked by pressing crtl shift p is supposed to be used over the one in Windows Terminal, you might as well close this issue. I have been unable to invoke the palette in any way other than that, no matter who I talk to or what I do.
<img width="960" alt="Capturejvkdbkjdnkvndjnvs" src="https://github.com/user-attachments/assets/f01dba1c-f031-46ba-8178-0c5588aa50ea">

**Comment by deathaxe** [comment]
Package Control does not interact with any terminal. It is a Sublime Text package / plugin.

Sublime Text provides a built-in installer script for easy installation of Package Control.
