### ISSUE TITLE
Always segfaults after a couple seconds

### ISSUE THREAD

**Issue by fornellas-udemy** [wbond/package_control#1689]
Every time I open Sublime, it segfaults a couple seconds after starting up.

How to reproduce:

- `rm -rf .cache/sublime-text .config/sublime-text` (start from clean state).
- `subl --multiinstance --debug`
- View > Show Console, then [install Package Control](https://github.com/wbond/package_control?tab=readme-ov-file#installation) with the Python command (`from urllib.request...`)
- It segfaults.

```
...
:0                                                                plugins loaded
('/home/fornellas/.config/sublime-text/Installed Packages/Package Control.sublime-package', <http.client.HTTPMessage object at 0x7ba6482ec9a0>)
reloading plugin Package Control.plugin
:0                                                                reloading settings Packages/User/Package Control.sublime-settings
[24515:24515:20241001,152318.011937:ERROR elf_dynamic_array_reader.h:64] tag not found
[24515:24515:20241001,152318.013533:ERROR elf_dynamic_array_reader.h:64] tag not found
[24515:24515:20241001,152318.013562:ERROR elf_dynamic_array_reader.h:64] tag not found
[24515:24515:20241001,152318.013630:ERROR elf_dynamic_array_reader.h:64] tag not found
[24515:24516:20241001,152318.017638:ERROR directory_reader_posix.cc:42] opendir /home/fornellas/.cache/sublime-text/Crash Reports/attachments/439b584e-48c7-408d-b6c8-26576644123a: No such file or directory (2)
Segmentation fault (core dumped)
```

[full console output](https://github.com/user-attachments/files/17211164/crash.log)

At this point, Sublime is "poisoned", and it won't work anymore. Next time it is open (with `subl --multiinstance --debug`), it ends up crashing the same way, just a few seconds after opening:

```
...
reloading plugin Package Control.plugin
:0                                                                plugins loaded
[25333:25333:20241001,152537.991642:ERROR elf_dynamic_array_reader.h:64] tag not found
[25333:25333:20241001,152537.993273:ERROR elf_dynamic_array_reader.h:64] tag not found
[25333:25333:20241001,152537.993304:ERROR elf_dynamic_array_reader.h:64] tag not found
[25333:25333:20241001,152537.993335:ERROR elf_dynamic_array_reader.h:64] tag not found
[25333:25334:20241001,152537.998173:ERROR directory_reader_posix.cc:42] opendir /home/fornellas/.cache/sublime-text/Crash Reports/attachments/c0eafac0-9cd6-43be-a510-5776e1b692a2: No such file or directory (2)
Segmentation fault (core dumped)
```

If I'm quick, I can enable Package Control debug, and we get a bit more info:

```
...
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs from OS native store
  Using hostname "packagecontrol.github.io" for TLS SNI extension
  Successfully upgraded connection to packagecontrol.github.io:443 with SSL Using TLSv1.3 with cipher TLS_AES_128_GCM_SHA256
  Server SSL certificate:
    subject: CN=*.github.io,O=GitHub, Inc.,L=San Francisco,S=California,C=US
    subject alt name: *.github.io, github.io, githubusercontent.com, www.github.com, *.github.com, *.githu[25530:25530:20241001,152652.742830:ERROR elf_dynamic_array_reader.h:64] tag not found
[25530:25530:20241001,152652.744252:ERROR elf_dynamic_array_reader.h:64] tag not found
[25530:25530:20241001,152652.744281:ERROR elf_dynamic_array_reader.h:64] tag not found
[25530:25530:20241001,152652.744309:ERROR elf_dynamic_array_reader.h:64] tag not found
[25530:25531:20241001,152652.748150:ERROR directory_reader_posix.cc:42] opendir /home/fornellas/.cache/sublime-text/Crash Reports/attachments/024119d1-6834-4380-8642-d5b6acfc4406: No such file or directory (2)
```

[full log](https://github.com/user-attachments/files/17211214/pc-debug-crash.log)

I'm running Ubuntu Oracular 24.10 (devel,  which should be released in the next few weeks) + Sublime Text 4180.

I've found some "kinda similar" issues with MacOS, which were related to Sublime packaging Python against an ssl version that is mismatched with system's, I wonder if there's anything similar going on here. I've `ldd` everything under `/opt/sublime_text/`, got a single "not found" case related to an old SSL lib libssl1.1:amd64, but installing it, fixes nothing.

Ideas? Thanks.

PS: removing Package Control seems to fix Sublime, so it looks like either Package Control is the trigger for segfaulting.

**Comment by deathaxe** [comment]
A valid connection would look like

```
...
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.github.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs from OS native store
  Using hostname "packagecontrol.github.io" for TLS SNI extension
  Successfully upgraded connection to packagecontrol.github.io:443 with SSL Using TLSv1.3 with cipher TLS_AES_128_GCM_SHA256
  Server SSL certificate:
    subject: CN=*.github.io,O=GitHub, Inc.,L=San Francisco,S=California,C=US
    subject alt name: *.github.io, github.io, githubusercontent.com, www.github.com, *.github.com, *.githubusercontent.com, github.com
    expire date: Mar 14 23:59:59 2025 GMT
  Certificate validated for packagecontrol.github.io
```

Package Control uses urllib from python's stdlib to establish TLS connections on Unix and MacOS.

The `[25530:25530:20241001,152652.742830:ERROR elf_dynamic_array_reader.h:64] tag not found
[25530:25530:20241001,152652.744252:ERROR elf_dynamic_array_reader.h:64] tag not found` messages indicate something going wrong in python interpreter or one of involved libraries - most likely openssl.

ST ship with its own openssl 1.1.1 libraries located in /opt/sublime_text/. Calling `ldd /opt/sublime_text/plugin_host-3.8` should display a line with a libssl located in this directory.

```
...
libcrypto.so.1.1 => /opt/sublime_text/./libcrypto.so.1.1 (0x00007f305d000000)
libssl.so.1.1 => /opt/sublime_text/./libssl.so.1.1 (0x00007f305dca0000)
...
```

If these are not found or loaded, it would for sure be the reason, which can't be fixed by Package Control.

There was a maybe related discussion on forums about ST loading sqlite3 from a system path instead of using the one from ST's installation directory. IIRC it was also on Ubuntu 24.

Could be caused by misconfiguration of library loading orders.

see: https://forum.sublimetext.com/t/what-is-libsqlite3-so-in-installation-package-for/73619/16

Disclaimer: the requestor was not very cooperative.

Otherwise I don't know how to debug issues raised in and/or caused by libraries. Package Control executes normal python stdlib APIs - nothing illegal


The only workaround - if nothing else helps maybe to use another downlaoder, like "curl" by adding the following to _Package Control.sublime-settings_.

```
	"downloader_precedence": {
		"windows": ["wininet"],
		"osx": ["curl"],
		"linux": ["curl"],
	},
```

If however bundled ssl libraries start to fail on modern OSs, situation becomes a bit tricky, with little alternatives. `oscrypto` which claims to support openssl3 also fails due to ABI changes, which I am not able to fix.

**Comment by fornellas-udemy** [comment]
> ST ship with its own openssl 1.1.1 libraries located in /opt/sublime_text/. Calling ldd /opt/sublime_text/plugin_host-3.8 should display a line with a libssl located in this directory.
> If these are not found or loaded, it would for sure be the reason, which can't be fixed by Package Control.

Hum... it looks like there's something else going on. The libs seem to be all there:

$ ldd /opt/sublime_text/plugin_host-3.8 
        linux-vdso.so.1 (0x000074af40ebb000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x000074af40e94000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x000074af40e8f000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x000074af40e8a000)
        libcrypto.so.1.1 => /opt/sublime_text/libcrypto.so.1.1 (0x000074af40200000)
        libssl.so.1.1 => /opt/sublime_text/libssl.so.1.1 (0x000074af40143000)
        libsqlite3.so => /opt/sublime_text/libsqlite3.so (0x000074af4005b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000074af3ff6e000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000074af40e5a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x000074af40e55000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000074af3fc00000)
        /lib64/ld-linux-x86-64.so.2 (0x000074af40ebd000)
$ dpkg -S libcrypto.so.1.1
sublime-text: /opt/sublime_text/libcrypto.so.1.1
libssl1.1:amd64: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
$ dpkg -S libssl.so.1.1
sublime-text: /opt/sublime_text/libssl.so.1.1
libssl1.1:amd64: /usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

Note that I had to install libssl1.1 from ancient Ubuntu 20.04 manually, it was failing before it was installed, and fails after.

> Otherwise I don't know how to debug issues raised in and/or caused by libraries. Package Control executes normal python stdlib APIs - nothing illegal

I completely understand. I'm not sure what `/opt/sublime_text/plugin_host-3.8` is (some sort of wrapper for python?), do you know if there's a way to run Python code directly from it? I think this could enable us to actually see the errors (which may be hidden by Sublime), and surely would make things easier to debug.

> The only workaround - if nothing else helps maybe to use another downlaoder, like "curl" by adding the following to Package Control.sublime-settings.

Unfortunately, it still crashes with this option, sorry.

> If however bundled ssl libraries start to fail on modern OSs, situation becomes a bit tricky, with little alternatives. oscrypto which claims to support openssl3 also fails due to ABI changes, which I am not able to fix.

I think you're likely correct here. If Sublime is packaged in a way that does not play ball nicely with different / modern OSs libraries, and does not have a static build that should "always work", we're cornered.

---

The weird thing is that I have 2 machines running 24.10 (dev version, to be released in a couple weeks), but only in one of them, this issue occurs. I'll dig some more, and try to identify what package / library differences there's between both, that could explain the problem.

Thanks for all the input!

**Comment by deathaxe** [comment]
Must be something specific to your configuration then, which I can't provide further support for.

I installed Ubuntu 24 and ST4180 via apt-get yesterday and all is running just perfectly fine.

**Comment by fornellas-udemy** [comment]
Thanks @deathaxe.
