### ISSUE TITLE
Package Control: There are no packages available for installation

### ISSUE THREAD

**Issue by samzhao** [wbond/package_control#179]
Hi, I just installed a new Windows 7 Ultimate SP1 64 bit, and I'm trying to install packages on Sublime Text 2. I get the following error when I tried to install packages (package control is installed without any errors):

Package Control: There are no packages available for installation

And this in the console:

Package Control: Error downloading channel. URL error _ssl.c:480: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed downloading https://sublime.wbond.net/repositories.json.
error: Package Control: There are no packages available for installation.

Is it a problem with the server, or is there something wrong with my installation?

Thanks

**Comment by jitendravyas** [comment]
I'm in India and I'm also getting this error on my Mac

**Comment by nihilon** [comment]
So, on Windows 7 Pro 64bit SP1, I just ran into the same issue. Oddly, just copying https://packagecontrol.io/channel_v3.json into a browser tab and navigating to it solved the problem. Hopefully this helps someone else.

**Comment by yeasy** [comment]
@nihilon can you give your steps?
Thanks!

**Comment by firhatsungkar** [comment]
@nihilon Thanks you sooooo much! thats working for me.

**Comment by zyaba** [comment]
Had the same problem on my Mac.
https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling
^ This helped me

**Comment by tcoyle20** [comment]
On OSX 10.10 I was able to solve the problem by adding the package's url to my proxies bypass list. In this case it was jQuery: https://codeload.github.com/*

On the mac Network > Advanced > Proxies > Bypass

**Comment by bobvanderlinden** [comment]
Same problem here. It seems packagecontrol.io is down: http://downforeveryoneorjustme.com/packagecontrol.io

**Comment by zbreit18** [comment]
Looks up now.

**Comment by tpaksu** [comment]
Still seems down.

**Comment by aarome** [comment]
Ditto.

**Comment by ivancucer** [comment]
Ah, yeah looks like the PC website is down...

**Comment by deanshelton913** [comment]
It is down for me right now too... Is this the right place to bring it up? Just looking for someone to notify.

**Comment by nonami** [comment]
https://packagecontrol.io does not seem down when I access it from the browser but I can't install anything.
https://packagecontrol.io/channel_v3.json gives the following response:
```
{
  "dependencies_cache": {},
  "repositories": [],
  "packages_cache": {},
  "schema_version": "3.0.0"
}
```

**Comment by deanshelton913** [comment]
This is exactly what i see. Clearing the cache in sublimetext manually does not resolve the issue either because, like you said @nonami, there is nothing in the JSON response at the actual endpoint

**Comment by wsarles** [comment]
I'm having the same issue. It seems that https://packagecontrol.io/channel_v3.json shoudl return something meatier. Check out this archived version of the same file: https://web.archive.org/web/20150406110812/https://packagecontrol.io/channel_v3.json

**Comment by neverfox** [comment]
I just started having the same problem.

**Comment by deanshelton913** [comment]
Something is wrong with package controls list of packages globally. 
Searching for git returns nothing. lol. The site is up now atleast, but it seems evident that they have yet to resolve 100% of their data issues. 
this is empty for me: https://packagecontrol.io/search/git

**Comment by harrynewsome** [comment]
This just started happening to me on my MacBook. Can confirm the website is back up though.

**Comment by tam5** [comment]
same problem

**Comment by Birowsky** [comment]
site up, manager down

**Comment by camilodelvasto** [comment]
...tried all the solutions listed here until I realized packagecontrol.io is down, so it's not machine related (hopefully!)

**Comment by rezzafr33** [comment]
we really need mirror for packagecontrol.io..

**Comment by harrynewsome** [comment]
related:

https://github.com/wbond/package_control/issues/1045#issuecomment-168394411

**Comment by nonami** [comment]
https://packagecontrol.io does not seem down when I access it from the browser but I can't install anything.
https://packagecontrol.io/channel_v3.json gives the following response:
```
{
  "dependencies_cache": {},
  "repositories": [],
  "packages_cache": {},
  "schema_version": "3.0.0"
}
```

**Comment by Whoaa512** [comment]
Temp fix: https://github.com/wbond/package_control/issues/959#issuecomment-168448993

**Comment by camilodelvasto** [comment]
Thanks @Whoaa512 that did the trick for me!

**Comment by tapiwan** [comment]
Worked for me too @Whoaa512

**Comment by royduin** [comment]
Thanks @Whoaa512! I hope @wbond will fix this soon.

**Comment by msoedov** [comment]
Bump !

**Comment by FichteFoll** [comment]
http://status.linode.com/

**Comment by tobsn** [comment]
was working 5 min ago, installed a package - now same response as OP.

**Comment by nonameolsson** [comment]
Not working for me..

**Comment by tobsn** [comment]
https://packagecontrol.io/channel_v3.json

just keep checking this - it seems to work just fine now - I guess it's a linode issue. maybe there should be a fallback built into package control.

maybe write to maxcdn (hosting bootstrap cdn and a ton of other stuff), they probably happily help with mirroring the .json catalogues and package infos. 

https://www.maxcdn.com/open-source/ - the whole page could be mirrored for free by them.

**Comment by wbond** [comment]
@tobsn Please see #1057
