### ISSUE TITLE
Handle merge conflicts when updating with git (and hg?)

### ISSUE THREAD

**Issue by tornewuff** [wbond/package_control#286]
It would be nice if Package Control handled merge conflicts when it updates a VCS-installed package (I haven't used any packages checked out from hg so maybe that already does). Currently the "git pull" executed will exit nonzero and leave the working directory in a state with conflict markers, which will break the plugin when Sublime autoreloads the changed files because Package Control doesn't check the exit status. Unfortunately there doesn't appear to be a way to tell pull/merge to abort if there are conflicts, so there only seem to be two choices: either just tell the user this has happened and expect them to go resolve the conflicts and commit the merge themselves, or run git merge --abort to reset the working directory to the previous state and tell the user so they can work out what to do.

**Comment by wbond** [comment]
As of 0000c10bebfe788ea4ee6c0e2648d84fc1b31f72 there is now better error detection of git commands, plus the `ignore_vcs_packages` setting is a list that contains packages names. If you are coding a package via git or hg, you should add it to this list and then manage the repository manually.
