### ISSUE TITLE
ST3 There are no packages available for installation

### ISSUE THREAD

**Issue by gollum23** [wbond/package_control#361]
I try install a package but console show:

Package Control: Error downloading channel. URL error unknown error (_ssl.c:2158) downloading https://sublime.wbond.net/repositories.json.
error: Package Control

There are no packages available for installation

**Comment by Morgan-Deng** [comment]
I install ST3 in my mac and have installed packages control. But today when I want to run "Package Control: Install Package" command, ST3 tell me "There are no packages available for installation".
The following is my debug console info:
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/Morgan/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at /Users/Morgan/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. URL error _ssl.c:534: The handshake operation timed out downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation

**Comment by wbond** [comment]
@Morgan-Deng This issue is closed.

Either way, it appears something is messing with your HTTPS connection.

**Comment by Morgan-Deng** [comment]
I`m very sorry to post my problem here. But how can I start to fix it?
