### ISSUE TITLE
Can't seem to install Package Control

### ISSUE THREAD

**Issue by rubans** [wbond/package_control#415]
I have copied the zip file in Installed Packages and I still don't have package manager optins.
Using Sublime Text 2.0.1.
In the log it does Package Setup not required, could that be the problem?
Here's my log:

startup, version: 2217 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Windows/system32
packages path: /C/Users/rsiva/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/rsiva/AppData/Roaming/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 1 files for base name Main.sublime-menu
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Vintage\vintage.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Vintage\vintage_commands.py
Reloading plugin C:\Users\rsiva\AppData\Roaming\Sublime Text 2\Packages\Vintage\vintage_motions.py
plugin init time: 0.0583187
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.164604
wrote startup cache, added files: 6 orphaned files: 0 total files: 98 cache hits: 92
startup time: 0.21974 (package setup was not run)
loaded 837 snippets

**Comment by danielrasmuson** [comment]
If it helps anyone else my vpn was blocking the connection.
