### ISSUE TITLE
Hangs Loading Repositories - SOLVED

### ISSUE THREAD

**Issue by webusat** [wbond/package_control#430]
Hi,

Down in the status line there is a message "Loading Repositories" with an [ = } that just moves back and forth.  I don't have many added packages but what made me notice it was I have wbond SFTP installed and when I make changes the status window opens to show items being added to my server but it stays blank and nothing happens.  I tried some suggestions I found but nothing has worked.

Any thoughts as to what is going on?

Thanks,
Stan

**Comment by joshbuchea** [comment]
Removing the SFTP plugin in Sublime Text 3 fixed the hanging "loading repositories" issue for me.
