### ISSUE TITLE
[ST3] "Unable to open" settings error: Installed packages aren't creating a settings file or directory

### ISSUE THREAD

**Issue by zakdances** [wbond/package_control#477]
When I try to access a packages settings through Preferences > Package Settings, I get an error such as

```
Unable to open /Users/zak/Library/Application Support/Sublime Text 3/Packages/Better CoffeeScript/CoffeeScript.sublime-settings
```

So I went and check the Package directory at `~/Library/Application Support/Sublime Text 3/Packages` and I've noticed that packages are not creating directories or settings files. Is this a bug?

**Comment by PetrusKiendys** [comment]
This still doesn't work.
Using Sublime Text 3 build 3126.

**Comment by matthewmorrone1** [comment]
This is still happening =[ it's a real pain having to extract the package and copy the settings file into the user directory every time a package is installed.

**Comment by vml2017** [comment]
I am getting this error for all the packages I have installed today.  How should I fix?

**Comment by TraceyC77** [comment]
For people finding this issue first, when searching for this error, here is the [open issue](https://github.com/sublimehq/sublime_text/issues/1433) in the Sublime Text Core issue tracker
