### ISSUE TITLE
ST3: ImportError: No module named 'package_control'

### ISSUE THREAD

**Issue by Walther** [wbond/package_control#504]
Installing as per instructions at http://wbond.net/sublime_packages/package_control/installation#ST3 on the newest ST3 release from http://www.sublimetext.com/3 results in no command palette / improper or failed installation.

From ST built-in console:

DPI scale: 1
startup, version: 3047 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/walther
packages path: /home/walther/.config/sublime-text-3/Packages
state path: /home/walther/.config/sublime-text-3/Local
hardware concurrency: 4
zip path: /opt/sublime_text/Packages
zip path: /home/walther/.config/sublime-text-3/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 3 orphaned files: 0 total files: 148 cache hits: 145
pre session restore time: 0.086627
using gamma: 1 (err: 0)
startup time: 0.172692
first paint time: 0.175793
launching: /opt/sublime_text/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "Package Control in /home/walther/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 7, in <module>
ImportError: No module named 'package_control'
plugins loaded
loaded 837 snippets

64-bit Ubuntu 13.04, 64-bit ST3

**Comment by yeunghao** [comment]
Traceback (most recent call last):
  File "package_control.package_installer in F:\software\sublime3\Sublime Text 3\Packages\Package Control.sublime-package", line 159, in on_done
  File "package_control.package_disabler in F:\software\sublime3\Sublime Text 3\Packages\Package Control.sublime-package", line 74, in disable_packages
ImportError: No module named 'package_control'

**Comment by guillaumegarcia13** [comment]
@yeunghao Check whether proxy is not causing problem. I had the same output as you and I had to modify the install script like this (check the <proxy> addition in ProxyHandler):
````pythonimport urllib.request,os,hashlib; h = '2915d1851351e5ee549c20394736b442' + '8bc59f460fa1548d1514676163dafc88'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler({'http': 'http://<proxy>:8080'})) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)````

**Comment by shohoku3** [comment]
https://www.rrosetta.com/computers-programming/sublime-text-3-importerror-no-module-named-package_control#comment-13388 click it helpful

**Comment by SakisHous** [comment]
I have the same issue with ST3. I copied and pasted the script from **[https://packagecontrol.io/installation#st3](url)** . Although, when I try to install a package I get the errors
```
Traceback (most recent call last):
  File "C:\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_installer.py", line 154, in on_done
  File "C:\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_disabler.py", line 76, in disable_packages
ImportError: No module named 'package_control'

and yet I have not understood the solution.
```
