### ISSUE TITLE
UnicodeEncodeError when trying to do almost anything

### ISSUE THREAD

**Issue by boinger** [wbond/package_control#510]
The last 7 lines will happen repeatedly if I try to do Install Package or Update Package.

---

Package Control: Curl HTTP Debug Write
  GET /repos/SublimeText/VintageEx/commits?sha=master&per_page=1 HTTP/1.1
  User-Agent: Sublime Package Control
  Host: api.github.com
  Accept: _/_
  Accept-Encoding: deflate, gzip
Package Control: Curl HTTP Debug Read
  HTTP/1.1 200 OK
  Server: GitHub.com
  Date: Tue, 09 Jul 2013 22:54:34 GMT
  Content-Type: application/json; charset=utf-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Status: 200 OK
  X-RateLimit-Limit: 60
  X-RateLimit-Remaining: 50
  X-RateLimit-Reset: 1373413322
  Vary: Accept
  Cache-Control: public, max-age=60, s-maxage=60
  Last-Modified: Wed, 13 Feb 2013 20:11:30 GMT
  ETag: "e8f5fdc52e381c07c9414865dacbe287"
  X-GitHub-Media-Type: github.beta
  Link: https://api.github.com/repositories/2686202/commits?sha=master&per_page=1&top=master&last_sha=4f81b8a6ef9d7ff0572bfa9728ad38ac0c8e7368; rel="next", https://api.github.com/repositories/2686202/commits?sha=master&per_page=1; rel="first"
  X-Content-Type-Options: nosniff
  Access-Control-Allow-Credentials: true
  Access-Control-Expose-Headers: ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes
  Access-Control-Allow-Origin: *
  Vary: Accept-Encoding
  Content-Encoding: gzip
Package Control: Curl HTTP Debug General
  Connection #0 to host api.github.com left intact
  Closing connection #0
Exception in thread Thread-3:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "./package_control/commands/upgrade_package_command.py", line 49, in run
  File "./package_control/package_installer.py", line 87, in make_package_list
  File ".\genericpath.py", line 18, in exists
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 65: ordinal not in range(128)

**Comment by Heimdell** [comment]
The error still emerges.
```
>>> import os, locale
>>> os.name
'posix'
>>> locale.getpredefinedencoding()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getpredefinedencoding'
>>> locale.getpreferredencoding()
'ANSI_X3.4-1968'
>>> sublime.platform()
'linux'
```

despite the fact I launched sublime with command `LANG=en_US.UTF-8 sublime_text`.

Does anyone have the solution for Archlinux?

**Comment by saghirha** [comment]
This is how I fixed this problem by setting a clean UTF-8 environment on Ubuntu
http://perlgeek.de/en/article/set-up-a-clean-utf8-environment
