### ISSUE TITLE
Package Control Items Missing from Sublime Text 2 after Package Control update

### ISSUE THREAD

**Issue by coastcreative** [wbond/package_control#569]
startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/robin/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/robin/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 18 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 14 files for base name Main.sublime-menu
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/AdvancedNewFile/AdvancedNewFile.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/AutoFileName/autofilename.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/AutoFileName/getimageinfo.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk_activity.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk_api.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk_blame.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk_deploy.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk_deployments.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk_open.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk_plugin_settings.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/beanstalk_preview.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/osx_keychain.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Beanstalk Tools/package_control.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Emmet/emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/add.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/annotate.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/commit.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/diff.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/flow.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/git.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/history.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/repo.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/stash.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/status.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Git/statusbar.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/JsFormat/js_formatter.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/LiveReload/livereload_st2.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Nettuts+ Fetch/Fetch.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./Package Control.py", line 68, in <module>
    from package_control import reloader
ImportError: cannot import name reloader
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Prefixr/Prefixr.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/SFTP/SFTP.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/SideBar.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/StatusBarFileSize.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/StatusBarModifiedTime.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/SublimeLinter/SublimeLinter.py
imported capp_lint
imported pep8
imported pyflakes
imported pyflakes.api
imported pyflakes.checker
imported pyflakes.messages
imported pyflakes.reporter
SublimeLinter: C loaded
SublimeLinter: c_cpplint loaded
SublimeLinter: CoffeeScript loaded
SublimeLinter: CSS loaded
SublimeLinter: Git Commit Message loaded
SublimeLinter: Ruby Haml loaded
SublimeLinter: haskell loaded
SublimeLinter: HTML loaded
SublimeLinter: Java loaded
SublimeLinter: JavaScript loaded
SublimeLinter: Lua loaded
SublimeLinter: Annotations loaded
SublimeLinter: Objective-J loaded
SublimeLinter: Perl loaded
SublimeLinter: PHP loaded
SublimeLinter: Puppet loaded
SublimeLinter: Python loaded
SublimeLinter: ruby-lint loaded
SublimeLinter: Ruby loaded
SublimeLinter: pylint loaded
SublimeLinter: XML loaded
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Tag/Tag.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Tag/tag_close_tag.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Tag/tag_close_tag_on_slash.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Tag/tag_indent.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Tag/tag_insert_as_tag.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Tag/tag_lint.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Tag/tag_remove.py
Reloading plugin /Users/robin/Library/Application Support/Sublime Text 2/Packages/Tag/tag_remove_attributes.py
plugin init time: 1.03648
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 1.22525
using gamma: 2 (err: 6.9282)
startup cache, total files: 142 cache hits: 142
startup time: 2.32906 (package setup was not run)
loaded 1543 snippets
reloading /Users/robin/Library/Application Support/Sublime Text 2/Packages/User/Fetch.sublime-settings

I tried both methods to reinstall Package Control but neither worked.
![no-package-control](https://f.cloud.github.com/assets/1095862/960119/3cbcd618-04ac-11e3-987c-efcae8b4a119.jpg)

**Comment by yanhaijing** [comment]
i have same problem
