### ISSUE TITLE
Some packages cause error on install (Sublime Text 2, Windows 7 64bit)

### ISSUE THREAD

**Issue by op1ekun** [wbond/package_control#584]
These packages give me "error occured while trying to unzip...":
SublimeLinter,
JsFormat,
LiveStyle,
Emmet

While these install with no problem:
BracketHighlighter,
SideBarEnhancement,
SyncedSideBar,
LiveReload,
Alignment

They ALL worked yesterday on my Ubuntu 12.04.

For example SublimeLinter is giving me this one (excerpt from ST2 console):
"Package Control: Error downloading package. Operation timed out (errno 12002) during HTTP write phase of downloading https://codeload.github.com/SublimeLinter/SublimeLinter/zip/v1.7.2.
error: Package Control"

and a very similar one for Emmet:
"Package Control: Error downloading package. Operation timed out (errno 12002) during HTTP write phase of downloading https://codeload.github.com/sergeche/emmet-sublime/zip/master.
error: Package Control"

I have disabled my Windows Firewall, McAffee and I'm running on mobile network to avoid proxy. Still no luck. Please help!

**Comment by ChopsII** [comment]
Realise you might be sick of this kind of issue, but I'm having this issue. I am behind a proxy, unfortunately, but this package usually works.

My symptoms are that package control can't find any packages to install, opening the console shows:
```
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Operation timed out (errno 12002) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation
```

I tried loading the URL https://packagecontrol.io/channel_v3.json in my browser, and it worked, in Chrome, Firefox and Internet Explorer. This indicates that my computer and network is *not* blocking the request.

I was receiving errno 12029 until I followed the instructions at https://packagecontrol.io/docs/troubleshooting. When I did that, I got to this issue, errno 12002.
I also tried reinstalling by following the instructions for purging old versions.

Is there a way I can copy/paste the json from my browser into Package Control, bypassing this issue for now?

**Comment by wbond** [comment]
I'm not sick of it, there just isn't really anything I can do. However, please don't expect me to respond to closed issues. It is just a coincidence that I saw this notification – there are about 800 unread in my GitHub account. :-)

Something about your computer or network is not letting the connection through. Unfortunately I can't help you debug it. Just because another program on your computer works, does not mean it is a problem with Package Control. It could be that your antivirus or firewall has blacklisted `plugin_host.exe`. Considering that both WinINet and urllib failed to connect, I think something is definitely thwarting the connection attempts.

**Comment by abhijitkumarbiswas** [comment]
I use **windows 10 Pro**
An error occurred while trying to unzip the package file for SublimeCodeIntel. Please try installing the package again.
I can not fix this problem and also there are no ans online. :(
