### ISSUE TITLE
After installation on win7 ctrl-shift-p doesn't work

### ISSUE THREAD

**Issue by scout4u** [wbond/package_control#59]
Even after executing the script of installing Package Control and then restart ST.
Mote doesn't apear in the suggessions after start typing it. Mote is installed ofcourse. 
Nothing works. For experimental purposes — used a clean installation. 1. Executing a script 2. Accessing to a list from Menu bar and then installation of the Mote.

**Comment by dimkk** [comment]
download master strikes back - turn it off

**Comment by RainFool** [comment]
I had the same problem.But it's a windos hot key conflict.LOL
