### ISSUE TITLE
Error checking for server certificate revocation (errno 12057)

### ISSUE THREAD

**Issue by piuccio** [wbond/package_control#633]
Hello

I'm so sorry to open a new issue on proxy related matter, but I get this error when I try to fetch available packages.

I'm behind a corporate proxy, not sure how it's configured.

Steps
- Install package control manually
- ctrl+shift+p  ->  install package

Console output

```
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3047
  Package Control Version: 2.0.0
Package Control: Download Debug
  URL: https://sublime.wbond.net/channel.json
  Resolved IP: 50.116.34.243
  Timeout: 30
Package Control: Error downloading channel. Error checking for server certificate revocation (errno 12057) during HTTP write phase of downloading https://sublime.wbond.net/channel.json.
error: Package Control

There are no packages available for installation
Package Control: WinINet HTTPS Debug General
  Closing connection to sublime.wbond.net on port 443 after 0 requests
```

If I connect to that url with the browser it works fine.

I've tried to put my username and passowrd and I've also changed the `user_agent` to match that of Chrome, but no luck.

When I inspect the traffic I see that every request to certificate revocation servers is redirected to my proxy that answers with a 401 Unauthorized.

The servers I'm trying to call are
- ctldl.windowsupdate.com
- ocsp.geotrust.com
- crl.geotrust.com
- rapidssl-crl.geotrust.com

**Comment by Clemzd** [comment]
It works. Thanks!
