### ISSUE TITLE
increase with of command pallet 

### ISSUE THREAD

**Issue by awebdeveloper** [wbond/package_control#642]
I cant see the full description of the package in Install Package. Is there a way to do it. Also increase the width of command pallet since some packages have big names

**Comment by Kristinita** [comment]
+1.

I use package [**Sublime Text API Helper**](https://packagecontrol.io/packages/Sublime%20Text%20API%20Helper).

If I use [**FichteFoll hack**](https://github.com/wbond/package_control/issues/642#issuecomment-27955843), I see command palette with big width.

![Command palette](http://i.imgur.com/v5DAIRe.png).

If <kbd>Ctrl+Shift+P</kbd> → `Sublime Text API Helper: sublime.View*` → <kbd>Enter</kbd> → I get panel with small width.

![API Helper](http://i.imgur.com/GlW63c1.png)

I don't can read text in some panel items.

Thanks.
