### ISSUE TITLE
 Install Package - SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by jbrashear** [wbond/package_control#663]
Hello I have installed  Package Control via the script on the instalation page for Sublime 3 . I restarted Sublime and opened the text console and typed : Install Package. I got this error:
Install Package
  File "<string>", line 1
    Install Package
                  ^
SyntaxError: unexpected EOF while parsing

Here is my start up in Sublime:
DPI scale: 1
startup, version: 3059 windows x32 channel: stable
executable: /C/Program Files (x86)/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files (x86)/Sublime Text 3
packages path: /C/Users/Jason/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Jason/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 8
zip path: /C/Program Files (x86)/Sublime Text 3/Packages
zip path: /C/Users/Jason/AppData/Roaming/Sublime Text 3/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 1 total files: 148 cache hits: 147
pre session restore time: 0.12547
startup time: 0.15047
first paint time: 0.15247
launching: /C/Program Files (x86)/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.Package Control
plugins loaded
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2014-01-09 11:58:27, next run at 2014-01-09 12:58:27 or after

> > > Install Package
> > >   File "<string>", line 1
> > >     Install Package
> > >                   ^
> > > SyntaxError: unexpected EOF while parsing

**Comment by mvdbiggelaar** [comment]
thanks ;-)

**Comment by Berserk-Guppies** [comment]
@FichteFoll Dude thank you so much
