### ISSUE TITLE
support gitlab

### ISSUE THREAD

**Issue by fnkr** [wbond/package_control#719]
Is it possible to host packages on [gitlab.com](https://gitlab.com/users/sign_in)'s git hosting service ([demo repository here](https://gitlab.com/fnkr/gitignore))?

**Comment by NotSqrt** [comment]
I would be really happy if I could use a variant of this new provider, but for an on-premises instance of Gitlab..

@fnkr Any hope of seeing your code (your clone does not seem to exist anymore), or should I just start from scratch ?

I see a ``match_url`` method in the provider, so we probably need to use something like ``r'^gitlab:https?://.*`` to allow any url.

**Comment by fnkr** [comment]
@NotSqrt You'll need to start from scratch, unluckily, I deleted my fork. Good luck!

**Comment by NotSqrt** [comment]
@fnkr Did you implement it by parsing the html pages, which you can do on public projects, or by requiring the user to put their token in the settings, hence allowing the use of the API ?

**Comment by wbond** [comment]
From a user experience perspective, it may make more sense to have package developers use Package Control to create a `.sublime-package` file and place it on an internal URL that can be accessed without access tokens. Otherwise you are getting into a whole world of configuration for every user just to check for updates.

**Comment by NotSqrt** [comment]
It's for an internal package that we host on our gitlab instance.. For the moment, it's just a git repository, so everything has to ``git pull`` it manually whenever there's an update.
I tried setting up a private repository with this package, but was not able to make it work at the time.

I guess what I need is probably a repository like 
```json
{
	"schema_version": "3.0.0",
	"packages": [
		{
			"details": "https://github.com/wbond/sublime_alignment",
			"releases": [
				{
					"version": "1.1.0",
					"url": "http://gitlab-hostname/user/package/repository/archive.zip?ref=1.1.0",
					"date": "2011-09-18 20:12:41",
					"sublime_text": "*"
				}
			]
		}
	],
	"dependencies": []
}
```
and update this file each time there is a release (easy to do with continuous integration on Gitlab CI)

**Comment by wbond** [comment]
@NotSqrt I believe something like that would probably be the simplest solution for you right now. You can look at https://sublime.wbond.net/packages_2.json and the entry for `SFTP` as an example of a package that does not use the `"details"` key tied to GitHub or BitBucket. In your situation you probably don't need all of the different releases.

**Comment by NotSqrt** [comment]
Managed to get CI working to auto-build ``.sublime-package`` files, and update the ``json`` repository :smile:

**Comment by wildeyes** [comment]
@fnkr did you ever got it working? gitlab is amazing, I want to host there.

**Comment by fnkr** [comment]
@wildeyes No, unfortunately not.

**Comment by FichteFoll** [comment]
With the high frequency updates of gitlab recently I believe that it should be added as a possible hosting provider.

**Comment by wbond** [comment]
This would be a great addition. It shouldn't be all that complicated for projects hosting on the public GitLab. Detecting third-party GitLab instances would require some other sort of configuration. Perhaps a new key would need to be added to the channel.json such as `provider`.

**Comment by oldcastlehq** [comment]
Any updates here? It would be great to give GitLab some love.

**Comment by oldcastlehq** [comment]
Hello?

**Comment by Oloryn** [comment]
With some developers leaving Github  due to the Microsoft buyout, does it make sense to up the priority  on this issue?

**Comment by wbond** [comment]
We can up the priority of the issue, however since it is a completely volunteer open source project, that would just mean whoever feels like working on it could choose to respect the "priority."

More or less it comes down to someone who has written a package who wants to host it on GitLab to take a couple of hours and determine the GitLab API call necessary to pull out the required info and then copy the GitHub provider and make the necessary changes.

**Comment by zedtux** [comment]
Looking for this too.
