### ISSUE TITLE
Package Control fails to install new packages

### ISSUE THREAD

**Issue by RedFred7** [wbond/package_control#725]
When I do a Package Control:Install Packages, I get the following console output

```
Package Control: Error parsing JSON from channel https://sublime.wbond.net/channel.json.
error: Package Control

There are no packages available for installation
```

I'm running ST3 Build 3059 on Ubuntu 14.04

**Comment by FrankBian** [comment]
I think I get the same issue, but the above solution from @collb can't work at my machine.
the paltform is Win 10 x64 + Git bash,more details from [Here](https://github.com/wbond/package_control/issues/1043)
