### ISSUE TITLE
Package control fails to download new packages

### ISSUE THREAD

**Issue by srikanth-dhondi** [wbond/package_control#736]
When trying to download a new package, ex: Phpcs, I am getting following error:

ignored packages updated to: [Vintage, Phpcs]
found 1 files for base name Default.sublime-theme 
theme loaded
reloading Packages/User/Preferences.sublime-settings 
found 1 files for base name Default.sublime-theme 
theme loaded

Package Control: Error downloading package. b'curl: (60) SSL certificate problem: certificate has expired\nMore details here: http://curl.haxx.se/docs/sslcerts.html\n\ncurl performs SSL certificate verification by default, using a "bundle"\n of Certificate Authority (CA) public keys (CA certs). If the default\n bundle file isn\'t adequate, you can specify an alternate file\n using the --cacert option.\nIf this HTTPS server uses a certificate signed by a CA represented in\n the bundle, the certificate verification probably failed due to a\n problem with the certificate (it might be expired, or the name might\n not match the domain name in the URL).\nIf you\'d like to turn off curl\'s verification of the certificate, use\n the -k (or --insecure) option.' downloading https://codeload.github.com/benmatselby/sublime-phpcs/zip/master.
error: Package Control

Unable to download Phpcs. Please view the console for more details.
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded

**Comment by Porioux** [comment]
Fixed for me too. Thanks !

**Comment by zedd45** [comment]
@zoechi's solution worked for me, as well.  OSX.9.5, Sublime Text Build 3065

**Comment by FichteFoll** [comment]
For all others still discovering this issue, you can find the "official" instructions here: https://packagecontrol.io/docs/troubleshooting#Purging_Old_Versions

**Comment by maodd** [comment]
I got this issue on Mac, and this didn't fix for me. But the settings from [here](https://forum.sublimetext.com/t/st3-3126-package-control-ssl-cert-invalid-errors-reinstall-didnt-help/23539) did the trick:
`"downloader_precedence": {
    "windows": ["wininet"],
    "osx": ["curl","urllib"],
    "linux": ["urllib", "curl", "wget"]
}`

By default osx only has urllib, manually added curl before urllib fixed my issue.

**Comment by CPfi12** [comment]
Where can you find the config files to delete?

**Comment by payamazadi** [comment]
This isn't strictly a Sublime versioning/bug issue. It seems this can happen on certain network environments, such as mine, where the system has particular proxy settings that screw with downloading content over HTTPS. The reason is if you have a proxy SSL certificate, then all certificates originating from a different domain are untrusted unless you trust them. The solution is to use a browser to download the certificate (e.g. from https://packagecontrol.io/channel_v3.json) and then adding it into your keychain/trusted certs/etc.

**Comment by Mufkalif** [comment]
like this ?

**

> indexing [job 75]: no files were indexed out of the 1 queued, abandoning crawl
> ignored packages updated to: ["Oceanic Color Scheme", "Vintage"]
> reloading settings Packages/User/Package Control.sublime-settings
> Exception in thread Thread-16:
> Traceback (most recent call last):
>   File "./python3.3/threading.py", line 901, in _bootstrap_inner
>   File "package_control.package_installer in C:\Users\john\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 202, in run
>   File "package_control.package_manager in C:\Users\john\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 1060, in install_package
>   File "./python3.3/tempfile.py", line 307, in mkdtemp
>   File "./python3.3/tempfile.py", line 251, in gettempdir
>   File "./python3.3/tempfile.py", line 192, in _get_default_tempdir
> FileNotFoundError: [Errno 2] No usable temporary directory found in ['c:\\temp', 'c:\\tmp', '\\temp', '\\tmp', 'C:\\Program Files\\Sublime Text 3']****

**

**Comment by tablatronix** [comment]
same problem

```
Package Control: Download Debug
  URL: https://api.github.com/repos/gepd/Deviot
  Timeout: 30
  Resolved IP: 192.30.253.116
  Resolved IPv6: ::ffff:192.30.253.116
Package Control: Urllib HTTPS Debug General
  Connecting to api.github.com on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/shawn/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Using hostname "api.github.com" for TLS SNI extension
Package Control: Error downloading repository. HTTP exception InvalidCertificateException (Host api.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://api.github.com/repos/gepd/Deviot.
Package Control: Error downloading repository. HTTP exception InvalidCertificateException (Host api.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://api.github.com/repos/gepd/Deviot.
Package Control: Error downloading repository. HTTP exception InvalidCertificateException (Host api.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://api.github.com/repos/bcharbonnier/SublimeFileSync.
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: Urllib HTTPS Debug General
  Closing connection to rawgit.com on port 443 after 1 request
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
```

**Comment by tablatronix** [comment]
this fixed it
https://github.com/renerocksai/sublime_zk/issues/50#issuecomment-377724551

**Comment by maestrale** [comment]
Updating to 3.1 solved it for me

**Comment by 7samasm** [comment]
@maodd thanks that's helps me alot even i am on linux
