### ISSUE TITLE
Invalid schema_version error on upgrading to version 3.0 for Windows ST3

### ISSUE THREAD

**Issue by technofreak** [wbond/package_control#801]
As per the release notes shown in control messages document, ran the piece of Python code given for upgrading to version 3.0 for Windows ST3. Upon running the given code in ST console, got the below error but I find Package Control to have been upgraded to 3.0.

Package Control: Channel https://packagecontrol.io/channel_v3.json does not appear to be a valid channel file because  the "schema_version" is not a valid number.
Package Control: No updated packages

Python Code:
import urllib.request,os; pr='Preferences.sublime-settings'; ip='ignored_packages'; n='Package Control'; s=sublime.load_settings(pr); ig=s.get(ip); ig.append(n); s.set(ip,ig); sublime.save_settings('Preferences.sublime-settings'); pf=n+'.sublime-package'; urllib.request.install_opener(urllib.request.build_opener(urllib.request.ProxyHandler())); by=urllib.request.urlopen('https://packagecontrol.io/'+pf.replace(' ','%20')).read(); open(os.path.join(sublime.installed_packages_path(),pf),'wb').write(by); ig.remove(n); s.set(ip,ig); sublime.save_settings(pr); print('Package Control: 3.0.0 upgrade successful!')

**Comment by Rainer** [comment]
I had the same error. Restarting ST3 with administrator privileges did the trick for me. The original error message didn't show up, and no purge was necessary. Cheers!
