### ISSUE TITLE
Error message on update to v3

### ISSUE THREAD

**Issue by MarkCheshire** [wbond/package_control#807]
Hi,

During the upgrade process to v3 I get the message that the upgrade was successful, but then a few lines later see this message in the log. What does it mean?
```Package Control: Channel https://packagecontrol.io/channel_v3.json does not appear to be a valid channel file because  the "schema_version" is not a valid number.```

Thanks for the great work.

**Comment by johndugan** [comment]
Instructions helped! Thx Will :-)

**Comment by MarkCheshire** [comment]
Thanks, glad this is helping others who run into the same error.

**Comment by FOr3st** [comment]
Thanks, Will!
