### ISSUE TITLE
Package manager disappeared after upgrading it to 3.0

### ISSUE THREAD

**Issue by wolfmanjm** [wbond/package_control#811]
Running sublime text 3 I upgraded to Package manager 3, and it disappeared. I followed the instructions for purging old versions, and tried a manual installation. still no luck, I seem to have lost package manager now.

Running on Linux BTW.

**Comment by wolfmanjm** [comment]
I also now seem to not be able to even get the old version running.

**Comment by wbond** [comment]
Check Preferences > Settings – User and see if it is in `ignored_packages`.

**Comment by wolfmanjm** [comment]
Yep it was in ignored_packages... how did it get there? Interesting. thank you, I'll try to upgrade again and see what happens.

**Comment by wbond** [comment]
A few linux users have run into trouble because they ran the instructions for Windows users, which fails since Linux does not have the SSL module, and then it leaves PC disabled. That may have been what happened to you.

**Comment by wolfmanjm** [comment]
Actually I just told package manager to upgrade itself. I did follow the instructions to execute the manual python code, I did not see that it said windows only users AFAIK. Maybe that message needs to be more specific.

**Comment by wolfmanjm** [comment]
Ok it upgraded this time :) Thank you.
