### ISSUE TITLE
Errno 12031

### ISSUE THREAD

**Issue by genych** [wbond/package_control#813]
Something wrong with installation of v3. (Fresh ST3, WindowsXP)

    Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. (errno 12031) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
    Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.

**Comment by FichteFoll** [comment]
I think this is the time where you recommend someone to update his Windows if it's connected with the internet.

**Comment by wbond** [comment]
Try using the directions for error 12029 at https://packagecontrol.io/docs/troubleshooting#Windows_Errors_12029_and_12057.
