### ISSUE TITLE
Error downloading channel. Errno 14 - not enough storage 

### ISSUE THREAD

**Issue by tmihetec** [wbond/package_control#814]
hi 
i'm getting this error when tryin to access package list...

````
Package Control: Fetching list of available packages
  Platform: windows-x32
  Sublime Text Version: 3065
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 0 requests
```

any quick help?
br
T

**Comment by wbond** [comment]
Hmm, never seen this before. What version of Windows are you running?

**Comment by tmihetec** [comment]
i guessed that... couldn't find anything similar...
anyway: Win7, 32bit... Sublime text 3, build 3065

**Comment by wbond** [comment]
Looking around online this error message seems to indicate your machine is out of file handles: http://www.unixwiz.net/techtips/not-enough-codes.html.

Do you have a lot of programs open, or processes running?

Do you have many packages installed that could be opening, but not closing file handles properly?

I am guessing the fact that you are running a 32bit version of Windows might make this error more apparent than if you were running x64.

**Comment by saas786** [comment]
Hi @wbond 
I am receiving same error.

```
SublimeLinter: debug mode: off
CodeFormatter: Plugin Initialized
found 8 files for base name Main.sublime-menu
Emmet: No need to update PyV8
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: Installing 1 missing dependencies
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: No updated packages
````

Specifications:
Win7, 64bit... Sublime text 3, build 3065

**Comment by saas786** [comment]
I have also tried sublime text 2

```
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 2221
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #0
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, select-windows, is not available
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 2221
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #0
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-01-06 16:11:35, next run at 2015-01-06 17:11:35 or after
```

**Comment by saas786** [comment]
Initially I noticed this issue when I tried to install new package, and it failed with "There are no packages available for installation.

Hopefully you find the issue.

**Comment by wbond** [comment]
Do you have a lot of programs open, or processes running?

Do you have many packages installed that could be opening, but not closing file handles properly?

Unfortunately I have not been able to replicate this issue. Additionally from looking online I don't know how to work around it.

**Comment by saas786** [comment]
@wbond 

No I don't have had too many programs opened or processes running.

No I don't have two many packages installed.

I restarted my pc twice and tried both v3 and v2 with fresh downloads as well.

And both failed to allow me to add new packages.

I can assist you with any kind of debugging.

Let me know how I can be off any assistance?

**Comment by wbond** [comment]
Do you have any antivirus or network security software running? If so, can you try temporarily disabling them and try again?

If it works then, you may have to whitelist `plugin_host.exe` and/or `sublime_text.exe`.

**Comment by whiteheatdesign** [comment]
I'm getting this too. Windows 7, 64bit, ST 3065. Hardly any processes running and tried disabling antivirus. No dice

    reloading plugin Package Control.bootstrap
    reloading plugin Package Control.Package Control
    reloading Packages/Package Control/Package Control.sublime-settings
    found 6 files for base name Main.sublime-menu
    reloading plugin 0_package_control_loader.00-package_control
    Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading  https://packagecontrol.io/channel_v3.json.
    Package Control: Installing 1 missing dependencies
    Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
    Package Control: The dependency specified, bz2, is not available
    Package Control: Skipping automatic upgrade, last run at 2015-01-06 21:13:29, next run at 2015-01-06 22:13:29 or after

**Comment by wbond** [comment]
If someone wants to take the time to clone the Git repo instead of using the `Package Control.sublime-package` and try to figure out at what point the error is being thrown, that would help.

It is being thrown somewhere in https://github.com/wbond/package_control/blob/master/package_control/downloaders/wininet_downloader.py. My guess is around here: https://github.com/wbond/package_control/blob/master/package_control/downloaders/wininet_downloader.py#L625-L632.

**Comment by wbond** [comment]
Could those affected try opening https://packagecontrol.io/channel_v3.json in Internet Explorer please?

**Comment by whiteheatdesign** [comment]
That asks me to save or open. When I click open it does so in ST3. What am I looking for?

**Comment by wbond** [comment]
Just making sure it isn't some sort of IE advanced setting that is borking any WinINet connection.

My guess is that one of the WinINet calls is not properly crossing the Python -> C++ foreign function interface via ctypes. I had run into an issue like that when writing the code to export SSL certificates.

The downside is that I haven't been able to replicate the issue, so it is kind of a pain to figure out if my ideas for changes actually fix the problem or not.

**Comment by saas786** [comment]
@wbond 

No I don't have any kind of Antivirus installed, and I keep my firewall disabled as well.

I have tried to use "Git clone"

I cloned the repo, compressed it as zip file and than renamed it to **Package Control.sublime-package** and replaced the original package file with this.

And than I went to package control typed **install** and it didn't even showed the install package option.

Can you tell me how I can convert repo files into *.sublime-pacage file?

Yes  https://packagecontrol.io/channel_v3.json opens in internet explorer (downloads into my system if I type it in url), and *.json file contains the same content.

Can you tell me how I can setup a testing environment for you package control? So I can debug it on my system and show the debug results / log? It might help you trace issue quickly ?

**Comment by wbond** [comment]
Did PC 2.0 work for all of you? I just looked at the difference and the only thing I changed in the WinINet downloader between 2.0 and 3.0 is that I read the Windows proxy info pre-emptively in 3.0 incase I need to fallback to the urllib downloader. I wonder if there is something about that fetching of the proxy info that is causing the error.

**Comment by wbond** [comment]
@saas786 To debug, you should do a git clone of package control into the `Packages/Package Control/` folder and delete the file `Installed Packages/Package Control.sublime-package`. After that, restart Sublime Text and set the [debug setting](https://packagecontrol.io/docs/settings#setting-debug) to `true`.

Once this is done you can replace lines 601-648 of `package_control/downloaders/wininet_downloader.py` with the following:

```python
    def read_option(self, handle, option):
        """
        Reads information about the internet connection, which may be a string or struct
        :param handle:
            The handle to query for the info
        :param option:
            The (int) option to get
        :return:
            A string, or one of the InternetCertificateInfo or InternetProxyInfo structs
        """

        option_buffer_size = 8192
        try_again = True

        console_write(u'Reading WinINet option %s' % option, True)

        while try_again:
            try_again = False

            to_read_was_read = wintypes.DWORD(option_buffer_size)
            option_buffer = ctypes.create_string_buffer(option_buffer_size)
            ref = ctypes.byref(option_buffer)

            success = wininet.InternetQueryOptionA(handle, option, ref, ctypes.byref(to_read_was_read))
            if not success:
                console_write(u'Reading WinINet option failed', True)
                if ctypes.GetLastError() != self.ERROR_INSUFFICIENT_BUFFER:
                    console_write(u'WinINet option read failed due to issue other than buffer size - %s' % ctypes.GetLastError(), True)
                    raise NonHttpError(self.extract_error())
                # The error was a buffer that was too small, so try again
                option_buffer_size = to_read_was_read.value
                try_again = True
                continue

            if option == self.INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT:
                length = min(len(option_buffer), ctypes.sizeof(InternetCertificateInfo))
                cert_info = InternetCertificateInfo()
                ctypes.memmove(ctypes.addressof(cert_info), option_buffer, length)
                return cert_info
            elif option == self.INTERNET_OPTION_PROXY:
                length = min(len(option_buffer), ctypes.sizeof(InternetProxyInfo))
                proxy_info = InternetProxyInfo()
                ctypes.memmove(ctypes.addressof(proxy_info), option_buffer, length)
                return proxy_info
            else:
                option = b''
                if to_read_was_read.value > 0:
                    option += option_buffer.raw[:to_read_was_read.value]
                return option.decode('cp1252').rstrip("\x00")
```

Then restart Sublime Text and try again. Post the contents of your console and let's see what is causing this.

**Comment by saas786** [comment]
Here you go with my current sublime with other settings & packages.

```
DPI scale: 1
startup, version: 3065 windows x32 channel: stable
executable: /F/soft/Sublime Text Build 3065/sublime_text.exe
working dir: /F/soft/Sublime Text Build 3065
packages path: /F/soft/Sublime Text Build 3065/Data/Packages
state path: /F/soft/Sublime Text Build 3065/Data/Local
hardware concurrency: 4
zip path: /F/soft/Sublime Text Build 3065/Packages
zip path: /F/soft/Sublime Text Build 3065/Data/Installed Packages
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 7 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Soda Light.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 291 cache hits: 289
pre session restore time: 0.249814
startup time: 0.289814
first paint time: 0.289814
launching: /F/soft/Sublime Text Build 3065/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
loaded 1309 snippets
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
Package Control: Error finding main directory from loader
reloading plugin Emmet.emmet-plugin
reloading plugin LESS.less_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin CodeFormatter.CodeFormatter
CodeFormatter: formatting python files on ST3 not supported.
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
CodeFormatter: Plugin Initialized
SublimeLinter: debug mode: off 
found 7 files for base name Main.sublime-menu
Emmet: No need to update PyV8
```

**Comment by saas786** [comment]
Here is the log with fresh download, and git clone into "Packages/Package Control" and content replaced like you said.

```
DPI scale: 1
startup, version: 3065 windows x32 channel: stable
executable: /F/soft/Sublime Text Build 3065/sublime_text.exe
working dir: /F/soft/Sublime Text Build 3065
packages path: /F/soft/Sublime Text Build 3065/Data/Packages
state path: /F/soft/Sublime Text Build 3065/Data/Local
hardware concurrency: 4
zip path: /F/soft/Sublime Text Build 3065/Packages
zip path: /F/soft/Sublime Text Build 3065/Data/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 1 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 167 cache hits: 165
pre session restore time: 0.179425
startup time: 0.209425
first paint time: 0.209425
launching: /F/soft/Sublime Text Build 3065/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
loaded 837 snippets
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
```

**Comment by saas786** [comment]
In both cases **I don't see install option under preference "Package Control".**

**Comment by FichteFoll** [comment]
The log shows that Package Control plugins are not loaded. Check if it is in the `ignored_packages` list.

**Comment by wbond** [comment]
@saas786 Something is amiss here. You should not have folders named `Packages` and `Data` in the `Package Control` folder. Perhaps you meant to say `Sublime Text`?

You put the `debug` setting in the wrong file. It needs to go into `Data/Packages/User/Package Control.sublime-settings`.

You can delete the `debug` and `repository_channels` settings from you main settings file. They don't do anything when placed in that file.

Do you have a folder named `Data/Packages/Package Control/`?

**Comment by ewrankin** [comment]
I was having the same issue as @saas786 so I did what @wbond recommended cloning from the repo and then inserting the code snippet for read_option.  Below is snippet from the command console:

```
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Reading WinINet option 50
Package Control: Reading WinINet option 38
Package Control: Reading WinINet option failed
Package Control: WinINet option read failed due to issue other than buffer size - 0
Package Control: Error downloading channel. The operation completed successfully. (errno 0) downloading https://packagecontrol.io/channel_v3.json.
Package Control: Installing 1 missing dependencies
Package Control: Reading WinINet option 38
Package Control: Reading WinINet option failed
Package Control: WinINet option read failed due to issue other than buffer size - 0
Package Control: Error downloading channel. The operation completed successfully. (errno 0) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-01-13 14:42:47, next run at 2015-01-13 15:42:47 or after
Package Control: Reading WinINet option 50
Package Control: Reading WinINet option 38
Package Control: Reading WinINet option failed
Package Control: WinINet option read failed due to issue other than buffer size - 0
Package Control: Error downloading channel. The operation completed successfully. (errno 0) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation
```
Hopefully this helps or if you need additional information.

**Comment by saas786** [comment]
@wbond yes  "Sublime Text Build 3065" folder :), sorry for creating misconception. 

No, I don't have Data/Packages/Package Control/?

**Comment by saas786** [comment]
Here is my new console log..

```
DPI scale: 1
startup, version: 3065 windows x32 channel: stable
executable: /F/soft/Sublime Text Build 3065/sublime_text.exe
working dir: /F/soft/Sublime Text Build 3065
packages path: /F/soft/Sublime Text Build 3065/Data/Packages
state path: /F/soft/Sublime Text Build 3065/Data/Local
hardware concurrency: 4
zip path: /F/soft/Sublime Text Build 3065/Packages
zip path: /F/soft/Sublime Text Build 3065/Data/Installed Packages
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 7 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Soda Light.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 0 total files: 291 cache hits: 290
pre session restore time: 1.09908
startup time: 1.15908
first paint time: 1.17908
launching: /F/soft/Sublime Text Build 3065/plugin_host.exe
loaded 1309 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
Package Control: Error finding main directory from loader
reloading plugin Emmet.emmet-plugin
reloading plugin LESS.less_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin CodeFormatter.CodeFormatter
CodeFormatter: formatting python files on ST3 not supported.
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
CodeFormatter: Plugin Initialized
SublimeLinter: debug mode: off 
Emmet: No need to update PyV8
found 7 files for base name Main.sublime-menu
````

**Comment by dogsoldier68** [comment]
I am having the same problem. Tried for hours to re-install, both version 2 and 3 (64-bit) and portable,
Tried all the things I've read in the forums.  Weird thing is another use was able to log into my machine (at work) and everything worked fine for him (he does not have more permissions than I do.

Here is the error I get when trying to goto the install packages:

DPI scale: 1
startup, version: 3065 windows x64 channel: stable
executable: /C/Sublime Text 3/sublime_text.exe
working dir: /C/Sublime Text 3
packages path: /C/Users/dave/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/dave/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Sublime Text 3/Packages
zip path: /C/Users/dave/AppData/Roaming/Sublime Text 3/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 169 cache hits: 169
pre session restore time: 2.33388
startup time: 2.36488
first paint time: 2.36488
launching: /C/Sublime Text 3/plugin_host.exe
loaded 837 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-01-19 12:20:50, next run at 2015-01-19 13:20:50 or after
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: xx.xxx.33.29
  Timeout: 30
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

**Comment by fqf2009** [comment]
I had the same error. I did what @wbond recommended cloning as well. I found the temporary workaround is to update the "Data\Packages\Package Control\package_control\downloaders\wininet_downloader.py" file, and comment out the following line:
self.cache_proxy_info()

**Comment by ewrankin** [comment]
@fqf2009 Thanks I tried that and it seems to work, but now it seems like it's getting caught in an infinite loop like below , did you see something similar?  When I have my settings open it seems like the Package Control is getting added and removed automatically from the ignored list.

This is message string is ongoing...
```
ignored packages updated to: [RestructuredText, Vintage, Package Control]
unloading plugin Package Control.bootstrap
unloading plugin Package Control.Package Control
reloading Packages/Package Control/Package Control.sublime-settings
reloading Packages/Package Control/package_control/Package Control.sublime-settings
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: Upgraded Package Control to latest git commit
ignored packages updated to: [RestructuredText, Vintage]
reloading plugin Package Control.bootstrap
Package Control: Settings change detected, clearing cache
reloading plugin Package Control.Package Control
reloading Packages/Package Control/Package Control.sublime-settings
reloading Packages/Package Control/package_control/Package Control.sublime-settings
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: Settings change detected, clearing cache
Package Control: Reading WinINet option 50
Package Control: None
Package Control: Installing 1 upgrades
ignored packages updated to: [RestructuredText, Vintage, Package Control]
unloading plugin Package Control.bootstrap
unloading plugin Package Control.Package Control
```

**Comment by saas786** [comment]
@wbond after sending you previous comment, I didn't get back to package control for couple of days, and few days ago I tried to install package control using your console installation method and it went fine.

And since than I have been able to install several packages as well.

So I guess your recent fixes must have resolved the issues.

But I will do a testing with fresh install on weekend and will get back to you if it still works or not.

Thanks for all of your efforts. CHEERS :dancer:

**Comment by saas786** [comment]
Hi @wbond 

I finally did downloaded latest v. **Sublime Text Build 3065 x64** and installed package control using your console installation method. And it works as well.

I will install some packages and will use it for couple of days and will let you know if problem persist or not.

**Comment by saas786** [comment]
@wbond seems your recent fixes fixed the issue.

In last two days its working fine, infact I have installed many new packages and all of them work fine so far.

I guess its now safe to close this issue.

**Comment by wbond** [comment]
3.0.1 was just released which includes the fix for this.

**Comment by ghprod** [comment]
got this error ..

```

Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
Package Control: No updated packages
Package Control: Error downloading channel. Not enough storage is available to complete this operation. (errno 14) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation
```

how to update package control?

**Comment by wbond** [comment]
@ghprod https://packagecontrol.io/docs/troubleshooting#Purging_Old_Versions

**Comment by clfeng** [comment]
got this error
Package Control: Urllib HTTPS Debug General
  Closing connection to dn-52cik.qbox.me on port 443 after 1 request
Package Control: Error downloading channel. HTTP error 404 downloading https://dn-52cik.qbox.me/channel_v3.json.

how to sovle?
