### ISSUE TITLE
How to use channels

### ISSUE THREAD

**Issue by jleeothon** [wbond/package_control#815]
I removed the default channel. Then I forked this project (no modifications), and added the URL for "channel.json" (I tried both https://github.com/jleeothon/package_control_channel/blob/master/channel.json and https://raw.githubusercontent.com/jleeothon/package_control_channel/master/channel.json), it always says that adding the channel was succesful. But then I try to "Install Package", it tells me there's no packages available for installation. How does it work, then?

**Comment by wbond** [comment]
The first URL won't work since it is an HTML URL. The second should work. Can you provide a debug log?

**Comment by jleeothon** [comment]
I got this...

```
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: https://raw.githubusercontent.com/jleeothon/package_control_channel/master/channel.json
  Resolved IP: 23.235.39.133
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/JohnnyLee/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to raw.githubusercontent.com on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to raw.githubusercontent.com on port 443
  CA certs file at /Users/JohnnyLee/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to raw.githubusercontent.com:443 with SSL
  Using TLSv1/SSLv3 with cipher RC4-SHA
  Server SSL certificate:
    subject: CN=www.github.com,O=Fastly, Inc.,L=San Francisco,S=California,C=US
    subject alt name: www.github.com, *.github.com, *.github.io, *.githubusercontent.com
    expire date: Mar  2 12:00:00 2015 GMT
  Certificate validated for raw.githubusercontent.com
Package Control: Urllib HTTPS Debug Write
  GET /jleeothon/package_control_channel/master/channel.json HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  Host: raw.githubusercontent.com
  If-None-Match: "b93447a97ed1a18e9348a862b4d1550190e39b6c"
  User-Agent: Package Control v3.0.0
  Connection: Keep-Alive
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Date: Sun, 04 Jan 2015 16:48:11 GMT
  Server: Apache
  Via: 1.1 varnish
  Last-Modified: Sun, 04 Jan 2015 16:48:11 GMT
  Cache-Control: max-age=300
  ETag: "b93447a97ed1a18e9348a862b4d1550190e39b6c"
  X-Served-By: cache-atl6235-ATL
  X-Cache: HIT
  X-Cache-Hits: 1
  Vary: Authorization,Accept-Encoding
  Expires: Sun, 04 Jan 2015 16:53:11 GMT
  Source-Age: 284
  Content-Length: 0
  Keep-Alive: timeout=10, max=50
  Connection: Keep-Alive
Package Control: Using cached content for https://raw.githubusercontent.com/jleeothon/package_control_channel/master/channel.json from /Users/JohnnyLee/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/b6f2725efac3d66dd9fc16196106b941
Exception in thread Thread-2440:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/JohnnyLee/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 43, in run
  File "package_control.package_installer in /Users/JohnnyLee/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 61, in make_package_list
  File "package_control.package_manager in /Users/JohnnyLee/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 343, in list_available_packages
  File "package_control.package_manager in /Users/JohnnyLee/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 306, in list_repositories
  File "package_control.providers.channel_provider in /Users/JohnnyLee/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 168, in get_renamed_packages
KeyError: 'packages_cache'

Package Control: Urllib HTTPS Debug General
  Closing connection to raw.githubusercontent.com on port 443 after 1 request
```

**Comment by wbond** [comment]
Ah, so it looks like `packages_cache` is not optional with the current codebase. Try adding that key to the JSON file with a blank value of `{}`.

I can tell you this almost certainly won't end up working out for you unless you either have a much simpler channel with only a handful of packages, or set up a server to scrape the repository info and generate the channel JSON periodically.

The default channel caches info from all of those repos to generate the real channel file. It takes many thousands of API HTTP requests to fetch the necessary info. Without an API key from GitHub, you'll hit their maximum of 60 requests per hour very quickly. If you do get an API key, it will take probably 30+ minutes to fetch all of the info for those packages.

If you were to create a channel of say, 5-10 packages, you should probably be able to fetch the info in 60 requests or less. It may take a minute or so to fetch all of the URLs, but Package Control does use keepalive for HTTP requests to try and improve performance.

If you are trying to create your own channel that has a subset of the packages in the default channel, it may make more sense to fetch the default channel JSON and trim it down to the list you want.

**Comment by jleeothon** [comment]
Oh, interesting, I wasn't aware of those constraints. I was actually just trying to see if a certain project would be easily downloadable and installable with Package Control. But I guess we'll just try submit it into the official channel when it's ready-er. Thanks!, and sorry for trouble.

**Comment by wbond** [comment]
If you just want to try a repository via package control, you can use `Add Repository` and paste in the public GitHub URL. Package Control will translate that URL into appropriate API calls and allow you to install the package without it being in the default channel. A single repository will definitely work within 60 API calls.

Depending on how the repository is named on GitHub, you may need to use [package_name_map](https://packagecontrol.io/docs/settings#setting-package_name_map) to translate a GitHub slug into the appropriate package name. For example:

https://github.com/wbond/sublime-foo-bar may need to be named `Foo Bar` when installed as a package. To do that, add `package_name_map` to your Package Control settings like so:

```json
{
    "package_name_map": {
        "sublime-foo-bar": "Foo Bar"
    }
}
```
