### ISSUE TITLE
Platform dependent settings files

### ISSUE THREAD

**Issue by coobas** [wbond/package_control#816]
Hi,
I ran into an issue with the latest Package Control version because its dependencies are platform-dependent and because I'm sharing config files across Windows and Linux machines. In particular, Linux requires ssl-linux while Windows does not. This means that installed_dependencies in "Package Control.sublime-settings" must be different on different platforms otherwise Sublime Text complains about platform incompatibilities in the Package Control plugin. This can be solved by using "Package Control (Platform).sublime-settings" files except that Package Control always creates "Package Control.sublime-settings" when Sublime Text starts if it's missing. The solution is I think to modify the `package_control.settings.pc_settings_filename` to check first for (Platform) setting files and use those.
Thanks,
Jakub

**Comment by wbond** [comment]
Ah, thanks for pointing this out.

While thinking about this specific issue, I think that the `installed_dependencies` list does not actually need to be maintained. Instead, I should leave the list of installed dependencies up to the `dependencies.json` files in packages and in the `package-metadata.json` files. That way platform-specific dependencies will be installed as needed.

That isn't to say that platform-specific settings may not be useful. I'll have to look and see if there is functionality to implement platform-specific settings files when using `sublime.save_settings()`.

**Comment by coobas** [comment]
Thanks for looking into this!

**Comment by MarkCheshire** [comment]
I am running into an issue based on this. It is not a blocker. This is from Window7. I think it may be attempting to add the ssl-linux dependency because I also run on Linux.

    Package Control: Installing 1 missing dependencies
    Package Control: The dependency "ssl-linux" is either not available on this platform or for this version of Sublime Text
    Package Control: Installed missing dependency ssl-linux

It seems that once PC detects that the dependency is not relevant for the platform, it could just ignore it rather than to proceed to install it on each start up.

Again it is not a blocker but probably useful to address at some point.

**Comment by wbond** [comment]
3.0.1 was just released. It removes the `installed_dependencies` setting since it is not necessary. The commit with the change is e5286d1199282d68da9847ca9dcdff6012a56fff.

**Comment by coobas** [comment]
Great, thank you for fixing this!
