### ISSUE TITLE
Error downloading repository and rate limit errors

### ISSUE THREAD

**Issue by bgreenlee** [wbond/package_control#824]
Installing Package Control on a fresh install of ST3 on OS X (10.10.1):

	>>> import urllib.request,os,hashlib; h = '2deb499853c4371624f5a07e27c334aa' + 'bf8c4e67d14fb0525ba4f89698a6d7e1'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
	170998
	reloading plugin Package Control.bootstrap
	reloading plugin Package Control.Package Control
	reloading Packages/Package Control/Package Control.sublime-settings
	found 2 files for base name Main.sublime-menu
	reloading plugin 0_package_control_loader.00-package_control
	reloading Packages/User/Package Control.sublime-settings
	Package Control: Installing 1 missing dependencies
	Package Control: Installed missing dependency bz2
	Package Control: No updated packages
	Package Control: Hit rate limit of 60 for api.github.com, skipping all futher download requests for this domain
	Package Control: Hit rate limit of 60 for api.github.com, skipping all futher download requests for this domain
	Package Control: Skipping due to hitting rate limit for api.github.com
	Package Control: Skipping due to hitting rate limit for api.github.com
	Package Control: Rate limit of 60 exceeded for api.github.com
	Package Control: Rate limit of 60 exceeded for api.github.com
	Package Control: Skipping due to hitting rate limit for api.github.com
	Package Control: Skipping due to hitting rate limit for api.github.com
	Package Control: Skipping due to hitting rate limit for api.github.com
       <snipped 300 lines of the same>
	Package Control: Skipping due to hitting rate limit for api.github.com
	Package Control: Error downloading repository. HTTP error 404 downloading https://packagecontrol.io/repository.json.

**Comment by FichteFoll** [comment]
I suspect that there is something fishy with your PC settings file. Can you please post its contents?

**Comment by bgreenlee** [comment]
Default settings:

```
{
	// A list of URLs that each contain a JSON file with a list of repositories.
	// The repositories from these channels are placed in order after the
	// repositories from the "repositories" setting
	"channels": [
		"https://packagecontrol.io/channel_v3.json"
	],

	// A list of URLs that contain a packages JSON file. These repositories
	// are placed in order before repositories from the "channels"
	// setting
	"repositories": [],

	// A list of packages to install pre-release versions for. Versions
	// under 1.0.0 are not considered pre-release, only those using the SemVer
	// -prerelease suffixes will be ignored if the package is not in this
	// list.
	"install_prereleases": [],

	// If debugging information for HTTP/HTTPS connections should be printed
	// to the Sublime Text console
	"debug": false,

	// This helps solve naming issues where a repository it not named the
	// same as the package should be. This is primarily only useful for
	// GitHub and BitBucket repositories. This mapping will override the
	// mapping that is retrieved from the repository channels.
	"package_name_map": {},

	// If package install, upgrade and removal info should be submitted to
	// the channel for aggregated statistics
	"submit_usage": true,

	// The URL to post install, upgrade and removal notices to
	"submit_url": "https://packagecontrol.io/submit",

	// If packages should be automatically upgraded when ST starts
	"auto_upgrade": true,

	// If missing packages should be automatically installed when ST starts
	"install_missing": true,

	// If a package was installed by Package Control (has a
	// package-metadata.json file) but is not in installed_packages, remove it
	// based upon the assumption that it was removed on another machine and
	// the Package Control.sublime-settings file was synced to this machine.
	"remove_orphaned": true,

	// The minimum frequency in hours in which to check for automatic upgrades,
	// setting this to 0 will always check for automatic upgrades
	"auto_upgrade_frequency": 1,

	// Packages to not auto upgrade
	"auto_upgrade_ignore": [],

	// Timeout for downloading channels, repositories and packages. Doesn't
	// have an effect on Windows due to a bug in WinINet.
	"timeout": 30,

	// The number of seconds to cache repository and package info for
	"cache_length": 300,

	// An HTTP proxy server to use for requests. Not used on Windows since the
	// system proxy configuration is utilized via WinINet.
	"http_proxy": "",
	// An HTTPS proxy server to use for requests - this will inherit from
	// http_proxy if it is set to "" or null and http_proxy has a value. You
	// can set this to false to prevent inheriting from http_proxy. Not used on
	// Windows since the system proxy configuration is utilized via WinINet.
	"https_proxy": "",

	// Username and password for both http_proxy and https_proxy. May be used
	// with WinINet to set credentials for system-level proxy config.
	"proxy_username": "",
	"proxy_password": "",

	// If HTTP responses should be cached to disk
	"http_cache": true,

	// Number of seconds to cache HTTP responses for, defaults to one week
	"http_cache_length": 604800,

	// User agent for HTTP requests. If "%s" is present, will be replaced
	// with the current version.
	"user_agent": "Package Control v%s",

	// Setting this to true will cause Package Control to ignore all git
	// and hg repositories - this may help if trying to list packages to install
	// hangs
	"ignore_vcs_packages": false,

	// Custom path(s) to "git" binary for when it can't be automatically
	// found on the system and a package includes a .git metadata directory.
	// Supports more than one path to allow users to sync settings across
	// operating systems.
	"git_binary": [],

	// This should NOT contain the name of the remote or branch - that will
	// be automatically determined.
	"git_update_command": ["pull", "--ff", "--commit"],

	// Custom path(s) to "hg" binary for when it can't be automatically
	// found on the system and a package includes a .hg metadata directory.
	// Supports more than one path to allow users to sync settings across
	// operating systems.
	"hg_binary": [],

	// For HG repositories, be sure to use "default" as the remote URL.
	// This is the default behavior when cloning an HG repo.
	"hg_update_command": ["pull", "--update"],

	// Additional packages to ignore when listing unmanaged packages.
	"unmanaged_packages_ignore": [],

	// Directories to ignore when creating a package
	"dirs_to_ignore": [
		".hg", ".git", ".svn", "_darcs", "CVS"
	],

	// Files to ignore when creating a package
	"files_to_ignore": [
		"*.pyc", ".hgignore", ".gitignore", ".bzrignore",
		"*.sublime-project", "*.sublime-workspace", "*.tmTheme.cache"
	],

	// Files to include, even if they match a pattern in files_to_ignore
	"files_to_include": [],

	// When a package is created, copy it to this folder - defaults to Desktop
	"package_destination": "",

	// A way to create different packaging profiles for different types of
	// package releases, such as for different platforms or binary-only
	// releases.
	//
	// The key of the object will be the profile name and a list of them will
	// be presenting when running the "Create Package File" command. The
	// profile "Default" will use the top-level version on the following
	// settings:
	//
	// - "dirs_to_ignore"
	// - "files_to_ignore"
	// - "files_to_include"
	// - "package_destination"
	//
	// If a profile does not include one of those three setting, it will fall
	// back to the top-level settings.
	"package_profiles": {
		"Binaries Only": {
			// Exclude all .py files, but consequently include all .pyc files
			"files_to_ignore": [
				"*.py", ".hgignore", ".gitignore", ".bzrignore",
				"*.sublime-project", "*.sublime-workspace", "*.tmTheme.cache"
			],

			// Include __init__.py so Sublime Text will load the package
			"files_to_include": [
				"__init__.py"
			]
		}
	},

	// Enable the ability to run the tests - this is only for development
	"enable_tests": false
}
```

User settings:

```
{
	"installed_dependencies":
	[
		"0_package_control_loader",
		"bz2"
	],
	"installed_packages":
	[
		"Package Control"
	]
}
```

**Comment by bgreenlee** [comment]
I restarted ST and reran the install command and nothing happened (just printed 170998)

**Comment by bgreenlee** [comment]
It does seem to be fine, though.

**Comment by wbond** [comment]
Something was in-memory, or there was a different `User/Package Control.sublime-settings` file at work. I can tell this because of `Package Control: Error downloading repository. HTTP error 404 downloading https://packagecontrol.io/repository.json`. That wouldn't happen with a fresh install of PC on a fresh copy of ST3.

I seems this is resolved, so I am going to close it.

**Comment by gwenzek** [comment]
I got the same error and DuckduckGo lead me here, so here are the steps to get a proper fix.
But you only need this if you intend to debug package control or something like that.
Otherwise the default quotas should be enough.

* Create a new [Github App](https://github.com/settings/apps/new)
* GitHub App name: Package Control
* Homepage URL: `https://github.com/wbond/package_control/issues/824`
* Webhook: untick the "Active" box
* Repository permissions: not sure here, I needed to only read one "repository" file so I granted read access to that one
* Where can this GitHub App be installed? > Only on this account 
* Create the app
* "install" it through: https://github.com/settings/apps/package-control/installations
* Copy app client id and secret id from: https://github.com/settings/apps/package-control
* Add the following dict to your package control settings:
```
	"query_string_params": {
		"api.github.com": {
			"client_id": <YOUR_CLIENT_ID>,
			"client_secret": <YOUR_CLIENT_SECRET>,
		},
	},
```

@wbond warned us that this will stop working around September 2020 when Github stop accepting tokens as URI parameters

**Comment by dvcrn** [comment]
Is there a proper solution to this that can work long term? I use private repositories and run into these api limitations a lot. Using a VPN to get a different API is only doing so much 😛

**Comment by wbond** [comment]
@dvcrn The proper solution is what @gwenzek described in his comment above yours.

The only clarification is that the settings under which you need to put your client_id and client_secret will likely change around September 2020, not that there won't be a solution then.

In short, you have to create a GitHub "application" on your account to get API credentials to do more than 60 requests per hour. There is no way around this.
