### ISSUE TITLE
Removing package when "cleaning up" fails (Windows)

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#835]
Based on `master` and few modifications from my pull requests. The package is not removed instantly, the following traceback appears after a restart:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "C:\tools\SUBLIM~1\Data\Packages\PACKAG~1\package_control\package_cleanup.py", line 54, in run
    if delete_directory(package_dir):
  File "C:\tools\SUBLIM~1\Data\Packages\PACKAG~1\package_control\clear_directory.py", line 112, in delete_directory
    shutil.rmtree(path, onerror=_on_error)
  File ".\shutil.py", line 221, in rmtree
  File "C:\tools\SUBLIM~1\Data\Packages\PACKAG~1\package_control\clear_directory.py", line 100, in _on_error
    os.rename(path, path + '.package-control-old')
WindowsError: [Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird
```
(cannot remove file because it's used by another process)

In the package itself there is a file named `package-control.cleanup`, the package is not inside `installed_packages`, nor in `ignored_packages`, nor in `in_process_packages`. Not before and not after the restart.

I suspect that the package is errorneously removed from the `ignored_packages` list despite awaiting cleanup. Adding it to the list manually before restarting makes it work.

**Comment by FichteFoll** [comment]
Okay, update on this.

The package in question had a plugin file that threw an exception on load (because it tried to import a depedency but PC currently does not seem to install those on package_install on ST2 - I'm working on this). This resulted in ST not releasing the file handle to that .py file which in return meant that PC had to mark the package as to-be-cleaned-up and then resulted in the problem reported above.

**Comment by wbond** [comment]
Windows crappy filesystem locking is the bane of file operations in Package Control.

**Comment by wbond** [comment]
This should be resolved by 652365937ecafc795408ad0a6e2d339e7b408d90. The code comment explains how.

**Comment by FichteFoll** [comment]
This issue is not fixed (wonder why I can't reopen).

Basically what needs to happen is that the package must be ignored before ST is restarted, then the package folder removed on restart and the package also removed from the ignored list.

Anyway, here's steps on how to reproduce:

1. Be on Windows and use ST2 (portable for me)
2. Create a new package folder (`RemoveTest` for me)
3. Create a new Python file in it and write an import statement that will fail (e.g. `import doesntexist`)
4. If ST is not running already, start it
5. Get the following in the console:

  ```
  Reloading plugin C:\tools\Sublime Text 2\Data\Packages\RemoveTest\test.py
  Traceback (most recent call last):
    File ".\sublime_plugin.py", line 62, in reload_plugin
      m = imp.load_module(modulename, *m_info)
    File ".\test.py", line 1, in <module>
      import doesntexist
  ImportError: No module named doesntexist
  ```

6. Run **Package Control: Remove Package** and try to remove the package we just created.
7. This happens:

  ```
  ignored packages updated to: [SublimeOnSaveBuild, WakaTime, Markdown, RequestsTest, Vintage, RemoveTest]
  Unloading plugin C:\tools\Sublime Text 2\Data\Packages\RemoveTest\test.py
  [...]
  Package Control: The package RemoveTest has been removed and will be cleaned up on the next restart
  ignored packages updated to: [Vintage, WakaTime, Markdown, RequestsTest, SublimeOnSaveBuild]
  [...]
  Reloading plugin C:\tools\Sublime Text 2\Data\Packages\RemoveTest\test.py
  Traceback (most recent call last):
    File ".\sublime_plugin.py", line 62, in reload_plugin
      m = imp.load_module(modulename, *m_info)
    File ".\test.py", line 1, in <module>
      import doesntexist
  ImportError: No module named doesntexist
  ```

8. Restart ST.
9. `Package Control: Unable to remove old directory RemoveTest - deferring until next start`
10. Repeat indefinitely, or manually add `"RemoveTest"` to the ignored_packages setting and see it work on the next restart.

I examined this with a tool that shows open file handles and the reason for this is that ST does not close handles of Python files that fail to load and throw an exception (`raise Exception("hiho")
` as source also leads to this behavior). Not even when the package is ignored.

Thus, I suggest to add the package to the ignored packages list (or just not removing it when cleanup is necessary) and then try to remove it on startup, after which it will be "enabled" again if it was successful.

**Comment by wbond** [comment]
I can not reproduce on Windows 7 x64 with Sublime Text 2 x64 and Package Control 3.0.1-beta2.

```
Reloading plugin C:\Users\wbond\AppData\Roaming\Sublime Text 2\Packages\RemoveTest\foo.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\foo.py", line 1, in <module>
    import doesntexist
ImportError: No module named doesntexist
```

Now running `Package Control: Remove Package`:

```
ignored packages updated to: [Vintage, Trimmer, RemoveTest]
found 1 files for base name Default.sublime-theme
Unloading plugin C:\Users\wbond\AppData\Roaming\Sublime Text 2\Packages\RemoveTest\foo.py
reloading /C/Users/wbond/AppData/Roaming/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /C/Users/wbond/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?package_control_version=3.0.1-beta2&sublime_platform=windows&package=RemoveTest&sublime_version=2221&version=None&operation=remove
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Tue, 28 Oct 2014 20:00:00 GMT
    expire date: Wed, 28 Oct 2015 19:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /submit?package_control_version=3.0.1-beta2&sublime_platform=windows&package=RemoveTest&sublime_version=2221&version=None&operation=remove HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  User-Agent: Package Control v3.0.1-beta2
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sat, 17 Jan 2015 13:39:31 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-App-Version: 1.1.1
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: The package RemoveTest has been removed
ReadDirectoryChangesW failed
ignored packages updated to: [Vintage, Trimmer]
found 1 files for base name Default.sublime-theme
reloading /C/Users/wbond/AppData/Roaming/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /C/Users/wbond/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading /C/Users/wbond/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
```

Now, the folder may appear to still exist for `RemoveTest`, however it will not be accessible via Windows Explorer, and will disappear as soon as Sublime Text 2 is closed.

**Comment by FichteFoll** [comment]
Same specs here, except for the portable version. Maybe you could try that?

**Comment by FichteFoll** [comment]
Okay, so I started working on this but am not sure how you would handle the return values. Basically, I need a secondary result from `manager.remove_package` that indicates if a package has been scheduled for clean-up and only then not re-enable the package, so that it will only be removed on the next restart after it actually was cleared, since it is still "in-progress". I'm considering `True`, `False` and additionally `None` as return values.

However, what should happen if PC failed to remove the .sublime-package file (installed or pristine) for whatever reason? Should the package be re-enabled or stay disabled?
