### ISSUE TITLE
No way to remove a dependency if you (somehow) got rid of the last package that used it

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#839]
I don't exactly know if PC does something like ref counting, but here's what happened:

I started ST, opened the cmd palette and removed a package with a dependency. That dependency however was not installed at that point and the "installing missing 1 dependencies" message occured right after that, or maybe even before.

Anyway, the package was removed and then the dependency was installed. This is not a bad thing by itself, but the problem is that there is no way to get rid of the dependency now because "Satisfy Dependencies" does not seem to remove it and it doesn't show up in "Remove Package" obviously. The only way is to manually delete the package folder, the loader file and the reference in the PC.settings file, I suppose. Or install and remove the package again.

Edit: To be precise, you can technically remove any package which would result in the cleanup code inside `package_manager.remove_package` being run, but that's not exactly great. It should just happen in "Satisfy Dependencies".

**Comment by wbond** [comment]
This was a race condition you experienced. The package_cleanup module will now take care of this when Sublime Text is started. Alternatively, your changes to Satisfy Dependencies will do the same.

**Comment by FichteFoll** [comment]
There are still ways to manually remove a package though (remove folder/.sublime-package and entry in installed_packages) in which case the dep would've been left alone until another package was removed. Not likely going to happen, but since the cleanup was revised this won't be an issue for long anymore.
