### ISSUE TITLE
PC 3.0 doesn't install on Windows x64/ ST3

### ISSUE THREAD

**Issue by andig** [wbond/package_control#842]
I've been happily using PC for ages. During the 3.0 upgrade I remember seeing a message that I manually needed to perform it. After upgrade, PC is gone. I've removed the `Package Control.sublime-package` file and started from scratch, then restartet, yet PC doesn't load. Here's the log of the install and after the restart:

	DPI scale: 1
	startup, version: 3065 windows x64 channel: stable
	executable: /C/Program Files/Sublime Text 3/sublime_text.exe
	working dir: /C/Program Files/Sublime Text 3
	packages path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Packages
	state path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Local
	hardware concurrency: 4
	zip path: /C/Program Files/Sublime Text 3/Packages
	zip path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Installed Packages
	found 12 files for base name Default.sublime-keymap
	found 2 files for base name Default.sublime-mousemap
	found 9 files for base name Main.sublime-menu
	loading bindings
	loading pointer bindings
	found 1 files for base name Default.sublime-theme
	theme loaded
	app ready
	wrote startup cache, added files: 1 orphaned files: 0 total files: 213 cache hits: 212
	pre session restore time: 0.526563
	startup time: 0.633563
	first paint time: 0.681563
	launching: /C/Program Files/Sublime Text 3/plugin_host.exe
	loaded 1328 snippets
	reloading plugin Default.block
	reloading plugin Default.comment
	reloading plugin Default.copy_path
	reloading plugin Default.delete_word
	reloading plugin Default.detect_indentation
	reloading plugin Default.duplicate_line
	reloading plugin Default.echo
	reloading plugin Default.exec
	reloading plugin Default.fold
	reloading plugin Default.font
	reloading plugin Default.goto_line
	reloading plugin Default.history_list
	reloading plugin Default.indentation
	reloading plugin Default.kill_ring
	reloading plugin Default.mark
	reloading plugin Default.new_templates
	reloading plugin Default.open_file_settings
	reloading plugin Default.open_in_browser
	reloading plugin Default.pane
	reloading plugin Default.paragraph
	reloading plugin Default.paste_from_history
	reloading plugin Default.save_on_focus_lost
	reloading plugin Default.scroll
	reloading plugin Default.set_unsaved_view_name
	reloading plugin Default.side_bar
	reloading plugin Default.sort
	reloading plugin Default.swap_line
	reloading plugin Default.switch_file
	reloading plugin Default.symbol
	reloading plugin Default.transform
	reloading plugin Default.transpose
	reloading plugin Default.trim_trailing_white_space
	reloading plugin CSS.css_completions
	reloading plugin Diff.diff
	reloading plugin HTML.encode_html_entities
	reloading plugin HTML.html_completions
	reloading plugin All Autocomplete.all_views_completions
	reloading plugin Better CoffeeScript.CoffeeScript
	reloading plugin DocBlockr.__init__
	reloading plugin DocBlockr.jsdocs
	reloading plugin EditorConfig.EditorConfig
	reloading plugin Emmet.emmet-plugin
	reloading plugin JsFormat.js_formatter
	reloading plugin Phpcs.phpcs
	reloading plugin SublimeLinter-coffee.linter
	SublimeLinter: coffee linter loaded 
	reloading plugin TrailingSpaces.trailing_spaces
	reloading plugin SublimeCodeIntel.SublimeCodeIntel
	reloading plugin SublimeLinter.commands
	reloading plugin SublimeLinter.sublimelinter
	reloading plugin SublimeLinter-phpcs.linter
	SublimeLinter: phpcs linter loaded 
	plugins loaded
	SublimeLinter: debug mode: off 
	SublimeLinter: WARNING: phpcs deactivated, cannot locate 'phpcs' 
	found 9 files for base name Main.sublime-menu
	Emmet: No need to update PyV8
	Could not import subprocess32 module, falling back to subprocess module
	>>> import urllib.request,os,hashlib; h = '2deb499853c4371624f5a07e27c334aa' + 'bf8c4e67d14fb0525ba4f89698a6d7e1'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by) 
	170998
	>>> 

Restart:

	DPI scale: 1
	startup, version: 3065 windows x64 channel: stable
	executable: /C/Program Files/Sublime Text 3/sublime_text.exe
	working dir: /C/Program Files/Sublime Text 3
	packages path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Packages
	state path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Local
	hardware concurrency: 4
	zip path: /C/Program Files/Sublime Text 3/Packages
	zip path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Installed Packages
	found 12 files for base name Default.sublime-keymap
	found 2 files for base name Default.sublime-mousemap
	found 9 files for base name Main.sublime-menu
	loading bindings
	loading pointer bindings
	found 1 files for base name Default.sublime-theme
	theme loaded
	app ready
	wrote startup cache, added files: 1 orphaned files: 0 total files: 213 cache hits: 212
	pre session restore time: 0.402176
	startup time: 0.549176
	first paint time: 0.557176
	launching: /C/Program Files/Sublime Text 3/plugin_host.exe
	loaded 1328 snippets
	reloading plugin Default.block
	reloading plugin Default.comment
	reloading plugin Default.copy_path
	reloading plugin Default.delete_word
	reloading plugin Default.detect_indentation
	reloading plugin Default.duplicate_line
	reloading plugin Default.echo
	reloading plugin Default.exec
	reloading plugin Default.fold
	reloading plugin Default.font
	reloading plugin Default.goto_line
	reloading plugin Default.history_list
	reloading plugin Default.indentation
	reloading plugin Default.kill_ring
	reloading plugin Default.mark
	reloading plugin Default.new_templates
	reloading plugin Default.open_file_settings
	reloading plugin Default.open_in_browser
	reloading plugin Default.pane
	reloading plugin Default.paragraph
	reloading plugin Default.paste_from_history
	reloading plugin Default.save_on_focus_lost
	reloading plugin Default.scroll
	reloading plugin Default.set_unsaved_view_name
	reloading plugin Default.side_bar
	reloading plugin Default.sort
	reloading plugin Default.swap_line
	reloading plugin Default.switch_file
	reloading plugin Default.symbol
	reloading plugin Default.transform
	reloading plugin Default.transpose
	reloading plugin Default.trim_trailing_white_space
	reloading plugin CSS.css_completions
	reloading plugin Diff.diff
	reloading plugin HTML.encode_html_entities
	reloading plugin HTML.html_completions
	reloading plugin All Autocomplete.all_views_completions
	reloading plugin Better CoffeeScript.CoffeeScript
	reloading plugin DocBlockr.__init__
	reloading plugin DocBlockr.jsdocs
	reloading plugin EditorConfig.EditorConfig
	reloading plugin Emmet.emmet-plugin
	reloading plugin JsFormat.js_formatter
	reloading plugin Phpcs.phpcs
	reloading plugin SublimeLinter-coffee.linter
	SublimeLinter: coffee linter loaded 
	reloading plugin TrailingSpaces.trailing_spaces
	reloading plugin SublimeCodeIntel.SublimeCodeIntel
	reloading plugin SublimeLinter.commands
	reloading plugin SublimeLinter.sublimelinter
	reloading plugin SublimeLinter-phpcs.linter
	SublimeLinter: phpcs linter loaded 
	plugins loaded
	SublimeLinter: debug mode: off 
	SublimeLinter: WARNING: phpcs deactivated, cannot locate 'phpcs' 
	found 9 files for base name Main.sublime-menu
	Emmet: No need to update PyV8

The file itself is there but apparently the plugin not loaded. I'm clueless where to look...

**Comment by FichteFoll** [comment]
Check if it is in the `ignored_packages` list in your user settings.

**Comment by andig** [comment]
Oh dear... I feel stupid. No idea how it ever got there... THANKS!!!

**Comment by msieurtoph** [comment]
Let's feel stupid together ... this post saved my day! ;)

**Comment by andig** [comment]
Thank you, much appreciated ;)

**Comment by sergiodebcn** [comment]
Same here! Thanks
