### ISSUE TITLE
Package not showing in package list

### ISSUE THREAD

**Issue by iRonin** [wbond/package_control#843]
Today I switched to ST3 and run into #657 
I was able to install a few `SublimeLinter-*` packages but they wouldn't work (they **did install**); I realized I didn't have the `SublimeLinter` package itself so I tried to install it but it wouldn't show up. I removed the other linter packages but still no juice and now they also won't show up.
I'm using `  Package Control Version: 3.0.0`.
I checked https://packagecontrol.io/channel_v3.json and the packages are there but they are not listed for me. 
When I do advanced install I get `Package Control: The package "SublimeLinter" is either not available on this platform or for this version of Sublime Text`.
I tried with clean slate install but I get the same.

[Log output when trying to install package](https://gist.github.com/iRonin/cc5ccb5cc503dd4e06f3)

**Comment by skj3gg** [comment]
This is a SublimeLinter issue, I'm trying to resolve this now, extremely sorry.

**Comment by skj3gg** [comment]
This has been resolved.

Please close this issue.

**Comment by iRonin** [comment]
Thanks @skj3gg :+1:
