### ISSUE TITLE
Numix theme customisation problem

### ISSUE THREAD

**Issue by himagra** [wbond/package_control#846]
Error trying to parse settings: Unexpected character, expected a comma or closing bracket in Packages/User/Preferences.sublime-settings:5:2 when I save my preferences during Numix theme installation .
FYI I installed theme manually because My package control: install get stuck on [loading repositries ==] and when I start my sublime text an error pops which says :- 
"Package Control
Your system's locale is set to a value that can not handle non-ASCII characters. Package Control can not properly work unless this is fixed.
On Linux, please reference your distribution's docs for information on properly setting the LANG environmental variable. As a temporary work-around, you can launch Sublime Text from the terminal with:

LANG=en_US.UTF-8 sublime_text"

![screenshot from 2015-01-16 16 33 39](https://cloud.githubusercontent.com/assets/8145085/5775248/7a51fff4-9d9d-11e4-9bea-f4ddb1c6848d.png)

**Comment by wbond** [comment]
This doesn't really have anything to do with Package Control.

You forgot to put a comma at the end of lines 4 and 5.

If you have trouble with Package Control, please create a new issue with a debug log.
