### ISSUE TITLE
Manual install not working

### ISSUE THREAD

**Issue by NeuroWinter** [wbond/package_control#847]
I am unable to install package control with the command line method, since I get this error:

urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

I think this is because I am behind a proxy at work. So I tried to install manually, but no matter what I try it just wont install. I don't know what I am doing wrong...

I have Package Control.zip in this folder:

C:\Users\###\AppData\Roaming\Sublime Text 3\Installed Packages

and yet package control will not show up in the preferences tab nor when I press ctrl+shift+p. Any help would be much appreciated.

**Comment by NeuroWinter** [comment]
I managed to install with the command line after changing some proxy settings. 

Please close.

**Comment by FichteFoll** [comment]
You can close your own issues yourself.
