### ISSUE TITLE
Packages download, are listed as installed but are not extracted to packages folder

### ISSUE THREAD

**Issue by dkebler** [wbond/package_control#850]
can't say exactly when this issue started by maybe since the update.  Now every package I install the archive doesn't extract to the packages folder.  It downloads fine to the installed packages directory but does not self exract.   If I manually extract it all is fine, package runs.

I see you mentioned such an issue about two years ago in another issue but saw nothing specific in terms of a resolved one.

Running ST3 on Mint/Ubuntu 17/14

**Comment by wbond** [comment]
This is by design.

ST3 allows keeping packages zipped, and then allows overriding files via the `Packages/` folder. See https://www.sublimetext.com/docs/3/packages.html for more info.
