### ISSUE TITLE
Export HTTP backends to a separate project

### ISSUE THREAD

**Issue by pomeh** [wbond/package_control#857]
Hi,

First of all, thanks you for building package control :) This package and your work is awesome.

Some packages for Sublime Text doesn't have support for handling proxy, or often the support is not wide enough to handle complex configuration (eg: HTTPS with `pac` file and authentication). As far as I'm concerned, I've never encountered this kind of problem while using Package Control, every where I am it can download package list, install and updated them correctly. I know you've done a lot of work to get this works as perfectly as possible, and I'm very thankful to you :) But I'm sad to see other packages doesn't have such a good proxy support.

So here is my suggestion: what about putting all the "network logic" currently embedded in Package Control into another, dedicated repository ? There are too many good things in there that could be shared and reused by other packages.

What do you think ?

**Comment by wbond** [comment]
Well, with Package Control 3.0, I've made the `package_control` module available to all other packages via injecting a loader early in the Sublime Text loading process.

Currently there is a `package_control.download_manager` submodule that exposes the downloader functionality. However, it does not support anything but `GET` requests. There is no support for `POST` or other HTTP verbs.

I would be open to contributions in this area if anyone feels like spending some time on it, however I don't currently have the time to work on it myself. Perhaps at some point later this year I may.

**Comment by pomeh** [comment]
Thanks for you reply.

> Well, with Package Control 3.0, I've made the package_control module available to all other packages via injecting a loader early in the Sublime Text loading process.
> Currently there is a package_control.download_manager submodule that exposes the downloader functionality.

Didn't know about that, it's nice :) Is this documented somewhere (api, simple/advanced examples etc) ?

> However, it does not support anything but GET requests. There is no support for POST or other HTTP verbs.

It's still better than none ! One step at a time :)

> I would be open to contributions in this area if anyone feels like spending some time on it, however I don't currently have the time to work on it myself. Perhaps at some point later this year I may.

I would love to contribute to it but I don't think I have enough Python knowledge to bring that up. But I'm willing to put a bounty on this "feature" :)

**Comment by wbond** [comment]
I haven't specifically documented it yet since it still needs some tweaks, but the core part is there. It implements a context manager and contains a pool of downloaders to allow connections to be reused, and various other neat features.

One of the current warts is that you need a settings `dict` to pass to the context manager, but I don't have a good publicly available way to grab the current settings as a `dict` (as opposed to a `sublime.Settings` object, which is not thread safe in ST2).

I haven't explored the idea of specific feature bounties, but there has been some interest recently by companies in sponsoring some new features. Do you have experience with any sites that provide a good system for open source bounties? I've heard of BountySource, but never used it other than to donate towards a fundraiser.

**Comment by pomeh** [comment]
I don't have that much experience with bounty programs but BountySource sounds good to me, I've heard a lot of good things about it and a lot of big companies are likely to use it.

For the docs part, I understand that you didn't have it documented if it's not stable enough for now. I don't know what I can do to help on this.

**Comment by pomeh** [comment]
Hi @wbond, do you have any news on this subject ? :)

**Comment by wbond** [comment]
Unfortunately not. Currently I am trying to focus on contract work, so it is unlikely I'll be working on this any time soon.

**Comment by pomeh** [comment]
Ok ok, thanks for the reply :)
