### ISSUE TITLE
Disabling packages flow

### ISSUE THREAD

**Issue by iamntz** [wbond/package_control#858]
I was thinking that a feature that would be helpful in cases of debugging misbehaviors would be a way to disable all packages. This is how i see this working:
1. Disable all packages
2. Disable all packages except X

Alternatively, a list all packages. Yes, i know this feature already exists, but would be more helpfully to get all this list in a separate view, to be easily copy/pasted into ignored packages.

Then would be also nice to have a way to show _recently active_ packages, in order to do, obviously:
1. Enable recently active packages
2. Enable recently active packages except X

**Comment by FichteFoll** [comment]
I did some theory crafing for this on the ex. SublimeText/Troubleshooting repo (has since been moved): https://github.com/titoBouzout/Troubleshooting/issues/1. While the troubleshooting package could include more things related troubleshooting than is within PC's scope, PC itself is probably still fine to include some mechanics for disabling all packages or searching for the offender.

**Comment by iamntz** [comment]
Yeah, also would be nice to have something like „enable next package”, when you can disable all packages (as mentioned above) then start enabling them one by one.

**Comment by FichteFoll** [comment]
Nah, using the c&d binary search algorithm is faster than enabling them one by one. Well, it could of course be added as well, but it's not as efficient.

**Comment by iamntz** [comment]
I'm not sure what c&d binary search means, but i was thinking at scenarios like this: say you have a weird behavior that occurs only on some special occasions, but often enough to be annoying. Disable all plugins, then start enabling one, do some work, after a random period of time i enable the next and so on.

**Comment by FichteFoll** [comment]
"c&d" should actually be "d&c" and means "divide and conquer". Binary search is a search algorithm of O(log n). It would do the same as your proposal but faster.

>- Halve the "to be disabled" packages list and only disable one half.
- Prompt the user to restart.
- Provide a command to shrink the ignored packages list by asking whether the problem went away or is still present.
- Select the corresponding half and repeat the whole procedure until one package is left. Depending on the "remaining packages candidates" the user could theoretically find the offending package earlier but I'm not too sure how to display that.

**Comment by iamntz** [comment]
Ah! Ok, well, i guess this would be complementary to my request then.

I'm also encounter sometimes the saving bug and i think it's a problem with various packages, since vanilla st works just fine, and something like this would be quite useful to me :smirk_cat:

**Comment by deathaxe** [comment]
ST4 can be started in SAFE MODE with all packages disabled for debugging purposes.
