### ISSUE TITLE
Disable packages does not work properly 

### ISSUE THREAD

**Issue by aziz** [wbond/package_control#859]
I'm using ST 3067 on a Mac with the latest package control. 
Here is what happens: 
I disable a package using the commands palette and package control disables it just fine. I check my user `Preferences.sublime-settings` and the package name is appended to the bottom of `ignored_packages` list and the package is actually disabled but something funny happens. 
If I restart the package is enabled again!

Investigating it a bit more I realized package control also add the package name to `in_process_packages` in `Package Control.sublime-settings` and when I restart ST, it clears the `in_process_packages` list but also removes the package from `ignored_packages` list of my preferences.  Hence, the plugin is enabled again! 

The only way I can disable a package now is to manually edit the `Preferences.sublime-settings` file and add the package name to the `ignored_packages` list.

**Comment by FichteFoll** [comment]
Please see #810. It will be fixed in the next release.

**Comment by Fironet** [comment]
Ah, was wondering if it was just me. Good to know it will be fixed. Using build 3065 btw.

**Comment by wbond** [comment]
This is fixed in 3.0.1, which was just released.
