### ISSUE TITLE
Package Control: Error downloading channel. URL error unknown error

### ISSUE THREAD

**Issue by axxehub** [wbond/package_control#860]
I am using Sublime Text 3 on Ubuntu 14.04  with the latest Package Control from the master branch. I am unable to retrieve a list of packages to install. Below is a debug trace when I start Sublime Text 3. I get the same `Error downloading channel. URL error unknown error` when I try to use the `Install Package` option.

    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.01-ssl-linux
    Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
    reloading plugin Package Control.Package Control
    loaded 837 snippets
    reloading plugin Package Control.bootstrap
    plugins loaded
    Package Control: Fetching list of available packages
      Platform: linux-x64
      Sublime Text Version: 3065
      Package Control Version: 3.0.0
    Package Control: Download Debug
      URL: https://packagecontrol.io/channel_v3.json
      Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
      Resolved IP: 50.116.33.29
      Timeout: 30
    Package Control: Urllib Debug Proxy
      http_proxy: 
      https_proxy: 
      proxy_username: 
      proxy_password: 
    Package Control: Urllib HTTPS Debug General
      Connecting to packagecontrol.io on port 443
    Package Control: Urllib HTTPS Debug General
      Connecting to packagecontrol.io on port 443
      CA certs file at /home/axxe/.config/sublime-text-3/Packages/User/Package Control.merged-ca-    bundle
    Package Control: Error downloading channel. URL error unknown error (_ssl.c:2228) downloading https://packagecontrol.io/channel_v3.json.
    Package Control: Installing 1 missing dependencies
    Package Control: Fetching list of available packages
      Platform: linux-x64
      Sublime Text Version: 3065
      Package Control Version: 3.0.0
    Package Control: Download Debug
      URL: https://packagecontrol.io/channel_v3.json
      Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
      Resolved IP: 50.116.33.29
      Timeout: 30
    Package Control: Urllib HTTPS Debug General
      Connecting to packagecontrol.io on port 443
    Package Control: Urllib HTTPS Debug General
      Connecting to packagecontrol.io on port 443
      CA certs file at /home/axxe/.config/sublime-text-3/Packages/User/Package Control.merged-ca bundle
    Package Control: Error downloading channel. URL error unknown error (_ssl.c:2228) downloading https://packagecontrol.io/channel_v3.json.
    Package Control: The dependency specified, bz2, is not available
    Package Control: Skipping automatic upgrade, last run at 2015-02-01 16:44:41, next run at 2015-    02-01 17:44:41 or after

**Comment by wbond** [comment]
Looking at the `_ssl` C source code, that implies an issue with the CA certs file. Looking at your debug log, it indicates the file path is `/home/axxe/.config/sublime-text-3/Packages/User/Package Control.merged-ca-    bundle` - I presume the spaces are from a copy-paste?

Could you check `/home/axxe/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle` and see what it contains?

**Comment by BenjaminSmith-cpe** [comment]
Same issue here on Suse Linux. 
Fresh install of ST3 build 3069 and package control. 

Package Control.merged-ca-bundle is empty.. any thoughts?

**Comment by BenjaminSmith-cpe** [comment]
Figured i'd try wget from a terminal -- results:
```
$wget https://packagecontrol.io
--2015-02-11 14:52:51--  https://packagecontrol.io/
Resolving <myproxy>.. <00.00.00.00>
Connecting to <myproxy>| <00.00.00.00>|:000... connected.
ERROR: cannot verify packagecontrol.io's certificate, issued by `/C=US/O=GeoTrust Inc./CN=GeoTrust EV SSL CA - G4':
  Unable to locally verify the issuer's authority.
ERROR: certificate common name `codexns.io' doesn't match requested host name `packagecontrol.io'.
To connect to packagecontrol.io insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
```

**Comment by wbond** [comment]
Your version of wget must be really old. The certificate is a multi-domain cert using subject alt name.

Most likely you don't have a CA cert bundle on your machine. Currently it looks in the locations listed at https://github.com/wbond/package_control/blob/master/package_control/ca_certs.py#L148:L156. Does your distro provide them in a different place?

**Comment by BenjaminSmith-cpe** [comment]
>Your version of wget must be really old.

Wget ver is 1.11.4, released in 2008... not too bad. This is coming from an enterprise Linux environment, to put things in perspective, FVWM is the officially supported WM. If you have a hunch it's 99 old environment problems, you're probably right.  

> Most likely you don't have a CA cert bundle on your machine.  Currently it looks in the locations listed at https://github.com/wbond/package_control/blob/master/package_control/ca_certs.py#L148:L156.

None of these paths exist in my environment, checked them all

> Does your distro provide them in a different place?

```
find /etc/ssh* -name "*.crt" -or -name "*.pem"
find /usr/ -name "*.crt" -or -name "*.pem"
find ~/ -name "*.crt" -or -name "*.pem"
```

All these turn up dry except some stuff in the python package directory. I do have a directory under ~/ssh2/ that contains .pub keys, including one for github.


===========
I'd guess the most important information is that the same setup worked with package control < ver 3.0. I also have ver 3.0+ installed on a windows machine and working in the same network, could that install provide  any information?

**Comment by wbond** [comment]
As mentioned in the 3.0 release notes (https://packagecontrol.io/news), PC is no longer in the business of distributing CA certs.

That is something best done by your operating system. There should be a package you can install that will provide an up-to-date list of CAs. Alternatively you can maintain your own certs in the `Package Control.user-ca-bundle`.

Unfortunately the SSL cert for PC will be a multi-domain cert moving forward. However, with the `ssl-linux` dependency I bootstrap for PC 3.0, neither wget or curl should be required any longer.

**Comment by BenjaminSmith-cpe** [comment]
> There should be a package you can install that will provide an up-to-date list of CAs
No root access in enterprise env... le sigh. However, I was able to copy the certificate from Windows and paste it into Package Control.user-ca-bundle. Everything seems to work well. 

Thanks for the quick response, and substantial contribution to open source software. Gratipay inbound :smile:

**Comment by wbond** [comment]
@axxehub Did you ever get to check your bundle file?

**Comment by wbond** [comment]
Cleaning up old issues for the 3.1 release. Feel free to open a new issue if you ever get to check into this.

**Comment by moisesluza** [comment]
@BenjaminSmith-cpe could you please explain the procedure you follow to copy the certificate from windows? I have the same problem as you with enterprise Suse Linux.

**Comment by wbond** [comment]
@moisesluza If you run Package Control on a windows machine it will generate `Packages/User/Package Control.merged-ca-bundle` with a combination of the exported system CA certs and the contents of `Packages/User/Package Control.user-ca-bundle`.

Alternatively you could grab some from the curl project (http://curl.haxx.se/docs/caextract.html) via https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt.

**Comment by BenjaminSmith-cpe** [comment]
sure, I'll have to do it tomorrow morning though... I'm studying for
midterms i'm taking today  :D

**Comment by moisesluza** [comment]
@wbond sorry took me a while to install sublime in my windows machine. I've copied the contents of Packages/User/Package Control.merged-ca-bundle to my sublime in linux but Packages/User/Package Control.user-ca-bundle is empty on windows even though I've tried like that and now im seeing this error:

Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation

**Comment by hailengc** [comment]
Well, struggling with this issue for a while, I made a workaround and it worked:
1. download this json file to you machine (for me, I just download it to /home/administrator), 
   you can dowload from browser or through command:
   wget https://packagecontrol.io/channel_v3.json --no-check-certificate
2. in sublime, Preferences->Package Settings->Package Controller -> Setting-User,
    paste below:
   {
	"installed_packages":
	[
		"Package Control"
	],
	"channels": [
		"/home/administrator/channel_v3.json"
	]
}

3. try ctrl+shift+p again, should load packages.

**Comment by wbond** [comment]
@hailengc By doing that, you may be downloading a file not from Package Control that may point to malicious code.

That is the reason Package Control does not allow disabling certificate checks. It is a dangerous concept when installing software.
