### ISSUE TITLE
Install Package can't find GhostText

### ISSUE THREAD

**Issue by seanf** [wbond/package_control#864]
GhostText is visible in the website (https://packagecontrol.io/packages/GhostText), but won't show up when I search for it.  I checked, and GhostText is *not* already installed.

debug log:

    DPI scale: 1.25
    startup, version: 3065 windows x64 channel: stable
    executable: /C/Program Files/Sublime Text 3/sublime_text.exe
    working dir: /C/Program Files/Sublime Text 3
    packages path: /C/Users/Sean/AppData/Roaming/Sublime Text 3/Packages
    state path: /C/Users/Sean/AppData/Roaming/Sublime Text 3/Local
    hardware concurrency: 8
    zip path: /C/Program Files/Sublime Text 3/Packages
    zip path: /C/Users/Sean/AppData/Roaming/Sublime Text 3/Installed Packages
    found 5 files for base name Default.sublime-keymap
    found 1 files for base name Default.sublime-mousemap
    found 37 files for base name Main.sublime-menu
    loading bindings
    loading pointer bindings
    found 1 files for base name Default.sublime-theme
    theme loaded
    app ready
    startup cache, total files: 318 cache hits: 318
    pre session restore time: 0.0936656
    using gamma: 1.9 (err: 81.5966)
    startup time: 0.161666
    first paint time: 0.176666
    launching: /C/Program Files/Sublime Text 3/plugin_host.exe
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_file_settings
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin Package Control.bootstrap
    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
        m = importlib.import_module(modulename)
      File "./importlib/__init__.py", line 90, in import_module
      File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 671, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "bootstrap in C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 35, in <module>
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 671, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "package_control.bootstrap in C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 21, in <module>
    ImportError: cannot import name downloader
    reloading plugin Package Control.Package Control
    loaded 857 snippets
    reloading plugin Superlime.Superlime
    reloading plugin SublimeREPL.__init__
    reloading plugin SublimeREPL.completions
    reloading plugin SublimeREPL.lang_integration
    reloading plugin SublimeREPL.run_existing_command
    reloading plugin SublimeREPL.sublimerepl
    reloading plugin SublimeREPL.sublimerepl_build_system_hack
    reloading plugin SublimeREPL.text_transfer
    plugins loaded
    Package Control: Skipping automatic upgrade, last run at 2015-02-03 20:49:03, next run at 2015-02-03 21:49:03 or after
    Package Control: Fetching list of available packages
      Platform: windows-x64
      Sublime Text Version: 3065
      Package Control Version: 2.0.0-alpha9
    Package Control: Download Debug
      URL: https://sublime.wbond.net/repositories.json
      Resolved IP: 50.116.34.243
      Timeout: 30
    Package Control: WinINet Debug Proxy
      proxy: 
      proxy bypass: 
      proxy username: 
      proxy password: 
    Package Control: WinINet HTTPS Debug General
      Server SSL Certificate:
        subject: ZtL8p1RCzFndzRrqxUKqA6bD5HjQv5Zb, US, sublime.wbond.net, GT52951423, See www.rapidssl.com/resources/cps (c)12, Domain Control Validated - RapidSSL(R), sublime.wbond.net
        issuer: US, "GeoTrust, Inc.", RapidSSL CA
        common name: sublime.wbond.net
        issue date: Mon, 07 Apr 2014 11:04:43 GMT
        expire date: Thu, 26 Feb 2015 19:13:18 GMT
    Package Control: WinINet HTTPS Debug Write
      GET /repositories.json HTTP/1.1
      If-Modified-Since: Tue, 03 Feb 2015 11:20:14 GMT
      Accept-Encoding: gzip,deflate
      User-Agent: Sublime Package Control v2.0.0-alpha9
      Host: sublime.wbond.net
      Connection: Keep-Alive
      Cache-Control: no-cache
    Package Control: WinINet HTTPS Debug Read
      HTTP/1.1 304 Not Modified
      Server: nginx
      Date: Tue, 03 Feb 2015 11:21:27 GMT
      Last-Modified: Tue, 03 Feb 2015 11:20:14 GMT
      Connection: keep-alive
      ETag: "54d0aeee-ec593"
    Package Control: Using cached content for https://sublime.wbond.net/repositories.json
    Package Control: Using "git_binary" from settings "C:/cygwin/bin/git.exe"
    Package Control: Using "git_binary" from settings "C:/cygwin/bin/git.exe"
    Package Control: Trying to execute command C:/cygwin/bin/git.exe fetch
    Package Control: Trying to execute command C:/cygwin/bin/git.exe log ..--ff/--commit
    Package Control: WinINet HTTPS Debug General
      Closing connection to sublime.wbond.net on port 443 after 1 request

**Comment by wbond** [comment]
From the error message in your log, it appears something is funky with your Package Control install. Please try following the directions at https://packagecontrol.io/docs/troubleshooting#Purging_Old_Versions to make sure you have a clean install of Package Control.

**Comment by seanf** [comment]
That did the trick, thanks!
