### ISSUE TITLE
Do something when selecting a package in "List Packages"

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#867]
Currently it just does nothing, which is ... kind of ... boring?

Anyway, here are a few ideas off the top of my head:
1. Open package site on packagecontrol.io
2. Open local package location (highlight .sublime-package file if "installed")
3. Open package homepage or issues

**Comment by yukulele** [comment]
for me it actually open package location

**Comment by r3volution11** [comment]
To expand on this it'd be great while looking at the install list if there were a shortcut to open the package site. 

Maybe I'm missing it but it's not documented any where and I tried a couple of common ones (ctrl+enter, option+enter).

**Comment by keith-hall** [comment]
I've created a PR (https://github.com/wbond/package_control/pull/1132) to fix the bug whereby it doesn't select the `.sublime-package` file in the `Installed Packages` folder.

However, I agree that there should be an option to instead go to the package's page on the packagecontrol website, as going to the package folder is already mainly covered by `Preferences -> Browse Packages` and PackageResourceViewer.
