### ISSUE TITLE
Search input bugs

### ISSUE THREAD

**Issue by callumlocke** [wbond/package_control#875]
1. type some text e.g. "abc"
2. hit cmd+A to select all, then quickly type some other text e.g. "123"

Instead of replacing the selected text, it gets appened, i.e. "abc123".

This happens only when you type quite fast. Affects Chrome on OS X, not tested in other browsers.

I'm also seeing characters randomly going missing from the middle of words as I type, which is harder to reproduce step-by-step, but is really annoying. I think these bugs are due to race conditions, where partial search request callbacks are refocusing (or just rewriting the value of) the search input.

**Comment by wbond** [comment]
Thanks for taking the time to submit an issue.

The website and issues are located at https://github.com/wbond/packagecontrol.io.

**Comment by wbond** [comment]
This is being tracked at https://github.com/wbond/packagecontrol.io/issues/42
