### ISSUE TITLE
Attribute Error in 0_package_control_loader.sublime-package

### ISSUE THREAD

**Issue by kans** [wbond/package_control#876]
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "02-bz2 in /Users/kans/Library/Application Support/Sublime Text 3/Installed Packages/0_package_control_loader.sublime-package", line 3, in <module>
AttributeError: 'module' object has no attribute 'add_dependency'

On OSX ST3 using master.

**Comment by wbond** [comment]
Could you try running the following from your Sublime Text console?

```python
from package_control import package_io
print(package_io.read_package_file('0_package_control_loader', '02-bz2.py'))
```

Also, can you execute the following from your terminal and paste the output?

```bash
cd /Users/kans/Library/Application\ Support/Sublime\ Text\ 3/Packages/Package\ Control/
git status
```

**Comment by kans** [comment]
>>> print(package_io.read_package_file('0_package_control_loader', '02-bz2.py'))

from package_control import sys_path
sys_path.add_dependency('bz2')

git status is clean - I'm on 4d179eb357d89c08ebf416c4aba4283a91af21dd which is the 3.0.1 tag (now 19 commits behind master)

For that matter, I just experienced a second strange behavior. PC was in an infinite loop updating packages - I only noticed because it was eating up half of a CPU.  Unfortunately, I killed sublime so I don't have a copy of the logs for you.

**Comment by wbond** [comment]
Something is really funky with your install. The `package_control.sys_path` module definitely has a function named `add_dependency()`.

Can you check and see if you have a file named `/Users/kans/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package` on your machine? It might be that you have two conflicting installs of Package Control.

**Comment by vaff** [comment]
I have the same problem.

**Comment by wbond** [comment]
@vaff Then please answer the questions asked.

**Comment by vaff** [comment]
Confirmed, I have that file

**Comment by wbond** [comment]
@vaff So you need to either delete `Installed Packages/Package Control.sublime-package` or `Packages/Package Control/`. Then try restarting Sublime Text.

**Comment by vaff** [comment]
That seams to resolve the conflict. The odd thing is, i just reinstalled sublime text and package control. I even removed the Application Support/Sublime Text 3/ folder

**Comment by vaff** [comment]
>>> from package_control import package_io
>>> print(package_io.read_package_file('0_package_control_loader', '02-bz2.py'))
False

Also seams to work correctly now.

**Comment by wbond** [comment]
@kans Can you check and see if you have both `/Users/kans/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package` and `/Users/kans/Library/Application Support/Sublime Text 3/Packages/Package Control/` on your machine?

**Comment by wbond** [comment]
@kans Nudge

**Comment by kans** [comment]
Sorry for the delay - this was the problem.  Thank you for helping me
diagnose something that was my own fault.

On Wednesday, February 25, 2015, Will Bond <notifications@github.com> wrote:

> @kans <https://github.com/kans> Can you check and see if you have both /Users/kans/Library/Application
> Support/Sublime Text 3/Installed Packages/Package Control.sublime-package
> and /Users/kans/Library/Application Support/Sublime Text
> 3/Packages/Package Control/ on your machine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control/issues/876#issuecomment-76015282>
> .
>


-- 
-Matt

**Comment by wbond** [comment]
It is good to have confirmation. I will add some checks to `Package Control.py` to make sure a user doesn't have both the packed and unpacked versions.

**Comment by wbond** [comment]
As of 21bf49830d36111c9f9d0f9a2fdaa405f9ee257b, Package Control will now detect if users have PC installed packed and unpacked and present instructions on how to fix it.
