### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by Mitchell-Riley** [wbond/package_control#880]
Keeps giving me this error window, even after uninstalling and re-installing Package Control:

```
Unable to download select-windows. Please view the console for more details.
Unable to download bz2. Please view the console for more details
```

Debug Log:

```
Package Control: Installing 2 missing dependencies
Package Control: Fetching list of available packages
  Platform: windows-x32
  Sublime Text Version: 2221
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Tue, 16 Dec 2014 19:00:00 GMT
    expire date: Thu, 29 Oct 2015 19:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: gzip,deflate
  If-Modified-Since: Mon, 16 Feb 2015 21:40:03 GMT
  User-Agent: Package Control v3.0.1
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Mon, 16 Feb 2015 21:50:34 GMT
  Content-Type: application/json
  Last-Modified: Mon, 16 Feb 2015 21:50:03 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Caching https://packagecontrol.io/channel_v3.json in C:\Documents and Settings\Mitchell\Application Data\Sublime Text 2\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
Package Control: Download Debug
  URL: https://codeload.github.com/codexns/sublime-select-windows/zip/1.0.0
  Resolved IP: 192.30.252.147
  Timeout: 30
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/codexns/sublime-select-windows/zip/1.0.0.
Package Control: Download Debug
  URL: https://codeload.github.com/codexns/sublime-select-windows/zip/1.0.0
  Resolved IP: 192.30.252.147
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at C:\Documents and Settings\Mitchell\Application Data\Sublime Text 2\Packages\User\Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
  CA certs file at C:\Documents and Settings\Mitchell\Application Data\Sublime Text 2\Packages\User\Package Control.merged-ca-bundle
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate (_ssl.c:480: error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm)) downloading https://codeload.github.com/codexns/sublime-select-windows/zip/1.0.0.
error: Package Control

Unable to download select-windows. Please view the console for more details.
Package Control: Fetching list of available packages
  Platform: windows-x32
  Sublime Text Version: 2221
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0
  Resolved IP: 192.30.252.147
  Timeout: 30
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
  CA certs file at C:\Documents and Settings\Mitchell\Application Data\Sublime Text 2\Packages\User\Package Control.merged-ca-bundle
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate (_ssl.c:480: error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm)) downloading https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0.
error: Package Control

Unable to download bz2. Please view the console for more details.
Package Control: Skipping automatic upgrade, last run at 2015-02-16 16:43:01, next run at 2015-02-16 17:43:01 or after
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
```

**Comment by wbond** [comment]
Can you check and see what files are in the folder `C:\Documents and Settings\Mitchell\Application Data\Sublime Text 2\Packages\0_package_control_loader\`.

Also check if `C:\Documents and Settings\Mitchell\Application Data\Sublime Text 2\Packages\ssl-windows\` exists.

**Comment by sketchpad** [comment]
Looks like I'm experiencing the same issue.

NB: I'm on Windows XP (yes, really) so understand this may be an issue "not worth fixing".

**Files in `\Packages\0_package_control_loader\`**
```
01-ssl-windows.py
01-ssl-windows.pyc
02-bz2.py
02-bz2.pyc
02-select-windows.py
02-select-windows.pyc
dependency-metadata.json
```

The `\Packages\ssl-windows\` directory exists, and contains `\st2_windows_x32\_ssl.pyd` and a 64bit version too.

If you want the entire debug log can post that -- didn't want to flood Mitchell's thread. 

```
Platform: windows-x32
Sublime Text Version: 2221
Package Control Version: 3.0.1

Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/facelessuser/BracketHighlighter/zip/st2-2.2.0.
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate (_ssl.c:480: error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm)) downloading https://codeload.github.com/facelessuser/BracketHighlighter/zip/st2-2.2.0.
error: Package Control
```

**Comment by wbond** [comment]
@sketchpad No, the more info I can get, the better. Can you execute this in the Sublime Text console and paste the output?

```python
import sys; sys.path
```

The error you two are running into is, I believe, that codeload.github.com is using a cert signed with sha2, but for some reason the patched `_ssl.pyd` I ship for Sublime Text 2 on Windows must not be loading properly for you.

Now, packagecontrol.io uses a sha2 cert also, but WinINet is able to connect to it without trouble, so it is not falling back to the urllib downloader, which uses the python ssl module.

For @sketchpad, it appears you are missing the `00-package_control.py` file, which is what enables the other loaders to work properly. It is likely that this is preventing `01-ssl-windows.py` from properly injecting the `_ssl.pyd` into `sys.path`. The current version of Package Control on the master branch, `3.0.2-beta` should fix this. If you run the *Add Repository* command from the command palette and paste `https://sublime.wbond.net/prerelease/packages.json`, then upgrade Package Control, hopefully it should resolve the issue for you.

**Comment by FichteFoll** [comment]
@sketchpad, you also need to add `"Package Control"` to the `install_prereleases` array of your user settings, e.g. `"install_prereleases": ["Package Control"]`.

**Comment by wbond** [comment]
Oh, good call @FichteFoll, thank you!

**Comment by sketchpad** [comment]
Excellent! Thanks – all working again, much appreciated :)

Here's the other info for reference:

First run of `import sys; sys.path` was:

 `['python26.zip', '.', 'C:\\Program Files\\Sublime Text 2']`

Now it displays:

 `['C:\\DOCUME~1\\SKETCH~1\\APPLIC~1\\SUBLIM~2\\Packages\\SELECT~1\\ST2_WI~1', 'C:\\DOCUME~1\\SKETCH~1\\APPLIC~1\\SUBLIM~2\\Packages\\SSL-WI~1\\ST2_WI~1', 'python26.zip', '.', 'C:\\DOCUME~1\\SKETCH~1\\APPLIC~1\\SUBLIM~2\\Packages\\bz2\\ST2_WI~1', 'C:\\Program Files\\Sublime Text 2']`

And I now have the `00-package_control.py` file.

**Comment by Mitchell-Riley** [comment]
```C:\Documents and Settings\Mitchell\Application Data\Sublime Text 2\Packages\ssl-windows\``` exists.

Contents of ***\Packages\0_package_control_loader\***

```00-package_control.py
00-package_control.pyc
dependency-metadata.json```

sys.path:
```['python26.zip', '.']```

**Comment by wbond** [comment]
@Mitchell-Riley Please follow the directions from https://github.com/wbond/package_control/issues/880#issuecomment-74680194 and https://github.com/wbond/package_control/issues/880#issuecomment-74684346 to install PC 3.0.2-beta. That should fix the issue for you.

**Comment by Mitchell-Riley** [comment]
Uninstalling PC via the "Package Control: Remove Package" and reinstalling actually fixed the error.

Thanks for your help!

**Comment by daumie** [comment]
['/home/daumie/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0', '/opt/sublime_text', '/opt/sublime_text/python3.3.zip', '/home/daumie/.config/sublime-text-3/Packages']

**Comment by kanekko** [comment]
HI guys, I have the same issue of first post from @mitchr =S
