### ISSUE TITLE
Allow primary usage of Urlib instead of WinInet

### ISSUE THREAD

**Issue by KuttKatrea** [wbond/package_control#884]
Please, add an option to choose whether to use WinInet or Urlib in windows. I am behind a firefall and use a proxy for specific things. Changing the global system proxy is not an option. 
But that makes Package Control painfully slow, because in each request it has first to fail because of WinInet and just then make the request with Urllib.

Or at least, make it "remember" that WiInet failed before and use Urlib instead in subsequent requests.

**Comment by wbond** [comment]
Good idea

**Comment by wbond** [comment]
As of dc7221f466275f1052c515032cf38e29fe905c00 there is a new setting `downloader_precedence` that allows setting the preferred downloaders for each platform.
