### ISSUE TITLE
HTTP exception InvalidCertificateException, Unable to download bz2

### ISSUE THREAD

**Issue by slambert** [wbond/package_control#892]
Running Sublime Text build 3065
Using most recent Package Control

This is what I get from the console:

`Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0.
error: Package Control`

`Unable to download bz2. Please view the console for more details.`

### Debug log:

    startup, version: 3065 osx x64 channel: stable
    executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
    working dir: /
    packages path: /Users/steve/Library/Application Support/Sublime Text 3/Packages
    state path: /Users/steve/Library/Application Support/Sublime Text 3/Local
    hardware concurrency: 8
    zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
    zip path: /Users/steve/Library/Application Support/Sublime Text 3/Installed Packages
    found 3 files for base name Default.sublime-keymap
    found 1 files for base name Default.sublime-mousemap
    found 2 files for base name Main.sublime-menu
    loading bindings
    loading pointer bindings
    found 1 files for base name Default.sublime-theme
    theme loaded
    app ready
    startup cache, total files: 169 cache hits: 169
    pre session restore time: 0.240923
    using gpu buffer for window
    using gamma: 2 (err: 6.9282)
    first paint time: 0.310127
    startup time: 0.318255
    launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_file_settings
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin Package Control.bootstrap
    reloading plugin Package Control.Package Control
    loaded 837 snippets
    plugins loaded
    Package Control: Installing 1 missing dependency
    Package Control: Fetching list of available packages
      Platform: osx-x64
      Sublime Text Version: 3065
      Package Control Version: 3.0.1
    Package Control: Download Debug
      URL: https://packagecontrol.io/channel_v3.json
      Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
      Resolved IP: 50.116.33.29
      Timeout: 30
    Package Control: Urllib Debug Proxy
      http_proxy: 
      https_proxy: 
      proxy_username: 
      proxy_password: 
    Package Control: Found previously exported CA bundle at /Users/steve/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
    Package Control: Urllib HTTPS Debug General
      Connecting to packagecontrol.io on port 443
    Package Control: Urllib HTTPS Debug General
      Connecting to packagecontrol.io on port 443
      CA certs file at /Users/steve/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
      Successfully upgraded connection to packagecontrol.io:443 with SSL
      Using TLSv1/SSLv3 with cipher DHE-RSA-AES256-SHA
      Server SSL certificate:
        subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
        subject alt name: dev.codexns.io, rc.codexns.io, packagecontrol.io, wbond.net, codexns.io
        expire date: Oct 29 23:59:59 2015 GMT
      Certificate validated for packagecontrol.io
    Package Control: Urllib HTTPS Debug Write
      GET /channel_v3.json HTTP/1.1
      User-Agent: Package Control v3.0.1
      If-Modified-Since: Sun, 01 Mar 2015 22:20:03 GMT
      Accept-Encoding: gzip,deflate
      Host: packagecontrol.io
      Connection: Keep-Alive
    Package Control: Urllib HTTPS Debug Read
      HTTP/1.1 304 Not Modified
      Server: nginx
      Date: Sun, 01 Mar 2015 22:23:12 GMT
      Last-Modified: Sun, 01 Mar 2015 22:20:03 GMT
      Connection: keep-alive
      ETag: "54f39093-1e2be0"
      Strict-Transport-Security: max-age=15552000
    Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/steve/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
    Package Control: Download Debug
      URL: https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0
      Resolved IP: 192.30.252.144
      Timeout: 30
    Package Control: Urllib Debug Proxy
      http_proxy: 
      https_proxy: 
      proxy_username: 
      proxy_password: 
    Package Control: Found previously exported CA bundle at /Users/steve/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
    Package Control: Urllib HTTPS Debug General
      Connecting to codeload.github.com on port 443
    Package Control: Urllib HTTPS Debug General
      Connecting to codeload.github.com on port 443
      CA certs file at /Users/steve/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
    Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0.
    error: Package Control

    Unable to download bz2. Please view the console for more details.
    Package Control: Skipping automatic upgrade, last run at 2015-03-01 17:06:06, next run at 2015-03-01 18:06:06 or after
    Package Control: Urllib HTTPS Debug General
      Closing connection to packagecontrol.io on port 443 after 1 request

**Comment by FichteFoll** [comment]
Please see the similar issues and if the proposed solutions work for you: https://github.com/wbond/package_control/issues/880, #885

**Comment by slambert** [comment]
Hi, looked through those and some others. #880 is for Windows and involved reinstalling, which I did try. #885 is for Linux but I extrapolated some. I don't have anything in a ~/.config folder for Sublime Text and don't have this directory `/usr/lib/ssl/certs/ca-certificates.crt`.

**Comment by slambert** [comment]
Ok, solved this myself. I had certificate issues. Eventually downloaded and re-installed the DigiCert High Assurance EV Root CA [as per this superuser post](https://superuser.com/questions/605900/why-wont-os-x-trust-githubs-ssl-certificate). All better now.

**Comment by heroprairievole** [comment]
Similar symptoms, different solution: the problem was the proxy as Sublime doesn't support SNI which is necessary to work with a transparent proxy. Ask your sysadmin to change config accordingly.

**Comment by LandisTwo** [comment]
i was only able to overcome this month old issue by adding the following to Preferences > Package Settings > Package Control > Settings - User:
(urllib and wget, wasn't getting it done)
```
"downloader_precedence":
	{
		"linux":
		[
			"curl"
		]
	},
```
ps, i know this issue is closed, but i may help someone.

**Comment by NikKovIos** [comment]
For mac users

```
"downloader_precedence":
	{
		"osx":
		[
			"curl"
		]
	},
```

or https://github.com/wbond/package_control/issues/1334#issuecomment-454413635

**Comment by ElectricFeet** [comment]
Thanks @NikKovIos This worked a treat for me!
