### ISSUE TITLE
how to uninstall Package Control ?

### ISSUE THREAD

**Issue by Siddhant** [wbond/package_control#894]
I was perusing the docs, but couldn't find any way on how to cleanly and properly remove Package Control. Can you please add some documentation for this ? Thanks.

**Comment by FichteFoll** [comment]
Do you just want to remove the package or also remove all the packages it "controls"?

If the former, it's basically the first few steps of the ["Purging old versions" guide](https://packagecontrol.io/docs/troubleshooting#Purging_Old_Versions). I think this could be improved though.

**Comment by Siddhant** [comment]
Ah! I was searching for the phrases 'uninstall' and 'remove' but did not think of searching for 'purging'.
Could you consider adding a phrase 'uninstall' somwwhere so that a search result for 'uninstall' points us to the purging guide?

In my experience, adding the instructions to uninstall on the same page whcih has installation instructions proves very helpful. Can you consider adding uninstall instruction to [ installation instructions](https://packagecontrol.io/installation) itself?

**Comment by wbond** [comment]
There is a repo for the website at https://github.com/wbond/packagecontrol.io.

**Comment by FichteFoll** [comment]
@wbond how about a command to remove package control itself? Since Python plugins are not unloaded immediately this should be possible and would improve the "purging" procedure as well.

**Comment by wbond** [comment]
I'm on holiday right now, so I'm not going to put much time into this, but I believe you should be able to use the Uninstall Package command to uninstall Package Control. I would consider it a bug if you can select it, but the uninstall fails.

**Comment by FichteFoll** [comment]
Oh, fancy, I though PC was excluded from the remove package list for some reason. In that case there is probably nothing to be done here.

**Comment by wbond** [comment]
Well, it seems adding documentation would be the logical step, but that needs to go on the website repo.

**Comment by wbond** [comment]
This enhancement is now being tracked at https://github.com/wbond/packagecontrol.io/issues/44
