### ISSUE TITLE
Consider using KEEP_OPEN_ON_FOCUS_LOST for quick panels

### ISSUE THREAD

**Issue by Narretz** [wbond/package_control#895]
Since Build 3070, there's a new flag for quick panels:
```
API: Window.show_quick_panel() now accepts the flag sublime.KEEP_OPEN_ON_FOCUS_LOST
```

This can be very useful for package control. E.g. when you have the list with installed packages or available packages open, and want to check something real quick in the browser, when you go back you have to reopen everything. Especially annoying for the list available packages.

Thanks for the great work!

**Comment by FichteFoll** [comment]
Since Will was the one to open the issue in the first place (https://github.com/SublimeTextIssues/Core/issues/381), I'm sure he'd love to use it. Actually, since he's on vacation I'll just submit a PR for it.
