### ISSUE TITLE
packagecontrol.io is down

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [wbond/package_control#901]
I'm not sure if this is the right place, but considering wbond is also the owner of the domain and the url, I want to point out that `packagecontrol.io` is down.

**Comment by willtownes** [comment]
also down for me. Blocks me from being able to install/ update packages. Does anyone know if there are mirrors for package control or alternative ways to run it?

**Comment by KrisSiegel** [comment]
I came here to post the same-thing. Seems like the most appropriate place to me. May be due to the linode maintenance ongoing (http://status.linode.com/).

**Comment by Fire-Dragon-DoL** [comment]
@KrisSiegel Thanks a lot, that gives me some hope! It's embarassing when this happens the only moment when you needed it (I didn't install any new package for months)

**Comment by ferreiravinicius** [comment]
@Fire-Dragon-DoL Same here, lol. I just installed a new distro today then now I cant install my sublime packages, happens.

**Comment by megadr01d** [comment]
@Fire-Dragon-DoL Well I haven't used Package Control in years (been using Nettuts-Fetch to get my packages) and the minute I decide to reinstall Package Manager, I'm able to install some packages and suddenly it stopped working. Murphy's Law at its best.

I thought I was blocked from wbond's server for installing more than a dozen packages in a row, but Down For Everyone was assuring.

**Comment by ifewalter** [comment]
As @KrisSiegel said, It's probably due to the lined maintenance currently on-going on all their servers.
Funniest thing is the server is responding to pings. /Shurgs/. Perhaps package control server need some sort of re-init scripts to run, (perhaps not automated?)

**Comment by varatep** [comment]
Just when I wanted to add on some linters :frowning:

**Comment by megadr01d** [comment]
It's up again! I saw it first.

**Comment by ifewalter** [comment]
@megadr01d Yay you.

**Comment by megadr01d** [comment]
And now I forgot what package I wanted to install...  😳

**Comment by mikecarr** [comment]
it is down again, is this due to linode again?

**Comment by mosleim** [comment]
down again??

**Comment by ashwinkshenoy** [comment]
yup it down...

**Comment by OlivierCuyp** [comment]
It seems it is more than 23h it is down, I have seen other older post telling it was down...

**Comment by palfrey** [comment]
Still down....

**Comment by jferiante** [comment]
there's thousands of users that can't install sublime text packages now..... :-1:

**Comment by mokico** [comment]
It's probably a problem with Linode http://status.linode.com looks like they're having some issues.

**Comment by KrisSiegel** [comment]
There have been a few issues as of late with attack's on linode and its availability isn't as great as many other providers.

Might be time to move this thing to a new provider and use at least two regions if we want it to stay up.

**Comment by skycoder-official** [comment]
Damn... just when I wanted to install some packages

**Comment by Fire-Dragon-DoL** [comment]
It's fun because you don't install anything for months, than the day you install it, goes down, lol (I'm fine today, no package needed)

**Comment by skycoder-official** [comment]
@Fire-Dragon-DoL  Lmao ikr

**Comment by sainoba** [comment]
Still down :(

**Comment by darkred** [comment]
It's up again!

**Comment by skycoder-official** [comment]
Yayy :D

**Comment by Kevin-Prichard** [comment]
packagecontrol.io appears to be down.  Given how reliant we all are on this system, is there something we can do to help keep the service running?  Distributed hosting sound interesting?

**Comment by jay3d** [comment]
It would be nice to provide some mirror, because it's down again as of today...

**Comment by KrisSiegel** [comment]
Why isn't this simply bundled as part of Sublime now anyway? The creator now works on Sublime itself and this is a huge missing feature from the base package. It should be bundled and the service(s) supporting it should be behind a load balancer in multiple regions.

**Comment by szymons99** [comment]
Developers need to work at Sunday :D

Packagecontrol.io still down...

**Comment by thaipirate** [comment]
found this thread checking if it was just down for me... nope, everyone ok... I noticed it was down earlier, then it came back on but as i type now, it appears to be down again...

**Comment by kumarravisingh** [comment]
Was using first time. . bad luck :( [https://isitup.org/packagecontrol.io](https://isitup.org/packagecontrol.io)

**Comment by DenJohX** [comment]
down again?

**Comment by FeliciousX** [comment]
it's down for me

**Comment by nvolakis** [comment]
Yep, it is still down. Fingers crossed that will be online soon enough

**Comment by maheshj567** [comment]
Seems to be working now...

**Comment by RopoMen** [comment]
...and down again.

**Comment by RopoMen** [comment]
I agree with @KrisSiegel I and many others has paid Sublime Text license and package control is essential feature.

**Comment by wbond** [comment]
There was a hardware issue, but Linode was quick to resolve it.

**Comment by hardikns** [comment]
Its down again?

**Comment by SJS-ONE** [comment]
Yup

**Comment by wenbert** [comment]
Weird timing. I was just looking for a theme.
I thought it was just my ISP...

**Comment by sphinxaf** [comment]
down down down

**Comment by 0xFEEDC0DE64** [comment]
still down -.-

**Comment by moham96** [comment]
Down for me too

**Comment by wbond** [comment]
See https://github.com/wbond/package_control/issues/1323#issuecomment-357670341.

**Comment by qjnr** [comment]
> Weird timing. I was just looking for a theme.
> I thought it was just my ISP...

Exactly the same for me, it's still down

**Comment by ayushlodhi11** [comment]
Down again!!

**Comment by wbond** [comment]
@ayushlodhi11 Back up!
