### ISSUE TITLE
Can't install package control in Sublime 3

### ISSUE THREAD

**Issue by tagotaco** [wbond/package_control#902]
Hi there

I am newbie here and also with Sublime 3. I tried to install the package control but when I choose 'install package', then there a message box appears "There are no packages availible for installation".

I tried to look around on internet but I couldn't find any further help. Maybe you could help me with this?

DPI scale: 1
startup, version: 3065 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Chayanee/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Chayanee/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Chayanee/AppData/Roaming/Sublime Text 3/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 0 total files: 169 cache hits: 168
pre session restore time: 0.0873633
startup time: 0.106363
first paint time: 0.107363
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.bootstrap
loaded 837 snippets
reloading plugin Package Control.Package Control
reloading plugin 0_package_control_loader.00-package_control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-03-09 13:16:44, next run at 2015-03-09 14:16:44 or after
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. (errno 12045) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. (errno 12045) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

Thank you very much for all the helps in advance! :-)
Regards,
tagotaco

**Comment by wbond** [comment]
It seems that your machine does not trust the Certificate Authority that has signed the secure certificate for `packagecontrol.io`. By default Package Control tries to use WinINet, which is controlled via the Internet Explorer settings. If you use IE and try connecting to https://packagecontrol.io, that should help you diagnose why things aren't working.

**Comment by vasil-pashov** [comment]
Hi, I have the same issue and IE won't open https://packagecontrol.io.
