### ISSUE TITLE
ignore_vcs_packages should be a list setting as well, like install_prereleases

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#904]
Due to 56e3afac02f86a1494bfdd81c8b9e5ae6a9c5add it was brought to my attention again that `ignore_vcs_packages` is a boolean and only allows global enabling or disabling. Since you might want to apply this to certain packages only, it should probably be a list.

However, the old feature to globally disable (or enable) it is still useful, so the boolean functionality should be preserved.

**Comment by wbond** [comment]
Implemented in 0000c10bebfe788ea4ee6c0e2648d84fc1b31f72
