### ISSUE TITLE
Can't install in ST3 portable

### ISSUE THREAD

**Issue by SanderElias** [wbond/package_control#905]
Hi, on a certain moment I noticed my package manager was gone.
So I tried to re-install it, but to no avail. If I do the manual install, the manager is not there,
If I do the C&P install I get: 174110, and that's it.

here is a bootstraping dump, including a C&P install.
DPI scale: 1
startup, version: 3075 windows x64 channel: dev
executable: /E/sublime/sublime_text.exe
working dir: /E/jdKapsalon
packages path: /E/sublime/Data/Packages
state path: /E/sublime/Data/Local
zip path: /E/sublime/Packages
zip path: /E/sublime/Data/Installed Packages
pre session restore time: 0.313902
loading dictionary Packages/Language - English/en_US.dic
startup time: 0.410903
first paint time: 0.434903
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin AAAPackageDev.AAA
[AAAPackageDev] Added E:\sublime\Data\Installed Packages\AAAPackageDev.sublime-package\Lib to sys.path.
[AAAPackageDev] Added E:\sublime\Data\Installed Packages\AAAPackageDev.sublime-package\Lib\_py3 to sys.path.
reloading plugin AAAPackageDev.build_sys_dev
reloading plugin AAAPackageDev.commands_file_dev
reloading plugin AAAPackageDev.completions_dev
reloading plugin AAAPackageDev.file_conversion
reloading plugin AAAPackageDev.package_dev
reloading plugin AAAPackageDev.scope_data
reloading plugin AAAPackageDev.settings_dev
reloading plugin AAAPackageDev.snippet_dev
reloading plugin AAAPackageDev.sublime_inspect
reloading plugin AAAPackageDev.syntax_def_dev
reloading plugin AngularJS.AngularJS-sublime-package
reloading plugin AngularJS.jscompletions
reloading plugin AngularJS.message
reloading plugin AngularJS.sublime_commands
reloading plugin AngularJS.viewlocation
reloading plugin AutoHotkey.ahkexec
reloading plugin AutoItScript.autoitbuild
reloading plugin Emmet.emmet-plugin
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Levels.levels_plugin
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin SCSS.scss_completions
reloading plugin tern_for_sublime.tern
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: eslint activated: C:\Users\sander.ESO\AppData\Roaming\npm\eslint.cmd 
PyV8: Creating new thread
Levels: Creating thread
Levels: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: No need to update PyV8
Levels: You have the most recent PyV8 binary

import urllib.request,os,hashlib; h = 'eb2297e1a458f27d836c04bb0cbaf282' + 'd0e7a3098092775ccb37ca9d6b2e4b7d'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
174110

**Comment by wbond** [comment]
Check Preferences > Settings – User and see if it is in `ignored_packages`.

**Comment by wbond** [comment]
I'm pretty certain this is the issue. let me know if it isn't.

**Comment by SanderElias** [comment]
It was indeed. I wonder how that happened? well, at least i now know where to look!
Thanks
