### ISSUE TITLE
Package Control Messages opens only showing the last line

### ISSUE THREAD

**Issue by fredrikpaues** [wbond/package_control#907]
Every time a Package Control message opens, it shows only the last line of the message. That is, it opens scrolled down. Say, if there are 19 rows in a message then I see only the 19:th row.

![image](https://cloud.githubusercontent.com/assets/1590227/6651399/d7b3248c-ca40-11e4-9c47-8c1e26d7a22e.png)

    SublimeLinter: WARNING: chktex deactivated, cannot locate 'chktex' 
    Writing file /C/Users/frpa8185/Dropbox/Listacular/Idag.txt with encoding UTF-8 (atomic)
    Package Control: Fetching list of available packages
      Platform: windows-x64
      Sublime Text Version: 3065
      Package Control Version: 3.0.1
    Package Control: Download Debug
      URL: https://packagecontrol.io/channel_v3.json
      Resolved IP: 50.116.33.29
      Timeout: 30
    Package Control: WinINet Debug Proxy
      proxy: 
      proxy bypass: 
      proxy username: 
      proxy password: 
    Package Control: WinINet HTTPS Debug General
      Server SSL Certificate:
        subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
        issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
        common name: codexns.io
        issue date: Wed, 17 Dec 2014 01:00:00 GMT
        expire date: Fri, 30 Oct 2015 00:59:59 GMT
    Package Control: WinINet HTTPS Debug Write
      GET /channel_v3.json HTTP/1.1
      Accept-Encoding: bzip2,gzip,deflate
      If-Modified-Since: Sat, 14 Mar 2015 10:40:04 GMT
      If-None-Match: "55041004-30b49"
      User-Agent: Package Control v3.0.1
      Host: packagecontrol.io
      Connection: Keep-Alive
      Cache-Control: no-cache
    Package Control: WinINet HTTPS Debug Read
      HTTP/1.1 304 Not Modified
      Server: nginx
      Date: Sat, 14 Mar 2015 10:47:33 GMT
      Content-Type: application/json
      Last-Modified: Sat, 14 Mar 2015 10:40:04 GMT
      Connection: keep-alive
      ETag: "55041004-30b49"
      Content-Encoding: bzip2
      Vary: Accept-Encoding
      Strict-Transport-Security: max-age=15552000
    Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from C:\Users\frpa8185\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
    Package Control: WinINet HTTPS Debug General
      Closing connection to packagecontrol.io on port 443 after 1 request
    Package Control: Fetching list of available packages
      Platform: windows-x64
      Sublime Text Version: 3065
      Package Control Version: 3.0.1
    Package Control: Fetching list of available packages
      Platform: windows-x64
      Sublime Text Version: 3065
      Package Control Version: 3.0.1
    ignored packages updated to: [knitr, Vintage, SublimeLinter-csslint]
    found 1 files for base name Default.sublime-theme
    reloading Packages/User/Package Control.sublime-settings
    Package Control: Fetching list of available packages
      Platform: windows-x64
      Sublime Text Version: 3065
      Package Control Version: 3.0.1
    theme loaded
    Package Control: Download Debug
      URL: https://codeload.github.com/SublimeLinter/SublimeLinter-csslint/zip/1.1.6
      Resolved IP: 192.30.252.147
      Timeout: 30
    reloading Packages/User/Preferences.sublime-settings
    found 1 files for base name Default.sublime-theme
    theme loaded
    Package Control: WinINet Debug Proxy
      proxy: 
      proxy bypass: 
      proxy username: 
      proxy password: 
    Package Control: WinINet HTTPS Debug General
      Server SSL Certificate:
        subject: US, California, San Francisco, "GitHub, Inc.", *.github.com
        issuer: US, DigiCert Inc, www.digicert.com, DigiCert SHA2 High Assurance Server CA
        common name: *.github.com
        issue date: Tue, 08 Apr 2014 02:00:00 GMT
        expire date: Wed, 12 Apr 2017 14:00:00 GMT
    Package Control: WinINet HTTPS Debug Write
      GET /SublimeLinter/SublimeLinter-csslint/zip/1.1.6 HTTP/1.1
      Accept-Encoding: bzip2,gzip,deflate
      User-Agent: Package Control v3.0.1
      Host: codeload.github.com
      Connection: Keep-Alive
      Cache-Control: no-cache
    Package Control: WinINet HTTPS Debug Read
      HTTP/1.1 200 OK
      Access-Control-Allow-Origin: https://render.githubusercontent.com
      Content-Security-Policy: default-src 'none'
      X-XSS-Protection: 1; mode=block
      X-Frame-Options: deny
      X-Content-Type-Options: nosniff
      Strict-Transport-Security: max-age=31536000
      Vary: Authorization,Accept-Encoding
      ETag: "9f116b8ed6bbc028ba0575b9cf140f164ed4efab"
      Content-Type: application/zip
      Content-Disposition: attachment; filename=SublimeLinter-csslint-1.1.6.zip
      Date: Sat, 14 Mar 2015 10:49:03 GMT
      Connection: close
    Package Control: Skipping cache since the response is a zip file
    Package Control: Download Debug
      URL: https://packagecontrol.io/submit?operation=install&version=1.1.6&package=SublimeLinter-csslint&package_control_version=3.0.1&sublime_version=3065&sublime_platform=windows
      Resolved IP: 50.116.33.29
      Timeout: 30
    Package Control: WinINet Debug Proxy
      proxy: 
      proxy bypass: 
      proxy username: 
      proxy password: 
    Package Control: WinINet HTTPS Debug General
      Server SSL Certificate:
        subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
        issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
        common name: codexns.io
        issue date: Wed, 17 Dec 2014 01:00:00 GMT
        expire date: Fri, 30 Oct 2015 00:59:59 GMT
    Package Control: WinINet HTTPS Debug Write
      GET /submit?operation=install&version=1.1.6&package=SublimeLinter-csslint&package_control_version=3.0.1&sublime_version=3065&sublime_platform=windows HTTP/1.1
      Accept-Encoding: bzip2,gzip,deflate
      User-Agent: Package Control v3.0.1
      Host: packagecontrol.io
      Connection: Keep-Alive
      Cache-Control: no-cache
    Package Control: WinINet HTTPS Debug Read
      HTTP/1.1 200 OK
      Server: nginx
      Date: Sat, 14 Mar 2015 10:49:03 GMT
      Content-Type: application/json
      Transfer-Encoding: chunked
      Connection: keep-alive
      Vary: Accept-Encoding
      X-App-Version: 1.1.1
      Strict-Transport-Security: max-age=15552000
      Content-Encoding: gzip
    reloading Packages/User/Package Control.sublime-settings
    ignored packages updated to: [knitr, Vintage]
    found 1 files for base name Default.sublime-theme
    reloading plugin SublimeLinter-csslint.linter
    SublimeLinter: csslint linter reloaded 
    theme loaded
    reloading Packages/User/Package Control.sublime-settings
    reloading Packages/User/Preferences.sublime-settings
    found 1 files for base name Default.sublime-theme
    theme loaded
    reloading Packages/User/Preferences.sublime-settings
    found 1 files for base name Default.sublime-theme
    theme loaded
    Package Control: WinINet HTTPS Debug General
      Closing connection to packagecontrol.io on port 443 after 1 request
    Package Control: WinINet HTTPS Debug General
      Closing connection to codeload.github.com on port 443 after 1 request

**Comment by wbond** [comment]
This should be fixed in master, and will be part of the 3.1.0 release next week.

**Comment by FichteFoll** [comment]
Actually, this particular issue is a bug in Sublime Text that was fixed in the dev channel, but 3.1.0 has a workaround for it.

See also #886.
