### ISSUE TITLE
provide a list of packages in json

### ISSUE THREAD

**Issue by syswow** [wbond/package_control#908]
Hi,
Thanks for this awesome project. :smile: 

When I want to disable several packages, I don't know the exact name of package, I have to disable them one by one. Can package_control provide a list of packages in json format or others better functions that batch manage packages ?

**Comment by FichteFoll** [comment]
So, uhm, I suppose you found the `installed_packages` setting?

**Comment by syswow** [comment]
@FichteFoll  Yeah, you got it. `installed_packages` works very well.  Thanks  again. :smile:
