### ISSUE TITLE
PackageControl takes 7 minutes to load in ST3

### ISSUE THREAD

**Issue by atstockland** [wbond/package_control#910]
If I go Preferences/PackageControl/InstallPackage...it takes between 5-8 minutes to load.  And, while its thinking...SP3 is so slow its basically unusable.

**Comment by wbond** [comment]
You forgot to include a debug log.

**Comment by wbond** [comment]
@atstockland Please provide a debug log.

**Comment by atstockland** [comment]
How do I do that?


Adam Stockland

**Comment by wbond** [comment]
https://packagecontrol.io/docs/settings

**Comment by atstockland** [comment]
In grabbing this debug log…Package control took 4 minutes from “Install Package” to the list of packages to appear.

Thanks

startup time: 2.39813
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
unexpected rule type, was expecting one of match, include, begin or patterns, got: {comment: Note how all @rules are prefixed.}
unknown include #string-double
unknown include #string-single
unknown include #string-single
unknown include #string-double
unknown include #media-query-list
unknown include #media-query-list
loaded 891 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin BeautifyRuby.beautify_ruby
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin ExportHtml.ExportBbcode
reloading plugin ExportHtml.ExportHtml
reloading plugin ExportHtml.HtmlAnnotations
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Instacode.instacode
reloading plugin LESS.less_completions
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin RuboCop.constants
reloading plugin RuboCop.file_tools
reloading plugin RuboCop.rubocop_command
reloading plugin RuboCop.rubocop_listener
reloading plugin RuboCop.rubocop_runner
reloading plugin RuboCop.rubocop_runner_tests
reloading plugin RubyEval.RubyEval
reloading plugin SCSS.scss_completions
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
plugins loaded
Package Control: No updated packages

**Comment by wbond** [comment]
This does not include Package Control debug information. Be sure the `debug` setting is set to `true`.

**Comment by atstockland** [comment]
Adam Stockland

**Comment by atstockland** [comment]
While package control is looking for available packages…it shows this, but nothing is getting written to the log.





Adam Stockland

**Comment by wbond** [comment]
Check and make sure you put the setting in the correct file. The docs page includes all of the info.

Here is an example of what the debug output will look like:

```
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3076
  Package Control Version: 3.1.0-beta
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/wbond/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/wbond/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher DHE-RSA-AES256-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
    subject alt name: dev.codexns.io, rc.codexns.io, packagecontrol.io, wbond.net, codexns.io
    expire date: Oct 29 23:59:59 2015 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  If-Modified-Since: Thu, 19 Mar 2015 03:10:04 GMT
  Connection: Keep-Alive
  Host: packagecontrol.io
  User-Agent: Package Control v3.1.0-beta
  If-None-Match: "550a3e0c-30835"
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Thu, 19 Mar 2015 03:40:47 GMT
  Content-Type: application/json
  Content-Length: 198943
  Last-Modified: Thu, 19 Mar 2015 03:40:04 GMT
  Connection: keep-alive
  ETag: "550a4514-3091f"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Accept-Ranges: bytes
Package Control: Caching https://packagecontrol.io/channel_v3.json in /Users/wbond/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: Looking for git at: "/usr/bin/git", "/bin/git", "/usr/sbin/git", "/sbin/git", "/usr/local/git/bin/git", "/usr/local/bin/git"
Package Control: Found git at "/usr/bin/git"
Package Control: Executing /usr/bin/git symbolic-ref -q HEAD [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Alignment]
Package Control: Executing /usr/bin/git config --get branch.master.remote [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Alignment]
Package Control: Executing /usr/bin/git config --get branch.master.merge [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Alignment]
Package Control: Executing /usr/bin/git fetch origin [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Alignment]
Package Control: Skipping automatic upgrade, last run at 2015-03-18 23:10:34, next run at 2015-03-19 00:10:34 or after
Package Control: Executing /usr/bin/git log ..origin/master [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Alignment]
Package Control: Executing /usr/bin/git symbolic-ref -q HEAD [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/ChannelRepositoryTools]
Package Control: Executing /usr/bin/git config --get branch.master.remote [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/ChannelRepositoryTools]
Package Control: Executing /usr/bin/git config --get branch.master.merge [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/ChannelRepositoryTools]
Package Control: Executing /usr/bin/git fetch origin [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/ChannelRepositoryTools]
Package Control: Executing /usr/bin/git log ..origin/master [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/ChannelRepositoryTools]
Package Control: Executing /usr/bin/git symbolic-ref -q HEAD [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Executing /usr/bin/git config --get branch.master.remote [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Executing /usr/bin/git config --get branch.master.merge [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Executing /usr/bin/git fetch origin [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Executing /usr/bin/git log ..origin/master [/Users/wbond/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
```

**Comment by atstockland** [comment]
Shit!  You’re right, I put the debug setting in the wrong prefs.  Here is the output your looking for.


startup time: 2.42
unexpected rule type, was expecting one of match, include, begin or patterns, got: {comment: Note how all @rules are prefixed.}
unknown include #string-double
unknown include #string-single
unknown include #string-single
unknown include #string-double
unknown include #media-query-list
unknown include #media-query-list
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
loaded 891 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin BeautifyRuby.beautify_ruby
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin ExportHtml.ExportBbcode
reloading plugin ExportHtml.ExportHtml
reloading plugin ExportHtml.HtmlAnnotations
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Instacode.instacode
reloading plugin LESS.less_completions
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin RuboCop.constants
reloading plugin RuboCop.file_tools
reloading plugin RuboCop.rubocop_command
reloading plugin RuboCop.rubocop_listener
reloading plugin RuboCop.rubocop_runner
reloading plugin RuboCop.rubocop_runner_tests
reloading plugin RubyEval.RubyEval
reloading plugin SCSS.scss_completions
reloading plugin SublimeLinter-rubocop.linter
SublimeLinter: rubocop linter loaded 
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-03-18 20:09:01, next run at 2015-03-18 21:09:01 or after
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/Hank/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at /Users/Hank/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL
  Using TLSv1/SSLv3 with cipher DHE-RSA-AES256-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
    subject alt name: dev.codexns.io, rc.codexns.io, packagecontrol.io, wbond.net, codexns.io
    expire date: Oct 29 23:59:59 2015 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-Modified-Since: Thu, 19 Mar 2015 03:20:04 GMT
  Host: packagecontrol.io
  Accept-Encoding: bzip2,gzip,deflate
  If-None-Match: "550a4064-31188"
  Connection: Keep-Alive
  User-Agent: Package Control v3.0.1
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Thu, 19 Mar 2015 03:53:22 GMT
  Content-Type: application/json
  Content-Length: 201078
  Last-Modified: Thu, 19 Mar 2015 03:50:04 GMT
  Connection: keep-alive
  ETag: "550a476c-31176"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Accept-Ranges: bytes
Package Control: Caching https://packagecontrol.io/channel_v3.json in /Users/Hank/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Package Control: Looking for git at: "/usr/bin/git", "/bin/git", "/usr/sbin/git", "/sbin/git", "/usr/local/git/bin/git", "/usr/local/bin/git"
Package Control: Found git at "/usr/bin/git"
Package Control: Trying to execute command /usr/bin/git symbolic-ref -q HEAD
Package Control: Trying to execute command /usr/bin/git config --get branch.master.remote
Package Control: Trying to execute command /usr/bin/git config --get branch.master.merge
Package Control: Trying to execute command /usr/bin/git fetch origin
Package Control: Trying to execute command /usr/bin/git log ..origin/master
Package Control: Trying to execute command /usr/bin/git symbolic-ref -q HEAD
Package Control: Trying to execute command /usr/bin/git config --get branch.master.remote
Package Control: Trying to execute command /usr/bin/git config --get branch.master.merge
Package Control: Trying to execute command /usr/bin/git fetch origin
Package Control: Trying to execute command /usr/bin/git log ..origin/master

Adam Stockland

**Comment by wbond** [comment]
Try setting `ignore_vcs_packages` to `true`. It may be that your git repos are taking a long time to fetch and generate the log for.

In the 3.1.0-beta, there is more granular control. `ignored_vcs_packages` is a list that accepts package names. Also, it more correctly detects errors executing git and prints info about what folder the commands are being executed in.

**Comment by atstockland** [comment]
Thanks, Will.  I set ignore_vcs_packages: true in the PackageControl User Settings (same place I set debug: true).  Then, attempted to install a package.  Same thing…took over 5 minutes.

Adam Stockland

**Comment by wbond** [comment]
What line in the debug is it hanging on?

**Comment by wbond** [comment]
@atstockland Were you able to identify which line in the log was printed right before the hang?

**Comment by kevinsmith** [comment]
I'm having the very same issue. I enabled debug and opened the console, and here's what I'm seeing right before the hang:

```
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/ksmith/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at /Users/ksmith/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL
  Using TLSv1/SSLv3 with cipher DHE-RSA-AES256-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
    subject alt name: dev.codexns.io, rc.codexns.io, packagecontrol.io, wbond.net, codexns.io
    expire date: Oct 29 23:59:59 2015 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  Host: packagecontrol.io
  If-None-Match: "550c384c-310c6"
  User-Agent: Package Control v3.0.1
  Connection: Keep-Alive
  If-Modified-Since: Fri, 20 Mar 2015 15:10:04 GMT
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Fri, 20 Mar 2015 15:18:00 GMT
  Content-Type: application/json
  Last-Modified: Fri, 20 Mar 2015 15:10:04 GMT
  Connection: keep-alive
  ETag: "550c384c-310c6"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/ksmith/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
```

**Comment by wbond** [comment]
@kevinsmith What about after the hang? The log you've shown so far seems to indicate that the download of the channel file goes fine and PC cleans up the connection.

**Comment by kevinsmith** [comment]
Nothing after the hang. The log stays the same. For the test I ran to generate the log above, it took a full 4 minutes for the list of packages to show up in the UI.

**Comment by wbond** [comment]
Hmm, what does your CPU usage look like for Sublime Text during that period?

**Comment by kevinsmith** [comment]
Hovers right around 14% according to Activity Monitor.

**Comment by kevinsmith** [comment]
At 0% once the list of packages pops up.

**Comment by wbond** [comment]
Weird, I have no idea what is going on.

Can you check and see if you have a folder named `/Users/ksmith/Library/Application Support/Sublime Text 3/Packages/Package Control/` on your machine?

Also, do you have a file named `/Users/ksmith/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package`?

**Comment by kevinsmith** [comment]
I do not have `/Users/ksmith/Library/Application Support/Sublime Text 3/Packages/Package Control/` on my machine. I **do** have `/Users/ksmith/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package` on my machine.

Probably worth noting that I just installed [this security update](https://support.apple.com/en-us/HT204563) and Command Line Developer Tools 6.2 this morning. This wasn't happening before those changes, but I also don't remember the last time I tried to do anything with Package Control.

**Comment by kevinsmith** [comment]
Just updated to ST3 Build 3080. I can't be sure if it was that or some other variables the changed, but I'm not having the problems described above anymore. @atstockland You might try that and see what happens.

**Comment by atstockland** [comment]
That fixed it for me!

THANKS!


Adam Stockland

**Comment by wbond** [comment]
Ok, so this seems to be a bug in Sublime Text between 3065 and 3080.
