### ISSUE TITLE
Since update to ST3 3080, cannot install packages.

### ISSUE THREAD

**Issue by gotofritz** [wbond/package_control#916]
I already commented on not being able to install new packages <a href="https://github.com/wbond/package_control/issues/94#issuecomment-85986355">here</a>.

After that I tried to uninstall and then reinstall PC using

    import urllib.request,os,hashlib; h = 'eb2297e1a458f27d836c04bb0cbaf282' + 'd0e7a3098092775ccb37ca9d6b2e4b7d'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)

ST3 hangs for a while then fails with:

    Traceback (most recent call last):
      File "./urllib/request.py", line 1248, in do_open
      File "./http/client.py", line 1065, in request
      File "./http/client.py", line 1103, in _send_request
      File "./http/client.py", line 1061, in endheaders
      File "./http/client.py", line 906, in _send_output
      File "./http/client.py", line 844, in send
      File "./http/client.py", line 822, in connect
      File "./socket.py", line 417, in create_connection
    socket.gaierror: [Errno 8] nodename nor servname provided, or not known

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "./urllib/request.py", line 156, in urlopen
      File "./urllib/request.py", line 469, in open
      File "./urllib/request.py", line 487, in _open
      File "./urllib/request.py", line 447, in _call_chain
      File "./urllib/request.py", line 1268, in http_open
      File "./urllib/request.py", line 1251, in do_open
    urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by ggirelli** [comment]
Unable to install packages with build 3083 too... :(

**Comment by unnamedcrewman** [comment]
Same issue...I think.  I did a completely fresh install of ST3 3083 on OSX Yosemite.  Package Control installed just fine, and it shows the list of available packages.  Attempting to install any package gives the following error in the console:

    Package Control: Error downloading package. URL error [Errno 54] Connection reset by peer downloading https://codeload.github.com/thinkpixellab/flatland/zip/master.
    error: Package Control

    Unable to download Theme - Flatland. Please view the console for more details.

**Comment by dubeg** [comment]
Im thinking its a github issue. Trying to download any release, and even clicking the button 'Download ZIP' in any repository results in a ERR_TIMED_OUT.

**Comment by wbond** [comment]
Timeout and connection reset errors from codeload.github.com are almost certainly due to the DDoS.

I am not sure why you'd be getting errno 8 – it is almost certainly outside of the purview of Package Control. I believe that is an OS error related to DNS lookups. I could check and make sure your machine can resolve the domain name `packagecontrol.io`. If that works, check and see if you have antivirus or network security software that may be blocking `plugin_host`/`plugin_host.exe` from the Sublime Text folder on your machine.

**Comment by unnamedcrewman** [comment]
I'm not sure what the problem was but it does seem like it must have been on the github end.  A short while after I posted, and a couple of restarts later, PC notified me that it had done some kind of update.  I checked and everything is back to normal, so I'm installing like crazy.

Thanks  for the help and sorry for the noise.

**Comment by gotofritz** [comment]
Yes it does seem to have cleared itself. thanks.

**Comment by togakangaroo** [comment]
This has been happening to me in version 3083.

     error: Package Control
     There are no packages available for installation
     indexing [queue 67]: no files were indexed out of the 1 queued, abandoning crawl

**Comment by wbond** [comment]
@togakangaroo Debug log please

**Comment by togakangaroo** [comment]
@wbond how do I get that?

**Comment by wbond** [comment]
https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log

**Comment by togakangaroo** [comment]
@wbond 

```
reloading Packages/User/Package Control.sublime-settings
Package Control: Settings change detected, clearing cache
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 2.0.0-alpha7
Package Control: Download Debug
  URL: https://sublime.wbond.net/repositories.json
  Resolved IP: 50.116.34.243
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: f42O34HKwvQTRlRAsXiRPvAWUUwbo22p, GT52951423, See www.rapidssl.com/resources/cps (c)15, Domain Control Validated - RapidSSL(R), sublime.wbond.net
    issuer: US, "GeoTrust, Inc.", RapidSSL CA
    common name: sublime.wbond.net
    issue date: Tue, 24 Feb 2015 00:47:53 GMT
    expire date: Mon, 28 Mar 2016 21:42:51 GMT
Package Control: WinINet HTTPS Debug Write
  GET /repositories.json HTTP/1.1
  Accept-Encoding: gzip,deflate
  If-Modified-Since: Tue, 01 Sep 2015 18:05:02 GMT
  User-Agent: Sublime Package Control v2.0.0-alpha7
  Host: sublime.wbond.net
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Tue, 01 Sep 2015 18:36:44 GMT
  Last-Modified: Tue, 01 Sep 2015 18:05:02 GMT
  Connection: keep-alive
  ETag: "55e5e8ce-300"
Package Control: Using cached content for https://sublime.wbond.net/repositories.json
Package Control: Found git at "C:\Program Files (x86)\Git\cmd\git.exe"
Package Control: Found git at "C:\Program Files\TortoiseSVN\bin\TortoisePlink.exe"
Package Control: Trying to execute command "C:\Program Files (x86)\Git\cmd\git.exe" fetch
Package Control: Trying to execute command "C:\Program Files (x86)\Git\cmd\git.exe" log ..--ff/--commit
error: Package Control

There are no packages available for installation
Package Control: WinINet HTTPS Debug General
  Closing connection to sublime.wbond.net on port 443 after 1 request
```

**Comment by wbond** [comment]
@togakangaroo You are using an old package list from PC 1.x. Check your PC user settings and remove `"channels"` to use the default.

**Comment by togakangaroo** [comment]
@wbond these are my PC user settings

```
{
	"auto_upgrade_last_run": null,
	"installed_packages":
	[
		"AdvancedNewFile",
		"Alignment",
		"All Autocomplete",
		"Babel",
		"Code Alignment",
		"CoffeeScript",
		"Emmet",
		"GoldenRatio",
		"HTML-CSS-JS Prettify",
		"HTMLBeautify",
		"HtmlTidy",
		"Indent XML",
		"Jade",
		"Jasmine CoffeeScript",
		"Logs Colorize",
		"Markdown Preview",
		"NightCycle",
		"Oceanic Color Scheme",
		"Package Control",
		"PowerShell",
		"Processing",
		"Razor",
		"Sass",
		"SchemeCycler",
		"Syntax Highlighting for Sass",
		"Theme - Brogrammer",
		"Tomorrow Color Schemes",
		"TypeScript",
		"TypescriptCompletion"
	]
}
```

**Comment by wbond** [comment]
Then I'd say you most likely have a very old version of Package Control installed. Trying following the directions at https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling.

**Comment by togakangaroo** [comment]
ah I see, thanks all
