### ISSUE TITLE
packagecontrol.io does not cache appveyor badge

### ISSUE THREAD

**Issue by randy3k** [wbond/package_control#918]
In my package page: https://packagecontrol.io/packages/UnitTesting
The appveyor badge is not correctly shown (while the travis badge does not have any problems).

My appveyor badge url: https://ci.appveyor.com/api/projects/status/9nnjlnj6tetbxuqd/branch/master?svg=true

I suspect it is related to the `?svg=true` options in the url.

**Comment by wbond** [comment]
Yeah, it is too bad that URL doesn't end in `.svg` since I think that would probably make all of the difference. I'll have to add code to the image caching that looks at the HTTP headers to determine if a file extension needs to be added.

Now tracking this at wbond/packagecontrol.io#48

**Comment by wbond** [comment]
This has been fixed in the latest release, so this image should be updated and fixed within the next hour as the crawler comes along and updates the readmes
