### ISSUE TITLE
Cache packages list 

### ISSUE THREAD

**Issue by luxtau** [wbond/package_control#919]
PackageControl always loads the package repositories instead of caching it for some time (or during session). It takes too much time, especially when installing several packages.

**Comment by tseven** [comment]
I agree and would love to see this feature. 
Perhaps you can show the cached list first, while checking for updates in the background.

**Comment by wbond** [comment]
The information is cached for 5 minutes by default. You can change it via the `https://packagecontrol.io/docs/settings#setting-cache_length` setting. The cache will always clear when restarting Sublime Text, however HTTP caching is used also.
