### ISSUE TITLE
Have some trouble installing Package on ST2

### ISSUE THREAD

**Issue by kongwy** [wbond/package_control#920]
I tried to install Package Control on the ST2 through the command on the [Installation page](https://packagecontrol.io/installation#st2).

It alarmed "Package Control just upgraded the Python _ssl module for ST2 on Windows because the bundled one does not include support for modern SSL certificates."

And after a restart, when I install any package by `Ctrl+Shift+P`, the message will show it is installed successfully but in fact the package haven't been installed.

I don't know why it is, and I'm in China with a web block but I'm using a proxy and have access to GitHub, etc.

**Comment by wbond** [comment]
I would need a debug log to give you any guidance on this. https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log
