### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by blinskey** [wbond/package_control#926]
Forgive me if this has already been reported elsewhere, but a number of packages are no longer showing up via the Install Package command or the website search. Two random examples: [Vintageous](https://packagecontrol.io/packages/Vintageous) and [SublimeLinter](https://packagecontrol.io/packages/SublimeLinter).

**Comment by sethen** [comment]
+1... I missing quite a few including Sass, various Sublime Linter plugins, TypeScript and others.  I encountered this issue when running my latest dotfiles repo.

**Comment by Void2258** [comment]
Additional vanished packages: 
DocBlockr
SideBarEnhancements
Inc-Dec-Value.

Happened in the last couple of days since I had no problem getting them into a new installation on Monday.

**Comment by timonwong** [comment]
Me included:

- SublimeAStyleFormatter
- OmniMarkupPreviewer
- ScalaFormat

**Comment by fnkr** [comment]
+1

Missing packages:
- SublimeCodeIntel
- SublimeLinter-jsl
- SublimeLinter-xmllint
- Trimmer
- SublimeLinter-pylint
- INI
- SublimeLinter-json
- DataConverter
- SublimeLinter-html-tidy
- DocBlockr
- SublimeLinter
- TrailingSpaces
- TodoReview
- HexViewer
- Project Manager
- SublimeLinter-php
- SublimeLinter-contrib-golint

**Comment by wbond** [comment]
Some sort of weird networking issue hit the server the crawler is on and prevented it from properly indexing packages. Because of this, packages became stale and were subsequently marked as removed since they have not been seen in a while.

The issue should be resolved now, and the crawler should be restoring package information as it updates the local cache.

**Comment by sethen** [comment]
Thanks for the quick action here @wbond!  Glad to have my plugins back.

**Comment by wbond** [comment]
This is resolved now.
