### ISSUE TITLE
NameError: name 'domain' is not defined

### ISSUE THREAD

**Issue by proyectords** [wbond/package_control#930]
Hello I am a student and so far I'm taking my first steps in Python, I want to simulate a topology, but I have this error: "NameError: name 'domain' is not defined", the variable is defined ... do not understand why the error this is code ... immensely grateful for your support.:

import random
from numpy import *
import scipy as Sci
import scipy.linalg

def argumentos(x):
    count = 0
    for i in range(0,len(x)):
        count += x[i]
    return count

    domain=0

def waxman(_lambda=None, alpha=None, beta=None, domain=None):

    n = argumentos(waxman)
    if (n < 4):    # default parameter values
        _lambda = 0.6    # intensity of the Poisson process
        alpha = 0.4    # parameter for the link probability
        beta = 0.1    # parameter for the link probability
        domain = mcat([0, 10, 0, 10])    # bounds for the "geografical" domain

xmin = domain(1)
xmax = domain(2)
ymin = domain(3)
ymax = domain(4)
clear(mstring('domain'))

area = (xmax - xmin) * (ymax - ymin)
npoints = scipy.stats.poisson(_lambda * area); print (npoints)

nd_coord = random.random(npoints, 2)
nd_coord(slice[:], 1).lvalue = nd_coord(slice[:], 1) * (xmax - xmin) + xmin
nd_coord(slice[:], 2).lvalue = nd_coord(mslice[:], 2) * (ymax - ymin) + ymin

x_rep = repmat(nd_coord(slice[:], 1), 1, npoints)
y_rep = repmat(nd_coord(slice[:], 2), 1, npoints)
dist_matr = sparse(triu(((x_rep - x_rep.cT) **elpow** 2 + (y_rep - y_rep.cT) **elpow** 2) **elpow** 0.5, 1))

prob_matr = alpha * spfun(mstring('exp'), -dist_matr /eldiv/ (beta * max(max(dist_matr))))

runi = sprand(dist_matr)
adj_matr = logical_and((runi > 0), (runi < prob_matr))

figure(1)
clf()
hold(mstring('on'))
plot(nd_coord(slice[:], 1), nd_coord(slice[:], 2), mstring('.'))
gplot(adj_matr, nd_coord)
hold(mstring('off'))

**Comment by FichteFoll** [comment]
This issue tracker is for issues or problems with Package Control, not your general Python problems.

Having said that, the `domain` identifier seems to not be defined. It can only come from `from numpy import *` currently, but that doesn't seem to define it either. You either forgot to copy a function from somewhere or an import statement.

**Comment by proyectords** [comment]
FichteFoll thank you very much for your quick response, I appreciate your help.
