### ISSUE TITLE
Feature request - How to manage installed package if using different SublimeText path/location

### ISSUE THREAD

**Issue by duytrung** [wbond/package_control#932]
Hi,

I want to extract the list of installed packages and configurations to a text file where I can use it at different locations, with computer my home, computer in my company. Is it possible for that because I found Package control can only support for one instance at a time. There is no synchronization functionality that allow users to use sublime text more flexible.

Thank you!

**Comment by FichteFoll** [comment]
https://packagecontrol.io/docs/syncing

**Comment by wbond** [comment]
In addition to the syncing documentation that @FichteFoll linked, the *Preferences > Package Settings > Package Control > Settings – User* file includes a setting `installed_packages` that lists all packages installed via Package Control.
