### ISSUE TITLE
Wrong version of the README.md

### ISSUE THREAD

**Issue by zhengbli** [wbond/package_control#933]
For the TypeScript plugin:
It seems that the README.md file on https://packagecontrol.io/packages/TypeScript is directly pulled from the master branch of the plugin repo, instead of from the corresponding [tag](https://github.com/Microsoft/TypeScript-Sublime-Plugin/tree/0.1.3), which is not expected.

**Comment by FichteFoll** [comment]
This is the expected, [albeit not explicitly documented](https://github.com/wbond/package_control/blob/d3bc04fd5c0c4bdb476a3ea798e6815508dc9bac/example-repository.json#L124), behavior.

The reason for this is that the readme needs to be the same for all releases provided, in case you have different code for ST2 and ST3 for example.
