### ISSUE TITLE
Sublime Text 2/3: There are no packages available for installation

### ISSUE THREAD

**Issue by iakovgan** [wbond/package_control#937]
Hi, 

On a fresh windows install i cannot install any package. 
```
Package Control: Settings change detected, clearing cache
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. (errno 12045) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at D:\Users\igan\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at D:\Users\igan\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.merged-ca-bundle
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation
```

**Comment by FichteFoll** [comment]
@wbond, I guess the error message (is kind of misleading and) hides information. It should probably mention that downloading "n out of m" channels failed, or similar, but it should at least mention to look into the console.

**Comment by wbond** [comment]
@iakovgan Seems like something on your machine or network is messing with the connection to the server.

**Comment by iakovgan** [comment]
Have no issues with downloading something via python requests library (with ssl deactivated). By the way there is something wrong with certificate.


Here is my test: I try to download  https://packagecontrol.io/channel_v3.json with and withot SSL check. 


```
D:\>ipython
Python 2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

In [1]: import requests

In [2]: res=requests.get("https://packagecontrol.io/channel_v3.json")
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
<ipython-input-2-ec59d0e07245> in <module>()
----> 1 res=requests.get("https://packagecontrol.io/channel_v3.json")
...
SSLError: hostname 'packagecontrol.io' doesn't match u'codexns.io'

In [3]: res=requests.get("https://packagecontrol.io/channel_v3.json", verify=False)

In [4]: res.json().keys()
Out[4]: [u'repositories', u'dependencies_cache', u'packages_cache', u'schema_version']
```

**Comment by wbond** [comment]
No, there is nothing wrong with the certificate. You can verify the cert is ok by visiting https://packagecontrol.io in Google Chrome and clicking on the lock icon to look at the certificate information.

The certificate uses the SSLv3 subject alt name extension to support multiple domain names with a single certificate. It seems the requests library is not using this information since it is trying to compare `packagecontrol.io` to `codexns.io` (that is the primary domain on the cert). 

Is it possible that you have a proxy or network device that is terminating SSL connections and then creates certificates on the fly? Compare the image I've attached with the issuer info you are seeing on your end. If the cert validating `packagecontrol.io` is not an EV cert from `GeoTrust EV SSL CA - G4`, then a device on your network is intercepting traffic and possibly causing the issue.
![cert_info](https://cloud.githubusercontent.com/assets/41734/7279652/72cf49fa-e8eb-11e4-86c7-2da69dc506db.png)

**Comment by iakovgan** [comment]
Wired
![image](https://cloud.githubusercontent.com/assets/9697819/7279685/06c3e2a6-e91e-11e4-93ef-50b67d7c23c8.png)

**Comment by wbond** [comment]
Yeah, so most likely there is a network device on your network that is intercepting SSL traffic and decrypting it and then re-encrypting it with a different cert. If you click on the link for the certificate information, you can see what cert is being used to sign the re-encrypted data.

If you trust that cert, you can add it to the file `D:\Users\igan\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.user-ca-bundle` and then Package Control should work. The cert will need to be in PEM format to be added to that file. PEM format starts with `-----BEGIN CERTIFICATE-----`.

Just know that someone is likely monitoring what you download from the internet. :-)

**Comment by iakovgan** [comment]
Very interesting. Can you redirect me to some way i can check more on that. 


1. When i check certificate, shows following info: 
```
CN = GeoTrust EV SSL CA - G4
O = GeoTrust Inc.
C = US
```
So it is the same as the original. 

2. Forefox does not see any issue
3. IE and Chrom do show certificat issue
4. I've exported the certificat to \Package Control.user-ca-bundle but the error is still the same.

**Comment by wbond** [comment]
Can you paste `Package Control.user-ca-bundle` here?

Can you also post a screenshot of the Firefox certificate information "General" screen?

**Comment by Gamzy** [comment]
I am also having this problem. Is there a way you could show as a sample of the Package Control.user-ca-bundle that adds the cert?

Thanks!

**Comment by wbond** [comment]
@Gamzy You need a PEM-encoded certificate. It will look like the following:

```
-----BEGIN CERTIFICATE-----
MIIGizCCBXOgAwIBAgIQYg46WU6Gb9G2jdI/8qVAIjANBgkqhkiG9w0BAQsFADBH
MQswCQYDVQQGEwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEgMB4GA1UEAxMX
R2VvVHJ1c3QgRVYgU1NMIENBIC0gRzQwHhcNMTQxMjE3MDAwMDAwWhcNMTUxMDI5
MjM1OTU5WjCB1DETMBEGCysGAQQBgjc8AgEDEwJVUzEeMBwGCysGAQQBgjc8AgEC
FA1NYXNzYWNodXNldHRzMR0wGwYDVQQPExRQcml2YXRlIE9yZ2FuaXphdGlvbjES
MBAGA1UEBRMJNDcxNzE0NjM5MQswCQYDVQQGEwJVUzEWMBQGA1UECBQNTWFzc2Fj
aHVzZXR0czEQMA4GA1UEBxQHTmV3YnVyeTEeMBwGA1UEChQVQ29kZXggTm9uIFN1
ZmZpY2l0IExDMRMwEQYDVQQDFApjb2RleG5zLmlvMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAn1IWBm9rvLbYyxu10iBprifB5hVJEWa7mQaXqU54v3up
llfcZzqpL2Bk0MHIfPTbxwg1n3B9m4+Ey1HOgWeiVFxOHA8dI6SgXCSAOvxPVLsT
cy82iNBVpBvJ+Ci1u3lLUh8UzS0j2eci8U+3rVrwrMjiaboexCIV1bXQteiOihWh
YnEpsqHivPXX8DQ6rvG9PMBXCVPkwqJLA0GAzGdwvddyqMa5760Yv2170XpwNg7v
wih3AH3pMKX39Cgd+Jn8zhzuB0RgYdkQuEcqI8V3O24DwBW6hLyVL3ajFDr1VQb1
kLT219G6rMND8PzSfaNiYvitPSjsHbDNFmD8hHppBwIDAQABo4IC4zCCAt8wUgYD
VR0RBEswSYIOZGV2LmNvZGV4bnMuaW+CDXJjLmNvZGV4bnMuaW+CEXBhY2thZ2Vj
b250cm9sLmlvggl3Ym9uZC5uZXSCCmNvZGV4bnMuaW8wCQYDVR0TBAIwADAOBgNV
HQ8BAf8EBAMCBaAwKwYDVR0fBCQwIjAgoB6gHIYaaHR0cDovL2dtLnN5bWNiLmNv
bS9nbS5jcmwwgaAGA1UdIASBmDCBlTCBkgYJKwYBBAHwIgEGMIGEMD8GCCsGAQUF
BwIBFjNodHRwczovL3d3dy5nZW90cnVzdC5jb20vcmVzb3VyY2VzL3JlcG9zaXRv
cnkvbGVnYWwwQQYIKwYBBQUHAgIwNQwzaHR0cHM6Ly93d3cuZ2VvdHJ1c3QuY29t
L3Jlc291cmNlcy9yZXBvc2l0b3J5L2xlZ2FsMB0GA1UdJQQWMBQGCCsGAQUFBwMB
BggrBgEFBQcDAjAfBgNVHSMEGDAWgBTez1xQt64CHxUXqhboDbUonWpa8zBXBggr
BgEFBQcBAQRLMEkwHwYIKwYBBQUHMAGGE2h0dHA6Ly9nbS5zeW1jZC5jb20wJgYI
KwYBBQUHMAKGGmh0dHA6Ly9nbS5zeW1jYi5jb20vZ20uY3J0MIIBAwYKKwYBBAHW
eQIEAgSB9ASB8QDvAHUApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BAA
AAFKVctwzgAABAMARjBEAiBhrEBQ6LfRQnQ2EQvOlsFtTu906MGMT+eXpr8RiJQ5
bAIgesSFdYX7Qqs5AmV4/A6UQswos0iUc9NrvkUjnCe5+FMAdgBo9pj4H2SCvjqM
7rkoHUz8cVFdZ5PURNEKZ6y7T0/7xAAAAUpVy3D0AAAEAwBHMEUCIGJv8m9tSDUh
b8Cx/+GKLZbgqhoR5KvmwqnUkomve8BUAiEAjDx9OdDiIpoFNTrabIAqFy4l9/z8
AcGY8ZYJNLjl5YIwDQYJKoZIhvcNAQELBQADggEBAFk2w3U4Rxa3pHBjuuq26ZZx
S38UV2MSGon2Vr0pNtsRs4A0lcfqwX63CljuEWVCWQcLap00CgnfL4Lk0Nvt3HNB
Vh3/rXzxyOUXvPzWhatyMmjl19y/iO6JGnEfPkk9Xzv6iLfCB0aZhm9V0pswbbKg
bST1kUrftEBMeAqOQYgK0wvFu2TB5wD1dnI5fziLsvBndq2jScvBr20XVpMrORQ/
K7+RlP1jWhlfoE3WMm9DlShpq+b67vP8JxySbeY8JJtG61W5re8TMFrDZXbnWJOt
4QVPZgEO87IX3vyrTu9XBmJ/vknv8NY1khUXpE/F/ONWZ4wDltEGOOr8jDOWCp8=
-----END CERTIFICATE-----
```

**Comment by wbond** [comment]
@iakovgan Could you paste the contents of your `Package Control.user-ca-bundle` here?

**Comment by developsoft** [comment]
I have the same as @iakovgan, so the Package Control.user-ca-bundle file has to be filled like above?

**Comment by TheDutchCoder** [comment]
All around the office, everyone is getting this error as of this morning as well (haven't checked earlier).
I'm assuming this is not an issue on the client side right now?

**Comment by wbond** [comment]
https://twitter.com/Package_Control/status/613330107202060289

**Comment by TheDutchCoder** [comment]
Ah thanks, sorry about reporting it!

**Comment by wbond** [comment]
No worries. We are back online now!

**Comment by wbond** [comment]
I'm closing this since I believe the correct solution is this problem is to find and install the intermediate SSL CA that the user's network is using to intercept traffic.

**Comment by NekR** [comment]
@wbond Just got "There are no packages available for installation" problem with 3.1 update. Is servers down again?

**Comment by wbond** [comment]
@NekR No, there are currently over 1,000 active connections at nginx pushing about 20mbit/s.

You should open a new issue with a debug log so I can help.

**Comment by jsonschema** [comment]
I'm getting this too:

`error: Package Control`
`There are no packages available for installation`

Build 3083
Windows 10 64-bit

**Comment by xstortionist** [comment]
+1 getting same message after most recent windows 10 update.

**Comment by wbond** [comment]
Please see #1057
