### ISSUE TITLE
There are no packages available for installation.

### ISSUE THREAD

**Issue by andreieftimie** [wbond/package_control#94]
When trying to install Packages i get the following error.

The log from the command line:

<pre><code>
Package Control: Error downloading channel. URL error _ssl.c:480: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol downloading https://sublime.wbond.net/repositories.json.
error: Package Control: There are no packages available for installation.
</code></pre>

I have very recently updated Sublime Text 2 to the latest build 2181

**Comment by gotofritz** [comment]
It has started again, OS X, as soon as I have installed build 3080. I don't have Charles or anything of the sort running, and no proxy at work.

**Comment by learningjs** [comment]
Getting this error today (first time ever, nothing has changed in my net, no proxy, before everything worked well ):  https://packagecontrol.io/channel_v3.json is unreachable (no ping etc).

**Comment by jtnegrotto** [comment]
@learningjs I'm suddenly getting it today as well. I can load `channel_v3.json`, but there's nothing to see there:

```
{
schema_version: "3.0.0",
packages_cache: { },
repositories: [ ],
dependencies_cache: { }
}
```

**Comment by dsmith1717** [comment]
I had the same issue, the json was empty but I checked again after a couple of minutes and this time it contained all the data. Try again, it might work.

**Comment by wbond** [comment]
Please see #1057 for information about the outage
