### ISSUE TITLE
Dependency installation fails silently if parsing dependencies.json fails

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#946]
For example when there are comments in the file.

See http://www.sublimetext.com/forum/viewtopic.php?f=6&t=18172.

**Comment by mrjoelkemp** [comment]
Yes. Bit me once before. Would love a popup telling the user why the installation failed.

**Comment by wbond** [comment]
Well, in most situations in I know an error can occur, I will present a general failure in a popup and more specific details in the console.

In this situation, the error was unexpected, so it resulted in an uncaught exception. Unfortunately the mechanism for handling these in Python is spectacularly bad. There can only be one uncaught exception handler, so you have to do all kinds of crappy work to try and chain them together.

In terms of this actual issue, I haven't decided yet if I think we should allow comments in the `.json` files.

**Comment by FichteFoll** [comment]
I agree with your comment on the forum thread that `.json` files usually do not allow comments, but on the other hand you do have comments in the `example-repository.json` file (for example).

Might be a good time to think about #819 as well.

**Comment by wbond** [comment]
Ok, as of bbda4458ece3ce7f97f1c51c3583e97ac63658d3 there will be a notice printed to the console about why the install failed

**Comment by wbond** [comment]
I should also mention I updated the various example files in 982fdcaf89cf397c08fd159b9edc383be0173455 to specifically mention removing comments being using them

**Comment by FichteFoll** [comment]
:+1:
