### ISSUE TITLE
bad (zip?) file header on fresh package install

### ISSUE THREAD

**Issue by jdc0589** [wbond/package_control#947]
People have been getting a "bad file header" error on and off for a while when installing [JsFormat](/jdc0589/JsFormat). It just happened to me personally.

I found a couple references to it being some weird github issue... so I'm assuming zips are served directly from there. Is that accurate, or could it potentially be a package control issue?

**Comment by FichteFoll** [comment]
It is correct that zips are served from github, but Package Control unpacks and later repacks them in the installation process, so PC may be at fault here. I have also encountered this issue a few times but am unaware of different methods of creating zip archives than what PC does currently.

**Comment by jdc0589** [comment]
hmm.. its really sporadic. usually a manual package reinstall fixes is.
pretty annoying though.

**Comment by wbond** [comment]
What version of Sublime Text and Package Control?

**Comment by wbond** [comment]
If someone can find me a backtrace, I should be able to add a retry.

**Comment by wbond** [comment]
Anyone seen this happen that can provide a backtrace?

**Comment by FichteFoll** [comment]
Haven't encountered this since the last comment sadly.

**Comment by parkan** [comment]
I'm seeing this with the Babel package:

```
Traceback (most recent call last):
  File "package_control.commands.upgrade_all_packages_command in /Users/arkadiy/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 74, in disable_packages
  File "package_control.package_disabler in /Users/arkadiy/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 74, in disable_packages
zipimport.ZipImportError: bad local file header in /Users/arkadiy/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package
```

I think it's the same issue?

**Comment by wbond** [comment]
@parkan Did you just get the Package Control 3.1.0 update installed?

I believe the issue you are seeing is related the way Sublime Text 3 handles importing `.sublime-package` (aka `.zip`) files. It uses a custom importer that does not properly respond to `reload()`ing of the contents of `.py` files in a `.sublime-package`. I did a bit of work for the 3.1.0 to try and sidestep this issue in the [`1_reloader.py`](https://github.com/wbond/package_control/blob/master/1_reloader.py), however it is possible that a specific situation or two may still contain bugs.

You can test this hypothesis by restarting Sublime Text and seeing if the error continues. Ideally I will send a patch to Jon at some point soon to try and prevent this issue in newer ST3 builds.

**Comment by parkan** [comment]
Yes, I think that's what happened -- I was getting the above error while trying to install babel, restarted ST3 and got the 3.1.0 update message. Restarting again didn't help, but quarantining the affected file and reinstalling PC via the sublime console _then_ restarting again did the trick.

**Comment by wbond** [comment]
If someone runs across this issue, please post a fresh issue with a backtrace. My suspicion based on recent work is that it has to do with reloading packed packages.

**Comment by jdc0589** [comment]
latest reported occurrence, jdc0589/JsFormat/issues/170

**Comment by wbond** [comment]
For future reference, I left a comment at https://github.com/jdc0589/JsFormat/issues/170#issuecomment-213031454 explaining what I believe is going on.

This also explains why it seems to affect JsFormat and not other packages.

**Comment by FichteFoll** [comment]
Just occured to me on Arch Linux (first time on a non-Windows system) after starting ST and having PC auto-update MarkdownTOC:

```
Package Control: Installing 1 upgrades
ignored packages updated to: ["Floobits", "InactivePanes", "Jedi - Python autocompletion", "MarkdownEditing", "MarkdownTOC", "Open-Include", "Plugin Debugger", "RestructuredText", "Stylus", "Table Editor", "Theme - Freesia", "Vintage"]
unloading plugin MarkdownTOC.__init__
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Upgraded MarkdownTOC to 3.0.2
ignored packages updated to: ["Floobits", "InactivePanes", "Jedi - Python autocompletion", "MarkdownEditing", "Open-Include", "Plugin Debugger", "RestructuredText", "Stylus", "Table Editor", "Theme - Freesia", "Vintage"]
reloading plugin MarkdownTOC.__init__
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /home/fichte/.config/sublime-text-3/Installed Packages/MarkdownTOC.sublime-package
```

However, when I copied the package file somewhere else (to backup) and tried to unzip it, it worked fine. In fact, even a restart of ST did not cause this exception to be raised again, so it doesn't appear to be of much help.

I attached the file anyway (renamed extension to `zip`): [MarkdownTOC.zip](https://github.com/wbond/package_control/files/1913139/MarkdownTOC.zip)


ST 3161, PC 3.3.1-beta4

**Comment by kaste** [comment]
A user of SublimeLinter posted the same stacktrace as FichteFoll https://github.com/SublimeLinter/SublimeLinter/issues/1468#issue-341349769

> Traceback (most recent call last):
  File "..\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in ..\Data\Installed Packages\SublimeLinter.sublime-package
Sublime Text 3175 x64 portable
Win 10 Pro 1803 x64
Package Control v3.3.0
SublimeLinter v4.7.0

**Comment by jrappen** [comment]
```text
Traceback (most recent call last):
  File "..\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in ..\Data\Installed Packages\SublimeLinter.sublime-package
```

bad file:

> SublimeLinter v4.7.2

[SublimeLinter.zip](https://github.com/wbond/package_control/files/2223103/SublimeLinter.zip)

same experience as @FichteFoll above:

* re-opening Sublime fixed the issue
* renaming to zip and exporting worked fine

Using:

```text
ST 3175 win x64 portable, dev channel
Win 10 Pro x64 Version 1803 with High-DPI

Package Control v3.3.0
SublimeLinter v4.7.2
```

---

/cc @braver @kaste

**Comment by FichteFoll** [comment]
My idea would be that st tries to load the package before it is entirely written to the file, but PC ignoring the package before doing any operation *should* prevent that. I say should because it's done asynchronously and races are still possible.
