### ISSUE TITLE
Poor performance loading repositories with many open windows on OS X

### ISSUE THREAD

**Issue by mattstevens** [wbond/package_control#948]
For a while now I've experienced poor performance when using the Install Package command on OS X 10.10. Similar to what is described in #812, when trying to run the command it will sit at "Loading repositories" for minutes despite the debug log showing that the channel data was  retrieved in just a few seconds. During this time the Sublime Text UI exhibits significant lag for any user input. I was able to reproduce the problem using a fresh Sublime Text data directory and track down the cause, which has a couple factors:

- Since `sublime.status_message()` updates the status bar in all windows, the time it takes to complete increases with each open window. The status message update operation also completes asynchronously so the next timeout is scheduled in `ThreadProgress.run()` before the current status message update operation completes. Once the time required to update the status bar in all windows exceeds 100 milliseconds this results in there being very little delay between status message update operations in the main process.

- Each invocation of `sublime.packages_path()` makes an IPC call to the main process to retrieve the data. Via the call to `PackageManager.is_vcs_package()` in `PackageInstaller.make_package_list()` at least two calls to `sublime.packages_path()` are made for each available package. As a result responses to several thousand IPC calls must be received before the package list is displayed, and with the main process occupied by the continual status message updates it takes a long time for all of these to be serviced.

Environment:

Mid-2012 Retina MacBook Pro (also reproduced on Late 2014 iMac 5k)
OS X 10.10.3
Sublime Text Build 3085
Package Control 3.0.1
Fresh ST data directory

Steps to reproduce:

1. Start Sublime Text.
2. Install Package Control.
3. Restart Sublime Text.
4. Ensure only one window is open.
5. Run Install Package, verify that the package list appears quickly.
6. Open 20 new windows. The exact number required to reproduce the issue may vary by system.
7. Run Install Package.

On both of my 10.10 systems this results in a stuttering "Loading repositories" animation and the package list takes minutes to appear.

There are a few possible solutions, any one of which should address the issue:

- Sublime Text could find a way to optimize the status message update operation.
- Package Control could limit the status message update to only the active view, or perhaps only views of the current window.
- Package Control could remove the status message animation.
- Assuming the value doesn't change, Sublime Text could cache the value of `sublime.packages_path()` in the plugin process to improve performance for situations like Package Control's where this API is called frequently.
- Assuming the value doesn't change, Package Control could cache the result of `sublime.packages_path()` in `PackageManager` to avoid the IPC call for each package.

The last two don't directly address the status message performance issue, but they eliminate the second contributing factor and allow `make_package_list()` to complete much faster in the problem scenario.

[Log and samples for native code](https://gist.github.com/mattstevens/aa4861f26521121e1803)

**Comment by wbond** [comment]
Very nice report, I should be able to reproduce and fix with this info.

**Comment by wbond** [comment]
I've addressed the IPC calls with a9bc7ad361586cf25316d83fc2d6464d06939f0e and worked around the poor performance of global window status updates with many open windows in d65406ee9ff65032d4a55689f602c704dc6cb70b.

If you can, please use git to checkout the master branch and let me know if you see an improvement on your end.

With the global window status change, I noticed with a large number of Windows open the status animation was no longer choppy, and the list packages operation ran in about half the time. Granted, I am running on a pretty fast rMBP, so it might be even more pronounced for other users.

**Comment by mattstevens** [comment]
These changes have resolved the issue for me as well, thanks!
