### ISSUE TITLE
There are no packages available for installation

### ISSUE THREAD

**Issue by twelch555** [wbond/package_control#950]
I had this issue once before (although I'm not sure if it was this platform, I run windows 8.1, Mac OSX and Ubuntu in Virtualboxes).

I believe the solution had something to do with certificates but I'll be damned if I can remember or find what it was now.

The odd thing is that Ubuntu in a virtualbox on this same machine works just fine.

Here's my console output from a fresh startup and two attempts to access packages:

DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /D/program files/Sublime Text 3/sublime_text.exe
working dir: /D/program files/Sublime Text 3
packages path: /C/Users/twelc_000/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/twelc_000/AppData/Roaming/Sublime Text 3/Local
zip path: /D/program files/Sublime Text 3/Packages
zip path: /C/Users/twelc_000/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.077818
startup time: 0.096818
first paint time: 0.097818
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Auto Semi-Colon.AutoSemiColon
reloading plugin DocBlockr.__init__
reloading plugin DocBlockr.jsdocs
reloading plugin GitGutter-Edge.git_gutter
reloading plugin GitGutter-Edge.git_gutter_change
reloading plugin GitGutter-Edge.git_gutter_compare
reloading plugin GitGutter-Edge.git_gutter_events
reloading plugin GitGutter-Edge.git_gutter_handler
reloading plugin GitGutter-Edge.git_helper
reloading plugin GitGutter-Edge.view_collection
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarGit.SideBarGitCommands
reloading plugin SideBarGit.StatusBarBranch
reloading plugin SublimeGit.SublimeGit
reloading plugin SublimeLinter-cppcheck.linter
SublimeLinter: cppcheck linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-clang.linter
SublimeLinter: clang linter loaded 
plugins loaded
SublimeLinter: debug mode: off 
Package Control: Installing 4 missing packages
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Tue, 16 Dec 2014 16:00:00 GMT
    expire date: Thu, 29 Oct 2015 16:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-Modified-Since: Tue, 12 May 2015 22:10:04 GMT
  Accept-Encoding: bzip2,gzip,deflate
  If-None-Match: "55527a3c-3358d"
  User-Agent: Package Control v3.0.1
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Tue, 12 May 2015 22:18:03 GMT
  Content-Type: application/json
  Last-Modified: Tue, 12 May 2015 22:10:04 GMT
  Connection: keep-alive
  ETag: "55527a3c-3358d"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from C:\Users\twelc_000\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
Package Control: Download Debug
  URL: http://sublime.wbond.net/repositories.json
  Resolved IPv6: 2600:3c02:e000:42::1
  Resolved IP: 50.116.34.243
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTP Debug Write
  GET /repositories.json HTTP/1.1
  If-Modified-Since: Tue, 12 May 2015 22:10:17 GMT
  Accept-Encoding: bzip2,gzip,deflate
  User-Agent: Package Control v3.0.1
  Host: sublime.wbond.net
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTP Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Tue, 12 May 2015 22:18:04 GMT
  Content-Type: application/json
  Last-Modified: Tue, 12 May 2015 22:10:17 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Content-Encoding: gzip
Package Control: Caching http://sublime.wbond.net/repositories.json in C:\Users\twelc_000\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\39bc41cae8ff8eda76f2f53c950d833d
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: The package "Evernote" is either not available on this platform or for this version of Sublime Text
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: The package "TypeTodo" is either not available on this platform or for this version of Sublime Text
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: The package "Keymaps" is either not available on this platform or for this version of Sublime Text
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: The package "Racket" is either not available on this platform or for this version of Sublime Text
Package Control: Skipping automatic upgrade, last run at 2015-05-12 14:30:58, next run at 2015-05-12 15:30:58 or after
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Package Control: WinINet HTTP Debug General
  Closing connection to sublime.wbond.net on port 80 after 1 request
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
error: Package Control

There are no packages available for installation
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
error: Package Control

There are no packages available for installation

**Comment by twelch555** [comment]
And then I noticed the url for one of the repositories:
http://sublime.wbond.net/repositories.json

Changing the "http" to "https" solved the problem.

**Comment by jamesRaybould** [comment]
Further to the above I spotted this today when attempting to troubleshoot my own installation - going to http://sublime.wbond.net/ results in the below

![image](https://cloud.githubusercontent.com/assets/2018774/7746305/2371e244-ffa9-11e4-8a4f-7489a6008fdd.png)

Which makes it look like the domain registration has lapsed

**Comment by wbond** [comment]
If you are connecting to `sublime.wbond.net`, you are using a very old, out-dated version of Package Control. Follow the directions at https://packagecontrol.io/docs/troubleshooting#Purging_Old_Versions to get the latest version.

**Comment by FichteFoll** [comment]
It could also be that you added the URL to the channel manually to pc's user settings. If that is the case, remove the entire "channels" setting so that the default will be used.

**Comment by twelch555** [comment]
It was in channels settings in the user file so I must have at some point. Thanks, deleting the channels settings as you suggest is working fine.

**Comment by wbond** [comment]
Once I finally move my packages off of my personal domain to my new company site, I will add an explicit check to make sure sublime.wbond.net is not being used.
