### ISSUE TITLE
OSX 10.6 ST2 Installation/Upgrade problem

### ISSUE THREAD

**Issue by bonzairob** [wbond/package_control#951]
Background: I had Package Control installed for a year or so and working fine, but a few months ago some parts of it stopped working (helpful!). I don't know if it was an ST2 update, a Package Control update, or something I changed in my system to do with Python. I develop in python but don't really touch system python. I noticed at first because the missing palette commands package disappeared.

The preferences are still in the menus: 
![image](https://cloud.githubusercontent.com/assets/212013/7669949/ee4a1162-fc84-11e4-9010-59ade3394522.png)

But it seems like half the options are missing from the command selector thing:
![image](https://cloud.githubusercontent.com/assets/212013/7669950/09980082-fc85-11e4-8dc0-b6ecec852f27.png)
(This used to have install/update, right..?)

If I paste in the install code into the console, I get an error about urandom:
![image](https://cloud.githubusercontent.com/assets/212013/7669957/3b8c29f6-fc85-11e4-9685-4c814f5cb7d6.png)

And if I try the manual install, the package just disappears from Installed Packages as soon as ST2 starts.

Thanks for any help - as I said, not sure if this is a bug or pebkac.

**Comment by wbond** [comment]
Hmm, yes, this appears to be an issue with the OS X Python 2.6 install. I don't have 10.6 available right at the moment to verify that it is your install, or a more general problem.

**Comment by bonzairob** [comment]
Horrendous hack fix: because that's not my primary python, edit random.py. Not at all recommended, but it works.
```
try:
    from os import urandom as _urandom
except ImportError:
    def _urandom(n):
        f = open("/dev/urandom")
        s = f.read(n)
        f.close()
        return s
```

**Comment by wbond** [comment]
Well, I don't think there is much Package Control can be doing here, and Snow Leopard has been unsupported by Apple for over a year, so I am going to close this.
