### ISSUE TITLE
There are no packages available for installation

### ISSUE THREAD

**Issue by discern** [wbond/package_control#957]
“There are no packages available for installation” started happening recently. The certificate validates in the browser, and others within the local network are not having this issue. I've got (homebrew) GNU Wget 1.16.3 installed.

OS X 10.10.3.

<pre>
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/user/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at /Users/user/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. URL error unknown error (_ssl.c:2228) downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation
</pre>

Thoughts?

**Comment by wbond** [comment]
According to the Python source (https://hg.python.org/cpython/file/c3896275c0f6/Modules/_ssl.c#l2228) it would appear there is an issue loading the file `/Users/user/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle`.

Can you paste the contents of that?

**Comment by discern** [comment]
That file contains zero bytes O_o. Prior to opening this issue, I had read through some similar threads, and reinstalled the Package Manager. The creation date for that bundle is this morning, when I reinstalled it. Does reinstalling the Package Manager replace this bundle? Why would it be empty?

**Comment by wbond** [comment]
So the merged file combines any user CA certs with the ones from the system. What does `/Users/user/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle` have in it?

**Comment by wbond** [comment]
You can delete the `Package Control.system-ca-bundle` and `Package Control.merged-ca-bundle` files and try installing a package again. This will regenerate the system one and then merge with your user ca bundle.

**Comment by discern** [comment]
Fixed. You are the man. Thank you!

**Comment by wbond** [comment]
So it sounds like I need to add a check for that. Did you see any errors after deleting those files?

**Comment by discern** [comment]
I do not see any further errors. Package Manager is successfully retrieving the packages. Thanks again, Will.

**Comment by wbond** [comment]
No problem!

**Comment by wbond** [comment]
This should be prevented in the future by 120b433241961066604a8f6e57f9fe122022755d

**Comment by neok-m4700** [comment]
Hi,
Reinstalling ca-certificates did the trick for me (linux mint - virtualbox)

sudo apt-get install --reinstall ca-certificates

**Comment by n8finch** [comment]
Thanks Will, just deleted `Package Control.system-ca-bundle` and `Package Control.merged-ca-bundle` files and it's working again. Just wanted to say this still works. Cheers!

**Comment by sisihagen** [comment]
Hello, 

i have same mistake. I has delete the files, restart sublime and same mistake. No Packages availible for Installation. I have try with sublime 2/3. Ever same. New install, delete config and so on. Its ever the same. 

I use Gentoo 32 Bit.

Silvio

**Comment by babalooi** [comment]
This gist helped me out https://gist.github.com/nick1m/0bb2e77f98666583a7f1

**Comment by sisihagen** [comment]
This gist work for me not, but i has installed the json file from archive.org to my server and now run again. Sure the mistake will be repair next week.

**Comment by ozai** [comment]
I deleted the Package Control.system-ca-bundle and Package Control.merged-ca-bundle
but I'm still getting the same error. Package Manager is not retrieving the packages :S 
It was working just fine only yesterday! 
could it be the memory clean software I'm using? :s

**Comment by nonameolsson** [comment]
This solved it for me: https://github.com/wbond/package_control/issues/959#issuecomment-168448993

**Comment by FichteFoll** [comment]
#1057

**Comment by 805056790** [comment]
You can delete the Package Control.system-ca-bundle and Package Control.merged-ca-bundle files and try installing a package again. This will regenerate the system one and then merge with your user ca bundle.

**Comment by tomoya92** [comment]
@805056790 me too

**Comment by benjam-es** [comment]
Im having this issue currently. Is it a server issue?

**Comment by syncher-bin** [comment]
@neok-m4700 fixed, tks!
