### ISSUE TITLE
Empty Installed Packages folder

### ISSUE THREAD

**Issue by jumbosushi** [wbond/package_control#958]
Hello,

So overall my package control is working fine ... until the installation part.

I tried to install packages (Browser Refresh, for example), and the sublime text 2 shows that "successfully installed packages". However, not only packages that I downloaded not reflected in the text editor, but also my "Installed Packages" folder inside "Sublime Text 2" folder is empty in Windows.

No error sign showed up, but it doesn't look like my packages are installed. I tried other packages, but the result is the same. What is going ?

**Comment by FichteFoll** [comment]
The Installed Packages folder is not supposed to contain anything, that's ST3-only.

Please paste a [debug log](https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log) of the installation process.

**Comment by jumbosushi** [comment]
Hello,

Thanks for the reply!

I'm also having trouble enabling debug log. 
![error 1](https://cloud.githubusercontent.com/assets/9669739/8151153/867ead12-12ba-11e5-86ff-0e6e612ea037.PNG)
this error pops up whenever I try to save it.

![error 2](https://cloud.githubusercontent.com/assets/9669739/8151154/9461e8ae-12ba-11e5-8264-57cf5e6e4dc6.PNG)
Is there something wrong with my user-setting code?

**Comment by FichteFoll** [comment]
If you read the error message closely, it tells you that it "expected a comma or closing bracket" at line 9. Basically, line 8 needs a trailing comma.

**Comment by jumbosushi** [comment]
My bad, but debug console is working now!

Here's what I get when I try to install "Browser Refresh" from package console:

Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 2221
  Package Control Version: 3.0.1
ignored packages updated to: [Browser Refresh]
found 1 files for base name Default.sublime-theme
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 2221
  Package Control Version: 3.0.1
reloading /C/Users/惇/AppData/Roaming/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /C/Users/惇/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: []
found 1 files for base name Default.sublime-theme
reloading /C/Users/惇/AppData/Roaming/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /C/Users/惇/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading /C/Users/惇/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded

**Comment by wbond** [comment]
Hmm, it seems the connection is hanging trying to connect.

Can you visit https://packagecontrol.io in Internet Explorer?

**Comment by jumbosushi** [comment]
Yup, I can do that

**Comment by wbond** [comment]
I am not sure why this would hand like that. Other than you diving into the code and adding some `print()` calls to see where the operation is failing, I don't know if there will be a solution.
