### ISSUE TITLE
Packages: Install Package fails

### ISSUE THREAD

**Issue by maryjos** [wbond/package_control#96]
I installed the package control and all the menu options are available, but when I select the Package: Install Package I just get an error that no packages are available. Any ideas? On Mac OS Lion, latest beta of Sublime 2.

**Comment by wonbin2011** [comment]
Upgrading connection to SSL using CA certs file at /home/wonbin/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. URL error _ssl.c:532: The handshake operation timed out downloading https://packagecontrol.io/channel_v3.json.
