### ISSUE TITLE
Package Control: Skipping automatic upgrade

### ISSUE THREAD

**Issue by mirkojovanovic** [wbond/package_control#962]
I have this error after fresh installation of sublime-text-dev(sublime text 3) on Arch Linux

`Package Control: Skipping automatic upgrade, last run at 2015-06-19 18:14:29, next run at 2015-06-19 19:14:29 or after
`
I have linked User folder to folder on Dropbox to be able to sync packages from my other machine. Now it won't install them. This worked previously on different linux distributions and windows.

**Comment by FichteFoll** [comment]
That's not an error.

**Comment by FichteFoll** [comment]
Does this always occur when you start Sublime Text? Do you start Sublime Text on both machines within one hour?

FWIW, you can always manuall trigger updating via **Package Control: Upgrade/Overwrite all Packages**.

**Comment by mirkojovanovic** [comment]
Yes, every time. I didn't used the working one today, so no. I have reinstalled all the plugins and now I have this errors:
`warning: mnemonic b not found in menu caption SFTP/FTP
warning: mnemonic LI not found in menu caption Lorem Ipsum...
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Codex
warning: mnemonic f not found in menu caption QueryPosts`

when I upgrade all from package control i get this(hundreds of times repeated):

`Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 439, in is_enabled_
    ret = self.is_enabled()
  File "Nodejs in /home/mirko/.config/sublime-text-3/Installed Packages/Nodejs.sublime-package", line 126, in is_enabled
AttributeError: 'NodeRunCommand' object has no attribute 'window'
`

It's not color picker's fault like in some other thread i found.

**Comment by mirkojovanovic** [comment]
This mnemonic errors shows up on both machines.

**Comment by mirkojovanovic** [comment]
Any idea?

**Comment by FichteFoll** [comment]
The mnemonic warnings are coming from packages that wrongly set the mnemonic to something that is not contained in the menu text (case sensitive). Sadly, the package/file where these warnings are caused, is not disclosed in the message.

The exception is from something in the [Nodejs package](https://github.com/tanepiper/SublimeText-Nodejs).

**Comment by wbond** [comment]
@mirkojovanovic So the original message you posted is not a bug, but expected functionality. Package Control only checks for updates once an hour, when the editor is restarted. At least according to the message, at `2015-06-19 18:14:29` you start Sublime Text and it checked for updates.

Unless there is something else going on, I'm not sure if there is a bug here to fix.

**Comment by yaoelcn** [comment]
via Package Control: Upgrade/Overwrite all Packages 。My problem is ok! Thank you for FichteFoll

**Comment by grace-snow** [comment]
How can you find out / correct whichever package it is? 
I keep getting the message warning: mnemonic t not found in menu caption Tools 

It's driving me crazy I can't get Ghost Text to work

**Comment by ildarkhasanshin** [comment]
search "mnemonic": "t" in *.sublime-menu
