### ISSUE TITLE
Not able to install packages using Sublime Package Control in ubuntu 14.04

### ISSUE THREAD

**Issue by gdad-s-river** [wbond/package_control#963]
Hi! 
I'm having problems installing packages in sublime text 3. I use ubuntu 14.04.Following is the console when I click preferences > Package Control > Installl Packages. 

>DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/av/.config/sublime-text-3/Packages
state path: /home/av/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/av/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.091733
startup time: 0.21927
first paint time: 0.228799
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
reloading plugin ssl-linux.loader
Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
Linux SSL: unloading http module so ssl will be available
Linux SSL: unloading urllib module so ssl will be available
plugins loaded
reloading Packages/User/Preferences.sublime-settings
Package Control: Removed directory for unneeded dependency b2z
Package Control: Installing 1 missing dependency
Package Control: Downloading https://packagecontrol.io/channel_v3.json timed out
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-06-21 18:05:55, next run at 2015-06-21 19:05:55 or after
Package Control: Downloading https://packagecontrol.io/channel_v3.json timed out
error: Package Control

>There are no packages available for installation

I spent a whole day trying to figure out these three problems, namely
1. Installing b2z dependency.
2. Installing ssl-linux dependency
3. Trying to figure out the "Package Control: Downloading https://packagecontrol.io/channel_v3.json timed out" error.

* ssl-linux dependency, I downloaded the zip file and unzipped it in the Packages directory, and when I restarted sublime, it was being loaded as was shown in the console, but it was being the case when I tried the same with b2z.

* For b2z I followed this [link](http://stackoverflow.com/questions/27752282/error-installing-sublime-text-3-package-control-bz2) and tried what Machael Lv have written. But as soon as I restarted the sublime the 'b2z' directory(of his answer) would automatically be removed.

* For the second channel_v3 time out, I'm getting no way. 

It would be extremely kind of you if you could help me figure out what is wrong.

**Comment by wbond** [comment]
The bz2 and ssl-linux dependencies will install if you figure out the timeout issue.

Have you tried running a traceroute to packagecontrol.io?

**Comment by GJKrupa** [comment]
I was seeing a similar issue. When I tried traceroute it looked like circular routing at 50.116.33.29 (li396-29.members.linode.com) as if the host didn't recognise its own alias as packagecontrol.io and was trying to forward packets on.  After 15 hops the traceroute terminated and when I checked the site became accessible.

**Comment by wbond** [comment]
The server was just upgraded, which resulted in a period of downtime. Most likely you saw this.

**Comment by AV12111994** [comment]
This is the output of I'm afraid I'm not savvy to figure out what's happening. 
`traceroute packagecontrol.io `


>traceroute to packagecontrol.io (50.116.33.29), 30 hops max, 60 byte packets
 1  192.168.1.1 (192.168.1.1)  30.084 ms  38.576 ms  38.723 ms
 2  abts (122.178.228.1)  146.860 ms  146.871 ms  146.863 ms
 3  abts (122.166.32.221)  130.353 ms  143.395 ms  143.404 ms
 4  aes (125.22.102.25)  150.267 ms  150.267 ms  150.261 ms
 5  182.79.222.1 (182.79.222.1)  480.133 ms 182.79.245.161 (182.79.245.161)  480.110 ms 182.79.222.1 (182.79.222.1)  480.171 ms
 6  213.242.116.157 (213.242.116.157)  504.314 ms 213.242.116.161 (213.242.116.161)  273.978 ms 213.242.116.157 (213.242.116.157)  264.888 ms
 7  ae (4.69.168.71)  281.783 ms ae-3-80.edge4.Paris1.Level3.net (4.69.168.135)  277.831 ms ae (4.69.168.71)  286.652 ms
 8  ae (4.69.168.135)  278.211 ms ae (4.69.168.199)  278.482 ms ae (4.69.168.7)  293.651 ms
 9  ae0.mpr1.cdg11.fr.zip.zayo.com (64.125.12.113)  235.525 ms  231.641 ms  275.536 ms
10  v95.ae29.cr1.dca2.us.zip.zayo.com (64.125.30.140)  308.823 ms  309.561 ms  943.969 ms
11  ae2.mpr4.atl6.us.zip.zayo.com (64.125.25.46)  943.928 ms  943.941 ms  277.581 ms
12  ae4.mpr3.atl6.us.zip.zayo.com (64.125.31.197)  275.597 ms  282.277 ms  278.243 ms
13  128.177.104.134.IPYX (128.177.104.134)  254.895 ms  257.642 ms  260.383 ms
14  router1 (64.22.106.10)  265.318 ms  268.639 ms  270.455 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by AV12111994** [comment]
wbond could you help?

**Comment by wbond** [comment]
Unfortunately I don't know of anything I can do. The server seems to be fully functional, receiving hundreds of thousands of requests a day. I don't know why your connection is timing out.

Can you browse https://packagecontrol.io in your browser?

**Comment by AV12111994** [comment]
yes I can.

**Comment by AV12111994** [comment]
I did a terrible terrible mistake. I have recently passed out of college, and I used a proxy server to access the web. http,https, ftp settings were still in the .bashrc file, I removed it and I'm able to install packages now.

**Comment by wbond** [comment]
Alright, this seems resolved.
