### ISSUE TITLE
Reinstalling existing package with Advanced Install crashes ST

### ISSUE THREAD

**Issue by bragur** [wbond/package_control#967]
Trying to find a way to install multiple packages at once. Installing over existing configuration results in a crash and ST doesn't respond. Couldn't see the crash log, but this appears afterwards and everything appears to be OK (just asked for 'LESS' in the installation query).

    Package Control: The package LESS is being re-enabled after a Package Control operation was interrupted
    reloading plugin LESS.less_completions

Perhaps the advanced installer could check if packages already exist?

**Comment by wbond** [comment]
Is this reproducible with other packages?

**Comment by bragur** [comment]
Yes, doesn't matter which package it is. First I put a whole bunch of them in (all of which were already installed), then tried a couple to see if it was only one that was causing the crash, but this happened by three individual packages, so I'm assuming it's not package related.

**Comment by wbond** [comment]
Was `LESS` disabled when you tried to reinstall it?

**Comment by wbond** [comment]
Alright, this should be fixed with f45e9b11c1cce0bd03229902ff7ab1dece5d14b7
