### ISSUE TITLE
Error while installing package in Sublime Text 2

### ISSUE THREAD

**Issue by mrnerbijay** [wbond/package_control#969]
When I press ctrl+`, it show following error, I don't know what is wrong with installing

.................................
Package Control: Installing 1 missing package
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Host not found (errno 12007) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error 11001 downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error 11001 downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

The package specified, SublimeCodeIntel, is not available
Package Control: Skipping automatic upgrade, last run at 2015-07-02 15:28:05, next run at 2015-07-02 16:28:05 or after
Reloading plugin C:\Users\BIJAY\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\ordereddict.py
Reloading plugin C:\Users\BIJAY\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\SublimeCodeIntel.py
found 7 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 5 files for base name Main.sublime-menu
Reloading plugin C:\Users\BIJAY\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel-master\SublimeCodeIntel.py
found 8 files for base name Default.sublime-keymap
found 3 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
loading pointer bindings
loading pointer bindings
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Host not found (errno 12007) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error 11001 downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages available for installation

**Comment by wbond** [comment]
It could be related to DNS. A number of users have been having trouble reaching packagecontrol.io in recent weeks. Around that time I saw a post discussing issues with the root `.io` name servers.

The best solution I have found for now is to use Google DNS for your DNS servers. They are 8.8.8.8 and 8.8.4.4.

In the long term I will likely switch to a different TLD to prevent this from continuing.

**Comment by wbond** [comment]
I don't believe this is a Package Control issue, but rather something related to your Windows configuration.
