### ISSUE TITLE
Sorting ignored packages when writing to preferences.sublime-settings

### ISSUE THREAD

**Issue by aziz** [wbond/package_control#970]
I'm not sure whether this is a package_control issue or a sublime one. but I'll share it here anyway. 

I keep my sublime User directory under git control, but every time I disable a package the `preferences.sublime-settings` file is a mess (diff wise) cause the ignored packages are written in a random order.

Is it possible to sort them before writing them to the settings?

**Comment by FichteFoll** [comment]
I also noticed the seemingly random order, which does not happen always though. I haven't taken a depper look at the source code however.

**Comment by wbond** [comment]
This should be resolved by 361d45ca469d82ef772f2e4a77a401a3d77c0ba1
