### ISSUE TITLE
auto_upgrade_ignore not working

### ISSUE THREAD

**Issue by TheDutchCoder** [wbond/package_control#972]
Hey there!

I have "auto_upgrade_ignore" enabled for the package called "Seti_UI", but it's still auto updating the package.

Any chance this is broken currently?

I've put it in the User Prefs file like so:
```
{
	"auto_upgrade_ignore":
	[
		"Seti_UI"
	],
       ...
       other stuff
       ...
}
```

**Comment by wbond** [comment]
What settings file is this located in?

**Comment by wbond** [comment]
I just tested this functionality and it seems to work fine.

My guess is that you placed it in the wrong settings file. It should be in *Preferences > Package Settings > Package Control > Settings – User* and NOT *Preferences > Settings – User*.

**Comment by TracerLee** [comment]
It should be in Preferences > Package Settings > Package Control > Settings – User and NOT Preferences > Settings – User.
