### ISSUE TITLE
Package Control installed on Sublime Text 3 but not shown in the list

### ISSUE THREAD

**Issue by NgYueHong** [wbond/package_control#973]
I am using Sublime Text 3 on Windows 7 with Package Control installed. I was able to use package control to install packages with it. But now I found that package control doesn't show up in the list when I press `ctrl+shift+p`. I am able see package control item in the preference menu. I have checked `Settings-user` and `Settings-default`, package control is not listed as ignored package. I also checked the `Installed Packages` folder and found that the `Package Control.sublime-package` is in it.

Why is that Package Control is not showing up in the list? How can I fix it?

**Comment by wbond** [comment]
Please provide a debug log (https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log).

**Comment by NgYueHong** [comment]
Thanks wbond for your reply. After setting `"debug": true`, seems like it fixes the problem. That's kind of weird. Now I am able to see package control on the list.
