### ISSUE TITLE
Put `Package Control.cache/*` files in sublime.cache_path() for ST3

### ISSUE THREAD

**Issue by gerardroche** [wbond/package_control#975]
In ST3 there is an api for a cache path location: [`sublime.cache_path()`](http://www.sublimetext.com/docs/3/api_reference.html). 

On linux this is `~/.config/sublime-text-3/Cache`.

Currently package control puts various cache files in the User directory. 

On linux `~/.config/sublime-text-3/Packages/Users`.

As these are cache files they could be put in the `sublime.cache_path()` path, at least on ST3.

**Comment by FichteFoll** [comment]
I have also thought about using the cache dir for some of my packages.
It appears you might have used it already, so maybe you know if  this directory is automatically  cleaned by ST at any point, and if so when? 

On Windows, the cache dir is in %localappdata% btw.

**Comment by gerardroche** [comment]
I don't know if ST auto cleans it at any time. I tend to clean out all cache related files regularly with [this script](https://gist.github.com/gerardroche/6e46cbdf8da19a39f9da). If it does I'm sure it does for a good reason and it's a cache so it shouldn't break anything if it's cleared out.

I don't think I've used it.

Theres also a "Local" directory but there's no api for it. 

On linux it's `~/.config/sublime-text-3/Local`.

Sessions and stuff like the License key is kept in there. 

Package control uses the "in_process_packages" setting in the `User/Package Control.sublime-settings` file. If I remember there were some issues with this. I've thought that the "Local" looks like it would be better location for "volatile" stuff like that. Because it's feels like session stuff.

**Comment by FichteFoll** [comment]
"in_process_packages" is relevant for when a package operation failed or is in progress and PC (or plugin_host) ended before it was finished. It is also highly relevant for the "installed_package" setting, which is in the same file. That's also relevant for when you are syncing your User folder.
Considering the cache dir is only available on ST3 anyway it's likely easier to keep saving this in the user settings file. It would also be bad if this data was lost somehow.

I was just wondering if I need to clean up files I leave there or if there happens to be a mechanic that auto-cleans it every once in a while, but I could just do that when the package is disabled.

**Comment by wbond** [comment]
So yes, the `Package Control.cache/` folder is a true cache that can be deleted and it won't affect anything other than possibly reducing performance. It sounds like we might need to get a question answered from Jon about that.

The `installed_packages` and `in_progress_packages` are settings that need to persist. And `in_progress_packages` wasn't the problem - in fact it was added to prevent issues where sometimes users would quit Sublime Text in the middle of an update, or the package would trigger a bug in Package Control during install, leaving things in a broken state.
