### ISSUE TITLE
:exclamation: Support for Github Emojis

### ISSUE THREAD

**Issue by mjkaufer** [wbond/package_control#976]
Often times, packages in Package Control link to README's on GitHub which have emojis in them. However, they render as plaintext on packagecontrol, which is kind of lame :disappointed: :cry: . Could we possibly remedy this? :dog:

**Comment by wbond** [comment]
I'm sure there is probably some way to do it. The website is located at https://github.com/wbond/packagecontrol.io. The site is written in python, so my guess is that a new markdown library would need to be found. Unfortunately I don't think there is a 100% bug-for-bug Python markdown parser that functions the way GitHub does, although I could be very wrong about that.

**Comment by wbond** [comment]
Closing in favor of tracking the issue at https://github.com/wbond/packagecontrol.io/issues/60
