### ISSUE TITLE
TextMate 2 support

### ISSUE THREAD

**Issue by elia** [wbond/package_control#977]
Would be nice if the service could support TM2 or be forked for it.

Not knowing Python I can't volunteer do a PR to add that support but I can help creating a `Package Control.tmbundle` to interact with the API.

cc @sorbits @infininight

**Comment by wbond** [comment]
Hmm, I don't know anything about the TextMate API. I am guessing that TextMate does not have a Python API, correct? If that is the case, the system Python would have to be used to run the code.

That said, may I ask what your you would like to accomplish through this suggestion? I imagine any plugins would fail to work – is it access to the snippets and syntax definitions? Or just the functionality of having a package manager auto update TM bundles?

On a semi-related side note, up until recently TextMate, Sublime Text and Atom shared syntax definition support, however the recent ST dev builds introduced a net syntax definition that works with the new parallel regex engine. I think this means the language support for Textmate/Atom and Sublime Text will start diverging in the coming months.

**Comment by elia** [comment]
Oh, sorry, it wasn't that clear. What's missing in the TM ecosystem is a package manager for non-official tmbundles. With that in mind I think it could live on something like `textmate.packagecontrol.io`, i.e. independent from the ST site.

As for the API I think there's an API to autoupdate official packages but for user packages it's enough to update them on the filesystem and TM will pick up the change, the same goes for the installation, dropping them in the right directory is enough. 

About the syntax definition I agree it's not a good idea to share the list of packages, if a package supports more than one editor it should be published separately for each one of them.

**Comment by FichteFoll** [comment]
I doubt package control has anything significant in common with a potential package manager for text mate. It would make more sense to write something completely new, imo.

**Comment by elia** [comment]
To me they're quite similar, they are both:

- mainly hosted on github
- consist of a folder with a specific structure
- can be installed manually by downloading them to a defined path
- they need to be discoverable and searched by users

and…

I just realized that this is the repo for the package and not for the server :confounded: 
anyways, with that in mind the proposal is still valid :)

**Comment by wbond** [comment]
So, from a practical perspective, I don't think this is a project that fits for me. I've never used TextMate (only having own a Mac for a short period after starting to support OS X users of ST), and I'm currently self-employed. Building another package manager does not seem like it will help pay the bills at all.

While there is some overlap in the packages (syntax and snippets) and I'm sure some of the code could be reused, I don't think supporting both editors in a single codebase would make sense.

I'm not going to close the issue as of now, in case further discussion or ideas happen to percolate here.

**Comment by wbond** [comment]
There doesn't seem to be anything else anyone wants to add here, so I am going to close this.

**Comment by elia** [comment]
:+1:
