### ISSUE TITLE
HELP!! Plug-ins not working or Package control issue

### ISSUE THREAD

**Issue by Drastiic** [wbond/package_control#979]
Windows 10, ST 3083, i install package control with the code and manually and I think if I was installed correctly cuz when i type crl + shift + p it shows Package control and i type install and it shows all the list but when i install a plugin it say successfully installed but it doesnt work i dont know what is the problem. My ubuntu pc has the same issue. i in my windows pc i install ST2 and instal Package control with the code dor ST2 and same issue. HELP!!!!

**Comment by wbond** [comment]
Please post a debug log

**Comment by Drastiic** [comment]
When i start ST3 (already have Package control "installed" and 1 plug-in)

DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Andres/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Andres/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Andres/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 3.74049
startup time: 3.88149
first paint time: 3.88149
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: No updated packages

**Comment by Drastiic** [comment]
Package Control Settings

{
	// A list of URLs that each contain a JSON file with a list of repositories.
	// The repositories from these channels are placed in order after the
	// repositories from the "repositories" setting
	"channels": [
		"https://packagecontrol.io/channel_v3.json"
	],

	// A list of URLs that contain a packages JSON file. These repositories
	// are placed in order before repositories from the "channels"
	// setting
	"repositories": [],

	// A list of packages to install pre-release versions for. Versions
	// under 1.0.0 are not considered pre-release, only those using the SemVer
	// -prerelease suffixes will be ignored if the package is not in this
	// list.
	"install_prereleases": [],

	// If debugging information for HTTP/HTTPS connections should be printed
	// to the Sublime Text console
	"debug": false,

	// This helps solve naming issues where a repository it not named the
	// same as the package should be. This is primarily only useful for
	// GitHub and BitBucket repositories. This mapping will override the
	// mapping that is retrieved from the repository channels.
	"package_name_map": {},

	// If package install, upgrade and removal info should be submitted to
	// the channel for aggregated statistics
	"submit_usage": true,

	// The URL to post install, upgrade and removal notices to
	"submit_url": "https://packagecontrol.io/submit",

	// If packages should be automatically upgraded when ST starts
	"auto_upgrade": true,

	// If missing packages should be automatically installed when ST starts
	"install_missing": true,

	// If a package was installed by Package Control (has a
	// package-metadata.json file) but is not in installed_packages, remove it
	// based upon the assumption that it was removed on another machine and
	// the Package Control.sublime-settings file was synced to this machine.
	"remove_orphaned": true,

	// The minimum frequency in hours in which to check for automatic upgrades,
	// setting this to 0 will always check for automatic upgrades
	"auto_upgrade_frequency": 1,

	// Packages to not auto upgrade
	"auto_upgrade_ignore": [],

	// Timeout for downloading channels, repositories and packages. Doesn't
	// have an effect on Windows due to a bug in WinINet.
	"timeout": 30,

	// The number of seconds to cache repository and package info for
	"cache_length": 300,

	// An HTTP proxy server to use for requests. Not normally used on Windows
	// since the system proxy configuration is utilized via WinINet. However,
	// if WinINet is not working properly, this will be used by the Urllib
	// downloader, which acts as a fallback.
	"http_proxy": "",
	// An HTTPS proxy server to use for requests - this will inherit from
	// http_proxy if it is set to "" or null and http_proxy has a value. You
	// can set this to false to prevent inheriting from http_proxy. Not
	// normally used on Windows since the system proxy configuration is
	// utilized via WinINet. However, if WinINet is not working properly, this
	// will be used by the Urllib downloader, which acts as a fallback.
	"https_proxy": "",

	// Username and password for both http_proxy and https_proxy. May be used
	// with WinINet to set credentials for system-level proxy config.
	"proxy_username": "",
	"proxy_password": "",

	// If HTTP responses should be cached to disk
	"http_cache": true,

	// Number of seconds to cache HTTP responses for, defaults to one week
	"http_cache_length": 604800,

	// User agent for HTTP requests. If "%s" is present, will be replaced
	// with the current version.
	"user_agent": "Package Control v%s",

	// Setting this to true will cause Package Control to ignore all git
	// and hg repositories - this may help if trying to list packages to install
	// hangs
	"ignore_vcs_packages": false,

	// Custom path(s) to "git" binary for when it can't be automatically
	// found on the system and a package includes a .git metadata directory.
	// Supports more than one path to allow users to sync settings across
	// operating systems.
	"git_binary": [],

	// This should NOT contain the name of the remote or branch - that will
	// be automatically determined.
	"git_update_command": ["pull", "--ff", "--commit"],

	// Custom path(s) to "hg" binary for when it can't be automatically
	// found on the system and a package includes a .hg metadata directory.
	// Supports more than one path to allow users to sync settings across
	// operating systems.
	"hg_binary": [],

	// For HG repositories, be sure to use "default" as the remote URL.
	// This is the default behavior when cloning an HG repo.
	"hg_update_command": ["pull", "--update"],

	// Additional packages to ignore when listing unmanaged packages.
	"unmanaged_packages_ignore": [],

	// Directories to ignore when creating a package
	"dirs_to_ignore": [
		".hg", ".git", ".svn", "_darcs", "CVS"
	],

	// Files to ignore when creating a package
	"files_to_ignore": [
		"*.pyc", ".hgignore", ".gitignore", ".bzrignore",
		"*.sublime-project", "*.sublime-workspace", "*.tmTheme.cache"
	],

	// Files to include, even if they match a pattern in files_to_ignore
	"files_to_include": [],

	// When a package is created, copy it to this folder - defaults to Desktop
	"package_destination": "",

	// A way to create different packaging profiles for different types of
	// package releases, such as for different platforms or binary-only
	// releases.
	//
	// The key of the object will be the profile name and a list of them will
	// be presenting when running the "Create Package File" command. The
	// profile "Default" will use the top-level version on the following
	// settings:
	//
	// - "dirs_to_ignore"
	// - "files_to_ignore"
	// - "files_to_include"
	// - "package_destination"
	//
	// If a profile does not include one of those three setting, it will fall
	// back to the top-level settings.
	"package_profiles": {
		"Binaries Only": {
			// Exclude all .py files, but consequently include all .pyc files
			"files_to_ignore": [
				"*.py", ".hgignore", ".gitignore", ".bzrignore",
				"*.sublime-project", "*.sublime-workspace", "*.tmTheme.cache"
			],

			// Include __init__.py so Sublime Text will load the package
			"files_to_include": [
				"__init__.py"
			]
		}
	},

	// Enable the ability to run the tests - this is only for development
	"enable_tests": false
}

**Comment by Drastiic** [comment]
Package control user settings

{
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Color Highlighter",
		"Package Control"
	]
}

**Comment by FichteFoll** [comment]
What exactly is the problem?

**Comment by Drastiic** [comment]
@FichteFoll plug-ins not working and when i install it say Installation successful but they not work.

**Comment by FichteFoll** [comment]
Well, Color Highlighter has clearly loaded without errors, as indicated in your console:
```
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
```

It doesn't look like Package Control is misbehaving here.

Are you sure that the packages are "not working"? Maybe check its readme on usage information?

**Comment by Drastiic** [comment]
I install BracketHiighlighter and dint work. This is what the console put:

ignored packages updated to: ["Vintage", "BracketHighlighter"]
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin BracketHighlighter.bh_core
reloading Packages/BracketHighlighter/bh_core.sublime-settings
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings

**Comment by Drastiic** [comment]
I reinstall ST3 and install Package control but i dint install any plugins so this is what the console puts:

DPI scale: 1
startup, version: 3083 windows x32 channel: stable
executable: /C/Program Files (x86)/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files (x86)/Sublime Text 3
packages path: /C/Users/Andres/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Andres/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files (x86)/Sublime Text 3/Packages
zip path: /C/Users/Andres/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.167045
startup time: 0.198045
first paint time: 0.198045
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: Installed missing dependency bz2
Package Control: Skipping automatic upgrade, last run at 2015-08-04 22:26:34, next run at 2015-08-04 23:26:34 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

**Comment by Drastiic** [comment]
Alright i install the plug-in BracketHiighlighter and it work, but ApplySyntax and ColorHiighlighter dont work in this case i think is the plug-ins but im not sure what happen.

**Comment by wbond** [comment]
This does not appear to be an issue with Package Control, so I am going to close this.
