### ISSUE TITLE
There are no packages available for installation ~ no firewall.

### ISSUE THREAD

**Issue by Simcat** [wbond/package_control#98]
Opening a new issue as per recommendation:

I also have the 'Package Control: There are no packages available for installation' issue.

No proxy at all here. I have also turned off my modem firewall.

I'm new to Sublime and Package Control. I'm hanging out to use Zen Coding and just have to move past this issue. 
Any help trouble shooting greatly appreciated :)

(Sublime beta build 2126 ~ OSX 10.6 Airport - Provider, Sonic Internet)

Console output below:

[  Package Control: Error downloading channel. URL error [Errno 64] Host is down downloading https://sublime.wbond.net/repositories.json.
error: Package Control: There are no packages available for installation. ]

**Comment by avisiedo** [comment]
Same problem! I have tried from the terminal to download with curl, and I am getting this output:

```
$ curl -vvv -L -o channel_v3.json "https://packagecontrol.io/channel_v3.json"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 50.116.34.243...
* TCP_NODELAY set
* Immediate connect fail for 50.116.34.243: Host is down
* Closing connection 0
curl: (7) Couldn't connect to server
```
