### ISSUE TITLE
Recommendations for package with "dev" and "stable" releases

### ISSUE THREAD

**Issue by danmosemsft** [wbond/package_control#980]
Yesterday I tagged a release which then deployed and broke "double click to select a word" for everyone with my package. Doh!

It would be great to have a separate "dev" channel for my package that a few people would use and help catch any boo-boos before it's marked as "stable". 

I'm thinking I could define a new package, named like "My Package (unstable)" and point it at a fork of the main repo, where I maintain a beta branch. I use the regular "st3-1.2.3" style tags in that repo to designate a beta release.

Is that a reasonable approach?

Although, I"m thinking the two similarly named packages in the dropdown might just be confusing.

**Comment by FichteFoll** [comment]
This is already possible in the form of pre-releases. Take a look at http://semver.org.

When you push a tag with pre-release info to your repo, PC will only install it if the user has added the package to his `install_prereleases` list setting.

**Comment by danmosemsft** [comment]
Yes awesome thanks - I missed that!
