### ISSUE TITLE
Total active installs?

### ISSUE THREAD

**Issue by danmosemsft** [wbond/package_control#981]
(Not sure where to ask this...) 

On a package's homepage on packagecontrol.io, does the install count represent "all downloads ever" or does it represent "all users that downloaded and didn't subsequently uninstall"

In other words, how could I get a rough idea of whether anyone's actually using it, and so whether it's worth improving it. 

The page says 24K downloads but it's accumulated those over 3 years and it currently only gets about 20-40 a day. So I've no idea if 10 people use it, or 20K.

**Comment by FichteFoll** [comment]
I assume it's "all downloads ever".

**Comment by wbond** [comment]
The total installs is the number of unique IP address/OS combinations that have ever sent an install notice back to the server. The daily graphs show the exact number of install notices sent each day, but do not filter out duplicates (if someone installs twice) and are not reduced by the number of uninstalls.

Unfortunately with the current setup i have no idea how to tell what the active number of users is. I only grab stats on install, upgrade and uninstall. I can't tell if someone is actively using the package, if it is disabled, etc.

**Comment by danmosemsft** [comment]
Is there any precedent for packages doing telemetry, do you know? Some approach I could look at.

**Comment by danmosemsft** [comment]
Hey, sorry to reactivate for a question. I can't reconcile your description with the [graph I see for my package] https://packagecontrol.io/packages/Web%20Inspector

It's basically flat and has been for at least 6 months. It seems unlikely that 20-30 people have installed it each day for months -- I would expect more variation, eg.,  when I put a new release out.

Could it be counting something else, like each of the "pings" checking for an upgrade, each time they start Sublime?

If it's the former, I really do have over 10K users. If it's the latter, I have about 30 users who restart Sublime once a day. I'd love to know which!

**Comment by danmosemsft** [comment]
Not sure how to reactivate - I"ll open a new one.
