### ISSUE TITLE
The Package Control said "The Package Install Successfully" but nothing happened

### ISSUE THREAD

**Issue by Cospotato** [wbond/package_control#983]
This is the fully debug message in console when startup the ST2:

startup, version: 2221 windows x64 channel: stable
executable: /F/Sublime Text 2/sublime_text.exe
working dir: /C/WINDOWS/System32
packages path: /F/Sublime Text 2/Data/Packages
settings path: /F/Sublime Text 2/Data/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): F:\Sublime Text 2
Py_GetProgramFullPath(): F:\Sublime Text 2\sublime_text.exe
Py_GetPath(): F:\Sublime Text 2\python26.zip;F:\Sublime Text 2\DLLs;F:\Sublime Text 2\lib;F:\Sublime Text 2\lib\plat-win;F:\Sublime Text 2\lib\lib-tk;F:\Sublime Text 2
Py_GetPythonHome(): F:\Sublime Text 2
catalogue loaded
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
Reloading plugin F:\Sublime Text 2\Data\Packages\0_package_control_loader\00-package_control.py
Reloading plugin F:\Sublime Text 2\Data\Packages\0_package_control_loader\01-ssl-windows.py
Reloading plugin F:\Sublime Text 2\Data\Packages\CSS\css_completions.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\comment.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\copy_path.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\delete_word.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\detect_indentation.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\duplicate_line.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\echo.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\exec.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\fold.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\font.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\goto_line.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\indentation.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\kill_ring.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\mark.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\new_templates.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\open_file_settings.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\open_in_browser.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\paragraph.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\save_on_focus_lost.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\scroll.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\set_unsaved_view_name.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\side_bar.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\sort.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\swap_line.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\switch_file.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\transform.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\transpose.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Default\trim_trailing_white_space.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Diff\diff.py
Reloading plugin F:\Sublime Text 2\Data\Packages\HTML\encode_html_entities.py
Reloading plugin F:\Sublime Text 2\Data\Packages\HTML\html_completions.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Package Control\Package Control.py
Reloading plugin F:\Sublime Text 2\Data\Packages\Package Control\bootstrap.py
plugin init time: 0.0957614
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.161588
wrote startup cache, added files: 2 orphaned files: 0 total files: 96 cache hits: 94
startup time: 0.211205 (package setup was not run)
loaded 837 snippets
Package Control: Installing 2 missing dependencies
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 2221
  Package Control Version: 3.1.0-beta2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Wed, 17 Dec 2014 08:00:00 GMT
    expire date: Fri, 30 Oct 2015 07:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.1.0-beta2
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: gzip,deflate
  If-Modified-Since: Sat, 22 Aug 2015 07:50:03 GMT
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Sat, 22 Aug 2015 07:58:22 GMT
  Last-Modified: Sat, 22 Aug 2015 07:50:03 GMT
  Connection: keep-alive
  ETag: "55d829ab-2144ef"
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from F:\Sublime Text 2\Data\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
**Exception in thread Thread-3:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "F:\SUBLIM\~1\Data\Packages\PACKAG~1\package_control\automatic_upgrader.py", line 113, in run
    self.install_missing()
  File "F:\SUBLIM\~1\Data\Packages\PACKAG~1\package_control\automatic_upgrader.py", line 145, in install_missing
    if self.installer.manager.install_package(dependency, is_dependency=True):
  File "F:\SUBLIM\~1\Data\Packages\PACKAG~1\package_control\package_manager.py", line 884, in install_package
    tmp_dir = tempfile.mkdtemp(u'')
  File ".\tempfile.py", line 316, in mkdtemp
  File ".\ntpath.py", line 108, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 9: ordinal not in range(128)**

Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request

My OS is **Windows 10** with the username in **Chinese**, this maybe the bug where happened
Thanks a lot

**Comment by wbond** [comment]
This should be fixed in master – I'll let you know when there is a beta to test containing the fix

**Comment by wbond** [comment]
To test out the beta with this fix, download https://sublime.wbond.net/prerelease/Package Control.sublime-package and place it in your `Installed Packages/` folder.

**Comment by wbond** [comment]
Please let me know if you still have trouble with that version.
