### ISSUE TITLE
God damn the moron who thought permanently deleting packages that contain json metadata without a prompt is a good idea!

### ISSUE THREAD

**Issue by GrayFace** [wbond/package_control#984]
Presence of package-metadata.json certainly means that the package was installed from Package Manager, deleted and synced OR more likely that it's being prepared for release on Package Manager. My case was the more likely one.

Must show prompt the first time and also use something like http://www.hardcoded.net/articles/send-files-to-trash-on-all-platforms.htm

**Comment by wbond** [comment]
I am unsure what issue you are trying to report.

Perhaps you are interested in the Backups folder that is a sibling of Packages?

**Comment by FichteFoll** [comment]
>more likely that it's being prepared for release on Package Manager

This file has never been used for releasing on Package Manager and it is not documented anywhere, thus no reason to create it.

Other than that, all removals should be backed up in the Backups folder.

**Comment by GrayFace** [comment]
I'm sorry. Indeed there is a Backups folder with my theme. Thank you and sorry for the words I wrote.

As for why I made the json file, I went into "List Packages" and saw mine has no description, then looked what file contains the description and added it.

**Comment by FichteFoll** [comment]
FYI, the description will be fetched from the data that Package Control downloads for the packages to install, which in return is usually fetched from your repo's description field, unless you overrode it in the wbond/package_control_channel repo.

So yeah, unless you installed the package via PC, it will not have any meta information displayed.

**Comment by wbond** [comment]
The description is pulled from your GitHub/BitBucket repo if you are hosting that way. Just fill in the description field on the website and Package Control will pick it up. This is the recommended way to host your package.

**Comment by GrayFace** [comment]
Thanks. Before I release it I should probably figure out what Widget.sublime-settings is for and how to make it work (it supposedly should effect console, but it doesn't), also there's a number of elements that I've never encountered. Maybe I should release it as is though.
