### ISSUE TITLE
Package Control unable to cleanup .sublime-package files which cannot be removed initially

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#985]
I'm debugging https://github.com/FichteFoll/InsertDate/issues/25 currently, which is caused by the package code keeping a file handle to the zip archive open that is not closed (because of a ST3-only import error in the `plugin_unloaded` code).

I suspect Package Control then to flag the package as "something" and then reenabling it on restart instead of properly remove and update, but I found the code to be very unlinear and have problems finding how the error message is caused in the first place because `remove_package` can only be called by `PackageRenamer.rename_packages`. I'll update this with when I find out more, but it's pretty ... weird.

**Comment by FichteFoll** [comment]
Okay, it seems I found at least why the package is not removed: It is actually **not** flagged at all. The "cleanup on next restart" logic **only** applies for extracted packages, not for packages in sublime-package files. This is a concerning issue because it requires manual intervention by the user for packages which can not be removed (e.g. in my case due to not releasing handles).

I'm unsure how we should handle this case, but my best idea currently is to create an override directory for the package and a cleanup file in there to tell PC to remove both, the installed and the override package on restart.

**Comment by wbond** [comment]
Yes, you are correct that there is currently no functionality to "cleanup" a locked .sublime-package file.

Unfortunately issues like this lead to all sorts of hacks. If I had a $1 for every time I dealt with file locking on Windows…

Anyway, the solution is almost certainly to introduce *another* new settings into the Package Control settings called something like `packages_to_cleanup`. Perhaps all of the cleanup logic could be changed to do the following:

 1. Add the package to "ignored_packages"
 2. Add the package to "packages_to_cleanup"
 3. On startup delete all folders and .sublime-package files related to "packages_to_cleanup"

**Comment by FichteFoll** [comment]
Yes, that would probably be easier than crawling the file system for `package-control.cleanup` files.

**Comment by FichteFoll** [comment]
Update: If you can put out a fix for this issue in a reasonable time frame (assumung I make the PR tomorrow), I don't have to explicitly reproduce the issue and check if update messages are still propagated to tell users how to manually force an update of my package.

**Comment by wbond** [comment]
My hope is to fix a few small issues in the next day or so, allow for some testing, and then make a release.

**Comment by wbond** [comment]
Ok, I believe I've fixed all of the other know bugs, so I am going to work on refactoring how Package Control cleans up packages that are stuck.

Once this change is done, I'll cut a beta for 3.1.0, then hopefully release in the next week.

**Comment by FichteFoll** [comment]
Good news :+1:

**Comment by wbond** [comment]
Actually just pushed a commit to fix this issue. Ended up being simpler than I originally planned: 97e62fc16c5f95c83a85d3a9ec3581d1340f4591.

**Comment by wbond** [comment]
I should note, I tested the fix using InsertDate 1.0.1.

**Comment by FichteFoll** [comment]
I have two questions regarding the code.

1. Where is `remove_package` called in the update process? I looked into it but couldn't find it, I only found `install_package`, and that doesn't call remove. Not important but would appreciate a pointer.
2. I don't understand why the code you committed fixes the issue. I mean, the package is not reenabled now when the removal failed, but why is it cleaned up on the next start? I don't see a flag being made anywhere and `in_process_packages` only re-enables iirc.

**Comment by wbond** [comment]
`remove_package` is called from the remove package command thread: https://github.com/wbond/package_control/blob/master/package_control/commands/remove_package_command.py#L82

The reason my commit fixes the issue is because:

 1. It no longer re-enabled the package, meaning the lock does not exists upon restart
 2. It doesn't bail from `PackageManager.remove_package()` early, so the package is removed from `installed_packages`

Thus, when Sublime Text restarts, it sees an in-process package that is disabled and no longer in the `installed_packages` list. In other words, the package shouldn't be there, so it is removed.

**Comment by FichteFoll** [comment]
1. Well yes, but `RemovePackageThread` is only instantiated by `RemovePackageCommand`, and that can only remove the package specified. I mean, the flawed code was obviously in the `remove_package` command, but that is only called by

   1. The Remove Package command.
   2. For dependencies (when cleaning up orphaned packages), and
   3. In `PackageRenamer.rename_packages`.

   1) can only be invoked manually, 2) is irrelevant and 3) should not be relevant either since we're not renaming and the "renamed to" package doesn't exist either.

2. Ah, I see. Yeah, removing it from the `installed_packages` is good, but how does it do the upgrade then? I mean, it should technically just remove it then since the package is not installed anymore.

**Comment by wbond** [comment]
Yes, I had been investigating the issue from the perspective of removing a package. Last night I looked at the upgrade process, which resulted in the commit 8aff0e49c2b5e780106caf520c2589117cef72a1 to fix that.

The thing that was causing the issue for upgrades was https://github.com/wbond/package_control/blob/f1c2ccce9e638e305c17de6a8459878c659c0885/package_control/package_manager.py#L1341. That is now wrapped in a try/except that names the file `.sublime-package-new` and prompts the user to restart Sublime Text. Then PackageCleanup will look for `.sublime-package-new` and replace the `.sublime-package` and re-enabled the package.

**Comment by FichteFoll** [comment]
Oh yeah, I see. I was only thinking of upgrading actually but the report didn't actually reflect that. All good now.
