### ISSUE TITLE
Why is my install graph strangely flat for months?

### ISSUE THREAD

**Issue by danmosemsft** [wbond/package_control#986]
Hey Will, a follow on from #981, where you said:

> The total installs is the number of unique IP address/OS combinations that have ever sent an install notice back to the server. The daily graphs show the exact number of install notices sent each day, but do not filter out duplicates (if someone installs twice) and are not reduced by the number of uninstalls.

I can't reconcile that description with the [graph I see for my package] (https://packagecontrol.io/packages/Web%20Inspector). It's basically flat and has been for at least 6 months. 

Either a steady 20-30 people have installed it each day for months -- which seems improbably smooth, I would expect more when I put a new release out, less other times, etc

Or, it's counting something else. Could it be counting each of the "pings" checking for an upgrade, each time they start Sublime?

If it's the former, I really do have over 10,000 users. If it's the latter, I only have about 30 users.

I'd love to know which to know whether to bother working on it!

**Comment by FichteFoll** [comment]
10k users is not unlikely I'd say. From the Package Control source code I analyzed I can tell you that pings (checking for updates) definitely do not count as a tick for installation because nothing is sent over the network unless you actually installed a package.

I'm not sure about updates though.

**Comment by wbond** [comment]
The graph is installs only, not updates. While it may seem illogical, I can tell you that fairly consistent install counts (and even purchases for paid packages) seems to be the norm. Here is one example: https://packagecontrol.io/packages/SFTP. You can browse around other packages that are not trending (those are by definition undergoing a large change) and you will tend to see fairly consistent numbers for packages that have more than a few thousand installs.

You can also feel free to look at the code for both [Package Control](https://github.com/wbond/package_control) and [packagecontrol.io](https://github.com/wbond/packagecontrol.io). Here is some of the code related to submitting, recording and displaying install stats:

 - https://github.com/wbond/package_control/blob/master/package_control/package_manager.py#L1814-L1856
 - https://github.com/wbond/packagecontrol.io/blob/master/app/controllers/submit.py
 - https://github.com/wbond/packagecontrol.io/blob/master/app/models/package/usage.py
 - https://github.com/wbond/packagecontrol.io/blob/master/app/models/package/find.py#L446-L499

**Comment by FichteFoll** [comment]
[this graph is highly suspicious to me](https://packagecontrol.io/packages/Package%20Control)

**Comment by wbond** [comment]
There was a bug in PC 3.0 that messed up reporting installs. The graph used to look like that. Also, yesterday over 12,000 people visited the installation page. It does not seem unreasonable that 1/3 would actually install the package. The stats for the rest of the year were suspect with on average over 10,000 views of the Installation page per day, but only a couple hundred installs.

**Comment by FichteFoll** [comment]
So packages actually most likely have more installs than reported?

**Comment by wbond** [comment]
Just Package Control itself.

**Comment by wbond** [comment]
https://github.com/wbond/package_control/commit/d2c7d0ec733ee908a66fd65fe8ea59c414929f72

**Comment by wbond** [comment]
I don't think there is any action item here, so I am closing.
