### ISSUE TITLE
no install package command under the command palette

### ISSUE THREAD

**Issue by unabomber87** [wbond/package_control#991]
i followed the instruction given by wbond https://github.com/wbond/package_control/issues/988#event-409900404

but the install package command disappear from the command palette

**Comment by wbond** [comment]
Please provide a debug log https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log

**Comment by wbond** [comment]
Actually, just grab the contents of the console, you don't need to enable `debug`.

**Comment by unabomber87** [comment]
voila

DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/zizou/.config/sublime-text-3/Packages
state path: /home/zizou/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/zizou/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.055033
startup time: 0.129932
first paint time: 0.13808
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
Package Control: Error finding main directory from loader
reloading plugin 0_package_control_loader.01-ssl-linux
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "01-ssl-linux in /home/zizou/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package", line 6, in <module>
ImportError: No module named 'package_control'
plugins loaded
reloading Packages/User/Preferences.sublime-settings

**Comment by wbond** [comment]
According to your log, Package Control is not installed. Please try following the directions at https://packagecontrol.io/installation again.

**Comment by unabomber87** [comment]
no i have already tried to install it
here is the debug for the second try 

>>>import urllib.request,os,hashlib; h = '462d6673ebd5b9ca297474c166b2e10d' + 'fd945a23b1a0642535aa906951315f52'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
186933
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading Packages/Package Control/Package Control.sublime-settings
reloading Packages/User/Package Control.sublime-settings
Package Control: Installing 1 missing dependency
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in /home/zizou/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 113, in run
  File "package_control.automatic_upgrader in /home/zizou/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 145, in install_missing
  File "package_control.package_manager in /home/zizou/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 1317, in install_package
  File "package_control.loader in /home/zizou/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 207, in add
  File "/home/zizou/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package/02-bz2.py", line 1, in <module>
ImportError: No module named 'package_control'

**Comment by wbond** [comment]
@unabomber87 The original console log you posted contained no reference to a package named `Package Control`, so I am fairly sure it was not installed then.

Please try deleting `/home/zizou/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package` and restarting Sublime Text.

**Comment by unabomber87** [comment]
it work thanks a lot!!! :+1:

**Comment by wbond** [comment]
Ok, great!
